### ISSUE TITLE
Look into removing ‘rate’ argument from CutMix/MixUp

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#100]
If we want this to be an option for random augmentations, we should really incorporate this into a base preprocessing layer.

this depends on how our users are using these layers though

**Comment by innat** [comment]
@LukeWood users may want to control the times of appearance of augmentation on the dataset during training, and that's why I think it's better to have an option like this. Also, if I'm not worng other augmentation libraries also provide `prob` params.

**Comment by bhack** [comment]
Yes I think we could introduce this in the base class

**Comment by chjort** [comment]
We could also move this into a separate layer like so:
```python
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras import backend

class RandomChance(layers.Layer):
    def __init__(self, function, probability, **kwargs):
        super(RandomChance, self).__init__(**kwargs)
        self.function = function
        self.probability = probability

    def call(self, inputs, training=True):
        if training is None:
            training = backend.learning_phase()

        do_function = tf.random.uniform([]) < self.probability
        x = tf.cond(
            pred=tf.logical_and(do_function, training),
            true_fn=lambda: self.function(inputs),
            false_fn=lambda: inputs,
        )
        return x

```

This could be used to wrap preprocessing layers and allow
for a flexible API for defining preprocessing flows, e.g:
```python
from keras_cv.layers import preprocessing

augmentations = tf.keras.models.Sequential(
    [
        tf.keras.layers.Resizing(256, 256),
        RandomChance(preprocessing.MixUp(), 0.5),
        RandomChance(preprocessing.RandomCutout(28, 28), 0.5),
        tf.keras.layers.Rescaling(scale=1/255)
    ]
)
```

**Comment by LukeWood** [comment]
Yeah, I've considered the last one too and just don't know if it's a very "nice to read" API.

It does tell me that we might as well remove the `rate` argument though from these layers.
