### ISSUE TITLE
Reorganize [ops] and [custom_ops]

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#1010]
Currently, we have some tech debt here: ops contains some custom layers as well as some ops.  We should really fix this and put the components that are like layers under layers instead of ops.  Then we can merge custom_ops into the ops directory.

Its confusing to have both.

**Comment by bhack** [comment]
Do you have any example?

**Comment by LukeWood** [comment]
`custom_ops`: https://github.com/keras-team/keras-cv/tree/master/keras_cv/custom_ops

should live under `ops` because it contains tensorflow ops.

ops on the other hand contains a ton of stuff (BoxMatcher, etc), but also IoU3D which is a custom TF op: 

https://github.com/keras-team/keras-cv/tree/master/keras_cv/ops

**Comment by innat** [comment]
Why [tensorflow ops](https://github.com/keras-team/keras-cv/tree/master/keras_cv/custom_ops) is here in the first place? Also it looks [bazel](https://github.com/keras-team/keras-cv#installing-custom-ops-from-source) is reuqired to build custom ops. It looks weird to see these in here as well.

**Comment by bhack** [comment]
> Why [tensorflow ops](https://github.com/keras-team/keras-cv/tree/master/keras_cv/custom_ops) is here in the first place? Also it looks [bazel](https://github.com/keras-team/keras-cv#installing-custom-ops-from-source) is reuqired to build custom ops. It looks weird to see these in here as well.

What do you mean?

**Comment by innat** [comment]
I mean, why do we need to write C code for some custom operations (ie. `PairwiseIou3D`?

**Comment by LukeWood** [comment]
Still a few utils to fix
