### ISSUE TITLE
move `keras_cv/models` to Functional Subclasses

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#1015]
Looking at [these](https://github.com/keras-team/keras-cv/tree/master/keras_cv/models), the classification mdoels (backbones) are written in functional api, whereas the object detection and semantic segmentation are written in subclass api. 

- Is it discussed to mix APIs in this cases? 
- Is it okay to have classification models can also be written in subclass api?
- Doing subclass APIs, we lost convinient functionality of `.summary` and `plot_model`. They don't work as expected. Any thoughts?

**Comment by ianstenbit** [comment]
@tanzhenyu IIRC you were considering restructuring the OD models slightly to be a functional subclass?

**Comment by tanzhenyu** [comment]
> @tanzhenyu IIRC you were considering restructuring the OD models slightly to be a functional subclass?

Yes, thanks for reporting this, we should be able to get some of the models to functional subclass before 0.4

**Comment by DavidLandup0** [comment]
Are we keeping regular models functional and OD/SemSeg models functional subclassing?

**Comment by tanzhenyu** [comment]
> Are we keeping regular models functional and OD/SemSeg models functional subclassing?

backbone models can still be pure functional, given they don't need overriding `train_step`

**Comment by DavidLandup0** [comment]
Awesome! Might be worth renaming the issue to "Move non-backbone `keras_cv/models` to Functional Subclasses"
