### ISSUE TITLE
BUG: StableDiffusion.inpaint() throws float tensor error

### ISSUE THREAD

**Issue by BFauber** [keras-team/keras-cv#1019]
I am using today's version (15Nov2022) of https://github.com/keras-team/keras-cv/ and I receive the following error when using `StableDiffusion.inpaint()`:

`InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a half tensor but is a float tensor [Op:AddV2]`

Is anyone also receiving this error when running `StableDiffusion.inpaint()`?

Here is my code:

```python
from tensorflow import keras
from keras_cv.models import StableDiffusion

keras.mixed_precision.set_global_policy("mixed_float16")

model = StableDiffusion(
    img_height=512, 
    img_width=512, 
    jit_compile=True
)

prompt = "photo of coffee beans"
seed = 52983

# NOTE: img1 was successfully generated using StableDiffusion.text_to_image() with the same prompt and seed values as shown above.
type(img.1) # numpy.ndarray (dtype=int8)
img1.shape # (1, 512, 512, 3)

type(mask) # numpy.ndarray (dtype=int8)
mask.shape # (1, 512, 512)

img2 = model.inpaint(
        prompt=prompt,
        image=img1,
        mask=mask,
        num_resamples=1,
        batch_size=1,
        num_steps=25,
        unconditional_guidance_scale=7.5,
        diffusion_noise=None,
        seed=seed,
        verbose=True,
        )
```

**Comment by bobqywei** [comment]
Thanks for finding this and letting me know @BFauber @bhack! I think i'll allow the user to specify the dtype for these internal ops so that they have control over the tradeoffs?

**Comment by BFauber** [comment]
Thanks for your suggestion @bobqywei. 

I've found the source of my error is the `mixed_float16` keras global policy:

```python
keras.mixed_precision.set_global_policy("mixed_float16")
```

If I omit this global policy line, the inpainting code runs without an error, but it only outputs a black box.

Thus, the `StableDiffusion.inpaint()` function is not compatible with `keras.mixed_precision.set_global_policy("mixed_float16")` https://keras.io/guides/keras_cv/generate_images_with_stable_diffusion/ and it is not properly inpainting.

**Comment by ianstenbit** [comment]
It seems like at the minimum, AIs here are to:
- Fix FP type issues in inpainting workflow _or_ document that mixed precision doesn't work with inpainting
- Figure out what's going wrong with this particular usage of `inpaint`

@BFauber can you please share a full repro script of your issue (either a Colab or a gist is good). I will take a look if you @ me on this thread.

**Comment by BFauber** [comment]
Thanks @ianstenbit! Here is a link to the gist:
https://gist.github.com/BFauber/92a275cf29d2806353c02f9666f43887

Thanks for looking into the usage of `inpaint`, and please let me know if you have any additional questions.

**Comment by ianstenbit** [comment]
I've also noticed that on a step-by-step basis, `latents` is becoming more and more uniform prior to becoming NaNs. The first latent looks normally distributed, but after a while end up looking like this:

```
[[ 0.01294876, -0.01969388, -0.02878554, -0.02118983],
         [-0.01029961, -0.01716631, -0.03993208, -0.01427874],
         [-0.01029961, -0.01716631, -0.03993208, -0.01427874],
         ...,
         [-0.01029961, -0.01716631, -0.03993208, -0.01427874],
         [-0.01029961, -0.01716631, -0.03993208, -0.01427874],
         [-0.01993897, -0.00069592, -0.03201018, -0.01465789]],
```

**Comment by ianstenbit** [comment]
Aha -- turns out the issue is actually just that your `mask` uses `0` and `255` instead of `0` and `1` 😄 
@BFauber if you divide your mask by 255 before calling `inpaint` this will work correctly.

I will add a note to the docstring stating that mixed precision is not currently supported for inpainting.
