### ISSUE TITLE
add augmix to preprocessing layers

### ISSUE THREAD

**Issue by ma7555** [keras-team/keras-cv#104]
Augmix: https://arxiv.org/abs/1912.02781

If it is needed, I have worked with it in the past and can submit a PR for it.

**Comment by innat** [comment]
@ma7555 it's been requested https://github.com/keras-team/keras-cv/issues/40
I think luke [mentioned](https://github.com/keras-team/keras-cv/issues/40#issuecomment-1018822682) that he'll include it from tf-similary.

**Comment by ma7555** [comment]
Alright i missed that. Thanks
