### ISSUE TITLE
Should we make `num_steps=50` in StableDiffusion?

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#1043]
Currently this defaults to 25, which creates some very weak outputs.

**Comment by ianstenbit** [comment]
I think we decided the answer is "yes" -- @LukeWood do you want to update this default? (Otherwise I can)

**Comment by bhack** [comment]
Are we not claiming a 50 default?

https://keras.io/guides/keras_cv/generate_images_with_stable_diffusion/#:~:text=Stable%20Diffusion%20consists%20of%20three,a%20higher%2Dresolution%20512x512%20image.

**Comment by ianstenbit** [comment]
> Are we not claiming a 50 default?

Yes, we are, and we should adjust the default in our implementation accordingly
