### ISSUE TITLE
Change test cases to keras-cv/tests

### ISSUE THREAD

**Issue by Navan0** [keras-team/keras-cv#105]
Currently the test cases for prepossessing are in the same directory. can we move it to a separate new directory ```keras-cv/tests``` ?

**Comment by LukeWood** [comment]
We actually decided as a team we prefer to have them alongside the original files to improve discoverability.  Tests also serve as documentation, showing how to use them.  If this becomes problematic in the future we can reconsider, but for now we like this approach.
