### ISSUE TITLE
RetinaNet train_step() should not evaluate custom metrics

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#1068]
This could be gated behind an argument like evaluate_train_time_metrics, but we should ONLY evaluate metrics in `evaluate_step` by default, not train_step.

Doing so in train step is too expensive.

**Comment by innat** [comment]
> evaluate_train_time_metrics: (Optional) whether or not to evaluate metrics passed in compile() inside of the train_step(). This is NOT recommended, as it dramatically reduces performance due to the synchronous label decoding and COCO metric evaluation. For example, on a single GPU on the PascalVOC dataset epoch time goes from 3 minutes to 30 minutes with this set to True. Defaults to False.

- What were the assumptions to add it in the beginning? 
- Is it dropping because of performance issue or not useful?

**Comment by tanzhenyu** [comment]
Done through recent series of refactoring
