### ISSUE TITLE
Define the best API for users to apply augmentations in a probabilistic manner.

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#108]
Maybe this will look like:
```
RandomChance(layer, rate=0.5)
```

or maybe:
```
MaybeApply(layer, rate=0.5)
```

Either way, this is important for the composition of image augmentation pipelines.

**Comment by bhack** [comment]
I think that we Need to think about this evaluating we want to achieve in:
 https://github.com/keras-team/keras-cv/issues/41

**Comment by innat** [comment]
@LukeWood @bhack @qlzh727 @kartik4949 

I think two types of functions need to be addressed regarding the processing layers.  For examples:

1. Randomly apply the layer 

```python

random_mixup  = RandomApply(Mixup(),  prob = 0.5)
random_cutmix = RandomApply(CutMix(), prob = 0.5)
random_equliz = RandomApply(Equalization(), prob = 0.5)
```

2. Randomly pick a layers

```python

random_mixup  = RandomApply(Mixup(),  prob = 0.5)
random_cutmix = RandomApply(CutMix(), prob = 0.5)

random_blur   = RandomPick( 
          [
              RandomApply(GaussianBlur(), prob = 0.5),
              RandomApply(MotionBlur(),   prob = 0.5),
              RandomApply(MediamBlur(),   prob = 0.5)
          ], 
     prob = 0.8
)
```

**Comment by kartik4949** [comment]
@innat 
I think by RandomPick you mean RandAug in defined space!

**Comment by innat** [comment]
It's like the `OneOf` method that is provided in [argumentation (cell 7)](https://albumentations.ai/docs/examples/example/) or img_aug libraries.

**Comment by bhack** [comment]
I think that we need to reason a little bit more generally about what kind of access to the augmentation layers an [auto augmentation](https://www.ilfattoquotidiano.it/2022/02/15/dopo-due-anni-di-emergenza-covid-i-medici-sono-costretti-a-scioperare-turni-insostenibili-poche-tutele-carenza-di-personale-poi-lo-schiaffo-dei-mancati-ristori/6494438/) policy need to achieve. 
Then I suppose we could think at `RandomApply` as just one o the simplest policy.

I don't know if @haifeng-jin has any feedbaqck.

**Comment by bhack** [comment]
Just a reminder, we had also https://github.com/keras-team/autokeras/issues/879

**Comment by LukeWood** [comment]
We've decided to include a `rate` argument in a base augmentation layer.  This provides the best user API imo:

```
RandomRotation(rate=0.5)
```

instead of:
```
MaybeApply(RandomRotation(), 0.5)
```

Scott is working on this in his base augmentation layer.

**Comment by innat** [comment]
@LukeWood instead of giving its name as `rate`, how about `prob`?

**Comment by LukeWood** [comment]
Historically, this is the sort of thing that isn't included in the Keras API and is delegated to users.  This is pretty trivial to implement:

```
class RandomChoice():
    def __init__(self, layers):
        self.layers = layers
        self.n = len(layers)
   
    def call(self, inputs):
        return layers[tf.random.choice(range(self.n))](inputs)
```

with some tensorflow-friendly changes takes care of it.

**Comment by LukeWood** [comment]
If we're already using this internally I don't see an issue with exposing it, but I don't particularly think it's a big value add to support is all.

**Comment by bhack** [comment]
I still hope that we could work more in general with augmentation policiy classes or that we could actively coordinate with autokeras (If It Is still an active project)

**Comment by innat** [comment]
@LukeWood 
What you're referring trivial to implement, in the breath, you can also say that implementing `rate` is also trivial to implement to end-users. The feature request in no. 2 is not actually a random request. It's followed in practice. 

If you see other popular augmentation libraries, for example, `img_aug` and `albumentation`, all of them offers such feature to users. In addition, if you see the `torch-vision`, you would find the same. In `torch`, you can use `RandomChoice` to apply a single transformation randomly picked from a list with a given probability. If this info motivates you, please reconsider the request.
