### ISSUE TITLE
feature: Mosaic Augmentation

### ISSUE THREAD

**Issue by kartik4949** [keras-team/keras-cv#110]
Hey,
I was thinking to add mosaic augmentation as a layer.
I have built this augmentation for google automl project
link: https://github.com/google/automl/blob/master/efficientdet/aug/mosaic.py
@LukeWood please have a look
Thanks

**Comment by bhack** [comment]
Is this the same request as https://github.com/keras-team/keras-cv/issues/21 ?

**Comment by kartik4949** [comment]
Yes, just saw it
Will close this request then thanks :)
