### ISSUE TITLE
Refactor Deeplab to be a functional subclassing model 

### ISSUE THREAD

**Issue by tanzhenyu** [keras-team/keras-cv#1104]
as title

**Comment by DavidLandup0** [comment]
Can I sign up to do this and introduce DeepLabV3+ besides V3?

**Comment by tanzhenyu** [comment]
> Can I sign up to do this and introduce DeepLabV3+ besides V3?

Yes that'd be great! Just a note that we'd want to have this in 0.4, which have a tight timeline (~1 week)

**Comment by DavidLandup0** [comment]
Sure! I've ported most of DeepLabV3 into using the functional API last night. Not sure if V3+ can be done in a week, but I'll try. Thanks!

Just to make sure we're on the same page - by "functional subclassing model", you mean using the functional API to make it and expose a method for constructing them, just like we do for image classification models?

**Comment by tanzhenyu** [comment]
> Sure! I've ported most of DeepLabV3 into using the functional API last night. Not sure if V3+ can be done in a week, but I'll try. Thanks!
> 
> Just to make sure we're on the same page - by "functional subclassing model", you mean using the functional API to make it and expose a method for constructing them, just like we do for image classification models?

We don't need V3+ to be included in 0.4 though (but it'd be a big plus if do).
by "functional subclassing", it is a hybrid of functional model and subclass model. See [this](https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/models/bert/bert_backbone.py#L177-L188)

**Comment by DavidLandup0** [comment]
I think DeepLabV3+ is working or is thereabout. Gotta test it and will open a PR later after the DLV3 port is finished.
I assumed that it was only the use of the functional API in #1119, so I'll update it.
BTW, what's the advantage of functional subclass over just functional?
