### ISSUE TITLE
OD models should take keras_cv.models as backbone

### ISSUE THREAD

**Issue by tanzhenyu** [keras-team/keras-cv#1105]
Instead of tf.keras.applications

**Comment by DavidLandup0** [comment]
I started on this one with #1080 - should I continue? 🤔

**Comment by tanzhenyu** [comment]
> I started on this one with #1080 - should I continue? 🤔

ResNet50V2 does not give competitive results than ResNet50, so I'm still debugging

**Comment by LukeWood** [comment]
Now done
