### ISSUE TITLE
Loss reduction inconsistency between RetinaNet and FasterRCNN

### ISSUE THREAD

**Issue by tanzhenyu** [keras-team/keras-cv#1106]
One takes SUM, one takes NONE. We should unify that before 0.4 release

**Comment by tanzhenyu** [comment]
This has been unified per 0.4 release, however it's not using the AUTO from core Keras. We're currently evaluating whether we should make it or not

**Comment by sachinprasadhs** [comment]
Thanks for reporting the issue.

`RetinaNet` with the new implementation is now part of [KerasHub](https://github.com/keras-team/keras-hub) a consolidated `KerasNLP` and `KerasCV` package.
The model weights are available in `Kaggle`, for details and usage refer https://www.kaggle.com/models/keras/retinanet

We will not be making any changes to the models in `KerasCV` which are made available in `KerasHub` or the APIs/Utils made available in `Keras`.
If you still face any issue, please file a new issue in [keras-hub](https://github.com/keras-team/keras-hub)
