### ISSUE TITLE
Supporting OCR models

### ISSUE THREAD

**Issue by tanzhenyu** [keras-team/keras-cv#1114]
We'd very much like to get OCR as part of the offering, preferrably some classical model such as EAST / Rossetta

**Comment by tanzhenyu** [comment]
@faustomorales Would you be interested?

**Comment by innat** [comment]
@tanzhenyu 
It would be great to have more details regarding OCR models from keras-team. Regarding 

- Text Detection
- Test Recognition

What sorts of models would be priorities? (For example, some SOTA models: [`MaskTextSpotter-V3`](https://github.com/MhLiao/MaskTextSpotterV3), [`ABCNet`](https://github.com/aim-uofa/AdelaiDet/tree/master/configs/BAText), etc,).

**Comment by bhack** [comment]
What about https://github.com/tensorflow/models/tree/master/official%2Fprojects%2Funified_detector

**Comment by tanzhenyu** [comment]
> What about https://github.com/tensorflow/models/tree/master/official%2Fprojects%2Funified_detector

Oh I wasn't aware of it.
@Jyouhou wdyt?

**Comment by bhack** [comment]
Note It is unified detector + layout.

It could be ok if I suppose that we want to have a two stage API design here (detection and recognition)

**Comment by tanzhenyu** [comment]
> Note It is unified detector + layout.
> 
> It could be ok if I suppose that we want to have a two stage API design here (detection and recognition)

My take here is we would need to have some two stage design anyway (just like OD)

**Comment by bhack** [comment]
> two stage design anyway (just like OD)

Here we could have singe(?) double and triple stage (detector + layout + recognition).

Instead I think that in OD we are 2 stage or 1 stage (e.g. anchor free).

**Comment by ianstenbit** [comment]
OCR is still something we'd like to include in the long-term but it's not currently a priority
