### ISSUE TITLE
Exception: URL fetch failure on https://huggingface.co/fchollet/stable-diffusion/resolve/main/kcv_encoder.h5: None -- [Errno 11002] getaddrinfo failed

### ISSUE THREAD

**Issue by VERISBABY** [keras-team/keras-cv#1118]
I got error on this code block:
```
import keras_cv
from tensorflow import keras
import matplotlib.pyplot as plt

model = keras_cv.models.StableDiffusion(img_width=512, img_height=512)
```

ERROR:
```
Downloading data from https://huggingface.co/fchollet/stable-diffusion/resolve/main/kcv_encoder.h5
...
Exception: URL fetch failure on https://huggingface.co/fchollet/stable-diffusion/resolve/main/kcv_encoder.h5: None -- [Errno 11002] getaddrinfo failed
```
And a long traceback from urllib & http of python.

**Comment by ADITYADAS1999** [comment]
hey [VERISBABY](https://github.com/VERISBABY) can you mention which editor you use to run the code block ? 
I use google colab notebook that works fine for me. 

![colab](https://user-images.githubusercontent.com/58718316/206907970-1c89d529-5c83-4903-8cc3-c07bfdba8cc2.PNG)

**Comment by LukeWood** [comment]
Seems like a temporary outage in the network, there’s nothing to do from KerasCV’s end here

**Comment by LukeWood** [comment]
> > hey [VERISBABY](https://github.com/VERISBABY) can you mention which editor you use to run the code block ? I use google colab notebook that works fine for me.
> > ![colab](https://user-images.githubusercontent.com/58718316/206907970-1c89d529-5c83-4903-8cc3-c07bfdba8cc2.PNG)
> 
> I use VS Code version 1.74.0

is it working now?
