### ISSUE TITLE
SmoothL1BoundingBoxLoss

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#112]
This is used in RetinaNet:

Basic prototype from keras.io example:
```
class SmoothL1BoundingBoxLoss(tf.losses.Loss):
    """Implements Smooth L1 loss"""

    def __init__(self, delta):
        super().__init__()
        self._delta = delta

    def call(self, y_true, y_pred):
        difference = y_true - y_pred
        absolute_difference = tf.abs(difference)
        squared_difference = difference ** 2
        loss = tf.where(
            tf.less(absolute_difference, self._delta),
            0.5 * squared_difference,
            absolute_difference - 0.5,
        )
        return tf.reduce_sum(loss, axis=-1)
```

**Comment by bhack** [comment]
https://github.com/tensorflow/models/blob/master/research/object_detection/core/losses.py#L18-L21

**Comment by bhack** [comment]
Now RetinaNet losses are at https://github.com/tensorflow/models/blob/master/official/vision/beta/losses/retinanet_losses.py

**Comment by MrinalTyagi** [comment]
Would like to work on this. Thanks :)

**Comment by LukeWood** [comment]
@MrinalTyagi feel free to add this and get started.  create a `losses` directory under `keras_cv/losses` and feel free to try it out!

**Comment by LukeWood** [comment]
I added this with the RetinaNet
