### ISSUE TITLE
Skip by default non regular tests

### ISSUE THREAD

**Issue by bhack** [keras-team/keras-cv#1132]
https://github.com/keras-team/keras-cv/pull/1125#discussion_r1046369903

If we don't adopt this policy we are going to annoying contributors executing local test and we are also going to risk to misalign  these "skipping" args in the CI scripts.

**Comment by LukeWood** [comment]
> [#1125 (comment)](https://github.com/keras-team/keras-cv/pull/1125#discussion_r1046369903)
> 
> If we don't adopt this policy we are going to annoying contributors executing local test and we are also going to risk to misalign these "skipping" args in the CI scripts.

agreed, @ianstenbit I definitely think we should disable these by default.

**Comment by ianstenbit** [comment]
I agree -- this is what I did with Custom Op tests (https://github.com/keras-team/keras-cv/blob/master/keras_cv/ops/iou_3d_test.py)

I think we need to do the same with Waymo tests. We _used_ to do this for expensive model tests, but now we control those via CI scripts. @LukeWood wdyt about those tests?

**Comment by bhack** [comment]
I repost some solutions we have as mentioned in the original comment:

https://jwodder.github.io/kbits/posts/pytest-mark-off/

**Comment by ianstenbit** [comment]
> I repost some solutions we have as mentioned in the original comment:
> 
> https://jwodder.github.io/kbits/posts/pytest-mark-off/

Ack -- this is what we're doing for custom ops tests. I think `skipif` is the right solution for the Waymo ones too

**Comment by bhack** [comment]
I think is that we need to cluster default  excluded tests. What we have now? 2 classes? C++ dep tests and slow? Or do we have more classes?

**Comment by bhack** [comment]
> Ack -- this is what we're doing for custom ops tests. I think skipif is the right solution for the Waymo ones too

If you check with  skipif we have also the option 2 using the decorator to cluster excluded tests.

**Comment by LukeWood** [comment]
> > I repost some solutions we have as mentioned in the original comment:
> > https://jwodder.github.io/kbits/posts/pytest-mark-off/
> 
> Ack -- this is what we're doing for custom ops tests. I think `skipif` is the right solution for the Waymo ones too

I’ll dig up the PR where I implemented decorators for skipping based on environment variables.  We can use that approach.

**Comment by bhack** [comment]
We also need to separate the test execution for custom ops in the CI and without the bazel build of non custom ops tests:

https://github.com/keras-team/keras-cv/pull/1150#issuecomment-1354631315

**Comment by bhack** [comment]
Also it is going to broke the Vscode pytest dicoverability:

```python
E   ImportError: cannot import name 'compute_pycoco_metrics' from 'keras_cv.metrics.coco' 
E   ModuleNotFoundError: No module named 'waymo_open_dataset'
E   ModuleNotFoundError: No module named 'waymo_open_dataset'
```
ERROR keras_cv/callbacks/pycoco_callback_test.py
ERROR keras_cv/datasets/waymo/load_test.py
ERROR keras_cv/datasets/waymo/transformer_test.py
!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!
```

**Comment by ianstenbit** [comment]
#1177 fixed this for Waymo tests

**Comment by ianstenbit** [comment]
This has been largely fixed by the run_large run_extra_large structure
