### ISSUE TITLE
Should we rename the ViTs?  

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#1137]
Right now they have a lot of underscores:  ViT_B_16

https://github.com/keras-team/keras-cv/pull/1014/

This deviates a bit from Keras standard: i.e. `EfficientNetBV2`

**Comment by DavidLandup0** [comment]
Sure thing! I'll rename them in a moment and push the change. Just gotta check that it doesn't break any tests.
Do we do fully without underscores (ViTB16) or add one (ViT_B16)?

**Comment by DavidLandup0** [comment]
Speaking of refactoring for the sake of API consistency, #1024 refactors MLPMixer (associated with ViTs) to adhere to code guidelines like the rest of the models here
