### ISSUE TITLE
Create a `DecodeBoundingBoxPredictions` layer

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#114]
This one requires some design work, as the exact semantics of how this will work are unclear.  What is clear is that most bounding box prediction networks use some sort of prediction decoding, often including `tf.image.non_max_supression`.

**Comment by kartik4949** [comment]
1. Most networks have bounding box filtration, we can have it as layer.
2. Bounding boxes are predicted on different spatial feature maps into one prediction array, we can make a layer to decode prediction to original input image scale e.g.
https://github.com/kartik4949/TensorPipe/blob/main/tensorpipe/funnels/funnels.py

please refer `TFDecodeMixin` class
3. Bounding Box format layer- x1,y2, x2,y2 to x,y,w,h utility layer or function.

**Comment by LukeWood** [comment]
this will be done as part of RetinaNet/Yolo not as part of the API itself.  https://github.com/LukeWood/KerasCV-RetinaNet/blob/master/retina_net/layers/decode_predictions.py#L7
