### ISSUE TITLE
Supporting MaxViT

### ISSUE THREAD

**Issue by tanzhenyu** [keras-team/keras-cv#1144]
MaxViT provides a hierachical way to process spatial input, so the computation only scales linearly with image size, and can better leverage inductive bias. It could also be used as backbone for detection and segmentation.

[paper](https://arxiv.org/pdf/2204.01697.pdf)

Contributor can follow the ViT PR, i.e., first provide all layers, and build up the model with checkpoint conversion. Although in this case, the [original](https://github.com/google-research/maxvit) MaxViT is trained using Keras already, so the conversion should be much easier compared with ViT.

**Comment by tanzhenyu** [comment]
@vztu

**Comment by DavidLandup0** [comment]
We already have #912

**Comment by tanzhenyu** [comment]
Oh great, closing it then
