### ISSUE TITLE
Migrate VGG16 to keras_cv.models

### ISSUE THREAD

**Issue by IMvision12** [keras-team/keras-cv#1159]
**Short Description**

Create a keras_cv.model version of VGG16 ported from keras.applications.  As FCN #1099 model requires vgg16 architecture.

@bhack @ianstenbit

**Comment by IMvision12** [comment]
Should we migrate vgg16 or should we just add vgg16 code along with FCN architecture in same file.

**Comment by suvadityamuk** [comment]
As far as I know, giving VGG16 as a backbone should be more of an option instead of a direct hard-coded use.

**Comment by ianstenbit** [comment]
VGG16 as a backbone SGTM. Should be a pretty straightforward move from the [Keras applications implementation](https://github.com/keras-team/keras/blob/master/keras/applications/vgg16.py).

PR is welcome -- assign me as a reviewer :)

**Comment by IMvision12** [comment]
Sure I will send a PR!

**Comment by IMvision12** [comment]
@ianstenbit should we also port the weights from Keras applications?

**Comment by ianstenbit** [comment]
@IMvision12 for backbones, we are preferring to train weights using our own training scripts for reproducibility
