### ISSUE TITLE
Stable Diffusion model clearing

### ISSUE THREAD

**Issue by Neizvestnyj** [keras-team/keras-cv#1161]
It would be nice to have a function that unloads modules from memory, otherwise when repeatedly using the StableDiffusion class, RAM overflow occurs

```py
import keras_cv

import matplotlib.pyplot as plt


def plot_images(images):
    plt.figure(figsize=(20, 20))
    for i in range(len(images)):
        plt.subplot(1, len(images), i + 1)
        plt.imshow(images[i])
        plt.axis("off")

    plt.show()

for i in range(2):
    model = keras_cv.models.StableDiffusion(img_width=512 // (i + 1), img_height=512 // (i + 1))
    images = model.text_to_image("photograph of an astronaut riding a horse", batch_size=2)
    plot_images(images)

# Some other stuff 
```

**Comment by freedomtan** [comment]
move the line
```python
model = keras_cv.models.StableDiffusion(img_width=512, img_height=512)
```
out of the loop. You only need to construct the pipeline once.

**Comment by Neizvestnyj** [comment]
> move the line
> ```python
> model = keras_cv.models.StableDiffusion(img_width=512, img_height=512)
> ```
> out of the loop. You only need to construct the pipeline once.

1) If I want to resize the image, then I will have to redefine the class.
2) When loading weights, RAM gets clogged, it would be nice to clean it, for example, I don't know how to fix this problem, because while my python script is running, ram is filled with 4.5GB extra

**Comment by tanzhenyu** [comment]
StableDiffusion is actually optimized for 512 by 512 images (or other 2^x size). If you do need different sizes, I suggest you run image resize after image generation.

**Comment by tanzhenyu** [comment]
or if you do need to clear the model, simply `del model` would work?

**Comment by Neizvestnyj** [comment]
> or if you do need to clear the model, simply `del model` would work?

No, I try different methods, but RAM is overflow. I know that model optimized for 512*512, but it is not unloaded from memory after execution, which is why 4GB of memory is just so full.

**Comment by tanzhenyu** [comment]
> > or if you do need to clear the model, simply `del model` would work?
> 
> No, I try different methods, but RAM is overflow. I know that model optimized for 512*512, but it is not unloaded from memory after execution, which is why 4GB of memory is just so full.

Would you mind trying this instead? https://stackoverflow.com/questions/52133347/how-can-i-clear-a-model-created-with-keras-and-tensorflowas-backend

**Comment by Neizvestnyj** [comment]
> > > or if you do need to clear the model, simply `del model` would work?
> > 
> > 
> > No, I try different methods, but RAM is overflow. I know that model optimized for 512*512, but it is not unloaded from memory after execution, which is why 4GB of memory is just so full.
> 
> Would you mind trying this instead? https://stackoverflow.com/questions/52133347/how-can-i-clear-a-model-created-with-keras-and-tensorflowas-backend

Yes, I've already tried it, it doesn't help, 2 starts already takes about 8 GB of RAM

**Comment by Neizvestnyj** [comment]
Please, restore issue
