### ISSUE TITLE
CSPDarkNet has weights only for when depth and width multiplier are 1.0

### ISSUE THREAD

**Issue by quantumalaviya** [keras-team/keras-cv#1171]
This makes the current weights compatible only with YoloX_l. 

Would it make sense to have CSPDarknet_tiny, _s, _m, _l and _x so that the imagenet weights can be trained for these separately?

cc. @ianstenbit @LukeWood

**Comment by ianstenbit** [comment]
Having separate API signatures for CSPDarkNetSmall/Medium/Large etc. sgtm -- that's consistent with our other backbone architectures.

**Comment by ADITYADAS1999** [comment]
> Having separate API signatures for CSPDarkNetSmall/Medium/Large etc. sgtm -- that's consistent with our other backbone architectures.

hey [ianstenbit](https://github.com/ianstenbit) this issue is still open. Can I take this one ?

**Comment by quantumalaviya** [comment]
The following multipliers must be used for the CSPDarkNet architectures:

```
DEPTH_MULTIPLIERS = {
    "tiny": 0.33,
    "s": 0.33,
    "m": 0.67,
    "l": 1.00,
    "x": 1.33,
}
WIDTH_MULTIPLIERS = {
    "tiny": 0.375,
    "s": 0.50,
    "m": 0.75,
    "l": 1.00,
    "x": 1.25,
}
```

@ADITYADAS1999 FYI if you're working on this.

**Comment by ADITYADAS1999** [comment]
> The following multipliers must be used for the CSPDarkNet architectures:
> 
> ```
> DEPTH_MULTIPLIERS = {
>     "tiny": 0.33,
>     "s": 0.33,
>     "m": 0.67,
>     "l": 1.00,
>     "x": 1.33,
> }
> WIDTH_MULTIPLIERS = {
>     "tiny": 0.375,
>     "s": 0.50,
>     "m": 0.75,
>     "l": 1.00,
>     "x": 1.25,
> }
> ```
> 
> @ADITYADAS1999 FYI if you're working on this.

thanks for sharing [quantumalaviya](https://github.com/quantumalaviya) 

Here I found the value of DEPTH_MULTIPLIERS, WIDTH_MULTIPLIERS  that is 1.0,

Can you ensure that all the changes are done here ?

https://github.com/keras-team/keras-cv/blob/04ca63c2c26431fa8157dc16a5004ab04b1eb2aa/keras_cv/models/csp_darknet.py#L40

**Comment by ianstenbit** [comment]
@ADITYADAS1999 sure feel free to add these! Thanks 😄

**Comment by ADITYADAS1999** [comment]
> @ADITYADAS1999 sure feel free to add these! Thanks 😄

awesome 😎

**Comment by quantumalaviya** [comment]
> Can you ensure that all the changes are done here ?

Yes @ADITYADAS1999. 
Thanks for picking this up! Feel free to tag me when you raise a PR for this.

**Comment by ADITYADAS1999** [comment]
> > Can you ensure that all the changes are done here ?
> 
> Yes @ADITYADAS1999. Thanks for picking this up! Feel free to tag me when you raise a PR for this.

Hi,  [quantumalaviya](https://github.com/quantumalaviya) can you review the PR    https://github.com/keras-team/keras-cv/pull/1180
