### ISSUE TITLE
HueSaturationValue preprocessing layer  

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#119]
ref https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.HueSaturationValue

**Comment by LukeWood** [comment]
so this shifts the HueSaturationValue.  Seems useful enough.  

The only question I have: is this actually distinct from color shift?  I believe that color shift and hue saturation value may have the same result if they are randomly sampled.

**Comment by innat** [comment]
I didn't check but do you think the requested layer can be achieved from this https://www.tensorflow.org/api_docs/python/tf/image/rgb_to_hsv

**Comment by qlzh727** [comment]
Should we have different KPL for Hue and Saturation? (They produce different math results).

On a side note, the color jitter layer seems to contain both Hue and Saturation adjustment.

**Comment by qlzh727** [comment]
Chatted with Luke offline, we will have two layers, one for Hue and one for Saturation.
