### ISSUE TITLE
Add imagenet pretrained weights for ResNet50 v1

### ISSUE THREAD

**Issue by jlee24** [keras-team/keras-cv#1193]
**Short Description**
Though ResNet50 v2 performs better, many past papers that serve as benchmarks/baselines use a ResNet50 v1. It would be great to be able to load a pretrained ResNet50 v1 model in Keras CV to make comparisons to those existing models.

**Comment by tanzhenyu** [comment]
Yes, we need to make this for some of our other CV tasks as well

**Comment by tanzhenyu** [comment]
Being fixed by https://github.com/keras-team/keras-cv/pull/1211
