### ISSUE TITLE
Integrate pre-commit hooks

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#12]
based on tensorflow/tensorflow#48371

**Comment by LukeWood** [comment]
@bhack

**Comment by bhack** [comment]
Please check https://github.com/keras-team/keras-cv/pull/14

**Comment by LukeWood** [comment]
We ended up deciding against this as a team.  Apologies again @bhack for the miscommunication, I hope this doesn't dissuade you from contributing to the repository as your contributions thus far have already been extremely helpful.

**Comment by bhack** [comment]
@LukeWood I supposed this was a green light with:

https://github.com/keras-team/keras-cv/pull/11#discussion_r747055087

I hope the we could make open  regular meetings soon like the other SIGs.
