### ISSUE TITLE
Blur preprocessing layer

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#121]
Refs

- [GaussianBlur](https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.GaussianBlur) 
- [MedianBlur](https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.MedianBlur) 
- [MotionBlur](https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.MotionBlur)

**Comment by artu1999** [comment]
Happy to take on this one. Just a few question before jumping into it:

- Do we want to have a class with a method for each type of blur (ie preprocessing.Blur.GaussianBlur, preprocessing.Blur.MedianBlur....) or a class for each blur type?
- GaussianBlur and MedianBlur are provided in Tensorflow (see [MedianFilter](https://www.tensorflow.org/addons/api_docs/python/tfa/image/median_filter2d and [GaussianFilter](https://www.tensorflow.org/addons/api_docs/python/tfa/image/gaussian_filter2d), I guess for MotionBlur you would just use Conv2D with the right kernel?

**Comment by LukeWood** [comment]
see issue https://github.com/keras-team/keras-cv/issues/26.

Closing in favor of that, leaving a comment to include support for these.
