### ISSUE TITLE
Support ConvNeXt V2 

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#1230]
**Short Description**

![model_scaling](https://user-images.githubusercontent.com/17668390/210395572-dea06395-a84c-42b1-a4c7-2410d1cd4f41.png)

**Papers**

https://arxiv.org/abs/2301.00808

**Existing Implementations**

https://github.com/facebookresearch/ConvNeXt-V2

**Other Information**

**Comment by innat** [comment]
keras code: https://github.com/edwardyehuang/iSeg/blob/master/backbones/convnext_v2.py
cc @edwardyehuang

**Comment by innat** [comment]
Reopned here https://github.com/keras-team/keras-cv/issues/1233 with PR https://github.com/keras-team/keras-cv/pull/1234. Closing.

**Comment by DavidLandup0** [comment]
My bad - I didn't see we already had an issue. I can close mine and we can reopen this one

**Comment by innat** [comment]
No need, please continue with your PR. :)
