### ISSUE TITLE
Current roadmap & GSoC'23

### ISSUE THREAD

**Issue by shivance** [keras-team/keras-cv#1242]
KerasCV is witnessing growing usage after it's release of fast implementation of stable diffusion models. Library participated in GSoC'22 and hosted projects that added a lot of valuable code here.

I'm interested in contributing here under GSoC'23. I have seen that prior contributions increase chances of selection, which brings me here opening this issue.

1. What's the current roadmap? What are some features, model that are on to-do priority list.
2. I see a lot of old issuess still open (eg. inceptionet v4, EfficientDet) are they stale because they are not currently on the roadmap.

I believe that solving issues related to current roadmap will actual value to kerasCV. Looking forward to contributing here. 

**cc** : @tanzhenyu , @ianstenbit , @LukeWood

**Comment by tanzhenyu** [comment]
Hi Anshuman,
Thanks for the interest!
The roadmap can be viewed [here](https://github.com/keras-team/keras-cv/blob/master/.github/ROADMAP.md).
issues opened and labeled contribution welcome are still active
