### ISSUE TITLE
Supporting GIOU Loss

### ISSUE THREAD

**Issue by tanzhenyu** [keras-team/keras-cv#1244]
Reference:
https://arxiv.org/abs/1902.09630

Today this exist in TF Addons. It is highly related to detection task and we should consider adding it

**Comment by quantumalaviya** [comment]
There is already an Approved PR for this #1006.

**Comment by quantumalaviya** [comment]
Can this be merged now btw @LukeWood? I will add the Step 2 once this is merged.

**Comment by LukeWood** [comment]
> Can #1006 be merged now btw @LukeWood? I will add the Step 2 once this is merged.

does https://github.com/keras-team/keras-cv/pull/1121 impact this at all?  If so I'd like to merge https://github.com/keras-team/keras-cv/pull/1121 as its already been rebased a LOT of times.

**Comment by quantumalaviya** [comment]
Hmm, I think it would be similar to the minor changes in the IoU loss? Since we're only passing boxes to it, we don't have to worry about the format being a dictionary. 

But sure, we can wait for #1121 to be merged.

**Comment by LukeWood** [comment]
> Hmm, I think it would be similar to the minor changes in the IoU loss? Since we're only passing boxes to it, we don't have to worry about the format being a dictionary.

Feel free to rebase, should be good to go.

**Comment by bhack** [comment]
Can we close this?

**Comment by sachinprasadhs** [comment]
Closing this based on the above linked PRs and comments and there is no pending action item. 
Comment down if there is any pending action item, I can reopen the issue. Thanks!
