### ISSUE TITLE
Rename scaling_factor_* to *_factor in GlobalScaling

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#1248]
https://github.com/keras-team/keras-cv/blob/master/keras_cv/layers/preprocessing3d/global_random_scaling.py#L54

This is currently inconsistent with the other KerasCV layers

**Comment by SauravMaheshkar** [comment]
Can I take this up ?

**Comment by ianstenbit** [comment]
Thanks @SauravMaheshkar! I'm closing them now
