### ISSUE TITLE
Rename `bounding_box.preserve_rel()`

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#1262]
maybe we name this, "match_rel"?  

@tanzhenyu and @ianstenbit both had questions about the usage of the API, so that indicates a need for a rename

**Comment by ianstenbit** [comment]
I think no matter what we rename this to, it's going to be confusing.

What if we add 3 util methods (open to other names for them):
`is_relative(bounding_box_format)`
`as_relative(bounding_box_format)`
`as_absolute(bounding_box_format)`

The code gets a bit more verbose but way easier to understand (including the motivation for why we do this in the first place:

```
compute_box_format = "yxyx"
if is_relative(input_box_format):
    compute_box_format = as_relative(compute_box_format)
```

**Comment by bhack** [comment]
If/when we [will have a bbox class](https://github.com/keras-team/keras-cv/issues/1252) an alternative could be to have these as methods.
