### ISSUE TITLE
Add YOLO v8

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#1263]
**Short Description**

Reposting from [here](https://github.com/keras-team/keras-cv/issues/1179#issuecomment-1379499023). YOLOv8 is out, by Ultralytics who also build YOLOv5. 

- Docs. https://docs.ultralytics.com/
- Code https://github.com/ultralytics/ultralytics
- Blog https://blog.roboflow.com/whats-new-in-yolov8/

**Papers**

I think, same as YOLOv5, it doesn't have [paper](https://github.com/ultralytics/ultralytics/issues/204) yet. They chose to keep [eating their hat](https://github.com/ultralytics/yolov5/issues/1333#issuecomment-936818045).

**Comment by bhack** [comment]
Or V6 3.0 https://github.com/meituan/YOLOv6 ?

**Comment by innat** [comment]
... overwhelmed, too many yolo. -_-

**Comment by IMvision12** [comment]
Do we have any research papers for V6 or V8??

**Comment by IMvision12** [comment]
@LukeWood can you assign this issue to me I am nearly completed converting yolov8 to tensorflow

**Comment by ianstenbit** [comment]
(Closed because YOLOV8 for OD is now included)
