### ISSUE TITLE
Wrong contributing documentation string on readme

### ISSUE THREAD

**Issue by MrinalTyagi** [keras-team/keras-cv#1268]
I have been trying to build from source on macOS (Intel) but finding it difficult to install on macOS. Also, the doc string on the main readme for contributing has an issue that might make build from source difficult for beginners. 

![image](https://user-images.githubusercontent.com/21031150/212328943-a12ea011-265c-4d0e-a88a-a71d6783728f.png)
In place of 
`pip install wheels/keras-cv-*.whl` 
it should be
`pip install wheels/keras_cv-*.whl`

as the wheel that gets build is of format keras_cv.

**Comment by MrinalTyagi** [comment]
@LukeWood @bhack @tanzhenyu Do provide your valuable feedback on this.

**Comment by bhack** [comment]
Can you send a small PR?

**Comment by bhack** [comment]
@ianstenbit

**Comment by ianstenbit** [comment]
Looks like this was fixed by #1284 
thank you Mrinal!
