### ISSUE TITLE
IoU and GIoU losses should support a way to reduce over NO axes

### ISSUE THREAD

**Issue by quantumalaviya** [keras-team/keras-cv#1273]
A [duplicate issue](https://github.com/keras-team/keras/issues/17207) exists in the Keras repo.

This is required for YoloX and was originally covered in #1006 with an approach suggested by @LukeWood([here](https://github.com/keras-team/keras-cv/pull/1006#discussion_r1020450632)). 

However, this was removed as per a recent review by @tanzhenyu.

**Comment by tanzhenyu** [comment]
Thanks for documenting it! Yeah we should find a unified way for KerasCV & Keras on this, I think it'd be useful

**Comment by LukeWood** [comment]
lets try to merging something into `backend.mean()` to support this.  I'll raise this with Francois in our 1:1

**Comment by LukeWood** [comment]
@quantumalaviya as a workaround lets just call expand_dims(axis=-1) in the `train_step()` of YOLOx right before computing loss in the meantime.  Does that sound good?
