### ISSUE TITLE
Getting Import Error

### ISSUE THREAD

**Issue by IMvision12** [keras-team/keras-cv#1277]
I was running some test files locally but I am facing this error
ImportError: cannot import name 'compute_pycoco_metrics' from 'keras_cv.metrics.coco' (keras-cv\keras_cv\metrics\coco\__init__.py)

does the imports in pycoco_callback.py `from keras_cv.metrics.coco import compute_pycoco_metrics` is wrong?
@tanzhenyu

**Comment by LukeWood** [comment]
Thanks for the bug report, I'll check it out!

**Comment by arnavrneo** [comment]
@LukeWood Don't you think an import statement (`from keras_cv.metrics.coco.pycoco_wrapper import compute_pycoco_metrics`) is missing in `__init__.py` of `metrics` directory.

**Comment by bhack** [comment]
Why the CI tests are not broken?

**Comment by tomrtk** [comment]
> Why the CI tests are not broken?

looks to be because in CI it installs the `test` extras, where `pycocotools` is pulled in. 

https://github.com/keras-team/keras-cv/blob/742fa2caa34b2f5772510955a22ec5e0ceeda2be/.github/workflows/actions.yml#L36

Installing `pycocotools` fixes the import errors, so it should maybe be added as a dependencie in `setup.py`?

**Comment by bhack** [comment]
Or we need to mark some tests as requiring extra.

**Comment by bhack** [comment]
@ianstenbit Is the contribution guide aligned with the CI receipt?

**Comment by ianstenbit** [comment]
> @ianstenbit Is the contribution guide aligned with the CI receipt?

@bhack I'm not sure I understand the question -- can you elaborate? By my understanding, #1279 should fix this

**Comment by bhack** [comment]
I meant are we executing these tests subset in the CI without these dependencies installed? Do we supposed that the contributor devenv could have these not installed following our Contributing makrdown?
