### ISSUE TITLE
Error executing keras_cv.datasets.pascal_voc.load() to get dataset for Object Detection

### ISSUE THREAD

**Issue by kechan** [keras-team/keras-cv#1278]
Following along this notebook on google colab:

https://keras.io/guides/keras_cv/retina_net_overview/

This failed at 

```
dataset, dataset_info = keras_cv.datasets.pascal_voc.load(
    split="train", bounding_box_format="xywh", batch_size=BATCH_SIZE
)
```

Error:

ValueError: in use

> ValueError: in user code:
> 
>     File "/usr/local/lib/python3.8/dist-packages/keras_cv/datasets/pascal_voc/load.py", line 39, in apply  *
>         bounding_boxes = bounding_box.convert_format(
>     File "/usr/local/lib/python3.8/dist-packages/keras_cv/bounding_box/converters.py", line 361, in convert_format  *
>         raise ValueError(
> 
>     ValueError: Expected `boxes` to be a Tensor with a final dimension of `4`. Instead, got `boxes.shape=(None, 5)`.

I think the last dim of 5 of the input box came from concat of the labels onto the bounding boxes in during .load, where the convert_format method doesn't expect this.

How is this supposed to work, if it had worked before. This is the first time I ran this and new to keras-cv in general.

**Comment by kechan** [comment]
I wrote some code to workaround the above issue. But got more and more errors. I think this notebook is completely broken when tried on Colab.

**Comment by bhack** [comment]
I think the main issue it that we are not regularly testing Notebook in the CI.

**Comment by kechan** [comment]
@bhack It seemed to be the case. The tutorial notebook was written last summer but it seemed keras_cv probably still in early dev. It seemed the dataset spec has changed for bounding boxes and the keras_cv.datasets.pascal_voc.load(...) didn't get the update. 

there are some *_demo.py under the examples directory. it looked like it was just updated 5 days ago so I assume they should be better than following the notebook.

**Comment by tomrtk** [comment]
I got the same error when testing the `examples/training/object_detection/pascal_voc/retina_net.py` example after getting similar errors in my code after updating to `v0.4.1`. 
Changing to the new dict format for bounding boxes as described in #1121 helped, but I am now trying to find out why I get `Incompatible shape` errors in box loss.

**Comment by bhack** [comment]
We have the same issue there as I don't think that examples are covered by CI so we are always at risk to be misaligned and we rely only to the reviewer attention to check these kind of effects.

**Comment by LukeWood** [comment]
> Following along this notebook on google colab:
> 
> https://keras.io/guides/keras_cv/retina_net_overview/
> 
> This failed at
> 
> ```
> dataset, dataset_info = keras_cv.datasets.pascal_voc.load(
>     split="train", bounding_box_format="xywh", batch_size=BATCH_SIZE
> )
> ```
> 
> Error:
> 
> ValueError: in use
> 
> > ValueError: in user code:
> > ```
> > File "/usr/local/lib/python3.8/dist-packages/keras_cv/datasets/pascal_voc/load.py", line 39, in apply  *
> >     bounding_boxes = bounding_box.convert_format(
> > File "/usr/local/lib/python3.8/dist-packages/keras_cv/bounding_box/converters.py", line 361, in convert_format  *
> >     raise ValueError(
> > 
> > ValueError: Expected `boxes` to be a Tensor with a final dimension of `4`. Instead, got `boxes.shape=(None, 5)`.
> > ```
> 
> I think the last dim of 5 of the input box came from concat of the labels onto the bounding boxes in during .load, where the convert_format method doesn't expect this.
> 
> How is this supposed to work, if it had worked before. This is the first time I ran this and new to keras-cv in general.

Sorry about this inconsistency!  I’m working on updating the guide to get rid of this reference now.  The loader function is outdated

I will tell you when the update is complete and point you back to the guide.

for now please see the examples/ directory!

**Comment by kechan** [comment]
I followed along the code at

https://github.com/keras-team/keras-cv/blob/2831784d507bcc80af33f091574a133638342bf1/examples/training/object_detection/pascal_voc/retina_net.py#L238

There's still a "bug" in proc_train_fn(...) where keras_cv.bounding_box.convert_format(...) again doesn't like the class addendum (resulting in last dim == 5) somewhere. I changed the code such that the concat is done AFTER the .convert_format(...). I hope this is fine. I went ahead and the training worked finally. 

Thanks for tracking the inconsistency.

**Comment by LukeWood** [comment]
@kechan thanks for the report - raised a fix.
