### ISSUE TITLE
Any plan on using python type hint throughout this project?

### ISSUE THREAD

**Issue by kechan** [keras-team/keras-cv#1280]
I have seen this done in other framework, such as those from huggingface. I found them to be highly useful when reading the code, particularly just browsing something without a runtime env.

I believe these hints are not only for human, they are also great for LLM (like GItHub copilot) to generate/predict better code.

**Comment by LukeWood** [comment]
> I have seen this done in other framework, such as those from huggingface. I found them to be highly useful when reading the code, particularly just browsing something without a runtime env.
> 
> I believe these hints are not only for human, they are also great for LLM (like GItHub copilot) to generate/predict better code.

We’ve discussed this across the keras team pretty extensively.  This is something that we want to keep consistent across all of our code bases. 

As of now we believe simple, optional type hints to be ok but we do not want to maintain long lists of custom types/more complex specs using unions etc.  

Maybe this will change in the future but as of now we’re keeping the status quo
