### ISSUE TITLE
Switching implementation to a generalized format

### ISSUE THREAD

**Issue by MrinalTyagi** [keras-team/keras-cv#1294]
**Short Description**

Most of the implementation present for CSPNet and Spatial Pyramidal Pooling layer is present more towards a specific use case, i.e. here being the DarkNet. In my opinion, I feel the implementation should be generalized. As we are creating those layers in the library, it should be built in such a manner that user is able to switch to their own new implementation without much hassle. Want to move in this direction to clean up the code as CSPDarknet and YOLO v7 both require Spatial Pyramidal Pooling Layer as well as Cross Stage Partial Layer, and I feel there is no point in creating two almost similar implementations, thereby clustering the code. 

Would like to get everyone's feedback on this. @bhack @ianstenbit @LukeWood @quantumalaviya

**Comment by LukeWood** [comment]
Personally I do not have the deep knowledge of these layers and their functionality required to come up with a highly generic abstraction --- but @quantumalaviya may.  He's currently focusing on finishing YOLOx, so perhaps we refactor these after we ensure YOLOx has proper numeric results?

**Comment by quantumalaviya** [comment]
I agree. It would be easier to add this after YoloX. 
If you can pick this up, feel free to include this in the YoloV7 PR @MrinalTyagi. I will create a PR to add a test that makes sure that the parameters stay the same for the YoloX internal layers after the change.

**Comment by ianstenbit** [comment]
We're generally moving forward with the principle that it's better to allow models to have their own custom e.g. FPN, LabelEncoder, TransformerEncoder, because trying to make things generic has resulted in some ugly and hard-to-use APIs
