### ISSUE TITLE
Implement Stochastic Depth layer

### ISSUE THREAD

**Issue by sayakpaul** [keras-team/keras-cv#130]
Stochastic Depth [1] is used for regularization used to randomly drop layer path connections during training. It's used in many modern neural architectures (ConvNeXt [2] for example). So, I believe it'd be a good addition. 

**References**

[1] https://arxiv.org/abs/1603.09382
[2] https://arxiv.org/abs/2201.03545

**Comment by sayakpaul** [comment]
I'd be keen to work on this one.

**Comment by LukeWood** [comment]
A reference implementation: https://www.tensorflow.org/addons/api_docs/python/tfa/layers/StochasticDepth

@qlzh727 @fchollet what do you guys think?  I'd be on board to accept this given its presence in many modern ConvNet architectures.

**Comment by innat** [comment]
https://github.com/tensorflow/models/blob/229e43e8b4578f4e69e02b35a5b33e655b6be3e8/official/vision/beta/modeling/layers/nn_layers.py#L227

**Comment by sebastian-sz** [comment]
I am a bit confused regarding this layer naming:

It seems like the names `DropPath` and `StochasticDepth` are used interchangeably, but their implementations should be different?

For example:

Drop path in `tensorflow/tpu`: [link](https://github.com/tensorflow/tpu/blob/b24729de804fdb751b06467d3dce0637fa652060/models/official/amoeba_net/network_utils.py#L164)
Drop path in `timm`: [link](https://github.com/rwightman/pytorch-image-models/blob/7c67d6aca992f039eece0af5f7c29a43d48c00e4/timm/models/layers/drop.py#L135)

is completely different from StochasticDepth in [Tensorflow Addons](https://github.com/tensorflow/addons/blob/8cec33fcaaf1cf90aec7bdd55a0fcdbb251ce5c2/tensorflow_addons/layers/stochastic_depth.py#L61)

**Comment by sayakpaul** [comment]
From `timm` docstrings:

```
"""Drop paths (Stochastic Depth) per sample (when applied in main path of residual blocks).
    This is the same as the DropConnect impl I created for EfficientNet, etc networks, however,
    the original name is misleading as 'Drop Connect' is a different form of dropout in a separate paper...
    See discussion: https://github.com/tensorflow/tpu/issues/494#issuecomment-532968956 ... I've opted for
    changing the layer and argument names to 'drop path' rather than mix DropConnect as a layer name and use
    'survival rate' as the argument.
    """
```

**Comment by sebastian-sz** [comment]
@sayakpaul sounds right. So, from what I understand
*  `DropPath` is a modification of `StochasticDepth` used in EfficientNet.
* Original `StochasticDepth` operates on batches, while `DropPath` operates on samples.
* `DropPath` introduces some additional operations (`tf.div`) in train time to simplifly the layer during test time.

Unless I misunderstood something. This comment explains it in more detail: https://github.com/tensorflow/tpu/issues/494#issuecomment-559819818 (by `DropConnect` they mean `DropPath` there).

**Comment by sayakpaul** [comment]
Sounds right except this:

> DropPath introduces some additional operations (tf.div) in train time to simplifly the layer during test time.

I didn't fully understand it.

**Comment by sebastian-sz** [comment]
In the original `StochasticDepth` implementation the values had to be rescaled during test time. `DropPath` introduced some modifications so that it's no longer needed.

I think this comment by the authors explains it better:
https://github.com/tensorflow/tpu/blob/cd433314cc6f38c10a23f1d607a35ba422c8f967/models/official/efficientnet/utils.py#L157

**Comment by sayakpaul** [comment]
Thanks!
