### ISSUE TITLE
stability of keras cv

### ISSUE THREAD

**Issue by Suzan009** [keras-team/keras-cv#1323]
keras cv is (lightly) documented in keras io. but the API is still consistently changing. And also many pr and issue is still eitheir untouch or slow in progress. When will be keras cv stable for end user? In contrast, keras nlp is much better in shape and consistently progressing.

**Comment by Suzan009** [comment]
Also https://github.com/keras-team/keras-cv/discussions/1184

**Comment by jbischof** [comment]
Thanks for reaching out @Suzan009! We are actually planning a convergence of the KerasCV and NLP APIs that should solve the issue in the next few months. Once we are confident about the API we will offer a [Getting Started guide](https://keras.io/guides/keras_nlp/getting_started/) and other docs similar to KerasNLP's.

**Comment by LukeWood** [comment]
Closing for now, we will do a pretty broad PR push once we feel our API is stable.
