### ISSUE TITLE
Data augmentation: Image swap layer

### ISSUE THREAD

**Issue by vladb99** [keras-team/keras-cv#1329]
Hello, I am trying to implement a custom data augmentation layer, where 'augment_image' method gets also a file path and swaps the input image with the image at file path. Is this possible to do with 'BaseImageAugmentationLayer'?
Thanks!

**Comment by LukeWood** [comment]
hey vlad.  I think we need some more information here.

Can you encode the file path into get_random_transformation()?

**Comment by LukeWood** [comment]
Closing, but feel free to re-open if you would like to provide more info!
