### ISSUE TITLE
Fix ConvMixer

### ISSUE THREAD

**Issue by IMvision12** [keras-team/keras-cv#1334]
Point Given by @DavidLandup0 :

- There's a typo in the `ConvMixer_Layer` (it's currently `CovnMixer_Layer`)
- This name should probably be `ConvMixerLayer` without the underscore to adhere to all other models we have
- We already have a public API layer for patching and embedding, while this model defines its own

Question : when we talk about existing PatchingAndEmbedding layers, are we referring about Vit's PatchingAndEmbedding Layer?

@DavidLandup0 @LukeWood

**Comment by LukeWood** [comment]
Thank you!
