### ISSUE TITLE
Give `vit_layers` their own  files

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#1338]
Keras convention is one component per file when possible - we should abide.

**Comment by IMvision12** [comment]
@LukeWood, could you perhaps elaborate on what is expected? what changes needs to be done?

**Comment by YimjuneLiu** [comment]
Hi @LukeWood @IMvision12 , Would you mind if I joined the job?

**Comment by IMvision12** [comment]
Yeah Sure, you can go ahead with a PR!!

**Comment by YimjuneLiu** [comment]
> Yeah Sure, you can go ahead with a PR!!

Thanks!

**Comment by YimjuneLiu** [comment]
Hi @LukeWood ,  I found that vit_layers is already in 'layers' folder, can you explain in detail what it does?
