### ISSUE TITLE
Remove redundant call to `compile` in `RetinaNet`

### ISSUE THREAD

**Issue by jbischof** [keras-team/keras-cv#1339]
`RetinaNet.compile()` chains to super twice. We can remove the first call ([link](https://github.com/keras-team/keras-cv/blob/5227e52147343232a2183fefec1d31ed4c655079/keras_cv/models/object_detection/retina_net/retina_net.py#L283)).

**Comment by soma2000-lang** [comment]
@jbischof Please assign me this
