### ISSUE TITLE
JpegCompression preprocessing layer

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#135]
Ref. https://www.tensorflow.org/api_docs/python/tf/image/random_jpeg_quality

**Comment by LukeWood** [comment]
That's an interesting idea.

Do you know of any empirical data/papers on this technique?  It would be good to see some data on how useful it is.

**Comment by bhack** [comment]
Not a so strong impact:
https://arxiv.org/abs/2007.14314

https://www.nature.com/articles/s41598-021-86726-w

**Comment by bhack** [comment]
Probably a little bit more in:
https://arxiv.org/abs/2011.08932

**Comment by LukeWood** [comment]
Yeah, if we can't find any references showing that this is in fact a useful augmentation I'm not 100% sure we want to add it.  That doesn't mean there aren't any references but I'd like to find some strong ones first showing that this does in fact help.  https://arxiv.org/abs/2011.08932 seems to point out a valid use case... I'm still not 100% convinced though

**Comment by LukeWood** [comment]
On the other hand, this layer is trivial to implement so maybe it is worth having.

**Comment by LukeWood** [comment]
ok, happy to take this.  we can implement this.  Feel free to use BaseImageAugmentationLayer - an example in https://github.com/keras-team/keras-cv/runs/5633736287?check_suite_focus=true

**Comment by qlzh727** [comment]
I feel this is more useful as a util function to compress the jpeg input, but I am not sure how this is fitting for model, eg compress tensor doesn't actually reduce the amount of data sending to the model. And also from the paper, the heavy compressed data does affect the model performance.

**Comment by LukeWood** [comment]
Comments per an offline conversation:

so the layer is RandomJpegQuality - and it will create jpeg artifacts randomly by actually performing jpeg compression to a random quality - it is simulating the effects of compression, not actually attempting to compress.

**Comment by artu1999** [comment]
Is anyone working on this? Happy to take on it.

**Comment by innat** [comment]
@artu1999 don't worry, just send the PR.
