### ISSUE TITLE
module 'keras_cv.layers' has no attribute 'MultiClassNonMaxSuppression'

### ISSUE THREAD

**Issue by arnavrneo** [keras-team/keras-cv#1351]
I'm trying to use `MultiClassNonMaxSuppression` but whenever I try to import it, it gives an `Attribute Error`:

```python
AttributeError: module 'keras_cv.layers' has no attribute 'MultiClassNonMaxSuppression'
```
My import statement is:

```python
from keras_cv import layers as cv_layers

layer = cv_layers.MultiClassNonMaxSuppression(
        bounding_box_format="xyxy",
        from_logits=True,
        max_detections=100,
)
```

- I've repeated the same in Github Codespaces as well as in Google Colab but the error is still there.

**Comment by ianstenbit** [comment]
Hi @arnavrneo -- sorry for this!

We updated our API example too early, and the 0.4.2 release which updates the name of this API isn't out yet.

In the meantime, you can use this layer by installing from Git using
`pip install git+https://github.com/keras-team/keras-cv.git@master`

**Comment by arnavrneo** [comment]
Oh, no worries! I'll install it from Git.
