### ISSUE TITLE
Raise a helpful error message from OD models when receiving a Ragged image input

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#1359]
Currently the error message is very arcane.  We can remedy this and greatly boost the UX.

We can instruct users to use:

- JitteredResize()
- Resizing(pad_to_aspect_ratio=True)

**Comment by IMvision12** [comment]
So basically we just need to add this?

```
if isinstance(images, tf.RaggedTensor):
    raise ValueError(
                "`RetinaNet` does not accept a `Ragged Input`"
                "Instead, please use `JitteredResize()` or `Resizing(pad_to_aspect_ratio=True)`"
            )
```
At line 320 of `retina_net.py`

**Comment by LukeWood** [comment]
> So basically we just need to add this?
> 
> ```
> if isinstance(images, tf.RaggedTensor):
>     raise ValueError(
>                 "`RetinaNet` does not accept a `Ragged Input`"
>                 "Instead, please use `JitteredResize()` or `Resizing(pad_to_aspect_ratio=True)`"
>             )
> ```
> 
> At line 320 of `retina_net.py`

yes sir!  We could workshop the message a bit but correct.

**Comment by IMvision12** [comment]
Okay will send a PR!!
