### ISSUE TITLE
[Remove] You do not have Waymo Open Dataset installed, so KerasCV Waymo metrics are not available.

### ISSUE THREAD

**Issue by ayulockin** [keras-team/keras-cv#1360]
KerasCV version: 0.4.2

When importing KerasCV (import keras_cv as kcv`), I get this warning message `You do not have Waymo Open Dataset installed, so KerasCV Waymo metrics are not available`. This warning is only necessary if someone is willing to use Waymo metrics. Getting this message at the package import level is unnecessary IMO.

cc: @LukeWood

**Comment by bhack** [comment]
https://github.com/keras-team/keras-cv/pull/1279#issuecomment-1383321291

**Comment by ayulockin** [comment]
Closing in favor of the comment.

**Comment by LukeWood** [comment]
Thanks for the error report.

Working on making this only occur when using those components.
