### ISSUE TITLE
The `_sample_from_beta` function is incorrect

### ISSUE THREAD

**Issue by JoaoMarcosCSilva** [keras-team/keras-cv#1361]
Hi there!
I believe that the `_sample_from_beta` function that is used in various preprocessing layers (e.g. [here](https://github.com/keras-team/keras-cv/blob/c8064e64043a35360e42023be2f411c9f5520b29/keras_cv/layers/preprocessing/mix_up.py#L50)) is not parameterized correctly:

```python
def _sample_from_beta(self, alpha, beta, shape):
    sample_alpha = tf.random.gamma(
        shape, 1.0, beta=alpha, seed=self._random_generator.make_legacy_seed()
    )
    sample_beta = tf.random.gamma(
        shape, 1.0, beta=beta, seed=self._random_generator.make_legacy_seed()
    )
    return sample_alpha / (sample_alpha + sample_beta)
```

The `alpha` and `beta` parameters of the beta distribution are passed to the inverse scale parameter (here called beta) of the gamma distribution. However, I believe they should be passed to the shape parameter (called alpha), as is done, for instance, in the `_sample_from_dirichlet` function defined [here](https://github.com/keras-team/keras-cv/blob/c8064e64043a35360e42023be2f411c9f5520b29/keras_cv/layers/preprocessing/aug_mix.py#L101):
```python
def _sample_from_dirichlet(self, alpha):
    gamma_sample = tf.random.gamma(
        shape=(), alpha=alpha, seed=self._random_generator.make_legacy_seed()
    )
    return gamma_sample / tf.reduce_sum(gamma_sample, axis=-1, keepdims=True)
```
In [this](https://colab.research.google.com/drive/12j1BkbFuwj7TmyEIEBD1oKxu1_grCX_1?usp=sharing) notebook I plot some samples from Beta(0.4, 0.4) and show that this function returns what seems to be uniformly distributed values:
![image](https://user-images.githubusercontent.com/40339986/217009281-8ae1a813-9ed7-4e52-a556-4c82adf15b12.png)

If the function instead passes the parameters to the alpha argument of `tf.random.gamma`, the results are distributed correctly:
![image](https://user-images.githubusercontent.com/40339986/217009622-48d90c26-02af-4b80-9dc4-90e53ac56890.png)

**Comment by LukeWood** [comment]
Thank you for the error report @JoaoMarcosCSilva !  Would you be willing to send a fix?

**Comment by JoaoMarcosCSilva** [comment]
Sure! I can do it later today

**Comment by LukeWood** [comment]
Thanks!!!
