### ISSUE TITLE
Vectorize RandomContrast

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#1376]
Based on PR https://github.com/keras-team/keras-cv/pull/1373 we would like to vectorize RandomContrast.

One issue with this is that `tf.image.adjust_contrast()` does not accept a batch argument for contrast adjustment, so we'll have to roll a pure TF version.

**Comment by bhack** [comment]
Is there a bug in `RandomContrast`? Check https://github.com/keras-team/keras-cv/issues/1382#issuecomment-1424267401
