### ISSUE TITLE
Standardize preprocessing call signature

### ISSUE THREAD

**Issue by bhack** [keras-team/keras-cv#138]
https://github.com/keras-team/keras-cv/pull/124#discussion_r806759607

`grep -R "def call(" *`
```
keras_cv/layers/preprocessing/grayscale.py:    def call(self, images, training=None):
keras_cv/layers/preprocessing/mix_up.py:    def call(self, images, labels, training=True):
keras_cv/layers/preprocessing/random_cutout.py:    def call(self, inputs, training=True):
keras_cv/layers/preprocessing/solarization.py:    def call(self, images):
keras_cv/layers/preprocessing/cut_mix.py:    def call(self, images, labels, training=True):
keras_cv/layers/preprocessing/grid_mask.py:    def call(self, images, training=None):
keras_cv/layers/preprocessing/equalization.py:    def call(self, images):
```

Do we want to standardize over `images` or `inputs`?

**Comment by chjort** [comment]
I agree we should standardize the signature. I think this should include both argument names, but also argument rank. I.e. I think we should decide on either `images` or `inputs`, but I also think we should standardize whether layers should expect 4D inputs only, or expect both 4D and 3D inputs.

**Comment by LukeWood** [comment]
Good catch :) 

we're working on a base augmentation layer that will resolve this.

**Comment by qlzh727** [comment]
FYI, the BaseImageAugmentationLayer is proposed in https://github.com/keras-team/keras/commit/9628af85a0a2cb04cf433b1ad991017b70ae2005

**Comment by qlzh727** [comment]
We will make it available as public API soon.

**Comment by LukeWood** [comment]
Once: https://github.com/keras-team/keras/pull/16130 

lands in nightly we can begin using it.  I will begin migrating layers to use it.

**Comment by qlzh727** [comment]
The BaseImageAugmentationLayer is available as Keras internal API for keras CV to use.

**Comment by qlzh727** [comment]
https://github.com/keras-team/keras/pull/16130
