### ISSUE TITLE
Quickstart example crashes most colab runtimes (>30GB RAM)

### ISSUE THREAD

**Issue by jbischof** [keras-team/keras-cv#1380]
When I ran the quickstart example it OOM'd a regular colab and barely runs on a premium colab runtime. Why does it require >30GB of RAM to run? Is this a good "quick start"? 

See the [Gist](https://colab.research.google.com/gist/jbischof/30562af9a2f83d27719053199f845dda/resnetv2-quickstart.ipynb)

<img width="424" alt="Screenshot 2023-02-08 at 7 43 34 PM" src="https://user-images.githubusercontent.com/1141045/217712509-1a06f8c8-3319-496b-9089-9d4e2eb1d381.png">

**Comment by LukeWood** [comment]
> When I ran the quickstart example it OOM'd a regular colab and barely runs on a premium colab runtime. Why does it require >30GB of RAM to run? Is this a good "quick start"?
> 
> See the [Gist](https://colab.research.google.com/gist/jbischof/30562af9a2f83d27719053199f845dda/resnetv2-quickstart.ipynb)
> 
> <img alt="Screenshot 2023-02-08 at 7 43 34 PM" width="424" src="https://user-images.githubusercontent.com/1141045/217712509-1a06f8c8-3319-496b-9089-9d4e2eb1d381.png">

I guess we should swap to a smaller network + batch size.  The history with DenseNet is that it was our first pretrained model, but no strong attachment.

**Comment by jbischof** [comment]
Fixed by #1379
