### ISSUE TITLE
Add MobileNet V1 and V2

### ISSUE THREAD

**Issue by james77777778** [keras-team/keras-cv#1381]
**Short Description**
MobileNet V1 and V2 (especially V2 variant) are widely adopted as feature backbone for mobile deployment.

**Papers**
[MobileNets: Efficient Convolutional Neural Networks for Mobile Vision Applications](https://arxiv.org/abs/1704.04861)
[MobileNetV2: Inverted Residuals and Linear Bottlenecks](https://arxiv.org/abs/1801.04381) (CVPR 2018)

**Existing Implementations**
MobileNetV1 in keras applications: [link](https://github.com/keras-team/keras/blob/v2.11.0/keras/applications/mobilenet.py)
MobileNetV2 in keras applications: [link](https://github.com/keras-team/keras/blob/v2.11.0/keras/applications/mobilenet_v2.py)

My current implementation:
[mobilenet_v1.py](https://github.com/james77777778/keras-cv/blob/master/keras_cv/models/mobilenet_v1.py)
[mobilenet_v1_test.py](https://github.com/james77777778/keras-cv/blob/master/keras_cv/models/mobilenet_v1_test.py)
[mobilenet_v2.py](https://github.com/james77777778/keras-cv/blob/master/keras_cv/models/mobilenet_v2.py)
[mobilenet_v2_test.py](https://github.com/james77777778/keras-cv/blob/master/keras_cv/models/mobilenet_v2_test.py)

**Other Information**
I have tested the implementation by following standalone script:

For MobileNetV1
<details>

```python
import tensorflow as tf
from keras.applications import MobileNet as KerasMobileNetV1

from keras_cv.models.mobilenet_v1 import MobileNetV1

TEST_CONFIGS = [
    {"input_shape": (224, 224, 3), "include_top": True, "classes": 1000, "alpha": 1.0},
    {"input_shape": (224, 224, 3), "include_top": True, "classes": 1000, "alpha": 0.75},
    {"input_shape": (224, 224, 3), "include_top": True, "classes": 1000, "alpha": 0.5},
    {
        "input_shape": (224, 224, 3),
        "include_top": False,
        "pooling": "avg",
        "classes": 1000,
        "alpha": 1.0,
    },
    {
        "input_shape": (224, 224, 3),
        "include_top": False,
        "pooling": "avg",
        "classes": 1000,
        "alpha": 0.75,
    },
    {
        "input_shape": (224, 224, 3),
        "include_top": False,
        "pooling": "avg",
        "classes": 1000,
        "alpha": 0.5,
    },
]

for i, config in enumerate(TEST_CONFIGS):
    keras_model: tf.keras.Model = KerasMobileNetV1(weights="imagenet", **config)
    kerascv_model = MobileNetV1(include_rescaling=False, **config)
    if i == 0:
        kerascv_model.summary()

    # set
    kerascv_model.set_weights(keras_model.get_weights())

    # check output
    x = tf.random.uniform((1, 224, 224, 3))
    keras_model_output = keras_model.predict(x, batch_size=1)
    kerascv_model_output = kerascv_model.predict(x, batch_size=1)
    print(
        f"Equal output: {tf.assert_equal(keras_model_output, kerascv_model_output) is None}"
    )

```
</details>

For MobileNetV2
<details>

```python
import tensorflow as tf
from keras.applications import MobileNetV2 as KerasMobileNetV2

from keras_cv.models.mobilenet_v2 import MobileNetV2

TEST_CONFIGS = [
    {"input_shape": (224, 224, 3), "include_top": True, "classes": 1000, "alpha": 1.0},
    {"input_shape": (224, 224, 3), "include_top": True, "classes": 1000, "alpha": 0.5},
    {"input_shape": (224, 224, 3), "include_top": True, "classes": 1000, "alpha": 1.4},
    {
        "input_shape": (224, 224, 3),
        "include_top": False,
        "pooling": "avg",
        "classes": 1000,
        "alpha": 1.0,
    },
    {
        "input_shape": (224, 224, 3),
        "include_top": False,
        "pooling": "avg",
        "classes": 1000,
        "alpha": 0.5,
    },
    {
        "input_shape": (224, 224, 3),
        "include_top": False,
        "pooling": "avg",
        "classes": 1000,
        "alpha": 1.4,
    },
]

for i, config in enumerate(TEST_CONFIGS):
    keras_model: tf.keras.Model = KerasMobileNetV2(weights="imagenet", **config)
    kerascv_model = MobileNetV2(include_rescaling=False, **config)
    if i == 0:
        kerascv_model.summary()

    # set
    kerascv_model.set_weights(keras_model.get_weights())

    # check output
    x = tf.random.uniform((1, 224, 224, 3))
    keras_model_output = keras_model.predict(x, batch_size=1)
    kerascv_model_output = kerascv_model.predict(x, batch_size=1)
    print(
        f"Equal output: {tf.assert_equal(keras_model_output, kerascv_model_output) is None}"
    )

```
</details>

The reimplemented models can load weights from `keras.applications` and the output tensors are the same.

Please assign me for this PR if these implementations help.

**Comment by LukeWood** [comment]
Are there any cases MobileNetv2 or v1 outperform V3?

**Comment by james77777778** [comment]
I find a paper indicates that V1 and V2 outperforms V3:
[Real-time Monocular Depth Estimation with Sparse Supervision on Mobile](https://arxiv.org/abs/2105.12053) (CVPR 2021 Mobile AI (MAI) Workshop)

|Model|RMSE⬇|delta1⬆|
|-|-|-|
|FastDepth (MobileNetV1)|0.599|0.775|
|MobileNetV2|0.583|0.775|
|MobileNetV3|0.607|0.749|

Actually, I'm working on monocular depth estimation and there are some papers using MobileNetV1 and V2 as their mobile deployment. (But most of them didn't provide the comparison between V1, V2 and V3)

- [FastDepth: Fast Monocular Depth Estimation on Embedded Systems](https://arxiv.org/abs/1903.03273)
- [From Big to Small: Multi-Scale Local Planar Guidance for Monocular Depth Estimation](https://arxiv.org/abs/1907.10326)

It will be more easy to reproduce their results by providing these famous mobile backbones.

**Comment by LukeWood** [comment]
good to know, yeah seems reasonable to include if this is the case.  This is more or less the same reason we have ResNetv1 too - it is a better backbone for OD than v2 for some reason even though nobody fully knows why.

**Comment by james77777778** [comment]
Also, MobileNetV1 and V2 are more easy to do quantization-aware training (QAT).
MobileNetV3 with `minimalistic==True` needs a lot of effort to do QAT due to Squeeze-and-Excite, HardSigmoid and HardSwish...
(extra info: https://github.com/tensorflow/models/tree/master/official/projects/qat/vision/modeling/layers)

**Comment by ianstenbit** [comment]
Closing since the PR was closed and this isn't high-priority.
