### ISSUE TITLE
Vectorize Auto Contrast.

### ISSUE THREAD

**Issue by sebastian-sz** [keras-team/keras-cv#1382]
**Short Description**
Testing the water with this issue as https://github.com/keras-team/keras-cv/pull/1373 is merged.

How do you feel about migrating more layers to use vectorized approach? Below is a simple performance comparison of vectorized vs current. 

EDIT: misclick and submitted the issue too early...

Eager performance is better.  
Graph performance is the same.
![Eager performance](https://user-images.githubusercontent.com/58402418/217739788-f412da2e-a43b-45ea-a68d-20548e52d3f8.png)
![Graph performance](https://user-images.githubusercontent.com/58402418/217739805-aeea4594-ead8-427b-af7b-594f9e4b43e7.png)

**Comment by bhack** [comment]
Can you do the same with `RandomContrast`? Thanks

**Comment by sebastian-sz** [comment]
@bhack Similar behaviour:
1. Eager: vectorized is quite faster
2. Graph (tf.function): similar, but this time original is a bit faster.
3. Graph (XLA): similar, but vectorized is a bit faster.
![Random Contrast - eager](https://user-images.githubusercontent.com/58402418/217828055-4ef34b89-31d1-4f0e-96ce-271a66aa7ed9.png)
![Random Contrast - tf function](https://user-images.githubusercontent.com/58402418/217828048-e26463dd-9d4e-4837-8e5d-dd76ebf68da5.png)
![Random Contrast - XLA](https://user-images.githubusercontent.com/58402418/217828053-f7b1822b-58fb-4590-84a6-efaf832c5fdb.png)

**Comment by sebastian-sz** [comment]
CPU

**Comment by bhack** [comment]
Is this the result of `RandomContrast` with a single value or a list/tuple for the `factor` param?

**Comment by sebastian-sz** [comment]
Single value: `RandomContrast(0.5)` - I don't think this should affect performance?

**Comment by bhack** [comment]
I suppose yes:
https://github.com/keras-team/keras-cv/blob/4e2d660196afa52962c335cc437b21335cfa28c1/keras_cv/layers/preprocessing/random_contrast.py#L58-L66

So It could be interesting to test, please also try to use realistic enough input (WxH) size for production use cases.

**Comment by bhack** [comment]
@sebastian-sz Can you double check? I am missing something? Where is the random?

https://github.com/keras-team/keras-cv/blob/4b08a7ddc26a4140a60ed53471034f0991f5dc44/keras_cv/layers/preprocessing/random_contrast.py#L69-L70

Do we have a bug?

**Comment by sebastian-sz** [comment]
@bhack I don't think there is a bug:
`self.factor = preprocessing.parse_factor((min, max), min_value=-1, max_value=2)` is parsed into [UniformFactorSampler](https://github.com/keras-team/keras-cv/blob/4b08a7ddc26a4140a60ed53471034f0991f5dc44/keras_cv/utils/preprocessing.py#L151), which returns a float, sampled from a uniform random distribution [upon call](https://github.com/keras-team/keras-cv/blob/4b08a7ddc26a4140a60ed53471034f0991f5dc44/keras_cv/core/factor_sampler/uniform_factor_sampler.py#L45).

**Comment by sebastian-sz** [comment]
> please also try to use realistic enough input (WxH) size for production use cases.

Here is a basic script that I'm using:
```python
# layer = RandomContrast((0,1))
layer = VectorizedRandomContrast((0,1))

@tf.function
def graph_mode(inputs):
    return layer(inputs)

@tf.function(jit_compile=True)
def xla_mode(inputs):
    return layer(inputs)

for batch_size in range(8, 132, 8):
    input_shape = (batch_size, 224, 224, 3)
    batch = tf.random.uniform(input_shape)

    for _ in range(10):
        layer(batch)

    results = []
    for _ in range(100):
        batch = tf.random.uniform(input_shape)
        start = time.perf_counter()
        layer(batch)
        stop = time.perf_counter()
        results.append(stop-start)

    print(batch_size, float(tf.reduce_mean(results).numpy()))
```

**Comment by sebastian-sz** [comment]
@bhack Sorry, my mistake in the previous comment. I'm using tuple for factor, not `0.5`.

**Comment by bhack** [comment]
Yes what I meant it is only in the the init phase not in the `get_ramdom_transformation` call for our x sample/within the batch randomization policy. 

E..g.  check 
https://github.com/keras-team/keras-cv/blob/4b08a7ddc26a4140a60ed53471034f0991f5dc44/keras_cv/layers/preprocessing/random_brightness.py#L78-L84

**Comment by bhack** [comment]
So I think that we have a bug in `RandomContrast`.

Can you plot `RandomBrightness`?

**Comment by bhack** [comment]
Ok sorry my bad, you are right it was a call not a variable.

**Comment by bhack** [comment]
@sebastian-sz I still don't undertand with your code example.

```python
import tensorflow as tf
from tensorflow import keras
from keras_cv.layers.preprocessing import RandomContrast

layer = RandomContrast((0,1))
input_shape = (20, 224, 224, 3)
batch = tf.random.uniform(input_shape)
layer(batch)
```

And if you add a debug print `tf.print(contrast_factor`) I still see only a single value.

https://github.com/keras-team/keras-cv/blob/b2037173a2d6eb3f35ba3ca7dab1662ad66cdf68/keras_cv/layers/preprocessing/random_contrast.py#L72-L73

**Comment by sebastian-sz** [comment]
@bhack Sorry for the confusion. The `0,1` argument was meant to be `value_range` but I passed it as a `factor` instead. This is only a benchmark so I don't think the value shift matters.

In this case the `0,1` is treated as min and max values, which after slight modifications:
https://github.com/keras-team/keras-cv/blob/b2037173a2d6eb3f35ba3ca7dab1662ad66cdf68/keras_cv/layers/preprocessing/random_contrast.py#L59-L61

Are passed to uniform factor sampler:
https://github.com/keras-team/keras-cv/blob/4b08a7ddc26a4140a60ed53471034f0991f5dc44/keras_cv/core/factor_sampler/uniform_factor_sampler.py#L39-L47

This sampler seems to be only a wrapper around `tf.random.uniform` to set it's min and max values.
Hency by calling `self.factor()`, it is equivalent to call `tf.random.uniform` with the default scalar shape `()`.

This is the value that can be printed via `tf.print(contrast_factor)` and it's the value passed to `tf.image.adjust_contrast`.

Currently, in case of vectorized implementation, if we use this `self.factor()` + `tf.image.adjust_contrast` (if I'm not mistaken) every image in the batch receives the same `contrast_factor`.

**Comment by sebastian-sz** [comment]
@bhack Wait, it's not called per sample?

**Comment by bhack** [comment]
I have used that gist.
I supposed the we have 1 factor for each sample in the batch but it print only a single scalar

**Comment by sebastian-sz** [comment]
From the code it looks like it is sampling new scalar per image:
https://github.com/keras-team/keras-cv/blob/b2037173a2d6eb3f35ba3ca7dab1662ad66cdf68/keras_cv/layers/preprocessing/base_image_augmentation_layer.py#L459-L460

`_augment` calls `get_random_transformation`, but on my end it's also printing only a single scalar, regardless of batch size.

**Comment by bhack** [comment]
@LukeWood ?

**Comment by bhack** [comment]
@sebastian-sz I suppose that `map_fn` expect a stacked elem. But who is stacking `factor`?

> elems: A tensor or (possibly nested) sequence of tensors, each of which will be unstacked along their first dimension.

**Comment by bhack** [comment]
`_augment calls get_random_transformation, but on my end it's also printing only a single scalar, regardless of batch size.`

`_augment` it is only called once and now I am very confused on how `map_fn` call was organized.

**Comment by bhack** [comment]
@sebastian-sz Check the analysis at https://github.com/keras-team/keras-cv/issues#issuecomment-1424701740.

It is why this benchmark seems so unexpected.

**Comment by LukeWood** [comment]
@sebastian-sz feel free to contribute this!  Thanks a lot for the contribution!  

In general we should look to vectorize layers unless there’s a clear reason not to.
