### ISSUE TITLE
Vectorize RandomSaturation

### ISSUE THREAD

**Issue by james77777778** [keras-team/keras-cv#1386]
**Short Description**
I firstly dig into #1378 and accidentally get some outcomes of vectorized RandomSaturation 

`RandomSaturation` is current implementation
`RandomSaturationV2` is vectorized by `VectorizedBaseImageAugmentationLayer`

I tested the performance based on [benchmarks/vectorized_grayscale.py](https://github.com/keras-team/keras-cv/blob/24fe395229f73d94834b63b9b453e296d863a4af/benchmarks/vectorized_grayscale.py) with `factor=0.5`

![1](https://user-images.githubusercontent.com/20734616/218042462-562cac0c-31c2-4a6c-93b2-11b8ceba4ca9.png)
![2](https://user-images.githubusercontent.com/20734616/218042481-5495c600-7faa-4b82-a503-1445d7570fba.png)

The implementation looks like:
```python
class RandomSaturationV2(VectorizedBaseImageAugmentationLayer):
    def __init__(self, factor, seed=None, **kwargs):
        super().__init__(seed=seed, **kwargs)
        self.factor = preprocessing.parse_factor(
            factor,
            min_value=0.0,
            max_value=1.0,
        )
        self.seed = seed

    def get_random_transformation_batch(self, batch_size, **kwargs):
        return self.factor(shape=(batch_size,))

    def augment_images(self, images, transformations, **kwargs):
        transformations = tf.convert_to_tensor(transformations)
        adjust_factors = transformations / (1 - transformations)

        # rgb -> hsv -> mul at s channel with clipping -> rgb
        images = tf.image.rgb_to_hsv(images)
        s_channel_batch = tf.multiply(images[..., 1], adjust_factors[:, tf.newaxis, tf.newaxis])
        s_channel_batch = tf.clip_by_value(s_channel_batch, clip_value_min=0.0, clip_value_max=1.0)
        images = tf.stack([images[..., 0], s_channel_batch, images[..., 2]], axis=-1)
        images = tf.image.hsv_to_rgb(images)
        return images
```

but the outputs might be slightly slightly different with `factor=(0.5, 0.5)`:
I compared first 100 images from cifar 10 and there was 1 image failed to pass `tf.experimental.numpy.allclose`
(at `x_train[99]` if you want to know...)

should I contribute this implementation?

**Comment by LukeWood** [comment]
Thank you for your hard work on this!

Yeah this looks like the right approach.  

One question I have is regarding the numerical differences.  Can we implement a numerical correctness test using a locally copy pasted version of the old saturation adjustment layer, and configure the `delta` in `allclose` to make it pass, then analyze how many failures we get.  If its only 1/100 failures, I think its probably fine as long as that failure is only has a 1-2% delta from the original.

**Comment by LukeWood** [comment]
In any case please open a PR!

**Comment by james77777778** [comment]
> One question I have is regarding the numerical differences. Can we implement a numerical correctness test using a locally copy pasted version of the old saturation adjustment layer, and configure the `delta` in `allclose` to make it pass, then analyze how many failures we get. If its only 1/100 failures, I think its probably fine as long as that failure is only has a 1-2% delta from the original.

Sure! I will begin to work on this with a configurable numerical tests.
It shouldn't take too long 🙂

**Comment by LukeWood** [comment]
Cool!  The numerical test can just have hard coded delta - it mainly just serves to have the margin of error documented somewhere.
