### ISSUE TITLE
Extend model serialization test to all backbones

### ISSUE THREAD

**Issue by jbischof** [keras-team/keras-cv#1387]
In #1367 we piloted a model serialization test using ResNetV2. Add [this test](https://github.com/keras-team/keras-cv/blob/fc3bea368db0af1ee9b985378b0dde76c8c906a2/keras_cv/models/resnet_v2_test.py#L57) to all backbone models (any files in `keras_cv/models/` and not its subfolders).

**Comment by jbischof** [comment]
@soma2000-lang will assign the issue to you

**Comment by soma2000-lang** [comment]
@jbischof Please assign me this issue.

**Comment by jbischof** [comment]
This is no longer relevant with our new backbone APIs
