### ISSUE TITLE
[API Naming]: alternative to COCOMeanAveragePrecision and COCORecall

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#1399]
Originally I named these metrics COCORecall and COCOMeanAveragePrecision for two reasons:

- 1.) we can't just call Recall "recall" because the name recall is used across tasks
- 2.)  they were first proposed alongside the microsoft COCO challenge and are usually evaluated using PyCOCOTools, so everyone knows what they are called

That being said, I don't really love the names COCORecall and COCOMeanAveragePrecision.  I still can't think of anything better, but open to ideas.

Any ideas?

**Comment by LukeWood** [comment]
( @ianstenbit @jbischof ) comment if you have any ideas

**Comment by IMvision12** [comment]
@LukeWood how about this:

1. COCORecall : 
 - (COCO_DR) or (CDR) COCO detection recall
 - (COCO_ODR) or (CODR) COCO object detection recall
 - (COCO_TPR) or (CTPR) COCO TPR (true positive rate)
2. COCOMeanAveragePrecision
 - COCO_mAP or CmAP
 - ODMAP (Object Detection Mean Average Precision)
 - COCO Object Detection Precision-Recall (CODPR)

**Comment by ianstenbit** [comment]
How about `BoxMeanAveragePrecision` and `BoxRecall`

**Comment by LukeWood** [comment]
> How about `BoxMeanAveragePrecision` and `BoxRecall`

On board with these.  I really prefer them to COCO.  I’ll add them in my PR.
