### ISSUE TITLE
Vectorize RandomBrightness, RandomContrast, RandomHue and RandomColorJitter

### ISSUE THREAD

**Issue by james77777778** [keras-team/keras-cv#1405]
**Short Description**

As #1392 was merged, I'm willing to contribute for vectorized `RandomBrightness`, `RandomContrast`, `RandomHue` and finally to complete vectorized `RandomColorJitter`.

`RandomColorJitter` is widely adopted, so the improvement from vectorization should benefit the community.

**Other Information**

There is an unsolved conversation at https://github.com/keras-team/keras-cv/pull/1392#discussion_r1107966121
and my questions are:
1. Should we move A/B testings from unit tests into `./benchmarks/random_*.py`?
2. `./benchmarks/` might be flooded by these scripts. Should we create a new folder for these?

For 1., take `./benchmarks/vectorized_random_saturation.py` as example:
```python
# add old implementation
class OldRandomSaturation(BaseImageAugmentationLayer):
    ...

# add tests
class RandomSaturationTest(tf.test.TestCase):
    def test_correctness_with_tf_adjust_saturation_normalized_range(self):
        ...
        self.assertAllClose(old_output, output, atol=1e-5, rtol=1e-5)

    def test_correctness_with_tf_adjust_saturation_rgb_range(self):
        ...
        self.assertAllClose(old_output, output, atol=1e-3, rtol=1e-5)


if __name__ == "__main__":
    # run benchmarks (get some figures for improvement)
    ...
    # run unit tests
    tf.test.main()
```

For 2., I think something like `./benchmarks/vectorization_strategy/vectorized_*.py` can be a better layout?

**Comment by IMvision12** [comment]
hey @james77777778 Just saw your last PR and that was wonderful work on vectorizing random saturation, are there any more augmentations that need to be vectorized, I would like to contribute.

Thanks

**Comment by james77777778** [comment]
Hi @IMvision12 
Thanks!

Currently, I'm not targeting any other preprocessing layer. Just want to complete RandomColorJitter in my own interest :)
As https://github.com/keras-team/keras-cv/issues/1382#issuecomment-1427035487 said, any vectorization should be contribution-welcome.
