### ISSUE TITLE
XLA compile all possible for loops in COCOMeanAveragePrecision

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#141]
We may also be able to XLA compile some of the inner loops on COCORecall!

**Comment by bhack** [comment]
I suppose that XLA has still some limits with `tf.math.bincount` op (at least on CPU):

> on XLA_CPU_JIT: Bincount (No registered 'Bincount' OpKernel for XLA_CPU_JIT devices compatible with node 

But the list is of CPU and GPU ops is outdated:
https://github.com/tensorflow/tensorflow/issues/14798#issuecomment-350814888

**Comment by LukeWood** [comment]
Ahhh man.  Yeah we can’t get around bincount.  Maybe we can use it for result though?

**Comment by bhack** [comment]
I've tried also to give a run with the "next-gen" MLIR bridge compiler `tf.config.experimental.enable_mlir_bridge()`. 
It seems that it fail to legalize it:

> OP_REQUIRES failed at xla_ops.cc:248 : INVALID_ARGUMENT: TF to XLA legalization failed: /usr/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:2203:1: error: 'tf.TensorListReserve' op unknown tensor list element shape

**Comment by bhack** [comment]
Just to reference the code block for visibility:

https://github.com/keras-team/keras-cv/blob/a25ee77ab8466163322332a6d707606794ddf259/keras_cv/metrics/coco/mean_average_precision.py#L135-L253

**Comment by bhack** [comment]
>  Maybe we can use it for result though?


Instead for result XLA without MLIR bridge is working 

With MLIR:
> INVALID_ARGUMENT: TF to XLA legalization failed: /usr/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:2203:1: error: The following operations cannot be legalized: tf.LowerBound (count: 10); tf.Where (count: 10). These legalization failure(s) may be due to missing TF to HLO lowerings and/or unsupported attributes, etc.


https://github.com/keras-team/keras-cv/blob/a25ee77ab8466163322332a6d707606794ddf259/keras_cv/metrics/coco/mean_average_precision.py#L255-L316

**Comment by bhack** [comment]
For result:
HLO graph CPU before optimization

![visualized_output](https://user-images.githubusercontent.com/1710528/154601409-90c4406b-069f-4c00-a447-44f3324e8798.svg)

HLO graph CPU after optimization
![visualized_output](https://user-images.githubusercontent.com/1710528/154601664-a6ec67df-8582-4ce0-ac6b-d51b23a50e7a.svg)

**Comment by joker-eph** [comment]
> I've tried also to give a run with the "next-gen" MLIR bridge compiler `tf.config.experimental.enable_mlir_bridge()`. It seems that it fail to legalize it:
> 
> > OP_REQUIRES failed at xla_ops.cc:248 : INVALID_ARGUMENT: TF to XLA legalization failed: /usr/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:2203:1: error: 'tf.TensorListReserve' op unknown tensor list element shape

If you can reduce this to a simple test case, please file a bug against TensorFlow, I can ping the bridge team.

**Comment by bhack** [comment]
@joker-eph Thanks it was just to explore what is the status with the next compiler stack but as you know we cannot use `tf.config.experimental.enable_mlir_bridge()` in an official API.

Do you know instead who is the maintainer of the XLA CPU/GPU ops list:
https://github.com/tensorflow/tensorflow/issues/14798#issuecomment-350814888

**Comment by LukeWood** [comment]
![image](https://user-images.githubusercontent.com/12191303/154762775-85a8cf56-ce93-4256-91dc-44aed0b8c921.png)

@bhack

**Comment by bhack** [comment]
Is this COCORecall without XLA?

**Comment by LukeWood** [comment]
> Is this COCORecall without XLA?

Its mean average precision w/o XLA

**Comment by bhack** [comment]
@LukeWood  Do you have a performance test to run? What we have in master is too small.

**Comment by LukeWood** [comment]
We can use random data to performance benchmark.  I can probably throw a script together.

```python

def produce_random_data(include_confidence=False, num_classes=20):
  """Generates a fake list of bounding boxes for use in this test.

  Returns:
    a tensor list of size [128, 25, 5/6].  This represents 128 images, 25 bboxes
      and 5/6 dimensions to represent each bbox depending on if confidence is
      set.
  """
  images = []
  for _ in range(128):
    num_boxes = math.floor(25 * random.uniform(0, 1))
    classes = np.floor(np.random.rand(num_boxes, 1) * num_classes)
    bboxes = np.random.rand(num_boxes, 4)
    boxes = np.concatenate([bboxes, classes], axis=-1)
    if include_confidence:
      confidence = np.random.rand(num_boxes, 1)
      boxes = np.concatenate([boxes, confidence], axis=-1)
    images.append(
        keras_cv.utils.bbox.xywh_to_corners(
            tf.constant(boxes, dtype=tf.float32)))

  images = [
      keras_cv.utils.bbox.pad_bbox_batch_to_shape(x, [25, images[0].shape[1]])
      for x in images
  ]
  return tf.stack(images, axis=0)
```

**Comment by LukeWood** [comment]
> For `result`: HLO graph CPU before optimization
> 
> ![visualized_output](https://user-images.githubusercontent.com/1710528/154601409-90c4406b-069f-4c00-a447-44f3324e8798.svg)
> 
> HLO graph CPU after optimization ![visualized_output](https://user-images.githubusercontent.com/1710528/154601664-a6ec67df-8582-4ce0-ac6b-d51b23a50e7a.svg)

What does HLO stand for here?

**Comment by joker-eph** [comment]
HLO is the set of operation XLA operates on: https://www.tensorflow.org/xla/operation_semantics

**Comment by bhack** [comment]
HLO is https://www.tensorflow.org/xla/architecture#how_does_xla_work

For MLIR stack see https://github.com/tensorflow/mlir-hlo#overview

**Comment by bhack** [comment]
You can see the fused  grey boxes, with a debug view of the fused ops, in the "after optimization" graph.

**Comment by LukeWood** [comment]
Thanks for the answers.

**Comment by bhack** [comment]
It could be really nice if you can contribute your reference performance test where we could conditionally enable the public Tensorflow profiler:
https://www.tensorflow.org/guide/profiler

In this way we could be on the same page with the community on performance evaluation without relying only on internal tools that are not available to the community.

**Comment by bhack** [comment]
We have now an XLA tf.bincount ticket at https://github.com/tensorflow/tensorflow/issues/54479

**Comment by LukeWood** [comment]
@bhack https://github.com/keras-team/keras-cv/pull/147
