### ISSUE TITLE
Keras.io tutorial covering data augmentation on GPU

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#1413]
I have a prototype of this prepared.  We get this more or less for “free”.  It is basically a nice side effect of our augmentations being implemented in TF.

**Comment by LukeWood** [comment]
Cool idea, but I don't really think this is particularly useful 🤷 

What do you think @jbischof and @ianstenbit ? I already wrote a colab for it, but its not a super useful pattern.

**Comment by ianstenbit** [comment]
I don't think there's a meaningful use case for this, so I'd propose we don't publish it.
