### ISSUE TITLE
`RetinaNetLabelEncoder`'s `call()` method does not support RaggedTensor inputs for the `images` argument.

### ISSUE THREAD

**Issue by slavazhulanov** [keras-team/keras-cv#1417]
Hi all
I recently discovered Keras_CV and immediately tried to reproduce the guide: https://keras.io/guides/keras_cv/retina_net_overview/. I get an error: 

    ValueError: Exception encountered when calling layer 'retina_net_label_encoder' (type RetinaNetLabelEncoder).
    
    in user code:
    
        File "C:\anaconda\lib\site-packages\keras_cv\layers\object_detection\retina_net_label_encoder.py", line 169, in call  *
            raise ValueError(
    
        ValueError: `RetinaNetLabelEncoder`'s `call()` method does not support RaggedTensor inputs for the `images` argument.  Received `type(images)=<class 'tensorflow.python.ops.ragged.ragged_tensor.RaggedTensor'>`.
    
    
    Call arguments received by layer 'retina_net_label_encoder' (type RetinaNetLabelEncoder):
      • images=tf.RaggedTensor(values=tf.RaggedTensor(values=Tensor("RaggedFromVariant/RaggedTensorFromVariant:2", shape=(None, 3), dtype=float32), row_splits=Tensor("RaggedFromVariant/RaggedTensorFromVariant:1", shape=(None,), dtype=int64)), row_splits=Tensor("RaggedFromVariant/RaggedTensorFromVariant:0", shape=(None,), dtype=int64))
      • box_labels={'classes': 'tf.Tensor(shape=(None, 32), dtype=float32)', 'boxes': 'tf.Tensor(shape=(None, 32, 4), dtype=float32)'}

**Comment by shreypareek1991** [comment]
@slavazhulanov Did you manage to solve this? I am getting the same error.

**Comment by jbischof** [comment]
@shreypareek1991 can you attach a minimal colab to reproduce? Thank you!

**Comment by shreypareek1991** [comment]
@jbischof I realized my error is slightly different. Please see #1964
