### ISSUE TITLE
Make ConvMixer a Functional subclass model + remove closures

### ISSUE THREAD

**Issue by ianstenbit** [keras-team/keras-cv#1418]
This should follow the example of #1412 and #1401, including

- Docstring updates
- Colab demonstrating that weight loading works (if pre-trained weights exist) and numerics are identical

**Comment by xyzhang7** [comment]
I would love to work on this. I am new to the open source community, can I please get a chance?

**Comment by ianstenbit** [comment]
@xyzhang7  -- for sure! Feel free to open a PR 👍

**Comment by ID6109** [comment]
I'm working on this, but I am getting an error =  TypeError: ('Keyword argument not understood:', 'dim')
Any suggestions would be helpful. TIA
