### ISSUE TITLE
Add Color Jitter KPL 

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#142]
**ColorJitter** is a type of image data augmentation where we randomly change the brightness, contrast, and saturation of an image.
[src. ](https://paperswithcode.com/method/colorjitter)
![output_35_0_DxAQHli](https://user-images.githubusercontent.com/17668390/154810353-7f206d68-0f16-43de-8916-ad365eac46fb.png)

basic 

```python

x = tf.image.adjust_brightnes
x = tf.image.adjust_contrast
x = tf.image.adjust_saturation
x = tf.image.adjust_hue
````

**Comment by LukeWood** [comment]
Hey @innat - please check the existing list of open issues before opening a new one!  This one has an existing issue.  Thanks!

**Comment by innat** [comment]
@LukeWood Uh, my bad. Sorry for this inconvenience. Closing the other one. Thank you.

**Comment by LukeWood** [comment]
Don't sweat it - thanks for your contributions! 👍

**Comment by LukeWood** [comment]
Thanks again @innat !
