### ISSUE TITLE
Make CSPDarknet a Functional subclass model and remove closures

### ISSUE THREAD

**Issue by ianstenbit** [keras-team/keras-cv#1420]
This should follow the example of #1412 and #1401, including

- Docstring updates
- Colab demonstrating that weight loading works (if pre-trained weights exist) and numerics are identical

**Comment by soma2000-lang** [comment]
working on this.

**Comment by soma2000-lang** [comment]
@YimjuneLiu I am already  working on this,will open a pr soon .Can you do some other task?

**Comment by YimjuneLiu** [comment]
Sure.
