### ISSUE TITLE
Make Darknet a Functional subclass model & remove closures.

### ISSUE THREAD

**Issue by ianstenbit** [keras-team/keras-cv#1421]
This should follow the example of #1412 and #1401, including

- Docstring updates
- Colab demonstrating that weight loading works (if pre-trained weights exist) and numerics are identical

**Comment by Ashutosh-4485** [comment]
Working on this.

**Comment by YimjuneLiu** [comment]
Hi @ianstenbit @Ashutosh-4485 , Would you mind if I joined the job?

**Comment by ID6109** [comment]
I'd like to work on this.
