### ISSUE TITLE
Make EfficientNetLite a Functional subclass model & remove closures

### ISSUE THREAD

**Issue by ianstenbit** [keras-team/keras-cv#1423]
This should follow the example of #1412 and #1401, including

- Docstring updates
- Colab demonstrating that weight loading works (if pre-trained weights exist) and numerics are identical

**Comment by xihajun** [comment]
I want to help with this issue :) 

Thanks

**Comment by xihajun** [comment]
Hi Ian, @ianstenbit can I help with this issue? 

Many thanks

**Comment by james77777778** [comment]
Hi @xihajun 
Sorry for not making a response in the issue before working on it. Maybe you can help me at #1440

**Comment by xihajun** [comment]
@james77777778 Ah, sorry, sure! Happy to help! How can I help with this?
