### ISSUE TITLE
Make RegNet a Functional subclass model & remove closures

### ISSUE THREAD

**Issue by ianstenbit** [keras-team/keras-cv#1428]
This should follow the example of #1412 and #1401, including

- Docstring updates
- Colab demonstrating that weight loading works (if pre-trained weights exist) and numerics are identical

**Comment by IMvision12** [comment]
@ianstenbit Working on this one.

**Comment by ianstenbit** [comment]
This is open to anyone to contribute a PR, yes!

**Comment by YimjuneLiu** [comment]
> This is open to anyone to contribute a PR, yes!

Thanks, I am working on this one.

**Comment by IMvision12** [comment]
@YimjuneLiu Go ahead!!

**Comment by yonigottesman** [comment]
Hi, out of curiosity, why is removing the closures a good idea? I thought that what best practice in keras

**Comment by ianstenbit** [comment]
Hi @yonigottesman -- in short, check out [this blog post](https://lukewood.xyz/blog/subclass-model-pitfall) from @LukeWood
