### ISSUE TITLE
Improve `get_feature_extractor` API

### ISSUE THREAD

**Issue by jbischof** [keras-team/keras-cv#1447]
PR #1438 copies the `as_backbone` API to our new `Backbone` class as `get_feature_extractor`. @fchollet, @mattdangerw, and @LukeWood suggested some improvements:
* The original `(min_level, max_level)` signature is confusing and insufficiently documented
* Intermediate layers are a sequence and should be presented as a `list` rather than a `dict`
* The final `ValueError` about feature extraction not being possible is not helpful.
* Feature extraction should possibly be a class rather than a method e.g., `FeatureExtractor(ResNet50V2Backbone())`
* Feature extraction could possibly be handled by the `Task` rather than the `Backbone`

**Comment by LukeWood** [comment]
> PR #1438 copies the `as_backbone` API to our new `Backbone` class as `get_feature_extractor`. @fchollet and @LukeWood suggested some improvements:
> 
> * The original `(min_level, max_level)` signature is confusing and insufficiently documented
> * Intermediate layers are a sequence and should be presented as a `list` rather than a `dict`
> * The final `ValueError` about feature extraction not being possible is not helpful.
> * Feature extraction should possibly be a class rather than a method e.g., `FeatureExtractor(ResNet50V2Backbone())`

what do we think about moving moving this logic into the Task models so users still just pass a backbone when constructing task models?  It could be nice to abstract the concept of "levels" from users.

**Comment by jbischof** [comment]
@LukeWood for the `Task` model to have clean ownership it would need to be able to featurize backbones with a single generic method without user oversight. For example, if one backbone has five and another has seven levels, should it always take the highest ones in the pyramid? Are there not cases where the user would want to employ a bespoke featurization strategy?

The thing we want to avoid is a sea of control flow in the `Task` memorizing all sorts of corner cases (e.g., our [input channels test](https://github.com/keras-team/keras-cv/blob/54fcdf2bb864888897fb5c6bb45b52ff27298bfe/keras_cv/models/models_test.py#L81))

**Comment by qlzh727** [comment]
> PR #1438 copies the `as_backbone` API to our new `Backbone` class as `get_feature_extractor`. @fchollet, @mattdangerw, and @LukeWood suggested some improvements:
> 
> * The original `(min_level, max_level)` signature is confusing and insufficiently documented
Will do
> * Intermediate layers are a sequence and should be presented as a `list` rather than a `dict`
Note that it is possible that the consumer of the feature might not want all the features from the backbone, and the dict here preserve the level information whereas list will miss them.

> * The final `ValueError` about feature extraction not being possible is not helpful.
Will do.

> * Feature extraction should possibly be a class rather than a method e.g., `FeatureExtractor(ResNet50V2Backbone())`
It depends on whether feature extractor has any state or just stateless. We should try to keep it stateless if possible.

> * Feature extraction could possibly be handled by the `Task` rather than the `Backbone`
Not sure what's Task here, but Feature extraction sounds like something could read/consume backbone and produce features, so backbone probably should not aware of feature extractor.

**Comment by qlzh727** [comment]
@jbischof I assume this issue need to be addressed after https://github.com/keras-team/keras-cv/pull/1438 get merged?

**Comment by jbischof** [comment]
Yes, I will take ownership for now and let you know if I need help.
