### ISSUE TITLE
Pilot KerasCV <> KerasNLP API unification

### ISSUE THREAD

**Issue by jbischof** [keras-team/keras-cv#1451]
Currently KerasCV and KerasNLP have very different APIs for loading pretrained models. Our goal is to make them seem like a unified offering while respecting differences in the CV space; particularly that CV architectures such as `ResNet50` have a distinct identity outside specific checkpoints unlike `BertBase`.

In this Issue we pilot each of the steps with a non-trivial example. Once each step is finalized, we will open downstream Issues to refactor other models in the same pattern---community contributions will be greatly appreciated!

Steps:
* [x] Refactor backbone models as functional subclasses and remove closures.
    * This is necessary for introducing a class hierarchy.
    * #1401
* [x] Introduce a `Backbone` base class with `from_preset` API.
    * Refactor inlined architectures as presets (e.g., `ResNet50V2`).
    * Remove classification heads.
    * #1438
* [x] Develop consensus `as_backbone` method for feature extraction
    * #1454  
* [x] Introduce `Task` base class for all e2e models with `from_preset` API.
    * Create a `Classifier` subclass for a classification task
    * Add all compatible backbones as presets.
    * Introduce e2e classifier checkpoints as Task-level presets
    * Decide whether to offer aliased e2e architectures like `ResNet50V2Classifier`
    * #1458 
* [x] Refactor advanced tasks such as object detection to `Task` model subclasses with presets

**Comment by suvadityamuk** [comment]
Are there any possible community contributions y'all are looking for, in this task? Would be happy to work, since it seems like a huge endeavor!

**Comment by jbischof** [comment]
Yes @suvadityamuk please check the Issues page!

**Comment by LukeWood** [comment]
Hey @jbischof I think:

> Refactor advanced tasks such as object detection to Task model subclasses with presets

Was the final one which is now done.  Feel free to re-open if you feel there is more to do here, but great work and excited to have it all done!  🔥 

![4f5a75c02f88d6096dfe7a2c647d9fac](https://user-images.githubusercontent.com/12191303/234776515-a6287c42-3cb7-4b0c-856f-03fbdc6de012.gif)
