### ISSUE TITLE
Vectorize Solarization.

### ISSUE THREAD

**Issue by sebastian-sz** [keras-team/keras-cv#1463]
**Short Description**
`Solarization` can be easily ported to use `VectorizedBaseImageAugmentationLayer`.

The implementation basically only changes:
`addition_factor(dtype=self.compute_dtype)` to `addition_factor(shape=(batch_size, 1, 1, 1), ...)`

**Performance summary**
* Eager -> improvement.
* Graph -> similar.
* XLA -> similar.

Graphs:
![comparison](https://user-images.githubusercontent.com/58402418/223444171-60e9ba93-e812-47bb-9c5c-67c7479032cf.png)
![comparison_no_old_eager](https://user-images.githubusercontent.com/58402418/223444172-532c05cc-97a1-4b07-abc0-daef3adac1fb.png)

If you approve I can submit a PR.

**Comment by LukeWood** [comment]
Go ahead @sebastian-sz !
