### ISSUE TITLE
mosaic layer, only works for 3 channel input image

### ISSUE THREAD

**Issue by Alejandro-Valdes** [keras-team/keras-cv#1464]
cutmix and mixup work fine for 1 channel input image, but mosaic layer has a squeeze statement in its update_image method which removes the dimension of a 1 channel input image.... is this deliberate?

**Comment by LukeWood** [comment]
>  cutmix and mixup work fine for 1 channel input image, but mosaic layer has a squeeze statement in its update_image method which removes the dimension of a 1 channel input image.... is this deliberate?

Not intentional!  Feel free to fix this
