### ISSUE TITLE
Rename `classes` to `num_classes` throughout KerasCV

### ISSUE THREAD

**Issue by ianstenbit** [keras-team/keras-cv#1473]
For consistency with the KerasNLP API, let's always refer to the number of classes in a classifier, OD model, etc., as `num_classes`. (Currently, `classes` is used in many places)

**Comment by ianstenbit** [comment]
@ID6109 I'm actually about to open a PR for this one

**Comment by ID6109** [comment]
Sure @ianstenbit , no worries.
