### ISSUE TITLE
Open vocabulary OD/Segmentation with stable diffusion

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#1491]
**Feature**:
Open vocabulary segmentation and object detection using stable diffusion

**Papers**

- https://jerryxu.net/ODISE/

**Comment by LukeWood** [comment]
![7B48E161-DD12-48A3-B26D-D026B4EFF16A](https://user-images.githubusercontent.com/12191303/224588792-4a915ea3-9748-434b-9fcf-41580ede4419.png)

Incredible!  All using stable diffusion

**Comment by ianstenbit** [comment]
We should probably prioritize this with SAM instead, since it's already en-route to the package
