### ISSUE TITLE
Support Image-to-Prompt

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#1493]
**Short Description**

Similar to image-captioning / retrieval model. 
Similar operatiions of `text-to-image`, `image-to-image`. 

**Papers**

[BLIP: Bootstrapping Language-Image Pre-training for Unified Vision-Language Understanding and Generation](https://blog.salesforceairesearch.com/blip-bootstrapping-language-image-pretraining/)

![1670928184033-62441d1d9fdefb55a0b7d12c](https://user-images.githubusercontent.com/17668390/224608817-38cacd43-5136-4a57-b481-d63a7bb3ad61.gif)

**Existing Implementations**

- https://github.com/salesforce/BLIP
- https://github.com/pharmapsychotic/clip-interrogator
- https://huggingface.co/docs/transformers/model_doc/blip

**Motivation**

- https://www.kaggle.com/competitions/stable-diffusion-image-to-prompts (on going).

**Other Information**

( If this ticket doesn't fit on issue section, please move it to discussion.)

**Comment by NiharJani2002** [comment]
Is this issue solved @innat ?  
If it is not solved, can you assign me this issue to work upon ?

**Comment by innat** [comment]
@NiharJani2002 Only keras team can assign. Please wait to hear back from keras team if it's ok to take it.  

ccing. @jbischof @ianstenbit

**Comment by innat** [comment]
@ianstenbit 

> Is the scope of this issue to add a image_to_text workflow to StableDiffusion?

(afaik), not entirely. But more likely image-captioning. In the first post, there's a model mentioned, BLIP, please take a look at that. 

Though image-captioning isn't listed in the current road-map but the relation of this domain with the current hote cake (stable-diffusion) becomes mutually close. A use case for example, I've a image dataset around 10k, and I'm using BLIP 2 to generate prompt (approximate) to make the training pairs.

**Comment by ianstenbit** [comment]
Hey @innat -- sorry I totally misunderstood. Was looking too fast :-)

This looks super interesting, and if someone in the community is interested in porting it to Keras, we can certainly look into making it a KerasCV offering. At this time, though, we can't add this to our near-term roadmap for the KerasCV team, so it would have to be a community driven effort.

Probably for something of this scale, the right approach would be to create a separate repo with BLIP components that depend on KerasCV where possible, and once it's up and running we can try to integrate it into our API.

**Comment by innat** [comment]
@ianstenbit Thanks for the response. You made a valid suggestion. I'm working with the [image2prompt](https://www.kaggle.com/code/ipythonx/keras-stable-diffusion-image-to-prompts-tpu-vm) at kaggle in my spare time, and I will look forward to translate BLIP in keras.

I've one query (probably old one, so sorry if it's already discussed and decided). What if the model consist of (around) same percentage of cv components and nlp components, where should it live? For example, arch of model [BLIP](https://github.com/salesforce/LAVIS/tree/main/projects/blip2#blip-2-bootstrapping-language-image-pre-training-with-frozen-image-encoders-and-large-language-models), consist of cv and nlp components; one of their LLMs model is variant of [T5](https://github.com/keras-team/keras-nlp/tree/master/keras_nlp/models/t5), vanila version of t5 is available on keras-nlp.

**Comment by ianstenbit** [comment]
Good question @innat -- our plan for now is to have KerasCV depend on KerasNLP for models which require both CV and NLP components, so if there are relevant NLP components that don't exist in KerasNLP yet, we should strive to include them there and we can depend on them as necessary.
