### ISSUE TITLE
Add auto-formatting for CPP code

### ISSUE THREAD

**Issue by ianstenbit** [keras-team/keras-cv#1496]
Perhaps https://github.com/marketplace/actions/clang-format-lint is a good approach, per @justinledford in #1487

**Comment by soma2000-lang** [comment]
@ianstenbit Can you please assign me this issue I would like to work on formatting the other cc files.

Thanks!

**Comment by ianstenbit** [comment]
@soma2000-lang sure -- please take a look at #1487 which reformatted existing CPP code.

This issue is about adding auto-formatting (probably to our `format.sh` script) which will catch format issues during CI
