### ISSUE TITLE
Doctring cleanup

### ISSUE THREAD

**Issue by ID6109** [keras-team/keras-cv#1500]
I have noticed several docstring issues in keras_cv/models. I can work on this by not modifying the files used in open PRs to skip any merge conflicts. Should I open a PR?

@ianstenbit @LukeWood

**Comment by ianstenbit** [comment]
Yes, feel free to send PRs cleaning up / improving docstrings for keras_cv/models.
I think that some typos / inaccuracies exist in many of these docs.

For docstring changes related to input format, see #1343.

**Comment by ID6109** [comment]
I'll take this up then. Can you assign it to me please?

**Comment by ID6109** [comment]
Closing as #1627 would deal with this internally.
