### ISSUE TITLE
Need a clean example PR for migrating models to backbone subclasses

### ISSUE THREAD

**Issue by haifeng-jin** [keras-team/keras-cv#1504]
I will be working on a PR, which only contain the necessary changes to migrate one model from `keras.Model` subclass to `keras_cv.models.backbones.backbone.Backbone` subclass.

I will migrate ResNetV1.
I will refer to #1438 for the implementation, which contains the ResNetV2 changes.

When finished the PR will be added to #1451 as an example PR to guide the community contributors to migrate more models.

**Comment by haifeng-jin** [comment]
@jbischof Would you please confirm my understanding of my task is correct?
Thanks.

**Comment by jbischof** [comment]
@haifeng-jin my view of the task is slightly more expansive: you should make all necessary changes to get the ResNetV1 code with all the bells and whistles currently in the ResNetV2 code. This changes occurred over several PRs and would be very confusing to share with our community. It might actually be easier to compare the implementations in master than to go through the PRs themselves.

**Comment by haifeng-jin** [comment]
@jbischof Got it. So get the ResNetV1 to the current state of ReNetV2 on the master branch with a single PR with all the changes necessary and exclusively. Refer to a series of PRs for the ResNetV2 changes.
