### ISSUE TITLE
vit rescaling

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#1526]
Should it be 

https://github.com/keras-team/keras-cv/blob/master/keras_cv/models/vit.py#L272-L280

```python
if include_rescaling:
    x = layers.Rescaling(1.0 / 255.0, name="rescaling")(x)
    # The previous layer rescales [0..255] to [0..1] if applicable
    # This one rescales [0..1] to [-1..1] since ViTs expect [-1..1]
    x = layers.Rescaling(scale=1.0 / 0.5, offset=-1.0, name="rescaling_2")(
        x
    )
else:
    # This one rescales [0..255] to [-1..1] since ViTs expect [-1..1]
    x = layers.Rescaling(scale=1./127.5, offset=-1.0, name="rescaling")(
        x
    )

# why not just else!
```

I've found some weird performance gap using keras-cv-vit and but consistent performance improvement using this open-source implementation https://github.com/faustomorales/vit-keras. Currently investigating, will share bug report if found.

**Comment by ayulockin** [comment]
I think the way it is setup is that if your data loader is not rescaling (`tf.image.convert_image_dtype`) one should use `include_rescaling=True`. cc: @DavidLandup0

**Comment by Niveath** [comment]
Hi! @innat  Is this still an open issue? If yes, I would like to take this up. I'm new to open source and this seems like a good place to start.

**Comment by DavidLandup0** [comment]
Yes - this was done because ViTs expect a `[-1, 1]` input, while all other KerasCV models expect `[0, 1]`.
This was done so someone can supply `[0, 255]`, `[0, 1]` and `[-1, 1]` inputs, and they all work.

If you supply `[0, 1]`, and have `rescaling=False`, it'll still be forced to `[-1, 1]`. In that way, the non-standard behavior isn't exposed to the end user, and everyone used to `[0, 1]` inputs in the library can continue providing them (i.e. there's conformity over all models).

Thanks for tagging @ayulockin!

**Comment by DavidLandup0** [comment]
Regarding the performance gap - could you share the setup? I've had pretty favorable performance with these (to be fair, haven't tested other implementations).

**Comment by innat** [comment]
( Later, I've noticed that the above mentioned repo (https://github.com/faustomorales/vit-keras) uses [fine-tuned weights](https://github.com/faustomorales/vit-keras/blob/28815edc5c24492612af726d1b2ca78295128d84/vit_keras/vit.py#L36) of imagenet-1k.)

@DavidLandup0 [gist](https://colab.research.google.com/drive/1dFxnhBVz4tZqluRPr4PXZbyK2sz241zk?usp=sharing). (testedw ith keras-cv-vit, huggingface-vit, faustomorales-vit).

**Comment by innat** [comment]
@DavidLandup0 To make the above gist more simplified, here is my last observation

- pretrained weight of keras-cv-vit [only trained on 1k image-net]
- pretrained weight of huggingface-vit [1st trained on 21k image-net, + fine-tuned 1k image-net]
- pretrained weight of faustomorales-vit (same as huggingface)

Do you think the performance gape can be due to this (checkpoints)? 
And I'm not sure, but why it's must to rescale (-1, 1) for keras-vit, whereas, in huggingface-vit, it can be (0,1).
