### ISSUE TITLE
Replace `tf.keras` with `keras` throughout KerasCV

### ISSUE THREAD

**Issue by ianstenbit** [keras-team/keras-cv#1527]
We should import from Keras directly instead of relying on `tf.keras` as a convention throughout our codebase.

**Comment by ianstenbit** [comment]
This is open to the community. If you'd like to contribute, feel free to open a PR tagging this issue and fixing these imports for some subset of KerasCV.

**Comment by vijaybirju** [comment]
can I make changes file by file? For example, if I make changes in any file ABC ( replaced tf.keras with keras) and request for pull for it. Or do I have to make changes in entier kerasCV then only I can request PR?

**Comment by ID6109** [comment]
Hey @vijaybirju , I believe #1530 will close this issue
