### ISSUE TITLE
Refactor bounding_box utils with `BoundingBox` class to represent box.

### ISSUE THREAD

**Issue by kartik4949** [keras-team/keras-cv#154]
```
class BoundingBoxMixin:

    @staticmethod
    def _get_corners(bbox):
        ...

    @staticmethod
    def _get_xywh(bbox):
        ...

    @staticmethod
    def _pad_bbox(bbox):
        ...

# will use internally in upcoming BoundingBox related more data augmentation or even provide this publicly
class BoundingBox(BoudningBoxMixin):
    _ALLOWED_FORMAT = ['xywh', 'corner']

    def __init__(self, box, type='xywh'):
        self._box = box
        # assert type.
        self._type = type

    @property
    def corners(self):
          return self._box

    @property
    def xywh(self):
          # convert to xywh.
          return _box
    @property
    def area(self):
        return _area

    @property
    def extended_corners(self):
        # return extended 4 corners  of box
        return _extended_corners

    def pad(self):
        return padded_bounding_box


# public endpoints.
def get_corner(bbox):
    return BoundingBoxMixin._get_corners(bbox)

def get_xywh(bbox):
    return BoundingBoxMixin._get_xywh(bbox)
```

@fchollet @LukeWood 
thoughts?

**Comment by LukeWood** [comment]
The other alternative we can consider is a tf extension type:
https://www.tensorflow.org/guide/extension_type

I'm not fully sold on any of the solutions, and think this is an important choice to make. 

If we do go for a class based solution, I'd probably want to wrap a tensorflow tensor in a `BoundingBoxes` class with a `xywh` and `corners` property - no need for anything more complex than that.

**Comment by kartik4949** [comment]
Hi,
Yeah class based solution makes sense to me, we can discuss more than see which way to go, if we are making it a class then i can contribute on this :)

And i see u are using area in coco utils so thought we can have area as property anyway we can have minimum properties 

Thanks 
> The other alternative we can consider is a tf extension type:
> 
> https://www.tensorflow.org/guide/extension_type
> 
> 
> 
> I'm not fully sold on any of the solutions, and think this is an important choice to make. 
> 
> 
> 
> If we do go for a class based solution, I'd probably want to wrap a tensorflow tensor in a `BoundingBoxes` class with a `xywh` and `corners` property - no need for anything more complex than that.

**Comment by kartik4949** [comment]
@LukeWood if we are good with class based solution as wrapper around (extension type) or may be plain class solution

I can contribute on the above :)

**Comment by LukeWood** [comment]
Hey @kartik4949 !  I'm not convinced that we want to use the class based solution yet.  For now I think the utility functions do everything the class solution does just fine.

**Comment by kartik4949** [comment]
@LukeWood hmm ,for now it do make sense! 
Closing for now
