### ISSUE TITLE
issue in `keras_cv.Rescaling`

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#1542]
Following this ticket, https://github.com/keras-team/keras-cv/issues/1526, I've observed a possible bug in the rescaling layer (specifically in evaluation time).

- [not ok] [keras_cv.layers.Rescaling](https://github.com/keras-team/keras-cv/blob/17abbdd45d095b47db72f42e06f17ce62c2ba43d/keras_cv/layers/preprocessing/rescaling.py#L28)
- [ok] [keras.layers.Rescaling](https://github.com/keras-team/keras/blob/e6784e4302c7b8cd116b74a784f4b78d60e83c26/keras/layers/preprocessing/image_preprocessing.py#L634)

Not much difference in implementation but how they behave in training phase makes the difference.

In my actual training code, I was using rescaling layer from keras-cv, and in evaluatiom time the performance of the model drops drastically (maybe because of not rescaling in evaluatiom time)

In the above gist, I used rescaling from keras, and it works as expected.

@divyashreepathihalli Please have a look. Here is the reproducible code. 

```python
(x_train, y_train), (_, _) = tf.keras.datasets.mnist.load_data()
def mnist_process(x, y):
    x = tf.expand_dims(tf.cast(x, dtype=tf.float32), axis=-1)  
    x = tf.repeat(x, repeats=3, axis=-1)      
    x = tf.image.resize(x, [32,32])  
    y = tf.one_hot(y , depth=10)  
    return x, y
train_ds = tf.data.Dataset.from_tensor_slices((x_train, y_train)).map(mnist_process)
train_ds = train_ds.batch(64)
input = tf.keras.Input(shape=(32, 32, 3))

# x = keras.layers.Rescaling(scale=1./127.5, offset=-1.0)(input)
x =  keras_cv.layers.Rescaling(scale=1./127.5, offset=-1.0)(input)

x = tf.keras.layers.Flatten()(x)
x = tf.keras.layers.Dense(128, activation='relu')(x)
y = tf.keras.layers.Dense(units=10, activation='softmax')(x) 
func_model = tf.keras.Model(inputs=[input], outputs=[y])
func_model.compile(
          loss  = tf.keras.losses.CategoricalCrossentropy(),
          metrics = tf.keras.metrics.CategoricalAccuracy(name='acc'),
          optimizer = tf.keras.optimizers.Adam())
func_model.fit(train_ds, validation_data=train_ds, epochs=num_epochs)
```
```python
with keras_cv.rescale()
Epoch 1/3
loss: 0.4046 - acc: 0.8799 - val_loss: 167.7411 - val_acc: 0.6743
Epoch 2/3
loss: 0.2205 - acc: 0.9335 - val_loss: 118.0847 - val_acc: 0.7573
Epoch 3/3
loss: 0.1778 - acc: 0.9464 - val_loss: 102.2185 - val_acc: 0.7974
```
```python
with keras.rescale()        
Epoch 1/3
loss: 0.3913 - acc: 0.8850 - val_loss: 0.3086 - val_acc: 0.9050
Epoch 2/3
loss: 0.2143 - acc: 0.9350 - val_loss: 0.2798 - val_acc: 0.9161
Epoch 3/3
loss: 0.1732 - acc: 0.9481 - val_loss: 0.1617 - val_acc: 0.9506
```

**Comment by Parul-Verma-16** [comment]
Hey, I would want to work on this rescaling issue #1542
