### ISSUE TITLE
Migrating the models from Keras Model to the Subclass backbone

### ISSUE THREAD

**Issue by soma2000-lang** [keras-team/keras-cv#1546]
@LukeWood @ianstenbit @jbischof @innat  I want to migrate the EfficientNet model to backbone as has been done for resnet v2.
Once approved I can start working on it

**Comment by ianstenbit** [comment]
Hi @soma2000-lang -- thanks for opening this!

Let's wait until #1508 is merged, and then I'll open some issues for doing this migration and I'll be sure to @ you on it. (We want to have an example PR set up for people to follow before we start opening issues for this migration)
