### ISSUE TITLE
Remove `Augmenter` and use `keras.Sequential` instead

### ISSUE THREAD

**Issue by haifeng-jin** [keras-team/keras-cv#1548]
Because `Augmenter` is similar to `keras.Sequential` in functionality, we would like to remove the `Augmenter` from KerasCV and recommend to use `keras.Sequential` instead.

The change require the following steps.
* Change the keras.io notebooks to use `keras.Sequential` instead of `Augmenter` based on KerasCV v0.4.1. Starting from [this notebook](https://keras.io/guides/keras_cv/retina_net_overview/).
* Remove the `Augmenter` and its usages from the codebase. Remember to update the release note.

**Comment by soma2000-lang** [comment]
@haifeng-jin It would be great to work on this issue.Can I send a PR for this.
