### ISSUE TITLE
Support segmentation masks in `CutMix` layer

### ISSUE THREAD

**Issue by ianstenbit** [keras-team/keras-cv#1549]
This should follow the same structure as segmentation mask augmentation in our other preprocessing layers.

Treating masks like 1-channel images for the purpose of applying CutMix should be a simple and effective approach for this.

**Comment by soma2000-lang** [comment]
@ianstenbit It would be great if you can assign me this issue.I would like to work on it.

**Comment by ianstenbit** [comment]
Sounds good -- thanks @soma2000-lang!

**Comment by jbischof** [comment]
Reopening this issue for contributors

**Comment by cosmo3769** [comment]
@jbischof I would love to take this issue. Thank You.
