### ISSUE TITLE
Support segmentation masks in MixUp layer

### ISSUE THREAD

**Issue by ianstenbit** [keras-team/keras-cv#1550]
This should follow the same structure as segmentation mask augmentation in our other preprocessing layers.

Treating masks like 1-channel images for the purpose of applying MixUp should be a simple and effective approach for this.

**Comment by cosmo3769** [comment]
Hey @ianstenbit 

Please assign me this. Thank you.

**Comment by ianstenbit** [comment]
Sounds good -- thanks @cosmo3769!
