### ISSUE TITLE
Update `BoxCOCOMetrics` to lazily compute result()

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#1595]
Right now, every `evaluation_freq` steps we are computing results; regardless of if the result is needed.  We should make this lazy.

Additionally `result(force=True)` is broken right now due to the constructor replacing the `result()` method with the wrapped py_func method.

**Comment by ianstenbit** [comment]
Closing this as it's not clear if this is still useful, and the `PyMetric` approach for COCO metrics is probably not going to survive the Keras Core rebase (due to lack of multi-backend support)
