### ISSUE TITLE
Rethink to rename `MaybeApply` to `RandomApply`

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#1609]
[code.](https://github.com/keras-team/keras-cv/blob/master/keras_cv/layers/preprocessing/maybe_apply.py)

```python
[now]
from keras_cv.layers.preprocessing.maybe_apply import MaybeApply

[what if?]
from keras_cv.layers.preprocessing.random_apply import RandomApply
```

The current layer name (maybe) is a bit anti-pattern w.r.t. other similar type of layer, i.e. [random_choice](https://github.com/keras-team/keras-cv/blob/master/keras_cv/layers/preprocessing/random_choice.py).

Similar functionality is provided in other framework ([torchvision.transforms.RandomApply](https://pytorch.org/vision/main/generated/torchvision.transforms.RandomApply.html)).

**Comment by innat** [comment]
@jbischof 
Any thoughts?

**Comment by jbischof** [comment]
Makes sense to me. @ianstenbit WDYT?

**Comment by jbischof** [comment]
SG. Marked this as "contributions welcome"

**Comment by avinair** [comment]
@jbischof I would like to take this up, could you assign it to me?
