### ISSUE TITLE
Add ShiftScaleRotate for KPL

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#162]
What does it do? 

> Randomly apply affine transforms: translate, scale, and rotate the input.

Reference. https://albumentations.ai/docs/api_reference/augmentations/geometric/transforms/#albumentations.augmentations.geometric.transforms.ShiftScaleRotate

(not sure if it's already added)

**Comment by LukeWood** [comment]
I think this is just a composition of 3 layers we have:
- translate
- resize
- rotation
lets leave this to users.
