### ISSUE TITLE
Migrate DenseNet to the new Backbone model style

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#1624]
To align KerasCV with the KerasNLP API, we're migrating our backbone models to subclass keras_cv.models.Backbone.
This allows us to have a more structured, modular API for high-level task models, including the new ImageClassifier model (see #1458).

A great step-by-step guide to this migration can be found in the description of #1508, which performed this migration for ResNetV1.

If you'd like to take this issue up, please leave a comment and the KerasCV team can assign the issue to you. When opening a PR, please tag this issue as fixed by your PR, and tag our tracking bug #1627 for bookkeeping.

**Comment by soma2000-lang** [comment]
@LukeWood I want to take this up .Please assign this to me.

**Comment by NiharJani2002** [comment]
@LukeWood, Can I Take this issue? Assuming this issue is still open and now solved yet.

**Comment by aseemk98** [comment]
Hello @LukeWood , 
I've been working on this issue referring to #1508, I'm confused with step 4 of creating present files for densenet backbone. I can see the weight file URL in `weights.py` but what about the rest of the information for the no weights preset?

**Comment by ID6109** [comment]
Considering this is a high priority, I think closing this soon is best. I'll make a ready-for-review PR by the weekend.

**Comment by jbischof** [comment]
Thanks @ID6109!

**Comment by soma2000-lang** [comment]
hi @ID6109  Sorry for health issues I have been inactive ,but I will close this by weekend
