### ISSUE TITLE
Migrate MobileNetV3 to new Task model

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#1625]
To align KerasCV with the KerasNLP API, we're migrating our backbone models to subclass keras_cv.models.Backbone.
This allows us to have a more structured, modular API for high-level task models, including the new ImageClassifier model (see #1458).

A great step-by-step guide to this migration can be found in the description of #1508, which performed this migration for ResNetV1.

If you'd like to take this issue up, please leave a comment and the KerasCV team can assign the issue to you. When opening a PR, please tag this issue as fixed by your PR, and tag our tracking bug #1627 for bookkeeping.

**Comment by ID6109** [comment]
I'd like to take this up. I've worked on MobileNetV3 in #1475
