### ISSUE TITLE
Migrate EfficientNetv2 to the new Backbone API

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#1626]
To align KerasCV with the KerasNLP API, we're migrating our backbone models to subclass keras_cv.models.Backbone.
This allows us to have a more structured, modular API for high-level task models, including the new ImageClassifier model (see #1458).

A great step-by-step guide to this migration can be found in the description of #1508, which performed this migration for ResNetV1.

If you'd like to take this issue up, please leave a comment and the KerasCV team can assign the issue to you. When opening a PR, please tag this issue as fixed by your PR, and tag our tracking bug #1627 for bookkeeping.

**Comment by soma2000-lang** [comment]
#1645

**Comment by devnavethefriend** [comment]
Hello @LukeWood, I am an aspiring GSoC 2023 candidate and I would like to handle this issue following your guide. Is anyone already assigned to it yet?

**Comment by soma2000-lang** [comment]
@devnavethefriend There are other contributions welcome issue open ,you can choose from them ,if you see no other pull request is linked to it.I am working on this one as you can see a PR being linked

**Comment by ID6109** [comment]
Solved. Can be closed.
