### ISSUE TITLE
[RFC] Getting import error in __init__.py while migrating EfficientNetLite Backbone

### ISSUE THREAD

**Issue by Anirban0011** [keras-team/keras-cv#1653]
![image](https://user-images.githubusercontent.com/39913940/229357606-004a998c-f3fd-4cf3-a307-9eaf2df5c202.png)

I am getting the above error while migrating the EfficientnetLite to new Backbone API, I feel it must be some naming issue that I am making but I can't seem to find it.
The import to `__init__.py` is 

```python

from keras_cv.models.backbones.efficientnet_lite.efficientnet_lite_backbone import (
    EfficientNetLiteB0Backbone,
)
``` 

`EfficientNetLiteB1`, `EfficientNetLiteB2`, `EfficientNetLiteB3` , `EfficientNetLiteB4` follow a similar pattern of import.

Here's a screenshot of the file hierarchy:
![image](https://user-images.githubusercontent.com/39913940/229357923-a7c3b424-9cb2-45d4-9db7-fe0ab696670c.png)

So basically I am trying to call `class EfficientNetLiteB0Backbone` which inherits superclass `class EfficientNetLiteBackbone`  in `keras_cv/models/backbones/efficientnet_lite/efficientnet_lite_backbone.py` through the above import in `__init__.py`.

I am pretty sure that I am not making any naming errors, although that might be the case.

Here's a screenshot of imports in `efficientnet_lite_backbone.py` file:
![image](https://user-images.githubusercontent.com/39913940/229358212-9cbb0d2a-38f5-48e2-b9cc-4cd26844654a.png)

And the code of `EfficientNetLiteBackbone` superclass:

[Code](https://pastebin.com/eVHfnxf3)

Although most of the code here might have nothing to do with the importing error.

And the called `EfficientNetLiteB0Backbone` class:

![image](https://user-images.githubusercontent.com/39913940/229358498-f1e05090-a21b-4bd4-9a36-e593a7412e0f.png)

The EfficientNetLite Model has no predefined weights in the weights.py file , so I removed the dictionaries involving `with_weights` in the `efficientnet_lite_backbone_presets.py` file.

The other two files `efficientnet_lite_backbone_presets_test.py` and `efficientnet_lite_backbone_test.py` are not ready yet, but don't get called anywhere.

I have tried sorting the imports across the files by running `isort .` locally, but no luck. I Have tried to follow @haifeng-jin 's PR(#1508) as closely as possible.

It would be great if someone could comment on this issue. Thanks!

**Comment by Anirban0011** [comment]
Here's the linked PR that I am trying to resolve ☝️

**Comment by ID6109** [comment]
You need to run `shell/format.sh`. It formats the code to match the style of the codebase.

**Comment by Anirban0011** [comment]
> You need to run `shell/format.sh`. It formats the code to match the style of the codebase.

How do you specifically do that ?

**Comment by Anirban0011** [comment]
![image](https://user-images.githubusercontent.com/39913940/229368428-69d8a745-d044-4f66-ab58-aea423bced6a.png)

Should this do ? @ID6109

**Comment by ID6109** [comment]
Refer to [this](https://github.com/keras-team/keras-cv/blob/master/.github/CONTRIBUTING.md#formatting-the-code).

**Comment by Anirban0011** [comment]
seems like clang-format isn't available for windows , this will take little time after all it seems , thanks for comment btw @ID6109

**Comment by ID6109** [comment]
@Anirban0011 Refer to [this](https://github.com/keras-team/keras-cv/blob/master/.github/CONTRIBUTING.md#formatting-the-code).
