### ISSUE TITLE
Various Keras guides failing

### ISSUE THREAD

**Issue by shilpakancharla** [keras-team/keras-cv#1665]
**Short Description**
This issue was from a few months ago, if you've already added this to the Colab environment, feel free to close this issue. 

A first initial step would be to include a !pip install keras_cv statement at the beginning of the tutorial, and also tell users to make sure they have TensorFlow 2.11.0 in order to use KerasCV (and include the installation command).

**Longer Description**

Here is a more detailed description of the failures.

1. guides/ipynb/keras_cv/retina_net_overview.ipynb: ModuleNotFoundError: No module named 'keras_cv'

2. guides/ipynb/keras_cv/custom_image_augmentations.ipynb: ModuleNotFoundError: No module named 'keras_cv'

3. guides/ipynb/keras_cv/coco_metrics.ipynb: ModuleNotFoundError: No module named 'keras_cv'

4. guides/ipynb/keras_cv/generate_images_with_stable_diffusion.ipynb: ImportError: cannot import name 'compute_pycoco_metrics' from 'keras_cv.metrics.coco' (/tmpfs/src/tf_docs_env/lib/python3.9/site-packages/keras_cv/metrics/coco/__init__.py)

5. guides/ipynb/keras_cv/cut_mix_mix_up_and_rand_augment.ipynb: ModuleNotFoundError: No module named 'keras_cv'

6. guides/ipynb/keras_tuner/tailor_the_search_space.ipynb:

StagingError: in user code:

    File "/tmpfs/src/tf_docs_env/lib/python3.9/site-packages/keras/engine/training.py", line 1249, in train_function  *
        return step_function(self, iterator)
    File "/tmpfs/src/tf_docs_env/lib/python3.9/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 208, in _update_step_xla  *
        return self._update_step(gradient, variable)
    File "/tmpfs/src/tf_docs_env/lib/python3.9/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 216, in _update_step  **
        raise KeyError(

    KeyError: 'The optimizer cannot recognize variable dense/kernel:0. This usually means you are trying to call the optimizer to update different parts of the model separately. Please call `optimizer.build(variables)` with the full list of trainable variables before the training loop or use legacy optimizer `tf.keras.optimizers.legacy.{self.__class__.__name__}.'

StagingError: in user code:

    File "/tmpfs/src/tf_docs_env/lib/python3.9/site-packages/keras/engine/training.py", line 1249, in train_function  *
        return step_function(self, iterator)
    File "/tmpfs/src/tf_docs_env/lib/python3.9/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 208, in _update_step_xla  *
        return self._update_step(gradient, variable)
    File "/tmpfs/src/tf_docs_env/lib/python3.9/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 216, in _update_step  **
        raise KeyError(

    KeyError: 'The optimizer cannot recognize variable dense/kernel:0. This usually means you are trying to call the optimizer to update different parts of the model separately. Please call `optimizer.build(variables)` with the full list of trainable variables before the training loop or use legacy optimizer `tf.keras.optimizers.legacy.{self.__class__.__name__}.'

**Fixes already made**

For custom_image_augmentations.ipynb, added the following:

!pip install keras-cv

Added **kwargs argument in the RandomBlueTint classes to avoid TypeError about bounding_boxes and labels arguments.

[Gist with fix](https://gist.github.com/shilpakancharla/cb6197c32ab2e8a38a0ca4b3eaa46987)

**Comment by LukeWood** [comment]
Yeah, we need to be diligent with adding the “””shell””” cells to our KerasCV guides

**Comment by sampathweb** [comment]
Thanks for reporting the issue. Keras-CV guides have been updated for Keras 3.  Please let us know if you still encounter any issues.
