### ISSUE TITLE
Bounding box formats

### ISSUE THREAD

**Issue by shilpakancharla** [keras-team/keras-cv#1666]
Should users be aware that you can pass in arguments like ‘yxyx’ (not just ‘xyxy’) when you need to specify the bounding box format somewhere? Perhaps a more comprehensive list in the documentation would be useful.

**Comment by jaygala223** [comment]
Hi @shilpakancharla, I would like to take this up

**Comment by shilpakancharla** [comment]
Hi @jaygala223 , yes that's part of it! I was talking more about specifying to users about the format types like 'yxyx' and not just 'xyxy'

**Comment by jbischof** [comment]
@shilpakancharla that guide is our current offering and is linked in the RetinaNet docstring ([link](https://github.com/keras-team/keras-cv/blob/3b308982ee66b5be0874d1a8090bb68fc6c85d8e/keras_cv/models/object_detection/retina_net/retina_net.py#L92)). Is there something missing that you were expecting?
