### ISSUE TITLE
Elastic Transformation in the Augmentation layer.

### ISSUE THREAD

**Issue by sabribarac** [keras-team/keras-cv#1667]
**Short Description**

Introducing Elastic Transformation in the augmentation layer.
See example (elastic transform), https://pytorch.org/vision/stable/auto_examples/plot_transforms.html#sphx-glr-auto-examples-plot-transforms-py

**Papers**
https://web.fe.up.pt/~jsc/publications/conferences/2018EMecaBHI.pdf
https://www.microsoft.com/en-us/research/wp-content/uploads/2003/08/icdar03.pdf
https://arxiv.org/pdf/2107.09391.pdf

**Existing Implementations**
https://gist.github.com/sabribarac/2d50cea94563b2f939eb1e6a46987de0
https://pytorch.org/vision/stable/generated/torchvision.transforms.ElasticTransform.html

**Other Information**

**Comment by innat** [comment]
https://github.com/keras-team/keras-cv/issues/163

**Comment by LukeWood** [comment]
yep - duplicate of 163!
