### ISSUE TITLE
Squeeze and Excitement Block

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#167]
https://arxiv.org/abs/1709.01507

**Comment by LukeWood** [comment]
This is used in:

- efficientnet
- mobilenet

I will base my implementation on these

**Comment by LukeWood** [comment]
https://github.com/tensorflow/models/blob/229e43e8b4578f4e69e02b35a5b33e655b6be3e8/official/vision/beta/modeling/layers/nn_layers.py#L89

**Comment by LukeWood** [comment]
@Blank0043 will take this!

**Comment by bhack** [comment]
Can we assign? It is easier to filter unassigned "contribution-welcome"..

**Comment by LukeWood** [comment]
> Can we assign? It is easier to filter unassigned "contribution-welcome"..

not until they comment.

**Comment by blank0043** [comment]
I will take this one
