### ISSUE TITLE
Avoid NaNs in RetinaNet training by adding an epsilon to `normalizer`

### ISSUE THREAD

**Issue by ianstenbit** [keras-team/keras-cv#1683]
If a training row has no boxes, the `normalizer` is 0, causing division by 0 and thus NaNs.

For YOLOv8 I'm just using an epsilon factor for now.

@LukeWood

**Comment by LukeWood** [comment]
Surprised this wasn't problematic in the RetinaNet, thanks for the fix.  I will add it to RetinaNet too
