### ISSUE TITLE
Getting rid of warnings Waymo Open Dataset

### ISSUE THREAD

**Issue by aqibsaeed** [keras-team/keras-cv#1688]
Hi,

Is there a way to get rid of this warning: "You do not have Waymo Open Dataset installed, so KerasCV Waymo metrics are not available.". I only want to use augmentation layer, it is really annoying to get these warnings in logs.

**Comment by LukeWood** [comment]
@ianstenbit any way we can address this ?

**Comment by tirthasheshpatel** [comment]
Although this was fixed by 34bc64e, there are a couple of these around:

```
You do not have pycocotools installed, so KerasCV pycoco metrics arenot available. Please run `pip install pycocotools`.
You do not have pyococotools installed, so the `PyCOCOCallback` API isnot available.
```

Would be nice to get rid of them too since pycocotools is an optional dependency, @ianstenbit?

**Comment by Anirban0011** [comment]
@aqibsaeed @LukeWood I was getting the same warning when importing keras_cv in a colab notebook via default pip install
```python
pip install keras-cv tensorflow --upgrade
``` 
but the warning disappeared when importing keras_cv through github master branch:
```python
pip install git+https://github.com/keras-team/keras-cv.git tensorflow --upgrade
```

**Comment by ianstenbit** [comment]
Good call @tirthasheshpatel! I've opened #1729 which should resolve this for PyCOCO.

For WaymoOpenDataset, the fix is in and the next release will include the change, as @Anirban0011 points out.

**Comment by ianstenbit** [comment]
> Hi,
> 
> Is there a way to get rid of this warning: "You do not have Waymo Open Dataset installed, so KerasCV Waymo metrics are not available.". I only want to use augmentation layer, it is really annoying to get these warnings in logs.

@aqibsaeed 
To explicitly answer your question -- this warning will disappear in the next released version, or if you install from GitHub.
