### ISSUE TITLE
Support for TFLite

### ISSUE THREAD

**Issue by AakashKumarNain** [keras-team/keras-cv#170]
Given that we are building models in a much better way, are we going to support TFLite model conversion as well as quantization-aware training here?

**Comment by LukeWood** [comment]
It depends what is needed to support these.  Some models it may not be possible

**Comment by AakashKumarNain** [comment]
Agreed that it won't be possible to support all but for detection, and segmentation use-cases, are we:
1. Going to allow the end user to extend the models in a modular way (surely not the way it is done in TF Object Detection Zoo)
2. Convert the common models to tflite

**Comment by LukeWood** [comment]
I think this is currently out of scope, but if some models don't work for tf lite we can look into making them work.  For now trying to avoid over specific issues to keep the repo clean.  Thanks!
