### ISSUE TITLE
Draw utility for common CV task. 

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#174]
I remember one of a MOOC course on coursera, drawing bounding boxes on samples/samples were needed. I think it would be good to have some **utility functions** to do this. For example:

```python
keras_cv.utils.draw_bounding_boxes
keras_cv.utils.draw_segmentation_masks
keras_cv.utils.draw_keypoints
keras_cv.utils.make_grid
```

As a reference, all of these functions/utilities are available in other frameworks too, [HERE](https://pytorch.org/vision/stable/utils.html).

**Comment by bhack** [comment]
Some of these could be ported/adapted from the TF ecosystem: 
https://github.com/tensorflow/models/blob/master/official/vision/utils/object_detection/visualization_utils.py

**Comment by kartik4949** [comment]
draw should be under `visualization`

Also we can get some implementation from efficient det (automl) https://github.com/google/automl/tree/master/efficientdet/visualize

**Comment by kartik4949** [comment]
@innat uhm, if we are thinking to have a separate visualise module then it make sense to have it in visualise it self, may be utility of it.

**Comment by LukeWood** [comment]
We now have specific issues for these.  Thanks @innat !
