### ISSUE TITLE
keras_cv.bounding_box needs a way to go from list format to tensor format

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#1777]
```
{
    "boxes": [mylist of boxes per image],
...
}
```
currently trips up validate_format() as it expects tensors.  I worked around this by writing:
```
final_bounding_boxes = {
    "boxes": tf.ragged.constant([box['boxes'] for box in bounding_boxes]),
    "classes": tf.ragged.constant([box['classes'] for box in bounding_boxes])
}
```

But this isn't a reasonable flow for the average user to work out

**Comment by sahusiddharth** [comment]
@LukeWood 

Excuse me, I'd really appreciate it if you could kindly **explain a bit more** about the issue. I want to make sure I fully understand the details and context. Thank you for your help.

**Comment by jbischof** [comment]
@ianstenbit is this still relevant?

**Comment by ianstenbit** [comment]
> @ianstenbit is this still relevant?

Not that I'm aware of. The use case isn't clear to me
