### ISSUE TITLE
Using MobileNetV3Backbone for object detection

### ISSUE THREAD

**Issue by barrypitman** [keras-team/keras-cv#1779]
As discussed here: https://github.com/keras-team/keras-cv/discussions/1772

I've run into some issues using the MobileNetV3Backbone with RetinaNet:

```
backbone = keras_cv.models.MobileNetV3Backbone.from_preset("mobilenet_v3_large_imagenet")
model = keras_cv.models.RetinaNet(
    backbone,
    num_classes=20,
    bounding_box_format="xywh",
)

img = tf.ones(shape=(1, 512, 512, 3))
output = model.predict(img, verbose=0)
```

Results in an error:
```
in user code:
    
        File "C:\Users\barry\work\keras_object_detection\src\main\python\venv_idea\lib\site-packages\keras_cv\models\object_detection\retinanet\feature_pyramid.py", line 46, in call  *
            p3_output = p3_output + self.upsample_2x(p4_output, training=training)
    
        ValueError: Dimensions must be equal, but are 64 and 128 for '{{node retina_net/feature_pyramid/add_1}} = AddV2[T=DT_FLOAT](retina_net/feature_pyramid/conv2d_18/BiasAdd, retina_net/feature_pyramid/up_sampling2d/resize_1/ResizeNearestNeighbor)' with input shapes: [?,64,64,256], [?,128,128,256].
    
    
    Call arguments received by layer 'feature_pyramid' (type FeaturePyramid):
      • inputs={3: 'tf.Tensor(shape=(None, 64, 64, 24), dtype=float32)', 4: 'tf.Tensor(shape=(None, 64, 64, 24), dtype=float32)', 5: 'tf.Tensor(shape=(None, 32, 32, 40), dtype=float32)'}
      • training=False
```

I suspect its related to [extractor_levels in retinanet.py](https://github.com/keras-team/keras-cv/blob/master/keras_cv/models/object_detection/retinanet/retinanet.py#L166) which are hard-coded as [3, 4, 5] but I presume they need to change based on the backbone used?

**Comment by jbischof** [comment]
@LukeWood can you take a look?

**Comment by jbischof** [comment]
@barrypitman it appears the `feature_pyramid_inputs` in `MobileNetBackbone` are wrong. Each level should be half the size of the next, but it appears that P3 and P4 are actually the same size. We should include better testing for this, but in the short term fixing this class should be our priority.

**Comment by jbischof** [comment]
I'm opening this as a "contributions welcome" issue since the fix is straightforward.
