### ISSUE TITLE
StyleTransfer Data Augmentation Layer

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#179]
I'll write a design for this

**Comment by qlzh727** [comment]
Let me know if you want to include this in the 0.1 release.

**Comment by LukeWood** [comment]
> Let me know if you want to include this in the 0.1 release.

Sorry, just saw this message.  I think the project is too ambiguous and the timeline too long to hold off on v1.  Hopefully we can get it implemented soon.

**Comment by LukeWood** [comment]
Deprioritizing this as its been stale for a long time; and the impact is unclear.
