### ISSUE TITLE
keras_cv.models.YOLOV8Detector.from_preset("efficientnetv2_b2_imagenet") fails

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#1793]
TypeError: YOLOV8Detector.__init__() missing required positional argument: 'backbone'

Also, it tries to provide multiple "num_classes" values.  Lets add a polish to this flow.

**Comment by ianstenbit** [comment]
This looks like it's because the init args are in a different order for `YOLOV8Detector` vs `RetinaNet`. I'll try to send a fix today. I assume you know how to work around in the meantime @LukeWood

**Comment by LukeWood** [comment]
Yes sir, just filing bugs as I demo the API a bit :)
