### ISSUE TITLE
BoxCOCOMetrics do not handle Ragged prediction inputs properly

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#1795]
```
def print_metrics(metrics):
    maxlen = max([len(key) for key in result.keys()])
    print("Metrics:")
    print("-" * (maxlen + 1))
    for k, v in metrics.items():
        print(f"{k.ljust(maxlen+1)}: {v.numpy():0.2f}")

coco_metrics.reset_state()

for images, y_true in tqdm.tqdm(iter(eval_ds)):
  y_pred = model.predict(images, verbose=0)
  coco_metrics.update_state(y_true, y_pred)

result = coco_metrics.result(force=True)
print_metrics(result)
```

is broken, but by simply inserting:

```
  y_pred = keras_cv.bounding_box.to_dense(y_pred, max_boxes=32)
```
after the y_pred line, it works again.  This indicates that the box metrics dont know how to handle ragged inputs.

**Comment by james77777778** [comment]
Hi @LukeWood 

I have investigated this bug a few days ago while attempting to reproduce YOLOV8 results.

Here is my solution:

https://github.com/keras-team/keras-cv/blob/15e19c590772c7c80994b9f2ea0d02076553949d/keras_cv/metrics/coco/pycoco_wrapper.py#L124-L145

will fail to ragged predictions.

This issue can be resolved by

```python
def _convert_predictions_to_coco_annotations(predictions):
    coco_predictions = []
    num_batches = len(predictions["source_id"])
    for i in range(num_batches):
        # no yxyx_to_xywh
        batch_size = predictions["source_id"][i].shape[0]
        for j in range(batch_size):
            max_num_detections = predictions["num_detections"][i][j]
            for k in range(max_num_detections):
                ann = {}
                ann["image_id"] = predictions["source_id"][i][j]
                ann["category_id"] = predictions["detection_classes"][i][j][k]  # <-
                ann["bbox"] = predictions["detection_boxes"][i][j][k]  # <-
                ann["score"] = predictions["detection_scores"][i][j][k]  # <-
                coco_predictions.append(ann)

    for i, ann in enumerate(coco_predictions):
        ann["id"] = i + 1

    return coco_predictions
```

With the combined improvement in

https://github.com/keras-team/keras-cv/blob/15e19c590772c7c80994b9f2ea0d02076553949d/keras_cv/callbacks/pycoco_callback.py#L103-L116

To convert the format of the bounding boxes to `xywh` to avoid the transformation in numpy (`_yxyx_to_xywh`)

```python
        box_pred = bounding_box.convert_format(
            box_pred, source=self.bounding_box_format, target="xywh"
        )

        predictions = {
            "source_id": [source_ids],
            "detection_boxes": [box_pred],
            "detection_classes": [cls_pred],
            "detection_scores": [confidence_pred],
            "num_detections": [valid_det],
        }

        metrics = compute_pycoco_metrics(ground_truth, predictions)
```

After making the modification, I was able to the training script without any issues. However, I didn't verify the numeric results.

I can submit a PR for the fix.

**Comment by LukeWood** [comment]
> Awesome! this all looks great - other than:
> 
> ```
>     box_pred = bounding_box.convert_format(
>         box_pred, source=self.bounding_box_format, target="xywh"  # <- to xywh, not yxyx
>     )
> ```
> 
> I believe PyCOCOTools requires yxyx. Feel free to double check me, but I believe that is not actually our choice.

Ah wait - looks like it may be double converted!  Feel free to double check this.
