### ISSUE TITLE
Refactor `MobileNetBackbone` for readability

### ISSUE THREAD

**Issue by jbischof** [keras-team/keras-cv#1806]
Our backbone modeling files are very large and hard to read. @LukeWood proposed two changes in #1745:

1. move aliases to their own file
2. move helpers below model declarations

#1745 provides a nice template for this change but sat around for a long time and now has big merge conflicts. Replicate this change rebased on the current master for `keras_cv/models/backbones/mobilenet_v3/`.

**Comment by ID6109** [comment]
I'll be starting/resuming work on #1637 , #1635 , #1634 , and #1628 next week. I'll implement the improvement suggested in #1745 in the PRs for these anyway, so how about I take up this, #1807 , #1808 , and #1809 as well? If all goes to plan, we should have ready-to-review PRs for all the issues mentioned by the end of the month.

**Comment by jbischof** [comment]
I assigned you #1759 but can you also comment on #1807, #1808, and #1809? Otherwise it won't let me. Thanks!

**Comment by jbischof** [comment]
@ID6109 really appreciate your help! Re: backbone conversions let's take one or two at time since it would take too long for a single person to do all of them.

**Comment by ID6109** [comment]
@jbischof I have #1642 , #1643 , #1649 , #1759 , and #1829 open for these conversions. Should I pause my work for #1635 , #1634 , and #1628 ?

**Comment by ID6109** [comment]
Thanks @jbischof! I'm comfortable with simultaneously working on my open PRs as of now. Most of these issues have been assigned to me, and I am taking up the rest because they have gone stale. I've earlier commented for #1649 (on #1630) and #1829 (on #1637). I'll also comment on #1635 and #1628 so they're formally assigned to me.

**Comment by jbischof** [comment]
@ID6109 I think the right strategy is to get assignments for what you can work on in the next week or so and then pick up more if you have time. This is a TON of work 😅

**Comment by ID6109** [comment]
I have PRs open for all the issues assigned to me. I'll focus on the comments I get on these for now rather than going for more. Thanks!
