### ISSUE TITLE
Refactor `ResNetBackbone` for readability

### ISSUE THREAD

**Issue by jbischof** [keras-team/keras-cv#1808]
Our backbone modeling files are very large and hard to read. @LukeWood proposed two changes in #1745:

1. move aliases to their own file
2. move helpers below model declarations

#1745 provides a nice template for this change for `MobileNetBackbone`. Replicate this change for `keras_cv/models/backbones/resnet_v1/`.

**Comment by ID6109** [comment]
[Here](https://github.com/keras-team/keras-cv/issues/1806#issuecomment-1555380503)
