### ISSUE TITLE
Utility function to visualize bounding boxes overlaid on images

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#181]

**Comment by innat** [comment]
@LukeWood It's been opened. 
https://github.com/keras-team/keras-cv/issues/174

**Comment by kartik4949** [comment]
@LukeWood 
a wrapper around this?

```
tf.image.draw_bounding_boxes
```

**Comment by innat** [comment]
cc. @bhack

```
tfio.experimental.image.draw_bounding_boxes(
    images, boxes, texts=None, colors=None, name=None
)
```

( Isn't it possible to **unify** the similar functions in TensorFlow? )

**Comment by bhack** [comment]
TF IO has an useful extra text arg:

https://github.com/keras-team/keras-cv/pull/373#issuecomment-1111313645

**Comment by kartik4949** [comment]
> TF IO has an useful extra text arg:
> 
> [#373 (comment)](https://github.com/keras-team/keras-cv/pull/373#issuecomment-1111313645)

very useful for multi class

**Comment by LukeWood** [comment]
Yes lets just use tf.io in this repo.

**Comment by bhack** [comment]
> Yes lets just use tf.io in this repo.

Are you sure? As generally I supposed we don't want to create dependencies on other SIGs.

**Comment by bhack** [comment]
> Yes lets just use tf.io in this repo.

It seems this is not the case as we are going to re-implement a python version https://github.com/keras-team/keras-cv/issues/300#issuecomment-1111401986
