### ISSUE TITLE
Bug with model.save()

### ISSUE THREAD

**Issue by hugopi** [keras-team/keras-cv#1812]
Hi !

I am working with retinaNet model and I want to save and reload the model. However when I use model.save(file_path), I got the following error : 
```
WARNING:absl:Found untraced functions such as retina_net_label_encoder_layer_call_fn, retina_net_label_encoder_layer_call_and_return_conditional_losses, anchor_generator_layer_call_fn, anchor_generator_layer_call_and_return_conditional_losses, multi_class_non_max_suppression_3_layer_call_fn while saving (showing 5 of 109). These functions will not be directly callable after loading.
Traceback (most recent call last):
  File "/snap/pycharm-community/332/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/home/hugo/miniconda3/envs/sinbad/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/hugo/miniconda3/envs/sinbad/lib/python3.10/site-packages/tensorflow/python/saved_model/nested_structure_coder.py", line 206, in do_encode
    encoded_dict.dict_value.fields[key].CopyFrom(encode_fn(value))
TypeError: 3 has type int, but expected one of: bytes, unicode

```

Is model.save() working on kerasCV models ? 

Thank you in advance 

Hugo PIRES

**Comment by jbischof** [comment]
Thanks @hugopi could you provide us with a minimal colab to replicate the error?

Just create a colab and save as a github gist.

**Comment by jbischof** [comment]
Using the new keras format instead yields a different error:
```
TypeError: 'dict' object is not callable
```

**Comment by ianstenbit** [comment]
I've confirmed that we're seeing the same issue with YOLOV8 and I've update your PR. 

The fact that this is also happening with YOLOv8 rules out this being the default anchor generator -- looks like it is definitely due to extraction of features from backbone. I'm looking for a fix.

**Comment by ianstenbit** [comment]
Looks like for YOLOV8, model saving _is_ working in the new Keras format. But not the TF format (same error).

The Keras format error for RetinaNet seems to be due to deserialization of the `box_head` parameter.
