### ISSUE TITLE
Import Error in Databricks

### ISSUE THREAD

**Issue by LeoAtSA** [keras-team/keras-cv#1814]
Title: `ImportError` in Databricks

Hi, I'm using the `keras-cv` library in a databricks environment ML 13.0 but I am getting an `ImportError: cannot import name 'builder' from 'from google.protobuf.internal import builder'` when I run import `keras_cv`. 

I've tried various solutions that I found on StackOverflow, such as:
- Uninstalling and reinstalling the `protobuf` package 
- Installing a specific version of the `protobuf` package (

None of these solutions have worked as the `protobuf` package is a part of the runtime and is not possible to change.

Has anyone else experienced this issue or does anyone know how to resolve it? Any help would be appreciated. 

Thank you!

Environment details:
- Databricks runtime: 13.0 ML ([list of all packages](https://docs.databricks.com/release-notes/runtime/13.0ml.html))

Note: Have also contacted Databricks re this

**Comment by jbischof** [comment]
@LeoAtSA thanks for reaching out! We aren't familiar with the Databricks platform and the error seems related to another library. Would it be possible to reach out on a Databricks-specific forum and reopen this issue if you're still having trouble?
