### ISSUE TITLE
[Bug] Loading saved models fails with Functional Subclassing API

### ISSUE THREAD

**Issue by DavidLandup0** [keras-team/keras-cv#1816]
This seems to be an issue with core Keras, and I've encountered it before in other personal projects. It looks like the Functional Subclassing API has some issues with loading saved models without specifying backbone classes are custom objects:

```
import keras_cv

efficientnet = keras_cv.models.EfficientNetV2Backbone.from_preset(
        "efficientnetv2_s"
    )
images = tf.ones((1, 256, 256, 3))
outputs = efficientnet.predict(images)

efficientnet.save('model2.keras')
efficientnet = tf.keras.models.load_model('model2.keras')
```

On the last line, we're hit with a:

```
ValueError: Unknown layer: 'EfficientNetV2Backbone'. Please ensure you are using a `keras.utils.custom_object_scope` and that this object is included in the scope. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
```

However, running:

```
tf.keras.utils.get_custom_objects()
```

...clearly shows that it is in fact, registered:

```
...
 'keras_cv.models>EfficientNetV2Backbone': keras_cv.models.backbones.efficientnet_v2.efficientnet_v2_backbone.EfficientNetV2Backbone,
...
```

**Comment by jbischof** [comment]
Interesting @DavidLandup0! We do have test coverage for this use case ([code](https://github.com/keras-team/keras-cv/blob/9ca2684503cba9c357e338bbaf5646cb226d16e6/keras_cv/models/backbones/efficientnet_v2/efficientnet_v2_backbone_test.py#L90)).

Would you be able to supply a colab replicating the issue? Happy to play around with this.

**Comment by DavidLandup0** [comment]
Yep! Here's a colab notebook: https://colab.research.google.com/drive/1XMFTFXZbJoP7ic2zD2UByvZV-AjlmOtR?usp=sharing

**Comment by ianstenbit** [comment]
Interesting -- if we don't use ".keras" in the name (and therefore just use the default TF save format), this seems to work.
@DavidLandup0 you should be able to use that as a workaround for now, but I'm still digging to find the root cause for the Keras format.

**Comment by jbischof** [comment]
Funny, I was just noticing the same thing @ianstenbit

**Comment by ianstenbit** [comment]
> Funny, I was just noticing the same thing @ianstenbit. Still unclear why we get a different result in our unit test.

I think this is because we explicitly set `save_format="keras_v3"` when using the `.keras` extension and `save_format="tf"` when excluding the `.keras` extension. IIRC there is some magic to pick a format based on file extension and this could be part of the issue.

**Comment by jbischof** [comment]
Ah, but also in future versions of Keras this will also be the default so this problem will resolve itself over time.

**Comment by ianstenbit** [comment]
@DavidLandup0 let me know if explicitly using `save_format="keras_cv"` doesn't work for you and we can do some more digging 😄 

Stoked to see you back on the repo!

**Comment by DavidLandup0** [comment]
> Interesting -- if we don't use ".keras" in the name (and therefore just use the default TF save format), this seems to work.
@DavidLandup0 you should be able to use that as a workaround for now, but I'm still digging to find the root cause for the Keras format.

Yes, the tf format works for an (unknown) but welcome reason! I'll use it or the `keras_v3` format instead then. It'd be great to have it plastered clearly somewhere, as inertia will keep people using legacy formats (I instinctively still try to save `.h5` files).

Thank you for the quick response and investigation!

> Stoked to see you back on the repo!
Thank you! Stoked to be back - I've been quite busy for the past few months 😅
