### ISSUE TITLE
model.summary() fails with YOLO_v8

### ISSUE THREAD

**Issue by Djkmarco** [keras-team/keras-cv#1818]
Tensorflow 2.11.0

```
import tensorflow as tf
import keras_cv as kcv


def build_model(n_classes: int, bounding_box_format: str, yolov8_version: str, fpn_depth: int):

    backbone = kcv.models.YOLOV8Backbone.from_preset('yolo_v8_' + yolov8_version + '_backbone')
    backbone.include_rescaling = True
    label_encoder = kcv.models.object_detection.yolo_v8.YOLOV8LabelEncoder(num_classes=n_classes, max_anchor_matches=10,
                                                                           alpha=0.6, beta=6.0)

    prediction_decoder = kcv.layers.MultiClassNonMaxSuppression(
                                                                bounding_box_format=bounding_box_format,
                                                                from_logits=False,
                                                                iou_threshold=1,
                                                                confidence_threshold=0,
                                                                max_detections=50,
                                                                max_detections_per_class=20
                                                                )

    detector = kcv.models.YOLOV8Detector(num_classes=n_classes, bounding_box_format=bounding_box_format,
                                         backbone=backbone, prediction_decoder=prediction_decoder,
                                         fpn_depth=fpn_depth, label_encoder=label_encoder)

    opt = tf.keras.optimizers.Adam(learning_rate=0.001)
    detector.compile(optimizer=opt, box_loss='iou', classification_loss='binary_crossentropy', jit_compile=False)
    return detector

detector = build_model(n_classes=9, bounding_box_format='xyxy', yolov8_version='xs', fpn_depth=3)

detector.summary()
```

>  Cell In[21], line 1
> ----> 1 detector.summary()
> 
> File [~/.cache/pypoetry/virtualenvs/yolov8-Gf8kLGOB-py3.10/lib/python3.10/site-packages/keras/engine/training.py:3297](https://file+.vscode-resource.vscode-cdn.net/home/franzo/AGVisionAI/YOLOv8_ST3/~/.cache/pypoetry/virtualenvs/yolov8-Gf8kLGOB-py3.10/lib/python3.10/site-packages/keras/engine/training.py:3297), in Model.summary(self, line_length, positions, print_fn, expand_nested, show_trainable, layer_range)
>    3291 if not self.built:
>    3292     raise ValueError(
>    3293         "This model has not yet been built. "
>    3294         "Build the model first by calling `build()` or by calling "
>    3295         "the model on a batch of data."
>    3296     )
> -> 3297 layer_utils.print_summary(
>    3298     self,
>    3299     line_length=line_length,
>    3300     positions=positions,
>    3301     print_fn=print_fn,
>    3302     expand_nested=expand_nested,
>    3303     show_trainable=show_trainable,
>    3304     layer_range=layer_range,
>    3305 )
> 
> File [~/.cache/pypoetry/virtualenvs/yolov8-Gf8kLGOB-py3.10/lib/python3.10/site-packages/keras/utils/layer_utils.py:430](https://file+.vscode-resource.vscode-cdn.net/home/franzo/AGVisionAI/YOLOv8_ST3/~/.cache/pypoetry/virtualenvs/yolov8-Gf8kLGOB-py3.10/lib/python3.10/site-packages/keras/utils/layer_utils.py:430), in print_summary(model, line_length, positions, print_fn, expand_nested, show_trainable, layer_range)
>     423         print_fn(
>     424             "|" * nested_level
>     425             + " " * (line_length - 2 * nested_level)
>     426             + "|" * nested_level
>     427         )
>     429 for layer in model.layers[layer_range[0] : layer_range[1]]:
> --> 430     print_layer(layer)
>     431 print_fn("=" * line_length)
>     433 if hasattr(model, "_collected_trainable_weights"):
> 
> File [~/.cache/pypoetry/virtualenvs/yolov8-Gf8kLGOB-py3.10/lib/python3.10/site-packages/keras/utils/layer_utils.py:400](https://file+.vscode-resource.vscode-cdn.net/home/franzo/AGVisionAI/YOLOv8_ST3/~/.cache/pypoetry/virtualenvs/yolov8-Gf8kLGOB-py3.10/lib/python3.10/site-packages/keras/utils/layer_utils.py:400), in print_summary..print_layer(layer, nested_level, is_nested_last)
>     398     print_layer_summary(layer, nested_level)
>     399 else:
> --> 400     print_layer_summary_with_connections(layer, nested_level)
>     402 if expand_nested and hasattr(layer, "layers") and layer.layers:
>     403     print_fn(
>     404         "|" * (nested_level + 1)
>     405         + "¯" * (line_length - 2 * nested_level - 2)
>     406         + "|" * (nested_level + 1)
>     407     )
> 
> File [~/.cache/pypoetry/virtualenvs/yolov8-Gf8kLGOB-py3.10/lib/python3.10/site-packages/keras/utils/layer_utils.py:387](https://file+.vscode-resource.vscode-cdn.net/home/franzo/AGVisionAI/YOLOv8_ST3/~/.cache/pypoetry/virtualenvs/yolov8-Gf8kLGOB-py3.10/lib/python3.10/site-packages/keras/utils/layer_utils.py:387), in print_summary..print_layer_summary_with_connections(layer, nested_level)
>     382 name = layer.name
>     383 cls_name = layer.__class__.__name__
>     384 fields = [
>     385     name + " (" + cls_name + ")",
>     386     output_shape,
> --> 387     layer.count_params(),
>     388     connections,
>     389 ]
>     391 if show_trainable:
>     392     fields.append("Y" if layer.trainable else "N")
> 
> File [~/.cache/pypoetry/virtualenvs/yolov8-Gf8kLGOB-py3.10/lib/python3.10/site-packages/keras/engine/base_layer.py:2143](https://file+.vscode-resource.vscode-cdn.net/home/franzo/AGVisionAI/YOLOv8_ST3/~/.cache/pypoetry/virtualenvs/yolov8-Gf8kLGOB-py3.10/lib/python3.10/site-packages/keras/engine/base_layer.py:2143), in Layer.count_params(self)
>    2141             self._maybe_build(self.inputs)
>    2142     else:
> -> 2143         raise ValueError(
>    2144             "You tried to call `count_params` "
>    2145             f"on layer {self.name}"
>    2146             ", but the layer isn't built. "
>    2147             "You can build it manually via: "
>    2148             f"`{self.name}.build(batch_input_shape)`."
>    2149         )
>    2150 return layer_utils.count_params(self.weights)
> 
> ValueError: You tried to call `count_params` on layer yolov8_label_encoder, but the layer isn't built. You can build it manually via: `yolov8_label_encoder.build(batch_input_shape)`.
> 
>

**Comment by jbischof** [comment]
The error is correct: you need to build the model! Either give an `input_shape` to the `backbone` model or call it on some data.

**Comment by jbischof** [comment]
Please reopen @Djkmarco if you're not able to fix

**Comment by Djkmarco** [comment]
Thank you @jbischof.

I was not able do fix. Can you provide a modified version of the code?

**Comment by jbischof** [comment]
No worries @Djkmarco. Can you provide a minimal colab reproducing the issue?

**Comment by innat** [comment]
```python
import keras_cv

with strategy.scope():
    model = keras_cv.models.YOLOV8Detector(
        num_classes=1,
        backbone=keras_cv.models.YOLOV8Backbone.from_preset("yolo_v8_m_backbone"),
        fpn_depth=2,
        bounding_box_format="xywh",
    )
    model.compile(
        optimizer='adam', 
        box_loss="iou", 
        classification_loss="binary_crossentropy"
    )
model.summary()
```

**Comment by jbischof** [comment]
@innat your code snippet has the same problem highlighted in the error message: you need to give a concrete input size! By default the backbone uses `(None, None, 3)`, which allows for input images of any size. Obviously the feature maps of a given kernel will be bigger for a bigger image.

**Comment by innat** [comment]
The problem is that here the `model.summary` starts printing but in the middle it fails because of not building the label encoder. Calling the whole model on dummy tensor `(model(tf.ones((..)))` or  `model.build(input_shape(...))` don't work here.

> ValueError: You tried to call count_params on layer yolov8_label_encoder, but the layer isn't built. You can build it manually via: yolov8_label_encoder.build(batch_input_shape)

It looks like I need to call [this layer](https://github.com/keras-team/keras-cv/blob/c83504f9904d9db5a0274607704557ec13b8007c/keras_cv/models/object_detection/yolo_v8/yolo_v8_label_encoder.py#L93) manually on some dummy input.

**Comment by jbischof** [comment]
That's why I was asking for a colab @innat! I'm going to update the Issues template to ask for this for all bugs. It's impossible to debug an error message without context.

**Comment by jbischof** [comment]
Thank you this is very helpful @innat!

**Comment by innat** [comment]
retina-net looks ok. (updated the gist)

**Comment by ianstenbit** [comment]
Just took a look, and I see the issue. We can just overwrite `count_params` on the LabelEncoder to return 0, because it doesn't have any weights.

I am, however, seeing that the resulting summary includes the backbone twice, which is clearly not correct. I'll dig into that.

**Comment by ianstenbit** [comment]
Thanks for the issue report @Djkmarco!

I've just opened two PRs (above) which should clean up the YOLOV8 summary.

**Comment by Djkmarco** [comment]
Thanks for the great fix!
