### ISSUE TITLE
Utility function to visualize segmentation maps on images

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#182]

**Comment by innat** [comment]
@LukeWood It's been opened. 
https://github.com/keras-team/keras-cv/issues/174

**Comment by kartik4949** [comment]
@LukeWood @innat 
Hey,
so I was thinking to have something like

```
from keras-cv.visualize import bbox_visualizer
# single image
image_with_bbox = bbox_visualizer.draw(image, bbox, line=1, color="gray")

#batch of image
images_with_bboxes = bbox_visualizer.draw(images, bboxes, line=1, color="gray")
```

**Comment by kartik4949** [comment]
```
from keras-cv import visualizer
bbox_visualizer = visualizer.Visualizer(type="bbox", color=visualizer.color.RED, line=1")
```
Alternative

**Comment by LukeWood** [comment]
The KerasCV team is attempting to narrow the package scope in order to more efficiently use our limited resources. As such, we are only accepting contributions directly related to items on the 6 month roadmap for the package.

If you feel this feature could be particularly useful, or would like to contribute it - please feel free to re-open this issue and ping LukeWood, ianstenbit or tanzhenyu

Feel free to read more on the roadmap:
https://github.com/keras-team/keras-cv/blob/master/.github/ROADMAP.md
