### ISSUE TITLE
Change `pyramid_level_inputs` to have string keys

### ISSUE THREAD

**Issue by jbischof** [keras-team/keras-cv#1820]
Currently `pyramid_level_inputs` uses `int` keys, but this breaks serialization (#1812). We patched this up in #1815 at the Task level, but a better fix is to change this attribute to use string keys in all the backbones ([example](https://github.com/keras-team/keras-cv/blob/ef7707f87362eb340190c71baa5b0b5d7f344a40/keras_cv/models/backbones/resnet_v2/resnet_v2_backbone.py#L359)) and in its docstring ([link](https://github.com/keras-team/keras-cv/blob/ef7707f87362eb340190c71baa5b0b5d7f344a40/keras_cv/models/backbones/backbone.py#L159)).

After that we can remove the ad hoc fix in the OD tasks themselves.

**Comment by avinair** [comment]
@jbischof Since we would be changing the datatype to strings, does it make sense to change the keys from <int_value> to "P<int_value>"? For example: the key 3 would become 'P3' instead. For now, I'll proceed with just changing it to '3' but let me know if you prefer 'P3' instead?

**Comment by jbischof** [comment]
Great, assigned to you @avinair! Let's leave the keys as `"3"` for now since `"P3"` won't add information.

**Comment by jbischof** [comment]
Actually @avinair I've changed my mind! I think `"P3"` might add readability to the code since it's standard notation in the literature. Let's try that!

**Comment by avinair** [comment]
@jbischof Will do!
