### ISSUE TITLE
Support Segmentation Maps in Resizing Layer

### ISSUE THREAD

**Issue by ariG23498** [keras-team/keras-cv#1830]
It would be really helpful is the `Resizing` layer supports segmentation maps.

**Comment by ayulockin** [comment]
cc: @cosmo3769 wanna take a stab maybe?

**Comment by cosmo3769** [comment]
@ayulockin Yes, I would love to take this. Please assign me this. Thank you. @ianstenbit @LukeWood

**Comment by jbischof** [comment]
Thank you @cosmo3769!
