### ISSUE TITLE
classification model loading with weight

### ISSUE THREAD

**Issue by pure-rgb** [keras-team/keras-cv#1833]
When we use the backbone model, how in keras cv let's load the model with pretrained weight and also customizing the parameters? For example, in the [doc](https://keras.io/guides/keras_cv/classification_with_keras_cv/)

```
backbone = keras_cv.models.EfficientNetV2B1Backbone()
model = keras.Sequential(
    [
        backbone,
        keras.layers.GlobalMaxPooling2D(),
        keras.layers.Dropout(rate=0.5),
        keras.layers.Dense(101, activation="softmax"),
    ]
)
```

Here how should we init the backbone with pretraiend weight but also changing the input shape, input scale method, etc? Like, how to:

```
backbone = keras_cv.models.EfficientNetV2B1Backbone(weight='imagenet', input_shape=.., include_scale=False)
```

**Comment by DavidLandup0** [comment]
You can initialize a pretrained backbone as:

```
backbone = keras_cv.models.EfficientNetV2Backbone.from_preset("efficientnetv2_b1_imagenet")
```

**Comment by jbischof** [comment]
@pure-rgb you just pass them as `kwargs`. Anything you can pass to the generic constructor can be overriden here. For example

```python
backbone = EfficientNetV2Backbone.from_preset(
    "efficientnetv2_b1_imagenet",
    include_rescaling=True,
)
```
