### ISSUE TITLE
CIoU Loss YOLOv8

### ISSUE THREAD

**Issue by IMvision12** [keras-team/keras-cv#1836]
Isn't this CIoU Loss?

https://github.com/keras-team/keras-cv/blob/b514c84650bc2851826e63328a6185077d7c747b/keras_cv/models/object_detection/yolo_v8/yolo_v8_iou_loss.py#L58

Should we rename: YOLOV8IoULoss -> YOLOV8CIoULoss

Also, should we add a separate layer in keras_cv.losses for CIoU and DIoU Loss?

@ianstenbit @jbischof

**Comment by ianstenbit** [comment]
I had originally intended to support CIoU in IoU loss, but upon reflection I think this _should_ be its own API.

So yes, we should rename this to `CIoULoss` and move it to `keras_cv.losses`!

**Comment by IMvision12** [comment]
You can assign this to me, working on it!
