### ISSUE TITLE
Replace `tf` with `np` for constants in tests

### ISSUE THREAD

**Issue by ianstenbit** [keras-team/keras-cv#1853]
In tests, wherever we're creating constants like `tf.constant` or `tf.ones` or `tf.zeros`, we should instead do this with `np.array`, `np.ones`, or `np.zeros`.

If someone wants to take this on, feel free to send it as one big PR.

**Comment by ID6109** [comment]
I'll send a PR for this once the open PRs for backbone conversions are managed.

**Comment by Seydifa** [comment]
I want to work in this if you allow me

**Comment by ID6109** [comment]
I don't think this will need a collaborative effort @Seydifa. In case I need any assistance, I will surely let you know. Thanks!

**Comment by ianstenbit** [comment]
I am open to either of you making this change, or if you'd like you can split up the tests and each do some of them.

@ID6109 since you've got some more experience contributing to KerasCV, this might be a good issue to leave to a newer community member 😄

**Comment by ID6109** [comment]
Haha, I see. No worries, in that case @Seydifa, feel free to take this up. I'd recommend waiting for conversions to be dealt with first, or this might cause major merge conflicts.

**Comment by ianstenbit** [comment]
This is largely fixed now, as all tests running Keras Core use Numpy necessarily. There are some stragglers that use TF, which are the test for yet-unported components. Those can be cleaned up as the components are ported to Keras Core.

**Comment by ID6109** [comment]
I can send in a PR here that'll lighten some of the workload for the port @ianstenbit

**Comment by ianstenbit** [comment]
> I can send in a PR here that'll lighten some of the workload for the port @ianstenbit

It's not a huge lift, but do feel free to send PRs to update tests (just not in one huge batch please!)
