### ISSUE TITLE
GCB tests failing on OOM

### ISSUE THREAD

**Issue by jbischof** [keras-team/keras-cv#1875]
Our current GCB testing fails due to OOM. I have tried small fixes in #1874, but they haven't worked. The fact is that relatively small memory allocations (~400MB in the linked PR) are triggering the failure, which makes me wonder if garbage collection is even happening correctly.

Some brute force options:
* Stop testing legacy code
* Request an accelerator with more RAM

**Comment by ianstenbit** [comment]
This is no longer failing
