### ISSUE TITLE
Broken File Links in Keras Stable DIffusion Docs

### ISSUE THREAD

**Issue by tochibedford** [keras-team/keras-cv#1876]
https://www.tensorflow.org/tutorials/generative/generate_images_with_stable_diffusion#wait_how_does_this_even_work

In the  "Wait how does this even work?" Section, the following links to files in the repo are broken:
![image](https://github.com/keras-team/keras-cv/assets/34871260/66919e1e-613d-4c8e-bbde-26b64835b25f)

**Comment by ID6109** [comment]
Thanks for pointing this out @tochibedford! This should have been fixed by [this](https://github.com/keras-team/keras-io/pull/1162) PR.

**Comment by tochibedford** [comment]
wow, over 6 months ago. I wonder why it doesn’t reflect on the main site yet, maybe it was part of a failed build? @ID6109

**Comment by ID6109** [comment]
The TensorFlow guide has yet to be updated since 2022-12-09 UTC. For now, might I recommend referring to the Keras.io guide [here](https://keras.io/guides/keras_cv/generate_images_with_stable_diffusion/)? Thanks!

**Comment by jbischof** [comment]
cc @MarkDaoust for syncing issues with keras-io

**Comment by MarkDaoust** [comment]
Ack. I'll look into it.
