### ISSUE TITLE
Add Table for bbox and segmentation

### ISSUE THREAD

**Issue by IMvision12** [keras-team/keras-cv#1878]
**Short Description**

Add a table representing which layer is supports bbox/segmentation in `README.md`

something like:

| Layer Name | Image | Masks | BBoxes |
| ----| :---: | :---: | :----: |
| RandomFlip  | ✓     | ✓     | ✓      |

@ianstenbit @jbischof

**Comment by ianstenbit** [comment]
I think a README under `layers/preprocessing` that shows this would be great, especially if we could mirror it on our KerasIO docs.

**Comment by ariG23498** [comment]
I would like to work on this! -- This will also help me understand which pre-processing layer needs segmentation and bbox support.
