### ISSUE TITLE
I've copy-pasted retinanet training example to colab. It fails

### ISSUE THREAD

**Issue by nkonovalchuk** [keras-team/keras-cv#1883]
It's failing at the end of the first epoch here. It failed the same way mid epoch when I tried using my private dataset. 
Using YOLOv8 also results in a fail.
Logs:
```
Epoch 1/100
4138/4138 [==============================] - ETA: 0s - loss: 0.9988 - box_loss: 0.4388 - classification_loss: 0.5600 - percent_boxes_matched_with_anchor: 0.9110

---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

[<ipython-input-18-816f3ea473f9>](https://localhost:8080/#) in <cell line: 1>()
----> 1 history = model.fit(
      2     train_ds,
      3     validation_data=eval_ds,
      4     epochs=FLAGS.epochs,
      5     callbacks=callbacks,

1 frames

[/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py](https://localhost:8080/#) in converted_call(f, args, kwargs, caller_fn_scope, options)
    437     try:
    438       if kwargs is not None:
--> 439         result = converted_f(*effective_args, **kwargs)
    440       else:
    441         result = converted_f(*effective_args)

TypeError: in user code:
https://colab.research.google.com/drive/1pYE4gv3yfQ14JaQcpbAxKwd0Gh6uNsvf?usp=sharing

    TypeError: outer_factory.<locals>.inner_factory.<locals>.tf__images_only() takes 1 positional argument but 2 were given
```
Colab link:
https://colab.research.google.com/drive/1pYE4gv3yfQ14JaQcpbAxKwd0Gh6uNsvf?usp=sharing
Code from:
https://github.com/keras-team/keras-cv/blob/master/examples/training/object_detection/pascal_voc/retinanet.py#L52

**Comment by IMvision12** [comment]
@nkonovalchuk once try following this tutorial: https://keras.io/guides/keras_cv/object_detection_keras_cv/

**Comment by ianstenbit** [comment]
Looks like this was due to the change to the COCO callback to use dictionaries

It looks like the issue is that `pad_fn` is returning the tuple-style of data inputs but our COCO callback expects the dict-style. Should be something like this:

```
def pad_fn(inputs):
    inputs["bounding_boxes"] = keras_cv.bounding_box.to_dense(
        inputs["bounding_boxes"], max_boxes=32
    )
    return inputs
```

Feel free to send a PR to update the training example, and in the meantime, +1 to @IMvision12's comment -- the guide is the best source of truth!

**Comment by nkonovalchuk** [comment]
@IMvision12 This tutorial consistently crashes at https://github.com/keras-team/keras-io/blob/8f49b3ec63c7d959b9457ab7cc961ce4ca922d2f/guides/keras_cv/object_detection_keras_cv.py#L652 due to some shape mismatch

**Comment by nkonovalchuk** [comment]
@ianstenbit this fixes the initial issue, but now it restarts the kernel at eval time due to "out of RAM". I guess it's out of Graphical RAM. 
Failing at eval time after a full successful training epoch seems like something that should not happen
