### ISSUE TITLE
RetinaNet Custom Feature Pyramid 

### ISSUE THREAD

**Issue by gianlucasama** [keras-team/keras-cv#1884]
Hi! I'd like to request a simple feature: the possibility of initializing the RetinaNet class using a custom "feature_pyramid", much like the "box_head" and "classification_head" parameters. It shouldn't take that much time to add this feature in, and it would make it a lot easier to create a completely custom object detector using the RetinaNet meta-architecture. In my case, I'm trying to build a RetinaNet detector using MobileNetV1's convolutional blocks, which I'd like to try in the feature pyramid too. Thanks for your time and for the incredible work you've been doing on this library!

**Comment by jbischof** [comment]
Hi @gianlucasama, we can support this but if you just want to use another backbone from our library this will work automatically! We accomplish this using a `pyramid_level_inputs` property to expose intermediate layers ([link](https://github.com/keras-team/keras-cv/blob/b3798d8140605b651ac46f40fe7072ea08175720/keras_cv/models/backbones/backbone.py#L164)).

We don't have MobileNetV1 at this time but we do have V3. If you have your own V1 implementation the easier route is just to implement `pyramid_level_inputs` instead of the whole FPN.

**Comment by gianlucasama** [comment]
I'm sorry if I haven't been clear enough before: I'm not referring to the backbone, but to the keras_cv.models.object_detection.retinanet.FeaturePyramid class, the layer that accepts the "pyramid_level_inputs" of the backbone as inputs. This layer seems to be used by default as the RetinaNet's feature pyramid, and there is no way to use another, custom, feature pyramid. My request is to add something along these lines:
``````
class RetinaNet(Task):
    def __init__(
        self,
        backbone,
        num_classes,
        bounding_box_format,
        anchor_generator=None,
        label_encoder=None,
        prediction_decoder=None,
        feature_pyramid=None, # New parameter
        classification_head=None,
        box_head=None,
        **kwargs,
    ):

        # Existing code
        feature_pyramid = FeaturePyramid()

        # New code
        feature_pyramid = feature_pyramid or FeaturePyramid()
``````
So that any compliant layer can be used as the "feature_pyramid" of the RetinaNet model.

**Comment by jbischof** [comment]
Makes sense @gianlucasama, I was just curious why a custom FPN is needed since it's basically part of the model architecture. I wanted to point out if you just want to bring a custom backbone we can already accommodate that.

**Comment by gianlucasama** [comment]
As the paper mentions:"many design choices are not crucial". It makes sense to permit custom layers, like the prediction ones that you already have, so that one can create an efficient architecture for the specific task he/she is trying to accomplish. Thank you again for your time, I really hope you'll implement this feature in a next release!

**Comment by jbischof** [comment]
Got it, sounds like you want a custom FPN! Are you interested in contributing a PR?

**Comment by gianlucasama** [comment]
Yeah, sure! I am going to work on it tomorrow.
