### ISSUE TITLE
[YOLOV8Detector] Example related to the YOLOV8Detector model is not working

### ISSUE THREAD

**Issue by alessiosavi** [keras-team/keras-cv#1897]
Hi Team,
The example related to the following link: https://keras.io/api/keras_cv/models/tasks/yolo_v8_detector/ is not working anymore.

The first error is related to the name of the module:
```python
model = keras_cv.models.YOLOV8Detector(
    num_classes=20,
    bounding_box_format="xywh",
    backbone=keras_cv.models.YOLOV8Backbone.from_preset("yolo_v8_m_coco"),
    fpn_depth=2.0,
)
```
The error related to the initialization of `YOLOV8Detector` are the following one:

1. The preset related to the `yolo_v8_m_coco` is no more valid. The error raised is the following one:
```text
ValueError: `preset` must be one of yolo_v8_xs_backbone, yolo_v8_s_backbone, yolo_v8_m_backbone, yolo_v8_l_backbone, yolo_v8_xl_backbone, yolo_v8_xs_backbone_coco, yolo_v8_s_backbone_coco, yolo_v8_m_backbone_coco, yolo_v8_l_backbone_coco, yolo_v8_xl_backbone_coco. Received: yolo_v8_m_coco.
```

2. The `fpn_depth` parameter have to be an integer. The error raised is the following one:
```text
TypeError: 'float' object cannot be interpreted as an integer
```
Using the following initialization, is possible to `predict` using the initialized object:
```python
images = tf.ones(shape=(1, 512, 512, 3))
labels = {
    "boxes": [
        [
            [0, 0, 100, 100],
            [100, 100, 200, 200],
            [300, 300, 100, 100],
        ]
    ],
    "classes": [[1, 1, 1]],
}

model = keras_cv.models.YOLOV8Detector(
    num_classes=20,
    bounding_box_format="xywh",
    backbone=keras_cv.models.YOLOV8Backbone.from_preset("yolo_v8_xs_backbone"),
    fpn_depth=2,
)

# Evaluate model
model(images)  # WORKING
model.predict(images)  # WORKING
```

Related to `compile`:
```python
# Train model
model.compile(
    classification_loss="binary_crossentropy",
    box_loss="ciou",
    optimizer=tf.optimizers.SGD(global_clipnorm=10.0),
    jit_compile=False,
)
```

1. The `box_loss="ciou"` is no more compatible (?). Using it, the following error is raised:
```text
ValueError: Invalid box loss for YOLOV8Detector: ciou. Box loss should be a keras.Loss or the string 'iou'.
```

Related to `fit`:
```python
model.fit(images, labels)
```
1. Using `(images, labels)` the following error is raised:
```python
ValueError: Failed to find data adapter that can handle input: <class 'tensorflow.python.framework.ops.EagerTensor'>, (<class 'dict'> containing {"<class 'str'>"} keys and {'(<class \'list\'> containing values of types {\'(<class \\\'list\\\'> containing values of types {\\\'(<class \\\\\\\'list\\\\\\\'> containing values of types {"<class \\\\\\\'int\\\\\\\'>"})\\\'})\'})', '(<class \'list\'> containing values of types {\'(<class \\\'list\\\'> containing values of types {"<class \\\'int\\\'>"})\'})'} values)
```

What is the correct way to fine tune a YOLOV8Detector in Keras-CV ?

**Comment by IMvision12** [comment]
Hi @alessiosavi I have created and keras.io example(PR under review) so I can answer your questions :)

There's no preset named `yolo_v8_m_coco` instead use `yolo_v8_m_backbone_coco`
Next, fpn_depth should be an integer value :)

```python
backbone = keras_cv.models.YOLOV8Backbone.from_preset(
                "yolo_v8_s_backbone_coco"  # We will use yolov8 small backbone with coco weights
            )

yolo = keras_cv.models.YOLOV8Detector(
            num_classes=len(class_mapping),
            bounding_box_format="xyxy",
            backbone=backbone,
            fpn_depth=1,
        )
```

About `ciou` loss I guess you are using an older version of the repo

use: `pip install git+https://github.com/keras-team/keras-cv.git`

regarding fit method I guess the input format to the model is not correct, input format should be:

```python
bounding_boxes = {
    # num_boxes may be a Ragged dimension
    'boxes': Tensor(shape=[batch, num_boxes, 4]),
    'classes': Tensor(shape=[batch, num_boxes])
}
```

The final dict should be:
```python
{"images": images, "bounding_boxes": bounding_boxes}
```


Here is the Colab notebook which will be available on keras.io in some time : https://colab.research.google.com/drive/1ldH481jQLIzEQNfbig1WoevLTmf5-e6u?usp=sharing

Hope this helps ‎😃

**Comment by alessiosavi** [comment]
Thank you @IMvision12  for the fast reply! I've updated the library using `git` and now the initialization working as expected! However I'm struggling with the shape of the data:
My shapes look like this:
![image](https://github.com/keras-team/keras-cv/assets/31842468/884d6431-8504-4184-a5cd-d82635d5d331)

After transforming and batching to a `tf.data.Dataset`, i've the following shapes:
![image](https://github.com/keras-team/keras-cv/assets/31842468/ef4ad2ea-8b23-42cf-bc0c-3b9ec2bc6587)

The error now is the following one:
```text
ValueError: Unexpected result of `train_function` (Empty logs). Please use `Model.compile(..., run_eagerly=True)`, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file a issue/bug to `tf.keras`.
```

I've tried using `run_eagerly` but the situation does not change.

Here the code to replicate the error.
https://colab.research.google.com/drive/1nLuchziqZjg7um4GXTXQxdtTiCkeBZb2?usp=sharing

In your opinion, is something related to the shape of the data?

**Comment by IMvision12** [comment]
hi, @alessiosavi yeah there are so many shape errors, i have fixed them:
Here's the colab :https://colab.research.google.com/drive/1upVa0zXg06MYDx9v2J8y42xxZQJZitCM?usp=sharing

Explanation:

First of all, you need to cast bbox to float32:

```python
def load_dataset(img, classes, bbox):
    bounding_boxes = {
        "classes": tf.cast(classes, dtype=tf.float32),
        "boxes": tf.cast(bbox, dtype=tf.float32),
    }
    return {"images": tf.cast(img, tf.float32), "bounding_boxes": bounding_boxes}
```
Also,  classes should start with 0, not 1 else yolov8_label_encoder throughs an error: 
```python 
classes = [0] * len(images)
```

Next, your classes list was like this: 

```python
[0,
 0,
 0,    # This whole list corresponds to only 1 image 
 0,    # i.e single image having 110 bbox 😅
 ....
```
this represents only 1 image but we have 110 so we need to expand the dims and convert it to something like this:

```python
array([[0]   -> image1,
       [0],      -> image2,
       [0],      -> image3,
    ....
```
Here each class corresponds to the image :)

if we had multiple class list would look like this:

```python
classes = [
    [8, 8, 8, 8, 8],      # 5 classes
    [12, 14, 14, 14],     # 4 classes
    [1],                  # 1 class
    [7, 7],               # 2 classes
 ...]
```

The same goes for Bbox:  

Before :
```python
[[206, 206, 100, 100],
 [206, 206, 100, 100],
 [206, 206, 100, 100],
....
```

After expand_dims:

```python
array([[[206, 206, 100, 100]],
       [[206, 206, 100, 100]],
       [[206, 206, 100, 100]],
       [[206, 206, 100, 100]],
....
```

If we had multiple bbox for single image then list would look like this:

```python
bbox = [
    [[199.0, 19.0, 390.0, 401.0],
    [217.0, 15.0, 270.0, 157.0],
    [393.0, 18.0, 432.0, 162.0],
    [1.0, 15.0, 226.0, 276.0],
    [19.0, 95.0, 458.0, 443.0]],     #image 1 has 4 objects
    [[52.0, 117.0, 109.0, 177.0]],   #image 2 has 1 object
    [[88.0, 87.0, 235.0, 322.0],
    [113.0, 117.0, 218.0, 471.0]],   #image 3 has 2 objects
 ...]
```

**Comment by alessiosavi** [comment]
Dude you are awesome! Thank you for the time spent.

**Comment by IMvision12** [comment]
hey, @alessiosavi I want to delete those colab notebooks let me know when you are done with them !!!
