### ISSUE TITLE
discrepancy between `model(input)` and `model.predict(input)`

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#1902]
## Description 

I try to inference on a sample with `model(input))` and `model.predict(input)` using retina-net and yolo-v8. Whereas I'm expecting same results but they behave differently. 

**retina-net**

```python
y_pred = retinanet(input)
for k, v in y_pred.items():
    print(k, v.shape)
> box (1, 76725, 4)
> classification (1, 76725, 5)

y_pred = retinanet.predict(input)
for k, v in y_pred.items():
    print(k, v.shape)
> boxes (1, None, 4)
> confidence (1, None)
> classes (1, None)
> num_detections (1,)
```

**yolo-v8**

```python
y_pred = yolo_v8(input)
for k, v in y_pred.items():
    print(k, v.shape)
boxes (1, 8400, 64)
classes (1, 8400, 5)

y_pred = yolo_v8.predict(input)
for k, v in y_pred.items():
    print(k, v.shape)
> boxes (1, None, 4)
> confidence (1, None)
> classes (1, None)
> num_detections (1,)
```

**Comment**

- `model(input)` and `model.predict(input)` give different set of outputs.
- Bounding box output of model **yolo-v8** with `model(input)` gives `64` signal instead of `4`.

**Gist**

[Code.](https://colab.research.google.com/drive/1rlMF-LghotrSPOMDpdrJPxs955lnHUcF?usp=sharing)

**Comment by jbischof** [comment]
I assume this is related to the `make_predict_function` method [link](https://github.com/keras-team/keras-cv/blob/master/keras_cv/models/object_detection/predict_utils.py)? @ianstenbit is this extra info just not needed in training?

**Comment by ianstenbit** [comment]
Yes it is -- `call` on our OD models does not perform box decoding + NMS, so you get raw predictions for each anchor, where `predict` gives us decoded predictions with NMS applied. This is the intended behavior, but based on this issue I'd say we should improve the documentation!

**Comment by LukeWood** [comment]
> Yes it is -- `call` on our OD models does not perform box decoding + NMS, so you get raw predictions for each anchor, where `predict` gives us decoded predictions with NMS applied. This is the intended behavior, but based on this issue I'd say we should improve the documentation!

Some context that might help:
There are really two useful sub-graphs you can think of with an object detection model.  The forward pass that is differentiable, usually tf.function() compile-able, and needs to be evaluated for a single training step - and then the graph including NMS which is needed to evaluate metrics and perform inference.  We decided to make predict perform decoding, while keeping fit() TPU compatible and performant by default.  That’s in short why call() doesn’t perform NMS.

**Comment by ianstenbit** [comment]
Opening this up for contribution if someone would like to add some explanation to this to the docstrings of our OD models

**Comment by pritamdodeja** [comment]
This approach breaks training these types of models using the trainer component in tfx. How can one call the nms subgraph directly?
