### ISSUE TITLE
Migrate Grayscale to use BaseImageAugmentationLayer

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#191]
https://github.com/keras-team/keras-cv/blob/master/keras_cv/layers/preprocessing/grayscale.py

**Comment by kksinghal** [comment]
I want to work on this. I don't think it's just changing the parent class, but it passed the grayscale_test with that.
Also, I can't find any code for this tensorflow.keras.__internal__.layers, not even on google search. So, can anyone give me a reference to that?

**Comment by quantumalaviya** [comment]
@kksinghal I think [this is the definition](https://github.com/keras-team/keras/blob/dd0f1f480613ceffd994658e5632d54c660d1e73/keras/layers/preprocessing/image_preprocessing.py#L213) of this class. At the very least, it provides an in-depth description of what needs to be done to port a layer to `BaseImageAugmentationLayer`. Moreover, I suggest going through the [API Design Guidelines](https://github.com/keras-team/keras-cv/blob/master/.github/API_DESIGN.md) for a brief overview.

**Comment by quantumalaviya** [comment]
This seems to be trivial. If you are not working on this, I can finish this up and make a PR @kksinghal.

**Comment by kksinghal** [comment]
@quantumalaviya Yeah, please go ahead.
