### ISSUE TITLE
0.5.1 breaks `plot_image_gallery`

### ISSUE THREAD

**Issue by Philmod** [keras-team/keras-cv#1923]
This line of code I was using with the version `0.5.0` is broken with `0.5.1`: 

```
keras_cv.visualization.plot_image_gallery(
  [image], rows=1, cols=1, value_range=(0, 255), show=True, scale=4
)
```

Here is the error: 

```
File ".../keras_cv/visualization/plot_image_gallery.py", line 134, in plot_image_gallery
    images.shape[0] if len(images.shape) == 4 else 1
AttributeError: 'list' object has no attribute 'shape'
```

**Comment by gianlucasama** [comment]
From what I see `[image]` should be a `tf.Tensor`, `np.array` or a `tf.data.Dataset` as written in the docs, not a list. Try `np.array(image)` and let me know if it works.

**Comment by Philmod** [comment]
I followed the [first example from this page](https://keras.io/guides/keras_cv/classification_with_keras_cv/) and it does use `np.array`: 

![Screenshot 2023-07-11 at 08 54 03](https://github.com/keras-team/keras-cv/assets/818310/c24fc966-728f-4cbe-be18-5a4bd9518ddf)

**Comment by gianlucasama** [comment]
The example is a little old probably, it should be fixed nonetheless addressing the API change, but for now you can just do:
```
image = np.array(image)
keras_cv.visualization.plot_image_gallery(
image, rows=1, cols=1, value_range=(0, 255), show=True, scale=4,
)
```

**Comment by Philmod** [comment]
![Screenshot 2023-07-11 at 09 55 29](https://github.com/keras-team/keras-cv/assets/818310/7e5df143-b15f-4bc8-a184-667161c27f3d)

**Comment by gianlucasama** [comment]
Apparently the visualization function wants a batched input for the "images" parameter. Just do:
```
image = np.array(image)
image = np.expand_dims(image, 0)
keras_cv.visualization.plot_image_gallery(
    image, rows=1, cols=1, value_range=(0, 255), show=True, scale=4
)
```

**Comment by jbischof** [comment]
Please file an issue on the guide to update.

**Comment by ianstenbit** [comment]
+1 -- this change did break our example, but it's because the example is wrong.

Thanks for the report -- if you open an issue on keras.io we can get the example updated

**Comment by ianstenbit** [comment]
This issue belongs on keras.io, so I'm going to close this copy of it.
