### ISSUE TITLE
`No module named 'keras_core'`

### ISSUE THREAD

**Issue by Philmod** [keras-team/keras-cv#1944]
After upgrading keras_cv to 0.6.x, importing the library fails with `No module named 'keras_core'`

![Screenshot 2023-07-13 at 11 36 51](https://github.com/keras-team/keras-cv/assets/818310/b36075d9-48bc-4020-9a2d-48b7ea5c727f)

It works if I manually install `keras_core` but I didn't see that instruction in the doc.

**Comment by Philmod** [comment]
This [doc](https://github.com/keras-team/keras-cv) only says to install `keras-cv` and `tensorflow`, maybe the new `keras-core` is included in `tensorflow` (which I have not upgraded)?

**Comment by jbischof** [comment]
@ianstenbit should we be adding `keras_core` to our dependencies [here](https://github.com/keras-team/keras-cv/blob/e34aef69035fd4c81302f05e235c3e9ed24a6992/setup.py#L52)?

**Comment by ianstenbit** [comment]
> here

Yes we should -- sorry this was included in `requirements.txt` but I forgot to add it here. I'll send a quick PR
