### ISSUE TITLE
RetinaNet Encoder Exception - ValueError :  None values not supported.

### ISSUE THREAD

**Issue by shreypareek1991** [keras-team/keras-cv#1964]
I am trying to build a `RetinaNet` Object Detector and getting this strange error which was not present in the past. 
I am using the same dataset with which this code has worked in the past. Unsure about what is happening here. 

```shell 
    ValueError: Exception encountered when calling layer 'retina_net_label_encoder' (type RetinaNetLabelEncoder).
    
    in user code:
    
        File "/home/ec2-user/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/keras_cv/models/object_detection/retinanet/retinanet_label_encoder.py", line 214, in call  *
            result = self._encode_sample(box_labels, anchor_boxes, image_shape)
        File "/home/ec2-user/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/keras_cv/models/object_detection/retinanet/retinanet_label_encoder.py", line 168, in _encode_sample  *
            box_ids = ops.arange(gt_boxes.shape[1], dtype=matched_gt_idx.dtype)
    
        ValueError: None values not supported.
    
    
    Call arguments received by layer 'retina_net_label_encoder' (type RetinaNetLabelEncoder):
      • images=tf.Tensor(shape=(4, 640, 640, 3), dtype=float32)
      • box_labels={'classes': 'tf.RaggedTensor(values=Tensor("RaggedFromVariant_1/RaggedTensorFromVariant:1", shape=(None,), dtype=float32), row_splits=Tensor("RaggedFromVariant_1/RaggedTensorFromVariant:0", shape=(5,), dtype=int64))', 'boxes': 'tf.RaggedTensor(values=Tensor("RaggedFromVariant/RaggedTensorFromVariant:1", shape=(None, None), dtype=float32), row_splits=Tensor("RaggedFromVariant/RaggedTensorFromVariant:0", shape=(5,), dtype=int64))'}
```

Platform Information 
```shell
python 3.10
keras                     2.13.1                   pypi_0    pypi
keras-core                0.1.2                    pypi_0    pypi
keras-cv                  0.6.1                    pypi_0    pypi
tensorflow                2.13.0                   pypi_0    pypi
tensorflow-datasets       4.9.2                    pypi_0    pypi
tensorflow-estimator      2.13.0                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.32.0                   pypi_0    pypi
tensorflow-metadata       1.13.1                   pypi_0    pypi
```

Full error trace
```shell
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[16], line 17
     15     if is_smoke_test:
     16         print("Training under smoke test mode. This is simply a drill...")
---> 17     history = model.fit(
     18         train_ds if not is_smoke_test else train_ds.take(10),
     19         validation_data=val_ds if not is_smoke_test else val_ds.take(10),
     20         epochs=epochs if not is_smoke_test else 3,
     21         verbose=1,
     22         callbacks=training_callbacks,
     23     )
     24 elapsed_time = time.time() - start_time
     25 actual_epochs = len(history.history["loss"])

File ~/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File /tmp/__autograph_generated_filea13eanx5.py:15, in outer_factory.<locals>.inner_factory.<locals>.tf__train_function(iterator)
     13 try:
     14     do_return = True
---> 15     retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
     16 except:
     17     do_return = False

File ~/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/keras_cv/models/object_detection/retinanet/retinanet.py:463, in RetinaNet.train_step(self, *args)
    454 x, y = unpack_input(data)
    456 y_for_label_encoder = bounding_box.convert_format(
    457     y,
    458     source=self.bounding_box_format,
    459     target=self.label_encoder.bounding_box_format,
    460     images=x,
    461 )
--> 463 boxes, classes = self.label_encoder(x, y_for_label_encoder)
    464 super_args = args[:-1] + (
    465     (
    466         x,
    467         {"box": boxes, "classification": classes, "unencoded": y},
    468     ),
    469 )
    471 return super().train_step(*super_args)

File /tmp/__autograph_generated_filel34djo7g.py:48, in outer_factory.<locals>.inner_factory.<locals>.tf__call(self, images, box_labels)
     46 anchor_boxes = ag__.converted_call(ag__.ld(ops).concatenate, (ag__.converted_call(ag__.ld(list), (ag__.converted_call(ag__.ld(anchor_boxes).values, (), None, fscope),), None, fscope),), dict(axis=0), fscope)
     47 anchor_boxes = ag__.converted_call(ag__.ld(bounding_box).convert_format, (ag__.ld(anchor_boxes),), dict(source=ag__.ld(self).anchor_generator.bounding_box_format, target=ag__.ld(self).bounding_box_format, image_shape=ag__.ld(image_shape)), fscope)
---> 48 result = ag__.converted_call(ag__.ld(self)._encode_sample, (ag__.ld(box_labels), ag__.ld(anchor_boxes), ag__.ld(image_shape)), None, fscope)
     49 encoded_box_targets = ag__.ld(result)['boxes']
     50 encoded_box_targets = ag__.converted_call(ag__.ld(ops).reshape, (ag__.ld(encoded_box_targets), (-1, ag__.ld(encoded_box_targets).shape[1], 4)), None, fscope)

File /tmp/__autograph_generated_filez1593rfd.py:55, in outer_factory.<locals>.inner_factory.<locals>.tf___encode_sample(self, box_labels, anchor_boxes, image_shape)
     53 batch_size = ag__.ld(box_shape)[0]
     54 n_boxes = ag__.ld(box_shape)[1]
---> 55 box_ids = ag__.converted_call(ag__.ld(ops).arange, (ag__.ld(gt_boxes).shape[1],), dict(dtype=ag__.ld(matched_gt_idx).dtype), fscope)
     56 matched_ids = ag__.converted_call(ag__.ld(ops).expand_dims, (ag__.ld(matched_gt_idx),), dict(axis=-1), fscope)
     57 matches = ag__.ld(box_ids) == ag__.ld(matched_ids)

ValueError: in user code:

    File "/home/ec2-user/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/keras/src/engine/training.py", line 1338, in train_function  *
        return step_function(self, iterator)
    File "/home/ec2-user/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/keras/src/engine/training.py", line 1322, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/ec2-user/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/keras/src/engine/training.py", line 1303, in run_step  **
        outputs = model.train_step(data)
    File "/home/ec2-user/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/keras_cv/models/object_detection/retinanet/retinanet.py", line 463, in train_step
        boxes, classes = self.label_encoder(x, y_for_label_encoder)
    File "/home/ec2-user/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/tmp/__autograph_generated_filel34djo7g.py", line 48, in tf__call
        result = ag__.converted_call(ag__.ld(self)._encode_sample, (ag__.ld(box_labels), ag__.ld(anchor_boxes), ag__.ld(image_shape)), None, fscope)
    File "/tmp/__autograph_generated_filez1593rfd.py", line 55, in tf___encode_sample
        box_ids = ag__.converted_call(ag__.ld(ops).arange, (ag__.ld(gt_boxes).shape[1],), dict(dtype=ag__.ld(matched_gt_idx).dtype), fscope)

    ValueError: Exception encountered when calling layer 'retina_net_label_encoder' (type RetinaNetLabelEncoder).
    
    in user code:
    
        File "/home/ec2-user/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/keras_cv/models/object_detection/retinanet/retinanet_label_encoder.py", line 214, in call  *
            result = self._encode_sample(box_labels, anchor_boxes, image_shape)
        File "/home/ec2-user/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/keras_cv/models/object_detection/retinanet/retinanet_label_encoder.py", line 168, in _encode_sample  *
            box_ids = ops.arange(gt_boxes.shape[1], dtype=matched_gt_idx.dtype)
    
        ValueError: None values not supported.
    
    
    Call arguments received by layer 'retina_net_label_encoder' (type RetinaNetLabelEncoder):
      • images=tf.Tensor(shape=(4, 640, 640, 3), dtype=float32)
      • box_labels={'classes': 'tf.RaggedTensor(values=Tensor("RaggedFromVariant_1/RaggedTensorFromVariant:1", shape=(None,), dtype=float32), row_splits=Tensor("RaggedFromVariant_1/RaggedTensorFromVariant:0", shape=(5,), dtype=int64))', 'boxes': 'tf.RaggedTensor(values=Tensor("RaggedFromVariant/RaggedTensorFromVariant:1", shape=(None, None), dtype=float32), row_splits=Tensor("RaggedFromVariant/RaggedTensorFromVariant:0", shape=(5,), dtype=int64))'}
```

**Comment by jbischof** [comment]
@shreypareek1991 can you please provide a minimal colab gist reproducing the issue?

**Comment by shreypareek1991** [comment]
@jbischof I will send the gist sometime tomorrow. But this appears to be another `0.6.1` issue. Downgrading to `0.5.1` fixed it.

**Comment by shreypareek1991** [comment]
@jbischof Surprisingly it works fine when I try it in a [colab](https://colab.research.google.com/gist/shreypareek1991/cc54471d567c4d74f9ab4c18a0e022d9/object_detection_keras_cv.ipynb). However I am still getting this error on my local machine as well as AWS Sagemaker. 

Perhaps there is an issue with my data. I will close this for now and post the solution if I ever figure it out.

At the moment - downgrading to `keras-cv==0.5.x`  Is working.

Thanks for the help.

**Comment by jbischof** [comment]
I've seen this error crop up a few times @shreypareek1991 with 0.6. Does passing an explicit `input_shape` fix the issue?

**Comment by shreypareek1991** [comment]
Hmm, okay. I will try it out and get back to you.

**Comment by shreypareek1991** [comment]
@jbischof 
Where exactly should I enter the `input_shape` parameter? I am not really sure how to do it for this case.

**Comment by jbischof** [comment]
You must pass `input_shape` to the `backbone`. It is the size of images expected by the model (batch dim excluded).

**Comment by Aillian** [comment]
having the same issue, any solution?

**Comment by jbischof** [comment]
@Aillian we're still waiting for a minimal colab gist on this one to reproduce. It's very difficult for us to triage a stack trace.

**Comment by matt-d** [comment]
I think I have put together a minimal colab - is there a preferred way to share it here?  

The basics are that using ```tf.data.Dataset.from_generator``` with an output_signature like ```output_signature = ({
    "images": tf.TensorSpec(shape=(IMG_HEIGHT, IMG_WIDTH, 3), dtype=tf.float32),
    "bounding_boxes": {
        "boxes": tf.TensorSpec(shape=(None, 4), dtype=tf.float32),
        "classes": tf.TensorSpec(shape=(None, ), dtype=tf.float32),
    }
})``` means the gt_boxes.shape[1] is None in the retinanet_label_encoder.py

```box_ids = ops.arange(gt_boxes.shape[1], dtype=matched_gt_idx.dtype)```


```     ValueError: Exception encountered when calling layer 'retina_net_label_encoder' (type RetinaNetLabelEncoder).
     
     in user code:
     
         File "/usr/local/lib/python3.8/dist-packages/keras_cv/models/object_detection/retinanet/retinanet_label_encoder.py", line 215, in call  *
             result = self._encode_sample(box_labels, anchor_boxes, image_shape)
         File "/usr/local/lib/python3.8/dist-packages/keras_cv/models/object_detection/retinanet/retinanet_label_encoder.py", line 169, in _encode_sample  *
             box_ids = ops.arange(gt_boxes.shape[1], dtype=matched_gt_idx.dtype)
     
         ValueError: None values not supported.
     
     
     Call arguments received by layer 'retina_net_label_encoder' (type RetinaNetLabelEncoder):
       • images=tf.Tensor(shape=(None, 640, 640, 3), dtype=float32)
       • box_labels={'boxes': 'tf.Tensor(shape=(None, None, 4), dtype=float32)', 'classes': 'tf.Tensor(shape=(None, None), dtype=float32)'}```

**Comment by jbischof** [comment]
Yes @matt-d, in Colab select "File > Save as a github gist" and share the link here.

**Comment by matt-d** [comment]
https://gist.github.com/matt-d/be987a646d81ae6b3909864f9caf2496

**Comment by matt-d** [comment]
If it helps with debugging - without setting the image shape in the output_signature (using (None, None, 3)), the anchor_generator also fails for what appears to be a similar reason.

```     TypeError: Exception encountered when calling layer 'retina_net_label_encoder' (type RetinaNetLabelEncoder).
     
     in user code:
     
         File "/usr/local/lib/python3.8/dist-packages/keras_cv/models/object_detection/retinanet/retinanet_label_encoder.py", line 206, in call  *
             anchor_boxes = self.anchor_generator(image_shape=image_shape)
         File "/usr/local/lib/python3.8/dist-packages/keras_cv/layers/object_detection/anchor_generator.py", line 179, in __call__  *
             results[key] = bounding_box.convert_format(
         File "/usr/local/lib/python3.8/dist-packages/keras_cv/layers/object_detection/anchor_generator.py", line 263, in __call__  *
             cx = ops.cast(
     
         TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
     
     
     Call arguments received by layer 'retina_net_label_encoder' (type RetinaNetLabelEncoder):
       • images=tf.Tensor(shape=(None, None, None, 3), dtype=float32)
       • box_labels={'boxes': 'tf.Tensor(shape=(None, None, 4), dtype=float32)', 'classes': 'tf.Tensor(shape=(None, None), dtype=float32)'}```

**Comment by jbischof** [comment]
Have you tried supplying `input_shape` to the backbone as I suggested above?

We need to look into this, but the long term fix is likely to defer building the label encoder until data is passed in.

**Comment by matt-d** [comment]
How do I do that?  Also, is that input_shape for the images or the bboxes and classes?

**Comment by matt-d** [comment]
To be clear - my main issue is the shape of the bboxes and classes not being fixed - the image shape I can work around by resizing in my data generator - but the length of the boxes and classes will vary from image to image...

**Comment by jbischof** [comment]
Ah, thanks for the clarification. Will flag this for further investigation.

**Comment by jbischof** [comment]
Talking with @tirthasheshpatel the problem is that we should be grabbing the symbolic tensor shape using `ops.shape` instead of using the `shape` method on the tensor directly (i.e., `gt_boxes.shape[1]`)

**Comment by shreypareek1991** [comment]
@jbischof Thanks for looking into this. Just wondering if there have been any updates on this? Still facing the error in `0.6.4`
Thanks

**Comment by sandhyaparna** [comment]
Value error is still persistent in 0.6.4 


`ValueError: in user code:`

    File "/Users/sandy/GitHub/na_carve/venv/lib/python3.11/site-packages/keras/src/engine/training.py", line 1377, in train_function  *
        return step_function(self, iterator)
    File "/Users/sandy/GitHub/na_carve/venv/lib/python3.11/site-packages/keras/src/engine/training.py", line 1360, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/Users/sandy/GitHub/na_carve/venv/lib/python3.11/site-packages/keras/src/engine/training.py", line 1349, in run_step  **
        outputs = model.train_step(data)
    File "/Users/sandy/GitHub/na_carve/venv/lib/python3.11/site-packages/keras_cv/src/models/object_detection/retinanet/retinanet.py", line 466, in train_step
        return super().train_step(*args, (x, y))
    File "/Users/sandy/GitHub/na_carve/venv/lib/python3.11/site-packages/keras/src/engine/training.py", line 1127, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "/Users/sandy/GitHub/na_carve/venv/lib/python3.11/site-packages/keras_cv/src/models/object_detection/retinanet/retinanet.py", line 406, in compute_loss
        boxes, classes = self.label_encoder(x, y_for_label_encoder)
    File "/Users/sandy/GitHub/na_carve/venv/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/var/folders/8n/ntrl95bx3y3c9ld55qxlk70r0000gp/T/__autograph_generated_filef8anzai2.py", line 48, in tf__call
        result = ag__.converted_call(ag__.ld(self)._encode_sample, (ag__.ld(box_labels), ag__.ld(anchor_boxes), ag__.ld(image_shape)), None, fscope)
    File "/var/folders/8n/ntrl95bx3y3c9ld55qxlk70r0000gp/T/__autograph_generated_filec6f_4o_9.py", line 55, in tf___encode_sample
        box_ids = ag__.converted_call(ag__.ld(ops).arange, (ag__.ld(gt_boxes).shape[1],), dict(dtype=ag__.ld(matched_gt_idx).dtype), fscope)

    ValueError: Exception encountered when calling layer 'retina_net_label_encoder' (type RetinaNetLabelEncoder).
    
    in user code:
    
        File "/Users/sandy/GitHub/na_carve/venv/lib/python3.11/site-packages/keras_cv/src/models/object_detection/retinanet/retinanet_label_encoder.py", line 215, in call  *
            result = self._encode_sample(box_labels, anchor_boxes, image_shape)
        File "/Users/sandy/GitHub/na_carve/venv/lib/python3.11/site-packages/keras_cv/src/models/object_detection/retinanet/retinanet_label_encoder.py", line 169, in _encode_sample  *
            box_ids = ops.arange(gt_boxes.shape[1], dtype=matched_gt_idx.dtype)
    
        ValueError: None values not supported.
    
    
    Call arguments received by layer 'retina_net_label_encoder' (type RetinaNetLabelEncoder):
      • images=tf.Tensor(shape=(2, 640, 640, 3), dtype=float32)
      • box_labels={'classes': 'tf.RaggedTensor(values=Tensor("RaggedFromVariant_1/RaggedTensorFromVariant:1", shape=(None,), dtype=float32), row_splits=Tensor("RaggedFromVariant_1/RaggedTensorFromVariant:0", shape=(3,), dtype=int64))', 'boxes': 'tf.RaggedTensor(values=Tensor("RaggedFromVariant/RaggedTensorFromVariant:1", shape=(None, None), dtype=float32), row_splits=Tensor("RaggedFromVariant/RaggedTensorFromVariant:0", shape=(3,), dtype=int64))'}`

**Comment by tirthasheshpatel** [comment]
Hi @sandhyaparna, this issue has been fixed by #2119 but hasn't been released yet. It will be available in v0.6.5. Until then, you can install from source: `pip install git+https://github.com/keras-team/keras-cv.git` to get the fix.

**Comment by sandhyaparna** [comment]
@tirthasheshpatel FYI, it still gave the same error when installing keras-cv from the source.

**Comment by tirthasheshpatel** [comment]
That's odd. Can you share the error and your code or a minimal reproducible example?
