### ISSUE TITLE
Add smaller pre-trained backbones to object detection models

### ISSUE THREAD

**Issue by elad-c** [keras-team/keras-cv#1971]
**Short Description**
Are you going to add smaller back bones (e.g. MobileNetV2) to the object detection models?

**Comment by jbischof** [comment]
Hi @elad-c, if you check the `presets` property of our OD models you'll see we already support MobileNet, DenseNet, and EfficientNet. Give them a spin!

```python
model = keras_cv.models.RetinaNet.from_preset(
    "mobilenet_v3_large_imagenet",
    num_classes=20,
    bounding_box_format="xywh",
)
```

**Comment by elad-c** [comment]
Thanks @jbischof ,
That's what I thought, so I'll rephrase my original question: Is there a plan to expand the e2e task-level presets for object detection, other than "retinanet_resnet50_pascalvoc" and "yolo_v8_m_pascalvoc"?

**Comment by elad-c** [comment]
Ok
Thanks for your help! much appreciated.
