### ISSUE TITLE
Gaussian Blur in regularization

### ISSUE THREAD

**Issue by Simardeep27** [keras-team/keras-cv#199]
I wanted to add Gaussian Blur layer to layers.regularization. It is widely used in downsampling images and is pretty helpful in basic edge detection and noise reduction. 

Would love to work on this.

**Comment by bhack** [comment]
We have already https://github.com/keras-team/keras-cv/pull/143

**Comment by Simardeep27** [comment]
Ahh okay. Just saw that it was added in for the next release. Will close the PR thanks.
