### ISSUE TITLE
Unable to import Keras_cv

### ISSUE THREAD

**Issue by hdparmar** [keras-team/keras-cv#1996]
I am working on Colab on the [fine-tuning Stable Diffusion](https://keras.io/examples/generative/finetune_stable_diffusion/) guide from Keras CV but I have tried all the solutions but non is working. 
I then tried to simply importing it on Google Colab like this:
```
!pip install keras-cv==0.4.0 -q
!pip install -U tensorflow --q
import tensorflow as tf
from tensorflow import keras
import keras_cv
import tensorflow_datasets as tfds
```
Everytime I am getting different errors: Latest one is:
```
ImportError                               Traceback (most recent call last)
[<ipython-input-3-665b25995468>](https://localhost:8080/#) in <cell line: 3>()
      1 import tensorflow as tf
      2 from tensorflow import keras
----> 3 import keras_cv
      4 import tensorflow_datasets as tfds

3 frames
[/usr/local/lib/python3.10/dist-packages/keras_cv/models/weights.py](https://localhost:8080/#) in <module>
     12 # See the License for the specific language governing permissions and
     13 import tensorflow as tf
---> 14 from keras.utils import data_utils
     15 
     16 

ImportError: cannot import name 'data_utils' from 'keras.utils' (/usr/local/lib/python3.10/dist-packages/keras/utils/__init__.py)
```
I know I shouldn't put trivial issues here but I'm not finding any solution

**Comment by jbischof** [comment]
@hdparmar can you attach a minimal colab gist reproducing this error?

Also, why 0.4.0?

**Comment by hdparmar** [comment]
Issue fixed with:
image_encoder = image_encoder()
Lol! 
Thank you @jbischof for your input and time! 👍🏼
