### ISSUE TITLE
Implement `BasePreprocessingLayerTest`

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#200]
This can handle things like `tf.function` compilation, output shape preservation, etc.

FYI @bhack

**Comment by qlzh727** [comment]
I think we have similar items in https://github.com/keras-team/keras/blob/793620ae1bdda7e37edd485b034e8962fff57f3e/keras/layers/preprocessing/image_preprocessing_test.py#L1896, and might be able to be reused.

**Comment by bhack** [comment]
We could check also if need to user internal style:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/impl/api.py#L501-L531

**Comment by tanzhenyu** [comment]
Probably no longer relevant. Closing it
