### ISSUE TITLE
BASNet model

### ISSUE THREAD

**Issue by martin-gorner** [keras-team/keras-cv#2006]
Add the BASNet segmentation model to KerasCV.

A keras.io [BASNet example](https://keras.io/examples/vision/basnet_segmentation/) already exists, based on this [BASNet implementation](https://github.com/hamidriasat/BASNet/tree/basnet_keras), both from [Hamid Ali](https://github.com/hamidriasat).

The API should follow that of the existing [DeepLabV3 model](https://github.com/keras-team/keras-cv/blob/master/keras_cv/models/segmentation/deeplab_v3_plus/deeplab_v3_plus.py).

**Comment by martin-gorner** [comment]
@hamidriasat, would you like to contribute your BASNet implementation?

**Comment by IMvision12** [comment]
I can add this model @martin-gorner !

**Comment by hamidriasat** [comment]
@martin-gorner Yes, I would be delighted to contribute my BASNet implementation to KerasCV.

**Comment by jbischof** [comment]
Thanks @hamidriasat! Thanks as well for your offer @IMvision12 but since Hamid wrote the example we'll give him first pass.

**Comment by innat** [comment]
The official repository of BASNet: https://github.com/xuebinqin/BASNet

<img width="565" alt="sod_qual_comp" src="https://github.com/keras-team/keras-cv/assets/17668390/0c8fadd0-a447-4551-be96-fb44b7e5ad6e">

**Comment by divyashreepathihalli** [comment]
@hamidriasat are you working on this?

**Comment by hamidriasat** [comment]
@divyashreepathihalli
Hi, sorry for the delay I was busy with other things.
But I am working on it, [here](https://github.com/hamidriasat/keras-cv/tree/feat/add-basnet-model/keras_cv/models/segmentation/basnet) you can check the initial progress with the model added.

I have also successfully added test cases for BASNet but will push the code once It's cleaned. 
My plan is to soon submit a pull request with the model and test cases, then paper weights will be added later, kindly let me know, will this work?

**Comment by tirthasheshpatel** [comment]
Glad to see so much progress! It looks good and should work. Feel free to open a draft PR if you want.

**Comment by divyashreepathihalli** [comment]
Thank you for submitting the PR @hamidriasat! Great job!!
