### ISSUE TITLE
Quickstart missing an import:

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#2022]
Quickstart missing an import:
https://github.com/keras-team/keras-io/blob/master/templates/keras_cv/index.md

```
import keras_cv
import keras_core as keras

filepath = keras.utils.get_file(origin="https://i.imgur.com/gCNcJJI.jpg")
image = np.array(keras.utils.load_img(filepath))
image_resized = ops.image.resize(image, (640, 640))[None, ...]

model = keras_cv.models.YOLOV8Detector.from_preset(
    "yolo_v8_m_pascalvoc",
    bounding_box_format="xywh",
)
predictions = model.predict(image_resized)
```
is missing
```
import numpy as np
from keras_core import ops
```
Numpy can probably be omitted for brevity; but to naive readers the location of `ops` is probably not super clear.
Perhaps an import would help.

Can't propose the update now, but didn't want to forget so opening a bug.   Feel free to fix, close, or whatever else - can send a PR later if that helps.

**Comment by jbischof** [comment]
@LukeWood I think we fixed this on KerasCV's readme but syncing to KerasIO is manual. We should copy our changes over.

**Comment by matt-d** [comment]
NameError: name 'ops' is not defined

**Comment by sampathweb** [comment]
Closing this issue since we have updated the page for `Keras 3`
