### ISSUE TITLE
ModuleNotFoundError: No module named 'keras_core'

### ISSUE THREAD

**Issue by X-TRON404** [keras-team/keras-cv#2026]
### Current Behavior:
The import:
`from keras_cv.layers import RandAugment`
throws an error 
```
---> 14 from keras_core.src.backend.tensorflow import *  # noqa: F403, F401
     15 from keras_core.src.backend.tensorflow import (  # noqa: F403, F401
     16     convert_to_numpy,

ModuleNotFoundError: No module named 'keras_core'
```
### Expected Behavior:
I expect the import to work properly as my tensorflow version is > 2.12.0

### Steps To Reproduce:
Run following in colab with T4 GPU:

```
!pip install keras-cv
!pip install tensorflow==2.13.0
```
```
from keras_cv.layers import RandAugment
```

### Version:
- keras-cv=1.4.0
- tensorflow=2.13.0

**Comment by ianstenbit** [comment]
Hey @X-TRON404 thanks for the report.

The next release will correctly include this as a dep, so you won't have to manually install, but for now you can just run `!pip install keras-core` to install this dependency.
