### ISSUE TITLE
Adding EffientDet model

### ISSUE THREAD

**Issue by Paryavi** [keras-team/keras-cv#2042]
**Short Description**

EfficientDet should be useful!; https://ai.googleblog.com/2020/04/efficientdet-towards-scalable-and.html
If you do not wanna add this model soon, how should I add it myself to my KerasCV pipeline?
**Papers**

**Existing Implementations**

**Other Information**

**Comment by Zekrom-7780** [comment]
@ianstenbit seems like a great idea!
