### ISSUE TITLE
how to convert bounding boxes dict to a tensor?

### ISSUE THREAD

**Issue by AbdelrhmanNile** [keras-team/keras-cv#2050]
i am trying to construct a tf.data.Dataset for my custom dataset for object detection.

my bounding boxes format is as you described in the documentations
for example:

```
bounding_boxes = {
    "classes": [0],
     "boxes": [[50, 100, 50, 100]]
}
```
 how could i make a tf.data.Dataset with this??

**Comment by IMvision12** [comment]
Hi @AbdelrhmanNile refer to this code example : https://keras.io/examples/vision/yolov8/

**Comment by AbdelrhmanNile** [comment]
Hi @IMvision12, thank you!! found it :)
