### ISSUE TITLE
"plot_bounding_box_gallery" doesn't work anymore

### ISSUE THREAD

**Issue by samedit66** [keras-team/keras-cv#2067]
### Current Behavior:
Hello! I'm trying to plot predictions produces by RetinaNet. Everything goes alright until I try to draw them using "plot_bounding_box_gallery": I get this error:

File "/home/barten/.local/lib/python3.11/site-packages/keras_cv/src/visualization/plot_bounding_box_gallery.py", line 127, in plot_bounding_box_gallery
    draw_fn = functools.partial(
              ^^^^^^^^^^^^^^^^^^
TypeError: the first argument must be callable

### Expected Behavior:
Earlier, like, 14-15 hours it worked for me successfully and bounded boxes were drawn correctly.

### Steps To Reproduce:

To reproduce this you can just run the example "plot_bounding_box_gallery.py" in /examples/vizualization folder

**Comment by ianstenbit** [comment]
Thanks for the issue report @samedit66! This was broken by 0.6.2 and 0.6.3 -- feel free to pin to version 0.6.1 for now and I will release a fix ASAP

**Comment by ianstenbit** [comment]
After my fix in #2068, this should be resolved. I'm pushing a 0.6.4 release today to get this fix live. My apologies for the breakage!
