### ISSUE TITLE
Ensure GitHub workflows run with minimal permissions

### ISSUE THREAD

**Issue by pnacht** [keras-team/keras-cv#2074]
**Short Description**
KerasCV's workflows currently run with the default `write-all` permissions. This makes these workflows potential supply-chain attack vectors. [GitHub itself](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-secrets) recommends ensuring all workflows run with minimal permissions.

I've taken a look at KerasCV's workflows, and they all seem to be for tests or deploying to PyPi. They therefore do not require such broad permissions.

This issue can be solved in two ways:

- add top-level read-only permissions to all the workflows; and/or
- set the default token permissions to read-only in the repo settings.

I'll be sending a PR along with this issue that sets the top-level permissions. If you instead (or also) wish to modify the default token permissions:

- Go to [Settings > Actions > General](https://github.com/keras-team/keras-cv/settings/actions)
- Under "Workflow permissions", set them to "Read repository contents and packages permissions"

**Other Information**
My name is Pedro and I work with Google and the [Open Source Security Foundation (OpenSSF)](https://www.openssf.org/) to improve the supply-chain security of the open-source ecosystem.

**Comment by ianstenbit** [comment]
Thank you for this issue! 

I really appreciate it -- I've updated the settings and I will approve your PR if the CI looks good.
