### ISSUE TITLE
Segmentations metrics

### ISSUE THREAD

**Issue by emi-research-dl** [keras-team/keras-cv#2078]
Would it be possible to include default metrics in Keras for image segmentation? E.x Dice, IoU, HD, etc.

I tried this:

```
from keras_core import backend as K

def jaccard_distance_loss(y_true, y_pred, smooth=100):
    intersection = K.sum(K.sum(K.abs(y_true * y_pred), axis=-1))
    sum_ = K.sum(K.sum(K.abs(y_true) + K.abs(y_pred), axis=-1))
    jac = (intersection + smooth) / (sum_ - intersection + smooth)
    return (1 - jac) * smooth

def dice_metric(y_pred, y_true):
    intersection = K.sum(K.sum(K.abs(y_true * y_pred), axis=-1))
    union = K.sum(K.sum(K.abs(y_true) + K.abs(y_pred), axis=-1))
    return 2*intersection / union

size = 10

y_true = np.zeros(shape=(size,size))
y_true[3:6,3:6] = 1

y_pred = np.zeros(shape=(size,size))
y_pred[3:5,3:5] = 1

loss = jaccard_distance_loss(y_true,y_pred)

metric = dice_metric(y_pred,y_true)

print(f"loss: {loss}")
print(f"dice_metric: {metric}")

```
It seems that keras_core does not yet have backend support.
Can someone help me?

Thanks in advanced!

**Comment by jbischof** [comment]
@emi-research-dl thank you! Could you please attach a minimal colab showing what issue you're running into?

**Comment by emi-research-dl** [comment]
@jbischof Keras Core does not include the backend module for now, so I would like to know if there is an alternative, could the metrics listed in https://docs.monai.io/en/stable/metrics.html also be included in keras-cv? That would be great

**Comment by jbischof** [comment]
Keras Core is a bit different than Keras for sure. It includes a backend-agnostic numpy API for operations like `sum` and `abs` called `ops`. You can check out an example [here](https://github.com/keras-team/keras-cv/blob/0cff8e2356fb68888b035a7232e904097d3fad46/keras_cv/bounding_box/iou.py#L176) of how to use this with KerasCV.

**Comment by emi-research-dl** [comment]
Thank you so much @jbischof !!!

**Comment by jbischof** [comment]
No problem @emi-research-dl! We welcome any contributions of missing losses and metrics as well.
