### ISSUE TITLE
model.save doesn't save the entire RetinaNet model

### ISSUE THREAD

**Issue by george-synx** [keras-team/keras-cv#2088]
### Current Behavior:
Saving a custom trained model initialised with the keras_cv.models.RetinaNet object with model.save doesn't save the full network. When you load the custom model with keras.saving.load_model() it doesn't have the anchor_generator or non-max-suppression layers and model.predict fails. The error message is Type_error: '_dictwrapper' is not callable

### Expected Behavior:
The full model saves and is loadable with keras.saving.load_model(), and model.predict executes without error

### Current Behavior:
Saving a custom trained model initialised with the keras_cv.models.RetinaNet object with model.save doesn't save the full network. When you load the custom model with keras.saving.load_model() it doesn't have the anchor_generator or non-max-suppression layers and model.predict fails. The error message is Type_error: '_dictwrapper' is not callable

### Expected Behavior:
The full model saves and is loadable with keras.saving.load_model(), and model.predict executes without error

### Steps To Reproduce:

Access this colab,
](https://colab.research.google.com/github/keras-team/keras-io/blob/master/guides/ipynb/keras_cv/object_detection_keras_cv.ipynb)

Add this box before the Inference and plotting results section:
model.save('my_model.keras')
predictor_model = keras.saving.load_model('my_model.keras')

model.summary()
predictor_model.summary()

Remove the initialization of the model, and add another visual_detections() call but for the predictor_model.

### Version:
tensorflow=2.13.0, keras=2.13.1, keras-cv=0.6.4

### Version:
tensorflow=2.13.0, keras=2.13.1, keras-cv=0.6.4

**Comment by ianstenbit** [comment]
Hi @george-synx -- thanks for the issue. Could you please create a repro colab which shows the error you're encountering?

**Comment by george-synx** [comment]
> Hi @george-synx -- thanks for the issue. Could you please create a repro colab which shows the error you're encountering?

Please find attached: 

https://colab.research.google.com/drive/1u_BlZ0ZN1b36TDs3-bHYbZ1ms18qsot1?usp=sharing

I've indicted in the comments of the colab file where the error occurs.

**Comment by george-synx** [comment]
Hi @ianstenbit, has there been any updates with this?

**Comment by ianstenbit** [comment]
> Hi @ianstenbit, has there been any updates with this?

Hey @george-synx -- so sorry for the delay. Can you please give me access to your colab (or save it as a GitHub gist?)

**Comment by ianstenbit** [comment]
Okay I reproduced this myself in a separate Colab -- I think this is caused by a deserialization issue with RetinaNet. Testing a fix.
