### ISSUE TITLE
`input.dtype != output.dtype`  with BaseImageAugmentationLayer!

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#209]
I've tried all the layers, [HERE](https://github.com/keras-team/keras-cv/tree/master/keras_cv/layers/preprocessing),  that have migrated to `BaseImageAugmentationLayer`. And found that the outputs are always cast to `float32`, regardless of any input `dtype`. 

In API Design Guidelines, it's stated: 

> Additionally, these preprocessing layers should cast back to the input images original `dtype` before the end of their `call` body. This API design decision is made to preserve the simplicity and provide the easiest API to use.
The decision to support inputs of any `dtype` is made based on the nuance that some Keras layers cast user inputs without the user knowing. For example, if `Solarization` expected user inputs to be of type `int`, and a custom layer was accidentally casting inputs to `float32`, it would be a bad user experience to raise an error asserting that all inputs must be of type `int`.

---

The casting operation to `float32` is done in [HERE](https://github.com/keras-team/keras/blob/dd0f1f480613ceffd994658e5632d54c660d1e73/keras/layers/preprocessing/image_preprocessing.py#L375), regardless of **training** mode or **inference** mode. The outputs are always cast to `float32`. Do I need to implement the `call` function and manually cast to the original input for this?

**Comment by LukeWood** [comment]
Updated.  Thanks the docs @innat .  You don't need to worry about that.

**Comment by innat** [comment]
@LukeWood Thanks. So, by subclassing the `BaseImageAugmentationLayer`, the output will auto re-cast back to the original input type? Currently, it doesn't do that, so will there be a fix?

**Comment by LukeWood** [comment]
No, as of now we don't re-cast back to the original dtype.  This is wasteful if all of the computation will be done in the `self.compute_dtype` realm anyways.  If there is a good reason to cast back we can start doing that, but  I'm not convinced that casting back to the original dtype is valuable to users.  

Thoughts?

**Comment by innat** [comment]
@LukeWood I think I didn't understand [this](https://github.com/keras-team/keras-cv/blob/master/.github/API_DESIGN.md#color-based-preprocessing-layers) instruction clearly. I thought it was encouraged to keep the `input.dtype` and `output.dtype` same. 

Anyway, I don't have any particular cases where such things are required heavily, i.e. `dtype` consistency. So, if this is the API design choice, great then.
