### ISSUE TITLE
Importing keras_cv after importing tensorflow freezes import

### ISSUE THREAD

**Issue by MonkeyBoy9999996** [keras-team/keras-cv#2091]
### Current Behavior:
```python3
import tensorflow as tf
import keras_cv
```
Code above freezes after importing keras_cv.

### Expected Behavior:
Should import keras_cv. If above commands are flipped. Everything works fine, probably some cross import error.

### Steps To Reproduce
OS: Ubuntu 23.04 64bit
- installation of tensorflow 2 according to official web page with nvidia driver 520, cuda 11.8 and cudnn.
     - tensorflow recognizes a gpu, command tf.config.list_physical_devices() lists both CPU and GPU
- `pip install keras-cv`
- + code seen above

### Version:
- 0.6.4

**Comment by ianstenbit** [comment]
I'm not currently able to reproduce this. It's possible that this is due to [this known import issue](https://github.com/tensorflow/tensorflow/issues/60109) with TF+Torch, but I'm not certain.

Are you using the torch backend?

**Comment by MonkeyBoy9999996** [comment]
No, i use keras with tensorflow as backend. My script is not importing pytorch, but I have it installed. I am currently not going to seek for a solution, problem was solved by rearranging the import order.
