### ISSUE TITLE
keras_cv.callbacks.PyCOCOCallback 0 and -1 mAP Problem

### ISSUE THREAD

**Issue by FanChiMao** [keras-team/keras-cv#2095]
## Environment
Ubuntu 20.04
<details>
<summary>pip list</summary>

    Package                      Version
    ---------------------------- ----------
    absl-py                      1.4.0
    array-record                 0.4.1
    astunparse                   1.6.3
    cachetools                   5.3.1
    certifi                      2023.7.22
    charset-normalizer           3.2.0
    click                        8.1.7
    contourpy                    1.1.0
    cycler                       0.11.0
    dm-tree                      0.1.8
    etils                        1.4.1
    flatbuffers                  23.5.26
    fonttools                    4.42.1
    gast                         0.4.0
    google-auth                  2.23.0
    google-auth-oauthlib         1.0.0
    google-pasta                 0.2.0
    googleapis-common-protos     1.60.0
    grpcio                       1.58.0
    h5py                         3.9.0
    idna                         3.4
    importlib-metadata           6.8.0
    importlib-resources          6.0.1
    keras                        2.13.1
    keras-core                   0.1.5
    keras-cv                     0.6.4
    kiwisolver                   1.4.5
    libclang                     16.0.6
    Markdown                     3.4.4
    markdown-it-py               3.0.0
    MarkupSafe                   2.1.3
    matplotlib                   3.7.3
    mdurl                        0.1.2
    namex                        0.0.7
    numpy                        1.24.3
    nvidia-cublas-cu11           2022.4.8
    nvidia-cublas-cu117          11.10.1.25
    nvidia-cudnn-cu11            8.6.0.163
    oauthlib                     3.2.2
    opencv-python                4.8.0.76
    opt-einsum                   3.3.0
    packaging                    23.1
    Pillow                       10.0.0
    pip                          23.2.1
    promise                      2.3
    protobuf                     3.20.3
    psutil                       5.9.5
    pyasn1                       0.5.0
    pyasn1-modules               0.3.0
    pycocotools                  2.0.7
    Pygments                     2.16.1
    pyparsing                    3.1.1
    python-dateutil              2.8.2
    regex                        2023.8.8
    requests                     2.31.0
    requests-oauthlib            1.3.1
    rich                         13.5.2
    rsa                          4.9
    setuptools                   68.0.0
    six                          1.16.0
    tensorboard                  2.13.0
    tensorboard-data-server      0.7.1
    tensorboard-plugin-wit       1.8.1
    tensorflow                   2.13.0
    tensorflow-datasets          4.9.3
    tensorflow-estimator         2.13.0
    tensorflow-io-gcs-filesystem 0.34.0
    tensorflow-metadata          1.14.0
    termcolor                    2.3.0
    toml                         0.10.2
    tqdm                         4.66.1
    typing_extensions            4.5.0
    urllib3                      1.26.16
    Werkzeug                     2.3.7
    wheel                        0.38.4
    wrapt                        1.15.0
    zipp                         3.16.2

</details>

## Description
I follow [**YOLOv8-keras**](https://keras.io/examples/vision/yolov8/) example code like following:
<details>
<summary>train.py</summary>

    import os

    os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
    from tqdm.auto import tqdm
    from glob import glob
    import time
    import xml.etree.ElementTree as ET
  
    import tensorflow as tf
    
    print("=> tensorflow version: ", tf.__version__)
    print("=> Physical GPU device: ", tf.config.list_physical_devices('GPU'))
    physical_devices = tf.config.experimental.list_physical_devices('GPU')
    if len(physical_devices) > 0:
        tf.config.experimental.set_memory_growth(physical_devices[0], True)
    from tensorflow import keras
    
    import keras_cv
    from keras_cv import bounding_box
    from keras_cv import visualization
    
    
    def parse_annotation(img_path, xml_file, class_map, xyxy=True):
        # Decode xml
        tree = ET.parse(xml_file)
        root = tree.getroot()
    
        image_name = root.find("filename").text
        image_path = os.path.join(img_path, image_name)
    
        boxes = []
        classes = []
        for obj in root.iter("object"):
            cls = obj.find("name").text
            classes.append(cls)
    
            bbox = obj.find("bndbox")
            xmin = float(bbox.find("xmin").text)
            ymin = float(bbox.find("ymin").text)
            xmax = float(bbox.find("xmax").text)
            ymax = float(bbox.find("ymax").text)
            if xyxy:
                boxes.append([xmin, ymin, xmax, ymax])
            else:  # xywh
                boxes.append([(xmax - xmin) / 2, (ymax - ymin) / 2, xmax - xmin, ymax - ymin])
    
        class_ids = [
            list(class_map.keys())[list(class_map.values()).index(cls)]
            for cls in classes
        ]
        return image_path, boxes, class_ids
    
    
    def load_image(image_path):
        image = tf.io.read_file(image_path)
        image = tf.image.decode_jpeg(image, channels=3)
        return image
    
    
    def visualize_dataset(inputs, value_range, rows, cols, bounding_box_format, class_map):
        inputs = next(iter(inputs.take(1)))
        images, bounding_boxes = inputs["images"], inputs["bounding_boxes"]
        visualization.plot_bounding_box_gallery(
            images,
            value_range=value_range,
            rows=rows,
            cols=cols,
            y_true=bounding_boxes,
            scale=4,
            font_scale=0.7,
            show=True,
            bounding_box_format=bounding_box_format,
            class_mapping=class_map,
        )
    
    
    def load_dataset(image_path, classes, bbox):
        # Read Image
        image = load_image(image_path)
        bounding_boxes = {
            "classes": tf.cast(classes, dtype=tf.float32),
            "boxes": bbox,
        }
        return {"images": tf.cast(image, tf.float32), "bounding_boxes": bounding_boxes}
    
    
    def dict_to_tuple(inputs):
        return inputs["images"], bounding_box.to_dense(
            inputs["bounding_boxes"], max_boxes=100
        )
    
    
    def visualize_detections(model, dataset, bounding_box_format, class_map):
        images, y_true = next(iter(dataset.take(1)))
        y_pred = model.predict(images)
        y_pred = bounding_box.to_dense(y_pred)
        visualization.plot_bounding_box_gallery(
            images,
            value_range=(0, 255),
            bounding_box_format=bounding_box_format,
            y_true=y_true,
            y_pred=y_pred,
            scale=4,
            rows=2,
            cols=2,
            show=True,
            font_scale=0.7,
            class_mapping=class_map,
        )
    
    
    DATASET = "Traffic_Signs"
    if __name__ == '__main__':
        import argparse
    
        parser = argparse.ArgumentParser(description='Train the YOLOv8 with keras')
        parser.add_argument('--batch', default=4, type=int, help='BATCH_SIZE')
        parser.add_argument('--lr', default=0.001, type=int, help='LEARNING_RATE')
        parser.add_argument('--epochs', default=5, type=float, help='EPOCH')
        parser.add_argument('--gclip', default=10.0, type=float, help='GLOBAL_CLIPNORM')
        parser.add_argument('--img_path', default='./datasets/Traffic_Signs/VOC2007/Image', type=str, help='total image path')
        parser.add_argument('--train_label', default='./datasets/Traffic_Signs/VOC2007/train_label', type=str,
                            help='train label path')
        parser.add_argument('--valid_label', default='./datasets/Traffic_Signs/VOC2007/val_label', type=str,
                            help='valid label path')
        parser.add_argument('--class_list', default=["prohibitory", "danger", "mandatory", "other"],
                            type=list, help='class list ex: ["person", "car", "bus", ...]')
        args = parser.parse_args()
    
        # Hyper-parameters
        BATCH_SIZE = args.batch
        LEARNING_RATE = args.lr
        EPOCH = args.epochs
        GLOBAL_CLIPNORM = args.gclip
    
        # Path dataset/label setting
        total_image = args.img_path
        train_annot = args.train_label
        valid_annot = args.valid_label
        train_labels_list = sorted(glob(os.path.join(train_annot, '*.xml')))  # xyxy
        valid_labels_list = sorted(glob(os.path.join(valid_annot, '*.xml')))  # xyxy
        total_images_list = sorted(glob(os.path.join(total_image, '*.jpg')))
    
        # Classes setting
        class_ids = args.class_list
        class_mapping = dict(zip(range(len(class_ids)), class_ids))
    
        print("=> Load train/valid labels and images")
        train_image_paths = []
        train_bboxes = []
        train_classes = []
        valid_image_paths = []
        valid_bboxes = []
        valid_classes = []
        for train_label in tqdm(train_labels_list, desc="Train dataset"):
            image_path, boxes, class_ids = parse_annotation(total_image, train_label, class_mapping, xyxy=True)
            train_image_paths.append(image_path)
            train_bboxes.append(boxes)
            train_classes.append(class_ids)
    
        for valid_label in tqdm(valid_labels_list, desc="Valid dataset"):
            valid_image_path, valid_boxes, valid_class_ids = parse_annotation(total_image, valid_label, class_mapping,
                                                                              xyxy=True)
            valid_image_paths.append(valid_image_path)
            valid_bboxes.append(valid_boxes)
            valid_classes.append(valid_class_ids)
    
        t_image_paths = tf.ragged.constant(train_image_paths)
        t_classes = tf.ragged.constant(train_classes)
        t_bbox = tf.ragged.constant(train_bboxes)
        v_image_paths = tf.ragged.constant(valid_image_paths)
        v_classes = tf.ragged.constant(valid_classes)
        v_bbox = tf.ragged.constant(valid_bboxes)
    
        train_data = tf.data.Dataset.from_tensor_slices((t_image_paths, t_classes, t_bbox))
        valid_data = tf.data.Dataset.from_tensor_slices((v_image_paths, v_classes, v_bbox))
    
        print('=> Build Training Dataloader with data augmentation')
        augmenter = keras.Sequential(
            layers=[
                # keras_cv.layers.RandomFlip(mode="horizontal", bounding_box_format="xyxy"),
                # keras_cv.layers.RandomShear(x_factor=0.2, y_factor=0.2, bounding_box_format="xyxy"),
                keras_cv.layers.JitteredResize(target_size=(640, 640), scale_factor=(0.75, 1.3),
                                               bounding_box_format="xyxy"),
            ]
        )
        train_ds = train_data.map(load_dataset, num_parallel_calls=tf.data.AUTOTUNE)
        train_ds = train_ds.shuffle(BATCH_SIZE * 4)
        train_ds = train_ds.ragged_batch(BATCH_SIZE, drop_remainder=True)
        train_ds = train_ds.map(augmenter, num_parallel_calls=tf.data.AUTOTUNE)
    
        print("=> Build Validation Dataloader with resizing")
        resizing = keras_cv.layers.JitteredResize(
            target_size=(640, 640),
            scale_factor=(0.75, 1.3),
            bounding_box_format="xyxy",
        )
        val_ds = valid_data.map(load_dataset, num_parallel_calls=tf.data.AUTOTUNE)
        val_ds = val_ds.shuffle(BATCH_SIZE * 4)
        val_ds = val_ds.ragged_batch(BATCH_SIZE, drop_remainder=True)
        val_ds = val_ds.map(resizing, num_parallel_calls=tf.data.AUTOTUNE)
    
        # Visualization
        print('=> Visualize dataset')
        visualize_dataset(train_ds, bounding_box_format="xyxy", value_range=(0, 255), rows=2, cols=2,
                          class_map=class_mapping)
        visualize_dataset(val_ds, bounding_box_format="xyxy", value_range=(0, 255), rows=2, cols=2, class_map=class_mapping)
    
        train_ds = train_ds.map(dict_to_tuple, num_parallel_calls=tf.data.AUTOTUNE)
        train_ds = train_ds.prefetch(tf.data.AUTOTUNE)
    
        val_ds = val_ds.map(dict_to_tuple, num_parallel_calls=tf.data.AUTOTUNE)
        val_ds = val_ds.prefetch(tf.data.AUTOTUNE)
    
        # Build YOLOv8 model
        print('=> Build YOLOv8 Backbone')
        backbone = keras_cv.models.YOLOV8Backbone.from_preset(
            "yolo_v8_xs_backbone_coco"  # _xs, _s, _m, ...
        )
    
        yolo_model = keras_cv.models.YOLOV8Detector(
            num_classes=len(class_mapping),
            bounding_box_format="xyxy",
            backbone=backbone,
            fpn_depth=1,
        )
    
        optimizer = tf.keras.optimizers.Adam(learning_rate=LEARNING_RATE, global_clipnorm=GLOBAL_CLIPNORM, )
        yolo_model.compile(optimizer=optimizer, classification_loss="binary_crossentropy", box_loss="ciou")
    
        coco_metrics_callback = keras_cv.callbacks.PyCOCOCallback(val_ds, bounding_box_format="xywh")
        # coco_metrics_callback = EvaluateCOCOMetricsCallback(val_ds, 'best_model.h5')
    
        print('=> Start Training')
        s = time.time()
        yolo_model.fit(
            train_ds,
            validation_data=val_ds,
            epochs=EPOCH,
            callbacks=[coco_metrics_callback],
        )
        yolo_model.save(f'./keras_yolov8_tiny_{DATASET}.h5')
        print(f"=> Total training time: {time.time() - s} seconds")

</details>

<details>
<summary>result log</summary>

    /home/dit-train-3/anaconda3/envs/tf2.13/bin/python /home/dit-train-3/Desktop/Jonathan/yolov8-keras/main.py
    => tensorflow version:  2.13.0
    => Physical GPU device:  [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
    Using TensorFlow backend
    => Load train/valid labels and images
    Train dataset: 100%|██████████| 630/630 [00:00<00:00, 6570.79it/s]
    Valid dataset: 100%|██████████| 111/111 [00:00<00:00, 22826.42it/s]
    => Build Training Dataloader with data augmentation
    => Build Validation Dataloader with resizing
    => Visualize dataset
    => Build YOLOv8 Backbone
    => Start Training
    Epoch 1/5
    27/27 [==============================] - 7s 148ms/step
    creating index...
    index created!
    creating index...
    index created!
    Running per image evaluation...
    Evaluate annotation type *bbox*
    DONE (t=0.00s).
    Accumulating evaluation results...
    Please run evaluate() first
    DONE (t=0.00s).
     Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
     Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = -1.000
     Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = -1.000
     Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
     Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
     Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = -1.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = -1.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
    157/157 [==============================] - 60s 179ms/step - loss: 1680.8624 - box_loss: 4.3087 - class_loss: 1676.5543 - val_loss: 102.0245 - val_box_loss: 4.1154 - val_class_loss: 97.9091 - val_AP: -1.0000 - val_AP50: -1.0000 - val_AP75: -1.0000 - val_APs: -1.0000 - val_APm: -1.0000 - val_APl: -1.0000 - val_ARmax1: -1.0000 - val_ARmax10: -1.0000 - val_ARmax100: -1.0000 - val_ARs: -1.0000 - val_ARm: -1.0000 - val_ARl: -1.0000
    Epoch 2/5
    27/27 [==============================] - 3s 125ms/step
    creating index...
    index created!
    creating index...
    index created!
    Running per image evaluation...
    Evaluate annotation type *bbox*
    DONE (t=0.01s).
    Accumulating evaluation results...
    DONE (t=0.01s).
     Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
     Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
     Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
     Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
     Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
     Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
    157/157 [==============================] - 24s 148ms/step - loss: 26.2103 - box_loss: 3.7892 - class_loss: 22.4212 - val_loss: 6.9511 - val_box_loss: 3.7243 - val_class_loss: 3.2268 - val_AP: 0.0000e+00 - val_AP50: 0.0000e+00 - val_AP75: 0.0000e+00 - val_APs: -1.0000 - val_APm: -1.0000 - val_APl: 0.0000e+00 - val_ARmax1: 0.0000e+00 - val_ARmax10: 0.0000e+00 - val_ARmax100: 0.0000e+00 - val_ARs: -1.0000 - val_ARm: -1.0000 - val_ARl: 0.0000e+00
    Epoch 3/5
    27/27 [==============================] - 4s 136ms/step
    creating index...
    index created!
    creating index...
    index created!
    Running per image evaluation...
    Evaluate annotation type *bbox*
    DONE (t=0.00s).
    Accumulating evaluation results...
    Please run evaluate() first
    DONE (t=0.00s).
     Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
     Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = -1.000
     Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = -1.000
     Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
     Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
     Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = -1.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = -1.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
    157/157 [==============================] - 25s 156ms/step - loss: 5.3587 - box_loss: 3.5377 - class_loss: 1.8210 - val_loss: 5.1936 - val_box_loss: 3.6672 - val_class_loss: 1.5263 - val_AP: -1.0000 - val_AP50: -1.0000 - val_AP75: -1.0000 - val_APs: -1.0000 - val_APm: -1.0000 - val_APl: -1.0000 - val_ARmax1: -1.0000 - val_ARmax10: -1.0000 - val_ARmax100: -1.0000 - val_ARs: -1.0000 - val_ARm: -1.0000 - val_ARl: -1.0000
    Epoch 4/5
    27/27 [==============================] - 4s 140ms/step
    creating index...
    index created!
    creating index...
    index created!
    Running per image evaluation...
    Evaluate annotation type *bbox*
    DONE (t=0.01s).
    Accumulating evaluation results...
    DONE (t=0.01s).
     Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
     Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
     Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
     Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
     Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
     Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
    157/157 [==============================] - 24s 151ms/step - loss: 4.9255 - box_loss: 3.5298 - class_loss: 1.3956 - val_loss: 5.7386 - val_box_loss: 3.4262 - val_class_loss: 2.3123 - val_AP: 0.0000e+00 - val_AP50: 0.0000e+00 - val_AP75: 0.0000e+00 - val_APs: -1.0000 - val_APm: -1.0000 - val_APl: 0.0000e+00 - val_ARmax1: 0.0000e+00 - val_ARmax10: 0.0000e+00 - val_ARmax100: 0.0000e+00 - val_ARs: -1.0000 - val_ARm: -1.0000 - val_ARl: 0.0000e+00
    Epoch 5/5
    27/27 [==============================] - 3s 125ms/step
    creating index...
    index created!
    creating index...
    index created!
    Running per image evaluation...
    Evaluate annotation type *bbox*
    DONE (t=0.00s).
    Accumulating evaluation results...
    Please run evaluate() first
    DONE (t=0.00s).
     Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
     Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = -1.000
     Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = -1.000
     Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
     Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
     Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = -1.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = -1.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
     Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
    157/157 [==============================] - 24s 151ms/step - loss: 4.1061 - box_loss: 2.9944 - class_loss: 1.1117 - val_loss: 3.9142 - val_box_loss: 2.7361 - val_class_loss: 1.1781 - val_AP: -1.0000 - val_AP50: -1.0000 - val_AP75: -1.0000 - val_APs: -1.0000 - val_APm: -1.0000 - val_APl: -1.0000 - val_ARmax1: -1.0000 - val_ARmax10: -1.0000 - val_ARmax100: -1.0000 - val_ARs: -1.0000 - val_ARm: -1.0000 - val_ARl: -1.0000
    /home/dit-train-3/anaconda3/envs/tf2.13/lib/python3.9/site-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
      saving_api.save_model(
    WARNING:tensorflow:Found duplicated `Variable`s in Model's `weights`. This is usually caused by `Variable`s being shared by Layers in the Model. These `Variable`s will be treated as separate `Variable`s when the Model is restored. To avoid this, please save with `save_format="tf"`.
    => Total training time: 158.72767400741577 seconds
    
    Process finished with exit code 0

</details>

<br>
It can train normally and the train/valid visualize samples are correct.
However, when I use `keras_cv.callbacks.PyCOCOCallback` to validate the validation set in each training epoch,
I get the mAP result = 0, -1 or extremely low value (happen on my 5 datasets).
I also notice the bounding_box_format like "xyxy", "yxyx" in the line  

`keras_cv.callbacks.PyCOCOCallback(val_ds, bounding_box_format="xywh")`.

but the results are the same😥
<br>
I loaded the model from the last epoch to run predictions on the validation set images, motivated by the fact that the loss value had been decreasing normally. Surprisingly, the model was able to make accurate predictions, as demonstrated below.

![predict](https://github.com/keras-team/keras-cv/assets/85726287/d5bdaac0-69d4-473c-b328-4efbf0805d63)

Could you offer some suggestions or advice? Thank you!

**Comment by ianstenbit** [comment]
Interesting -- I'd definitely make sure the box format matches (in this case it looks like "xyxy" is the right format), but it seems like you've tried that.

The other thing to make sure is that your validation dataset isn't being shuffled before being passed to the metrics callback, because this breaks the numerics. (You can look at the docstring for the callback for more detail, but basically you need to either make sure the validation data is never shuffled or cache it before passing it into the callback).

Based on your code, it looks like you _are_ shuffling the validation dataset so I expect that's the problem. Definitely re-open the issue if that doesn't fix it!
