### ISSUE TITLE
Not able to build Stable Diffusion model using `KerasCV`

### ISSUE THREAD

**Issue by sayannath** [keras-team/keras-cv#2100]
### Current Behavior:

While working with the Keras Example [Fine-tuning Stable Diffusion](https://keras.io/examples/generative/finetune_stable_diffusion/).

In the colab notebook, it is using KerasCV v0.4.0 and TensorFlow version is 2.14.0. So it is throwing an error while importing KerasCV i.e

<img width="942" alt="Screenshot 2023-10-11 at 12 38 15 PM" src="https://github.com/keras-team/keras-cv/assets/41967348/f6d60974-f8f0-45e3-b5df-c8d8d669d601">

PS: I haven't made any changes in the code. [Colab Notebook](https://colab.research.google.com/github/keras-team/keras-io/blob/master/examples/generative/ipynb/finetune_stable_diffusion.ipynb)

After installing the latest KerasCV version i.e 0.6.4, it is throwing an error for `SimpleTokenizer`, `DiffusionModel`.

<img width="942" alt="Screenshot 2023-10-11 at 1 02 47 PM" src="https://github.com/keras-team/keras-cv/assets/41967348/883432e4-f37f-4bee-8f46-701fda188461">

**Comment by jbischof** [comment]
We cleaned up the submodel exports in #2080. See the colab in the description

**Comment by sayannath** [comment]
Thanks for the response @jbischof. As it is working, I am closing this issue.
