### ISSUE TITLE
AttributeError: module 'keras_cv.metrics' has no attribute 'COCORecall'

### ISSUE THREAD

**Issue by EdIzaguirre** [keras-team/keras-cv#2103]
### Current Behavior:
When I attempt to instantiate an instance of either the **COCORecall** metric or the **COCOMeanAveragePrecision** metric via the methods demonstrated in the guides, I get an "AttributeError: module 'keras_cv.metrics' has no attribute 'COCORecall'".

`coco_metrics = keras_cv.metrics.BoxCOCOMetrics(
    bounding_box_format="xyxy", evaluate_freq=20
)
`

### Expected Behavior:
I expect the metric to be created. 

### Steps To Reproduce:
Just go to the Colab linked on the [developer guide](https://colab.research.google.com/github/keras-team/keras-io/blob/master/guides/ipynb/keras_cv/coco_metrics.ipynb), run all and you will see the error. Make sure to add the following line to the top of the cell to download the latest version of Keras.  

`!pip install --upgrade -q git+https://github.com/keras-team/keras-cv`

### Version:
Keras 0.6.4

### Anything else:
I haven't noticed anyone else mention this in the Issues tab here on GitHub, nor have I noticed any sort of removal of these metrics in the version updates. Please let me know if I am missing something. I have some free time, I can try and look into why this is happening if it really is a bug.

**Comment by ianstenbit** [comment]
We're moving toward `keras_cv.callbacks.PyCOCOCallback` for COCO metrics as they are compatible with all 3 Keras backends. That COCO metrics developer guide is outdated and shouldn't be presented anywhere as up-to-date. Are you finding that developer guide linked somewhere in our documentation?

**Comment by EdIzaguirre** [comment]
I believe I accessed it by searching for 'KerasCV metrics' in the Keras documentation, [see this link](https://keras.io/search.html?query=KerasCV%20Metrics). It pops up a a few articles regarding COCO metrics, including the guide. It does appear as though you can't access it by just clicking your way through the Keras documentation, looks like you have to search to find it.
