### ISSUE TITLE
Import keras_cv fails with Keras-nightly

### ISSUE THREAD

**Issue by fbadine** [keras-team/keras-cv#2111]
### Current Behavior:

I am trying to use keras_cv along with keras-nightly i.e. 3.0.0.dev2023102103 but a importing Keras_cv is failing and the error shown is:
ImportError: cannot import name '_initialize_variables' from 'keras.src.backend' (/usr/local/lib/python3.10/dist-packages/keras/src/backend/__init__.py)

### Expected Behavior:

Import should be successful

### Steps To Reproduce:

The following code reproduces the issue:
```
!pip install -U keras-nightly
!pip install -U keras-cv
import os
os.environ["KERAS_BACKEND"] = "tensorflow"
import keras
import keras_cv
```

### Version:

- keras
- 3.0.0.dev2023102103
- keras_cv
- 0.6.4

**Comment by sachinprasadhs** [comment]
Thanks for reporting the issue, I was able to replicate the reported behavior and here is the Gist attached https://gist.github.com/sachinprasadhs/cb54e2f3f369ce0ebfb89ca8134b3a61.

Till we fix the issue, you can use the Keras Core library as below.

```python
!pip install -U keras-core
!pip install -U keras-cv
import os
os.environ["KERAS_BACKEND"] = "tensorflow"
import keras_cv
import keras_core as keras
```

**Comment by sampathweb** [comment]
`keras-core` should only be used if you need to use `keras 2` and use `TensorFlow 2.14` and can't upgrade to `TensorFlow 2.15` and `keras 3`.  The following steps work.

```
!pip install -U tensorflow keras  # Keras-CV needs TF 2.15 when used with Keras 3
!pip install -U keras-cv
import os
os.environ["KERAS_BACKEND"] = "tensorflow"
import keras
import keras_cv
```

Closing this issue.  Please re-open if its still an issue.
More details on installation, refer to compatibility matrix in https://keras.io/getting_started/
