### ISSUE TITLE
`TypeError` while training theStable diffusion model.

### ISSUE THREAD

**Issue by sayannath** [keras-team/keras-cv#2115]
Working on [Fine-tuning Stable Diffusion](https://keras.io/examples/generative/finetune_stable_diffusion/)

### Current Behavior:

```python
epochs = 1
ckpt_path = "finetuned_stable_diffusion.h5"
ckpt_callback = tf.keras.callbacks.ModelCheckpoint(
    ckpt_path,
    save_weights_only=True,
    monitor="loss",
    mode="min",
)
diffusion_ft_trainer.fit(training_dataset, epochs=epochs, callbacks=[ckpt_callback])
```

```python
print(training_dataset)
```

```
<_PrefetchDataset element_spec={'images': TensorSpec(shape=(None, 256, 256, 3), dtype=tf.float32, name=None), 'tokens': TensorSpec(shape=(None, 77), dtype=tf.float64, name=None), 'encoded_text': TensorSpec(shape=(None, 77, 768), dtype=tf.float32, name=None)}>
```

Error: 
![Screenshot 2023-10-23 at 8 32 44 PM](https://github.com/keras-team/keras-cv/assets/41967348/bff0a842-cc6b-434b-a6a2-665e51eb9225)

**Comment by divyashreepathihalli** [comment]
@sayannath  are you facing this error while running the example colab as is without making any changes?
Tagging the authors of this example - @sayakpaul could you please take a look?

**Comment by sayakpaul** [comment]
I think it might be because of the version changes. I would suggest checking the versions around the time this tutorial was published and seeing if that works.

**Comment by sayannath** [comment]
> I think it might be because of the version changes. I would suggest checking the versions around the time this tutorial was published and seeing if that works.

Yes, I have tried using that exact version but it was throwing errors while importing the ClipTokenizer and the other modules.

Here is the issue I created. [Link](https://github.com/keras-team/keras-cv/issues/2100)
The solution Keras team provided. [Link](https://github.com/keras-team/keras-cv/pull/2080)

**Comment by divyashreepathihalli** [comment]
@sayannath this should be fixed now, can you check?
