### ISSUE TITLE
RandomColorDegeneration and Equalization are not implemented as vectorized operations

### ISSUE THREAD

**Issue by sup3rgiu** [keras-team/keras-cv#2120]
### Current Behavior:

As Keras_CV==0.6.4, [RandomColorDegeneration](https://github.com/keras-team/keras-cv/blob/v0.6.4/keras_cv/layers/preprocessing/random_color_degeneration.py) and [Equalization](https://github.com/keras-team/keras-cv/blob/v0.6.4/keras_cv/layers/preprocessing/equalization.py) preprocessing layers are not subclasses of `VectorizedBaseImageAugmentationLayer`, thus resulting in a slow forward pass.

### Expected Behavior:

[RandomColorDegeneration](https://github.com/keras-team/keras-cv/blob/v0.6.4/keras_cv/layers/preprocessing/random_color_degeneration.py) and [Equalization](https://github.com/keras-team/keras-cv/blob/v0.6.4/keras_cv/layers/preprocessing/equalization.py) preprocessing layers should be subclasses of `VectorizedBaseImageAugmentationLayer` (introduced in v. 0.5.0).
The implementation of `RandomColorDegeneration` is quite straightforward, while `RandomColorDegeneration` has a potential  bottleneck represented by [tf.histogram_fixed_width](https://www.tensorflow.org/api_docs/python/tf/histogram_fixed_width).
In the following Colab I propose an implementation for both layers.

### Colab:

This colab includes a possible vectorized implementation of the given layers, and also a benchmark.
https://colab.research.google.com/drive/1t5b4a11ae3HWxUoyL-R50E2z8dkNSQYP?usp=sharing

### Version:

0.6.4

**Comment by divyashreepathihalli** [comment]
@sup3rgiu  thank you for filing the issue! If you can open a PR for vectorized implementation of these layers with example outputs showing different augmentations for each image in a batch. that would be great!

**Comment by sup3rgiu** [comment]
Done

> @sup3rgiu thank you for filing the issue! If you can open a PR for vectorized implementation of these layers with example outputs showing different augmentations for each image in a batch. that would be great!

Done https://github.com/keras-team/keras-cv/pull/2214
