### ISSUE TITLE
Augmentation layers do not handle training flag

### ISSUE THREAD

**Issue by sup3rgiu** [keras-team/keras-cv#2121]
### Current Behavior:

For some reason, since version 0.5.0 the augmentation layers no longer handle the `training` flag:

[v0.4.2](https://github.com/keras-team/keras-cv/blob/v0.4.2/keras_cv/layers/preprocessing/base_image_augmentation_layer.py#L365) vs [v0.6.4](https://github.com/keras-team/keras-cv/blob/v0.6.4/keras_cv/layers/preprocessing/base_image_augmentation_layer.py#L414)

### Expected Behavior:

`call` method of both [BaseImageAugmentationLayer](https://github.com/keras-team/keras-cv/blob/v0.6.4/keras_cv/layers/preprocessing/base_image_augmentation_layer.py#L414) and [VectorizedBaseImageAugmentationLayer](https://github.com/keras-team/keras-cv/blob/v0.6.4/keras_cv/layers/preprocessing/vectorized_base_image_augmentation_layer.py) should handle the `training` flag. When set to `False`, no augmentation should be done and the original input image should be returned.

### Colab:

https://colab.research.google.com/drive/1xCVUFQAlDqObeZqBa9C67HYuagAGb_Vq?usp=sharing

### Version:

0.6.4

**Comment by divyashreepathihalli** [comment]
Hi Sup3rgiu, this is the intended behavior. It has been intentionally taken out - it is SUPER confusing and weird to magically have the layer shutoff based on a global training flag. it is totally unexpected and "magical" from a user perspective.  Plus, what if you actually WANT this to work all the time? 
Finally, putting these layers inside a model you are training is just kind of a bad idea.
