### ISSUE TITLE
'tuple' object has no attribute 'rank' while using feature pyramid network

### ISSUE THREAD

**Issue by sineeli** [keras-team/keras-cv#2133]
### Current Behavior:

'tuple' object has no attribute 'rank' while using feature pyramid network

### Steps To Reproduce:

https://colab.sandbox.google.com/gist/sineeli/48885c70cac00415b953e46db8cdaa44/untitled10.ipynb

### Version:

keras_cv==0.64
keras_core==0.1.7
keras==2.14.0

**Comment by sampathweb** [comment]
Please update to `keras 3` with TensorFlow 2.15.  That resolves the issue - 
https://gist.github.com/sampathweb/e2e92d3c9e3255eb5836e4ad9e1a7048
