### ISSUE TITLE
Implement dropblock_2d regularization layer in keras 3

### ISSUE THREAD

**Issue by divyashreepathihalli** [keras-team/keras-cv#2135]
keras-cv/keras_cv/layers/regularization/dropblock_2d.py

**Comment by divyashreepathihalli** [comment]
@sami-bg thank you for your interest. This layer would not be straightforward because it is subclassing an Keras 2 legacy internal baseRandomLayer.

**Comment by divyashreepathihalli** [comment]
No worries! If you are interested we would love to have as many computer vision keras io examples converted to keras 3. This is a priority and could be a good one to start with. - https://github.com/keras-team/keras-io/tree/master/examples/vision

here is a list of them we are yet to convert 

- [ ] learnable_resizer
- [ ]  deit
- [ ]  mixup
- [ ]  perceiver_image_classification
- [ ]  shiftvit
- [ ]  bit
- [ ]  simsiam
- [ ]  generative/dcgan_overriding_train_ste
- [ ]  forwardforward
- [ ]  nnclr
- [ ]  handwriting_recognition
- [ ]  xray_classification_with_tpus
- [ ]  edsr
- [ ]  mobilevit
- [ ]  yolov8
- [ ]  video_classification
- [ ]  nl_image_search
- [ ]  supervised-contrastive-learning
- [ ]  depth_estimation
- [ ]  fully_convolutional_network
- [ ]  vivit
- [ ]  randaugment
- [ ]  consistency_training
- [ ]  basnet_segmentation
- [ ]  barlow_twins
- [ ]  adamatch
- [ ]  pointnet
- [ ]  vit_small_ds
- [ ]  retinanet
- [ ]  temporal_latent_bottleneck
- [ ]  near_dup_search
- [ ]  3D_image_classification
- [ ]  swin_transformers
- [ ]  focal_modulation_network

**Comment by sami-bg** [comment]
I'll give it a try! Thank you for the suggestion :)
