### ISSUE TITLE
Skip value_range in a preprocessing chain

### ISSUE THREAD

**Issue by bhack** [keras-team/keras-cv#214]
https://github.com/keras-team/keras-cv/pull/198#issuecomment-1076669016

**Comment by kartik4949** [comment]
may be useful for #193

**Comment by LukeWood** [comment]
Can you provide a thorough description of the issue here and a proposed solution?  Thanks

**Comment by bhack** [comment]
https://github.com/keras-team/keras-cv/pull/198#issuecomment-1076711598
> @qlzh727  if the value range for all the image are (0, 255) for the input image, then it will benefit from this change (since it skip the conversion). When the input range are (0, 1), then any chain of the layer will keep converting them between (0, 1) and (0, 255). 

> We might want to add some warning to user if this method has been hit several times in the pipeline, and suggest user to pre-convert their value to (0, 255).

I prefer to have something better than just an user warning. Can we find a way to communicate between a KLP chain that we have already converted the value range?

**Comment by bhack** [comment]
I suppose that we need to find some kind of extra input arg for KLP to tell that it is the final in a chain (or leaf). 
I don't know if the KLP layer can be self-aware of its position.

**Comment by qlzh727** [comment]
So far all the KPLs are independent and not aware of each other. If there is an API for teh container of all KPLs (eg a preprocessing stage that connect between raw input and model), then we could control the value range conversion logic there.

**Comment by bhack** [comment]
@qlzh727 It is also that Keras never designed something like (optional) metadata to be passed between layers and that could be ignored other then of course encoding this info directly in an auxiliary output.
Another ugly alternative is that the user could pass an extra parameter to the "last" preprocessing layer to convert back to the original value range so that we will skip useless conversions in the chain.

**Comment by innat** [comment]
The input image for KPL should be in the range of `[0, 255]` by default, right? Why do we need a [values range](https://github.com/keras-team/keras-cv/pull/249) then?

**Comment by LukeWood** [comment]
> The input image for KPL should be in the range of `[0, 255]` by default, right? Why do we need a [values range](https://github.com/keras-team/keras-cv/pull/249) then?

We want to avoid the possibility of silent failures.  Consider you have a data preprocessing pipeline with values [0, 1] - quite common after Rescaling.  If you passed this and didn't know about value_range, RandAugment would output gibberish

**Comment by LukeWood** [comment]
RandAugment now does this
