### ISSUE TITLE
Add requirements for GPU env (TensorFlow, PyTorch, Jax)

### ISSUE THREAD

**Issue by y-vectorfield** [keras-team/keras-cv#2181]
We should add the requirements for GPU env.
The GPU env means all Deep Learning libraries are installed in the GPU version, such as TensorFlow, PyTorch, and Jax.
Therefore, we should merge three requirements-*-cuda.txt

**Comment by sampathweb** [comment]
The issue is deep learning frameworks have different Cuda requirements and can conflict with each other when installed in same env.  If you want to install the GPU version of all the frameworks, what we have seen work is - 
```
pip install -U torch  # Installs Cuda 12
pip install -U jax
pip install -U tensorflow
pip install -r requirements-common.txt
```
You could find more at https://keras.io/getting_started/

**Comment by y-vectorfield** [comment]
Hello, @sampathweb, I see.
Thank you very much for your comment.
