### ISSUE TITLE
YOLOV8 not working with JAX Backend

### ISSUE THREAD

**Issue by IMvision12** [keras-team/keras-cv#2182]
I am not able to import the pre-trained backbone yolov8 model using `from_preset`.

colab : https://colab.research.google.com/drive/1aXzULmIP-MGJ7nxjBuueqR7RUcDvkAvf?usp=sharing

@ianstenbit

**Comment by divyashreepathihalli** [comment]
Hi @IMvision12! This error should be resolved now.
Please remove the keras-core install. Use the following setup code for your colab(this will be simplified soon)
```
!pip install --upgrade git+https://github.com/keras-team/keras-cv -q
!pip install --upgrade torch
!pip install --upgrade tensorflow
!pip install --upgrade jax
!pip install --upgrade keras
```
I just tested your colab and it seems to be working now.
