### ISSUE TITLE
Error with retinanet_resnet50_pascalvoc preset.

### ISSUE THREAD

**Issue by ma7555** [keras-team/keras-cv#2189]
### Current Behavior:
`retinanet_resnet50_pascalvoc` preset throws an error with a custom number of classes. it seems that the model weigths include the head as well. using `resnet50_imagenet` works as expected.
```
model = keras_cv.models.RetinaNet.from_preset(
    "retinanet_resnet50_pascalvoc",
    num_classes=1,
    bounding_box_format="xyxy",
)
```
```
ValueError: Cannot assign value to variable ' prediction_head_10/kernel:0': Shape mismatch.The variable shape (3, 3, 256, 9), and the assigned value shape (3, 3, 256, 180) are incompatible.
```

### Version:
0.7.0

**Comment by sachinprasadhs** [comment]
`resnet50_imagenet` is a backbone with weights and the classification head will get constructed based on the number of classes you specify.
But, `retinanet_resnet50_pascalvoc` is a pre-trained model where classification head is already constructed based on the `pascalvoc` fixed class ids below and it can not be changed.

```
class_ids = [
    "Aeroplane",
    "Bicycle",
    "Bird",
    "Boat",
    "Bottle",
    "Bus",
    "Car",
    "Cat",
    "Chair",
    "Cow",
    "Dining Table",
    "Dog",
    "Horse",
    "Motorbike",
    "Person",
    "Potted Plant",
    "Sheep",
    "Sofa",
    "Train",
    "Tvmonitor",
    "Total",
]
```
For more details on `retinanet_resnet50_pascalvoc` refer the tutorial https://keras.io/guides/keras_cv/object_detection_keras_cv/

**Comment by divyashreepathihalli** [comment]
Thank you for the response @sachinprasadhs.
