### ISSUE TITLE
Improvement readability and comprehensibility of cast process of generate_image() in Stable Diffusion

### ISSUE THREAD

**Issue by y-vectorfield** [keras-team/keras-cv#2195]
According to line 238, the casting method is implemented abruptly and unnaturally.
I added this method previously in pull request #2102.
Hence, I should move this method to line 237 and add comments about the reason for the casting. 
https://github.com/keras-team/keras-cv/blob/925d99d852accdea6fea47c7a778e7a0e82f68cc/keras_cv/models/stable_diffusion/stable_diffusion.py#L238

**Comment by divyashreepathihalli** [comment]
changes merged

**Comment by y-vectorfield** [comment]
@divyashreepathihalli, thank you very much!
