### ISSUE TITLE
Redundant return in `convert_format`

### ISSUE THREAD

**Issue by ariG23498** [keras-team/keras-cv#2201]
In the following lines I have noticed that the bounding boxes are converted in place. I am not sure why we return the dictionary again. This does not raise a bug, but breaks the mental model of inplace and out of place changes.
https://github.com/keras-team/keras-cv/blob/925d99d852accdea6fea47c7a778e7a0e82f68cc/keras_cv/bounding_box/converters.py#L372-L381

It would rather be useful to create a **new** dictionary and return the converted bbox where the original is kept as is.

If that is a good change, I would like to contribute to this (will be a quick fix)

**Comment by LukeWood** [comment]
Agreed - seems better to abide by functional programming paradigms in order to match tf/jax/torch's API styles!

**Comment by divyashreepathihalli** [comment]
@ariG23498 Thanks for filing the issue! please go ahead and open a PR!
