### ISSUE TITLE
quantization of object detection model

### ISSUE THREAD

**Issue by sandhyaparna** [keras-team/keras-cv#2202]
I am currently encountering challenges while attempting to apply both post-training quantization and quantization-aware training (QAT) to an object detection model developed using the Keras CV package. Does Keras CV currently support quantization techniques?

**Comment by sachinprasadhs** [comment]
Hi, 

Thanks for reporting the issue.

As mentioned in the comment here https://github.com/keras-team/keras-cv/issues/170, team is not having any plan to work on this. 
You can close this issue, since it is a duplicate of the above linked issue.
