### ISSUE TITLE
None of KerasCV object detection examples were working in past few months(edits on Keras.io were not published), should they be written in Keras 3?

### ISSUE THREAD

**Issue by Paryavi** [keras-team/keras-cv#2204]

**Comment by Paryavi** [comment]
FYI; @fchollet @sampathweb @ianstenbit @jbischof 
There are unpublished versions of KerasCV examples on Keras.io that fix the bugs, but they need a publish authority. Whose gonna publish those?

**Comment by sampathweb** [comment]
Thanks for reporting the issue. They are updated for Keras 3.  They will be published in the next few days.  You can check them out in the GitHub: https://github.com/keras-team/keras-io/tree/master/guides/keras_cv

**Comment by Paryavi** [comment]
Aloha Ramesh,
Any new updates on the link you shared?
Thanks,
MoZen
