### ISSUE TITLE
PyCOCOCallback -1 mAP problem

### ISSUE THREAD

**Issue by QimaoYang** [keras-team/keras-cv#2212]
I encountered the same situation as #2095 when doing binary classification. After check every possible solution, I found that this function regard the class_id start from 1: [num_detections = ops.sum(ops.cast(gt_classes >0, "int32"), axis=-1)](https://github.com/keras-team/keras-cv/blob/37ffac047e9d700235801cb8820982887a114e28/keras_cv/callbacks/pycoco_callback.py#L102C45-L102C45). Which is incompatible with those class_id beginning with 0, and will finally lead to -1 mAP. I also checked some [discussions](https://github.com/ultralytics/yolov5/issues/10814#issuecomment-1406075422) for YOLO and found out class_id from 0 is allowed. Maybe change the logic to ">=" may helpful.

**Comment by divyashreepathihalli** [comment]
@QimaoYang thank you for filing the issue. Have you tried the suggestion by Ian here - https://github.com/keras-team/keras-cv/issues/2095#issuecomment-1773514264

If this has not worked for you can you please provide a minimal repro or some code context about what you are trying to do?

**Comment by divyashreepathihalli** [comment]
closing because the issue is stale.
