### ISSUE TITLE
Grad-CAM++ visualization tool

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#227]

**Comment by innat** [comment]
- https://github.com/adityac94/Grad_CAM_plus_plus
- https://github.com/totti0223/gradcamplusplus
- https://github.com/samson6460/tf_keras_gradcamplusplus

**Comment by LukeWood** [comment]
Hey @innat - do you happen to know if GradCam++ is strictly better than GradCam and if the API would differ at all?

Thanks for any information!

**Comment by innat** [comment]
As far as I know, not strictly but it's kinda a generalized version of grad-cam. [Here](https://www.mdpi.com/2313-433X/7/7/106) is a review article regarding them, it shows that the results are comparable.
