### ISSUE TITLE
Add a `from_preset()` constructor for StableDiffusion

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-cv#2296]
For consistency with the rest of CV, and the ability to run StableDiffusion offline in Kaggle notebooks, we should port `StableDiffusion` to the `from_preset()` constructor, and host all weights on Kaggle.

- Existing usages all continue to work for compat.
- Expose a new `from_preset("id")` constructor to match other models.
- All weights saved and downloaded from Kaggle hub.

**Comment by carrycooldude** [comment]
hey @mattdangerw , is it begineer friendly issue. I want to contribute to keras-cv.

**Comment by mattdangerw** [comment]
@sampathweb was going to take a look here I think.

This might not be the most external friendly issue because some of it will be moving assets around on the backend, but will leave it to @sampathweb to decide!

**Comment by divyashreepathihalli** [comment]
Closing because this has been completed.
