### ISSUE TITLE
Can you tell me the road map of keras-cv？

### ISSUE THREAD

**Issue by HLearning** [keras-team/keras-cv#23]
I'm very interested in this warehouse. Is it an upgraded version of keras app? Like torchvision?

**Comment by LukeWood** [comment]
Hey @HLearning (and everyone who liked the comment).  We’re working on getting the roadmap ready still.  I have a PR for review with some readme updates that explain the general goals of the repo.  They can be best summarized as reusable components (layers, preprocessing layers, metrics, losses) that aid in the three big computer vision tasks: image classification, image segmentation, and object defection.

I hope this provides some insight and we can share the full roadmap when it’s ready!
