### ISSUE TITLE
Keras3 Submodel Creation Issue: Initial Layer Skipping Problem

### ISSUE THREAD

**Issue by hamidriasat** [keras-team/keras-cv#2314]
### Goal:
The objective is to take the current model and extract a submodel by using only a portion of it, skipping some of the first layers and passing the input straight to a middle layer, and receiving the result from later layers. 

### Current Behavior:
Now, this was supported in Keras 2, but when using the same code in Keras3, it stops at the given output layer but does not skip the initial layers. Instead of starting from the specified/given layer, it starts from the first layer of the base model, which is not required.

### Expected Behavior:
Rather of starting from the first layer of the base model, create a submodel from the given/specified layer. Imagine that you require a new model, one that does not require the initial layers of an already-existing model.
From [here](https://keras.io/guides/functional_api/) I found no way to achieve this.

### Steps To Reproduce:
[Colab link](https://colab.research.google.com/gist/hamidriasat/4b38c169962aa651d56992397c948b4a/create_submodel_in_keras3.ipynb) with further details to reproduce and understand problem. 

### Code Snippet:
```python

import keras_cv
import keras

backbone = keras_cv.models.ResNet34Backbone()

submodel = keras.models.Model(
        inputs=backbone.get_layer("v2_stack_0_block1_1_conv").input,
        outputs=backbone.get_layer("v2_stack_0_block3_out").output
    )
submodel.summary()
```

**Comment by hamidriasat** [comment]
@divyashreepathihalli @fchollet Kindly check this issue it will help me complete [this](https://github.com/keras-team/keras-cv/pull/2271) pull request.

**Comment by divyashreepathihalli** [comment]
@hamidriasat what you are doing in the colab looks right and I got identical outputs for keras 2 and keras 3.

**Comment by hamidriasat** [comment]
@divyashreepathihalli Thanks, Kindly `Restart Session` after executing 3rd last cell where we update Keras to version 3 (cell code below), then you will find a different submodel.  

```
!pip install --upgrade keras-cv tensorflow
!pip install --upgrade keras
# After installation click on restart session button to load latest version of keras.
```

**Comment by hamidriasat** [comment]
Fixed.
Thanks
