### ISSUE TITLE
All the KerasCV layers should register to tf.keras.utils.register_keras_serializable

### ISSUE THREAD

**Issue by qlzh727** [keras-team/keras-cv#233]
This will allow layers to be serialized and deserialized correctly by keras framework, and enable save model etc.

**Comment by qlzh727** [comment]
See https://www.tensorflow.org/api_docs/python/tf/keras/utils/register_keras_serializable for more details.

**Comment by LukeWood** [comment]
would this automatically occur?  Can we make it work in a first party manner where users don't have to provide layer implementations themselves when loading?

**Comment by qlzh727** [comment]
It won't happen automatically, usually the layer owner has to register it, otherwise the model loading will fail since it doesn't know what layer to map to when it see the string version of the config.

**Comment by qlzh727** [comment]
See #235 and all the related test failures discovered during unit test.
