### ISSUE TITLE
How to use KerasCV models on Cell phones? 

### ISSUE THREAD

**Issue by Paryavi** [keras-team/keras-cv#2332]
**Short Description**

Can you show how to convert a KerasCV model for use on an Android phone by converting it (probably to TFLite?)?
Is there a Keras tutorial about it(classification or detection)?
FYI, @sampathweb 

**Papers**

**Existing Implementations**

**Other Information**

**Comment by sachinprasadhs** [comment]
@Paryavi , You can follow the tutorial here for converting Keras model to TFLite model. https://keras.io/examples/vision/mobilevit/#results-and-tflite-conversion
