### ISSUE TITLE
YOLOv8Detector vs YOLOv8 ultralytics

### ISSUE THREAD

**Issue by ksv87** [keras-team/keras-cv#2333]
### Current Behavior:
The keras_cv YOLOv8 model is not trained on an unbalanced data set

### Expected Behavior:
The original YOLOv8 model is successfully trained on an unbalanced data set

### Steps To Reproduce:
to take an unbalanced dataset, I have 4 classes, 3000 objects of the first class, 1500 objects of the second class, 900 objects of the third class, 600 objects of the fourth class.
an attempt to train on such a dataset YOLOv8Detector does not give results, MaP:0.50-0.95 = 0
and if you train the model in the ultralytics framework, the model achieves MaP:0.50-0.95 = 0.30

### Version:
keras: 2.15.0
keras_cv: 0.7.2
tf: 2.15.0

### Anything else:
I think it's all about the dfl

**Comment by Alparslan-Tamer** [comment]
I have some solutions for this problem;

1- don't forget to add global_clipnorm=10.0 to your optimizer.
2- try different classification_loss_weight and box_loss_weight, it is good to increase the classification_loss_weight value to learn the classes better.

example: 
``
model.compile(
		classification_loss="binary_crossentropy",
		classification_loss_weight=10.0,
		box_loss="ciou",
		box_loss_weight=1.0,
		optimiser=optimizer,
	)
``

3- Augmentation is important!

**Comment by sachinprasadhs** [comment]
You can try resizing the images to 640x640, also you can try modifying the code here to modify the grid scale https://github.com/keras-team/keras-cv/blob/dc7a7c00fc533e6f85cfa1bd57dcbef17024ba05/keras_cv/models/object_detection/yolo_v8/yolo_v8_detector.py#L80
