### ISSUE TITLE
Ragged Tensor in Inference issue  

### ISSUE THREAD

**Issue by Paryavi** [keras-team/keras-cv#2352]
I fixed the ragged tensor issue on Keras CV (Btw I am using the latest Keras 3) Object detection using the following code;

def dict_to_tuple(inputs):
    return inputs["images"], bounding_box.to_dense(
        inputs["bounding_boxes"], max_boxes=32
    )

And was able to train the model, and have positive mAPs, but when I wanna do inference using [Object Detection documentation code, inference section,](https://keras.io/guides/keras_cv/object_detection_keras_cv/#inference-and-plotting-results) i.e. the cell copied below, I get the following ragged tensor error;

model.prediction_decoder = keras_cv.layers.NonMaxSuppression(
    bounding_box_format="xywh",
    from_logits=True,
    iou_threshold=0.5,
    confidence_threshold=0.75,
)

Error:
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
[<ipython-input-48-43f46df229cc>](https://localhost:8080/#) in <cell line: 8>()
      6 )
      7 
----> 8 visualize_detections(model, dataset=visualization_ds, bounding_box_format="xywh")

1 frames
[/usr/local/lib/python3.10/dist-packages/keras_cv/src/bounding_box/to_ragged.py](https://localhost:8080/#) in to_ragged(bounding_boxes, sentinel, dtype)
     55     """
     56     if backend.supports_ragged() is False:
---> 57         raise NotImplementedError(
     58             "`bounding_box.to_ragged` was called using a backend which does "
     59             "not support ragged tensors. "

NotImplementedError: `bounding_box.to_ragged` was called using a backend which does not support ragged tensors. Current backend: tensorflow.

visualize_detections(model, dataset=visualization_ds, bounding_box_format="xywh")

**Comment by Paryavi** [comment]
@sachinprasadhs 
Should I limit max_box to 32 again in inference as well?

**Comment by innat-asj** [comment]
@Paryavi I think your issue is ragged tensor with keras 3, which doesn't support yet. 

> NotImplementedError: bounding_box.to_ragged was called using a backend which does not support ragged tensors. Current backend: tensorflow.

Maybe, you can do padding instead. 

```python
preprocessor = keras.Sequential(
    layers=[
        keras_cv.layers.Resizing(
            input_shape, 
            input_shape,
            bounding_box_format=bbox_format,
            pad_to_aspect_ratio=True
        ),
    ],
)

def pad_fn(inputs):
    inputs["bounding_boxes"] = keras_cv.bounding_box.to_dense(
        inputs["bounding_boxes"], max_boxes=32
    )
    return inputs
```
```python
visualization_ds = eval_ds.unbatch()
visualization_ds = visualization_ds.ragged_batch(16)
visualization_ds = visualization_ds.map(
        preprocessor, num_parallel_calls=tf.data.AUTOTUNE
    ) 
visualization_ds= visualization_ds.map(
        pad_fn, num_parallel_calls=tf.data.AUTOTUNE
    )
visualization_ds= visualization_ds.prefetch(tf.data.AUTOTUNE)
```

**Comment by Paryavi** [comment]
Thanks @innat-asj 
I use the padding in the training the model section, and also I used your padding code after training the model (.fit), but I get this error when running the last part of your code;

visualization_ds = visualization_ds.map(
        preprocessor, num_parallel_calls=tf.data.AUTOTUNE
    ) 
visualization_ds= visualization_ds.map(
        pad_fn, num_parallel_calls=tf.data.AUTOTUNE
    )
visualization_ds= visualization_ds.prefetch(tf.data.AUTOTUNE)

Error:
TypeError                                 Traceback (most recent call last)
[<ipython-input-49-5e6ac2ca8ce3>](https://localhost:8080/#) in <cell line: 1>()
----> 1 visualization_ds = visualization_ds.map(
      2         preprocessor, num_parallel_calls=tf.data.AUTOTUNE
      3     ) 
      4 visualization_ds= visualization_ds.map(
      5         pad_fn, num_parallel_calls=tf.data.AUTOTUNE

18 frames
[/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py](https://localhost:8080/#) in error_handler(*args, **kwargs)
    155         bound_signature = None
    156         try:
--> 157             return fn(*args, **kwargs)
    158         except Exception as e:
    159             if hasattr(e, "_keras_call_info_injected"):

TypeError: Sequential.call() got multiple values for argument 'training'

**Comment by divyashreepathihalli** [comment]
@Paryavi what backend are you using? and what is the input tensor's backend? because JAX and pytorch does not support ragged tensors.
