### ISSUE TITLE
stable_diffusion vs diffusion_model

### ISSUE THREAD

**Issue by Reginald-L** [keras-team/keras-cv#2362]
there are two py files: stable_diffusion.py and diffusion_model.py, what is the difference between these two names stable diffusion and diffusion model?
![image](https://github.com/keras-team/keras-cv/assets/67569154/3f31fa5b-ecf8-4b00-9e9f-dd6e5efb0d09)

**Comment by sachinprasadhs** [comment]
`stable_diffusion.py` is base class for `StableDiffusion`, where as `diffusion_model.py` ( `Diffusion Model`) is the sub-component of `StableDiffusion`.

**Comment by tirthasheshpatel** [comment]
To add on to @sachinprasadhs's answer, `diffusion_model.py` is just the UNet for predicting the noise distribution. The `stable_diffusion.py` brings all the components together (i.e. the text encoder, noise scheduler, time step embeddings, the diffusion UNet, and the image encoder/decoder) to provide the users an end-to-end text-to-image model.

I hope this answers your question! I am closing this issue but feel free to reopen if you have further questions.
