### ISSUE TITLE
Is image warping already ported from tfa? 

### ISSUE THREAD

**Issue by FabianSchuetze** [keras-team/keras-cv#2363]
Thanks for providing this repo! 

I wonder if:

- Tf dense image warping: https://www.tensorflow.org/addons/api_docs/python/tfa/image/dense_image_warp is already ported to keras-cv? Is there a way to warp an image in keras-cv? I couldn't find one but am convinced there must be one
- Can the ported method be used with tensorflow-lite?

**Comment by innat** [comment]
Take a look 

https://github.com/keras-team/keras-cv/issues/644
https://github.com/keras-team/keras-cv/issues/163

**Comment by FabianSchuetze** [comment]
Thanks for the quick reply! Ok, then I understand, that's also what I looked at. Will close this issue. Thanks again.
