### ISSUE TITLE
kerascv layers demonstration

### ISSUE THREAD

**Issue by IMvision12** [keras-team/keras-cv#2366]
I've created a repository to showcase KerasCV layers and developed the interface using Streamlit. We can incorporate this into either KerasCV or Kerasio, allowing developers to understand the functionality of KerasCV layers and see how images are changed when we apply different layers to it.

repo: https://github.com/IMvision12/kerascv-demo

https://imvision12-kerascv-demo-app-15jw4n.streamlit.app/

@divyashreepathihalli @fchollet

**Comment by divyashreepathihalli** [comment]
@IMvision12 that is a really cool demo. I think opening this issue on Keras.io could be better.

**Comment by tirthasheshpatel** [comment]
Closing this in favor of keras-team/keras-io#1782
