### ISSUE TITLE
KerasCV on Google Colab

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#2376]
Tried to install keras-cv in colab with latest packages but got the following issue. However, this might be issue with colab and not keras-cv - not sure!!

```python
!pip install --upgrade keras-cv-nightly tf-nightly keras-nightly

import tensorflow as tf
tf.__version__
2.17.0-dev20240310

import keras
keras.__version__
3.1.0.dev2024031103

import keras_cv
keras_cv.__version__
```
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-5-e37ee6d8d2a2>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import keras_cv
      2 keras_cv.__version__

10 frames
[/usr/local/lib/python3.10/dist-packages/keras/api/_v2/keras/__internal__/backend/__init__.py](https://localhost:8080/#) in <module>
      1 """AUTOGENERATED. DO NOT EDIT."""
      2 
----> 3 from keras.src.backend import _initialize_variables as initialize_variables
      4 from keras.src.backend import track_variable

ImportError: cannot import name '_initialize_variables' from 'keras.src.backend' (/usr/local/lib/python3.10/dist-packages/keras/src/backend/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

**Comment by sachinprasadhs** [comment]
I was able to install all these packages in individual cell in colab, here is the Gist https://colab.sandbox.google.com/gist/sachinprasadhs/2c9a60d3e51bc986c37999c222675e87/2376.ipynb

**Comment by innat** [comment]
Not exactly. Inspect the first post, the packages did install but import error for keras-cv.

**Comment by RichiDot** [comment]
I have encountered the same issue. Although the Keras packages appear to be installed, I'm facing difficulties importing the modules. For instance, I encountered this error:

```
ModuleNotFoundError                       
Traceback (most recent call last)
[<ipython-input-2-1a02c2e511a0>](https://localhost:8080/#) in <cell line: 10>()
      8 import tensorflow as tf
      9 import tensorflow.experimental.numpy as tnp
---> 10 from keras_cv.models.stable_diffusion.clip_tokenizer import SimpleTokenizer
     11 from keras_cv.models.stable_diffusion.diffusion_model import DiffusionModel
     12 from keras_cv.models.stable_diffusion.image_encoder import ImageEncoder

ModuleNotFoundError: No module named 'keras_cv.models.stable_diffusion.clip_tokenizer
```

**Comment by smitlg** [comment]
I am trying to fix it in #2394. This isn't an issue on colab side.

**Comment by smitlg** [comment]
> I was able to install all these packages in individual cell in colab, here is the Gist https://colab.sandbox.google.com/gist/sachinprasadhs/2c9a60d3e51bc986c37999c222675e87/2376.ipynb

Installation should work fine. `import keras_cv` will fail.

**Comment by smitlg** [comment]
The failure comes from `import keras_cv`.

**Comment by scienceLabwork** [comment]
> I have encountered the same issue. Although the Keras packages appear to be installed, I'm facing difficulties importing the modules. For instance, I encountered this error:
> 
> ```
> ModuleNotFoundError                       
> Traceback (most recent call last)
> [<ipython-input-2-1a02c2e511a0>](https://localhost:8080/#) in <cell line: 10>()
>       8 import tensorflow as tf
>       9 import tensorflow.experimental.numpy as tnp
> ---> 10 from keras_cv.models.stable_diffusion.clip_tokenizer import SimpleTokenizer
>      11 from keras_cv.models.stable_diffusion.diffusion_model import DiffusionModel
>      12 from keras_cv.models.stable_diffusion.image_encoder import ImageEncoder
> 
> ModuleNotFoundError: No module named 'keras_cv.models.stable_diffusion.clip_tokenizer
> ```

Try using **src** in between keras_cv and models while importing
``` python
from keras_cv.src.models.stable_diffusion.clip_tokenizer import SimpleTokenizer
from keras_cv.src.models.stable_diffusion.diffusion_model import DiffusionModel
from keras_cv.src.models.stable_diffusion.image_encoder import ImageEncoder
```
