### ISSUE TITLE
Support `CutMix` for video data

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#2384]
**Short Description**

Same as 2D [cutmix](https://github.com/keras-team/keras-cv/blob/master/keras_cv/layers/preprocessing/cut_mix.py), the requested feature is for 3D volume.

<img src="https://github.com/keras-team/keras-cv/assets/17668390/a9612cb9-3eb9-4644-9a0e-a1c49f75c2e6" width="400" height="400" />

**Papers**

https://arxiv.org/abs/1905.04899

**Existing Implementations**

**Other Information**

**Comment by tirthasheshpatel** [comment]
This should theoretically be supported since we allow any tensors of shape `(..., H, W, C)`. I am guessing videos are just frames of images with shape `(B, NUM_FRAMES, H, W, C)`. Not sure though, how consistent is this support across all the preprocessing layers but IMO, it should be an easy fix even if it's broken.

**Comment by tirthasheshpatel** [comment]
I can see an argument for temporal consistency across frames when preprocessing but that seems like too much of a stretch from what KerasCV is designed to do. If we can treat frames independently, it would be much easier to add/advertise support for video data.

**Comment by innat** [comment]
The above gif is generated after adjusting some computation of the image-[cutmix](https://github.com/keras-team/keras-cv/blob/master/keras_cv/layers/preprocessing/cut_mix.py).  If it's wanted, we can send a draft PR for evaluation.

**Comment by tirthasheshpatel** [comment]
I don't have a strong opinion. At the first glance though, I'd be against adding this simply because you can always reshape the input tensors to make them work for videos:

```python
import keras_cv
import keras
from keras import ops

B, F, H, W, C = tuple(image.shape)
images = ops.reshape(image, (B * F, H, W, C))
augmented = keras_cv.layers.CutMix()(images)
augmented = ops.reshape(augmented, (B, F, augmented.shape[-3], augmented.shape[-2], augmented.shape[-1]))
```

Does this work for your use case @innat?

**Comment by innat** [comment]
I tried reshaping approach at first. In the above code example, there are couple of issue. 

**First**, it becomes limited due to `num_frames == num_classes`.   **Second**, introducing complexity for augmented labels.  **Third**, cutmixing is happening on video_a from many video samples in a given timestep, which breaks the temporal consistency, IMO. Instead, cutmixing video_a and video_b makes such sense to me. (Same goes to MixUp).

**Comment by tirthasheshpatel** [comment]
Again, no strong opinion. If you have a diff, feel free to propose. It would be also nice to first identify the layers where videos need to be treated differently. Like CutMix and MixUp. If you have a list, that'd be really helpful.
