### ISSUE TITLE
Import `keras_cv` fails on current master

### ISSUE THREAD

**Issue by smitlg** [keras-team/keras-cv#2400]
Some parts of `keras_cv` depends on `keras_nlp` and `tensorflow_text`. The following errors pops up:
```py
[/usr/local/lib/python3.10/dist-packages/keras_cv/models/feature_extractor/clip/clip_tokenizer.py](https://localhost:8080/#) in <module>
     14 import regex as re
     15 import tensorflow as tf
---> 16 import tensorflow_text as tf_text
     17 
     18 try:

ModuleNotFoundError: No module named 'tensorflow_text'
``` 

Fixing this error by `pip install tensorflow_text`, gives a new error:

```py
[/usr/local/lib/python3.10/dist-packages/keras_cv/models/feature_extractor/clip/clip_tokenizer.py](https://localhost:8080/#) in <module>
    105 
    106 
--> 107 class CLIPTokenizer(BytePairTokenizer):
    108     def __init__(self, **kwargs):
    109         super().__init__(**kwargs)

NameError: name 'BytePairTokenizer' is not defined
```

This will be only fixed by installing `keras_nlp` or by the approach used in #2394

**Comment by sachinprasadhs** [comment]
Hi,

Could you please let us know, what is the API which is causing error while importing.

**Comment by smitlg** [comment]
Steps to reproduce(assuming you are on current master branch):
1. Uninstall both `keras_nlp` and `tensorflow_text`.
2. `pip install .`
3. Now, do `import keras_cv`.

**Comment by sachinprasadhs** [comment]
Thanks for the input, I was able to reproduce the error [![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.sandbox.google.com/gist/sachinprasadhs/de536e4742839f805edf569dcbf6b2f4/2400.ipynb)

**Comment by ayaz-markovate** [comment]
Same problem on Colab. Following this example: https://keras.io/examples/vision/yolov8/#creating-model

**Comment by VarunS1997** [comment]
Verified fix was successful and issue is no longer present.
