### ISSUE TITLE
Devcontainer

### ISSUE THREAD

**Issue by bhack** [keras-team/keras-cv#242]
Can we have a `.devcontainer` like in Keras?

https://github.com/keras-team/keras/tree/master/.devcontainer

**Comment by bhack** [comment]
Can you double check this with the internally board before I start? 

Honestly I had a not so good experience with another PR in this repo:
https://github.com/keras-team/keras-cv/pull/11#discussion_r747055087
https://github.com/keras-team/keras-cv/pull/14#issuecomment-1016937939

**Comment by LukeWood** [comment]
Understandable and still sorry about that.  Cheers - I will double check tomorrow for you.

Does .devcontainer impact anyone else's workflow or only those who opt in to using them?

**Comment by LukeWood** [comment]
Hey @bhack yeah happy to accept this.  Just checked

**Comment by LukeWood** [comment]
Lets mirror keras-tuner's, but I don't think we want the linter as a pre-commit hook from what we have generally discussed as a team.

So our setup.sh will just have:
```
pip install -e ".[tests]"
pip install -e ".[examples]"
```

Cheers - if anyone wants to pick this up happy to accept

**Comment by bhack** [comment]
Do we want to depend on latest or nightly Tensorflow images?

https://github.com/keras-team/keras-tuner/blob/master/.devcontainer/Dockerfile#L1

See also out thread at:
https://github.com/keras-team/keras-cv/issues/195#issue-1177283651

**Comment by LukeWood** [comment]
we can use nightly for now, until the next tensorflow version comes out which will have BaseImageAugmentationLayer in the keras namespace.

**Comment by bhack** [comment]
> we can use nightly for now, until the next tensorflow version comes out which will have BaseImageAugmentationLayer in the keras namespace.

Do you have a minimal date for nightly?

**Comment by LukeWood** [comment]
> Do you have a minimal date for nightly?

minimal in what sense?  A date when we can move to normal tf?  I believe this can be done the release after 2.9, so 2.10.  after 2.9 lands we can try changing the dependency to `tensorflow` from `tf-nightly` and see if it works.
