### ISSUE TITLE
Ensure our bounding box format matches pycocotools'

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#245]
https://github.com/keras-team/keras-cv/blob/master/keras_cv/utils/bounding_box.py

FYI @bhack I will be double checking this and get back tp you.

**Comment by LukeWood** [comment]
So, we took our conversion formulas from model garden.  I think (as you pointed out) this mismatches COCO's format.  I will need to update this.  The format of x and y being in the middle of the box is absolutely NOT canonical to image processing.

**Comment by bhack** [comment]
We could close this
