### ISSUE TITLE
Detecting more than 100 objects in a single image using retinanet

### ISSUE THREAD

**Issue by DKosatov** [keras-team/keras-cv#2452]
Hello, could you explain if it is possible to use retinanet to find more than 100 objects in one image?

My images may contain more than 100 objects of the same type.
I'm setting max_detections=400 for MultiClassNonMaxSuppression.
```
keras_cv.layers.MultiClassNonMaxSuppression(
    bounding_box_format="xyxy",
    from_logits=True,
    iou_threshold=0.2,
    confidence_threshold=0.6,
    max_detections=400
)
```
But
```
y_pred = mt.predict(image_batch)
print(y_pred['confidence'][0])
```
It always contains no more than 100 predicted objects and 300 (-1.).
Please tell me if there is a way to fix this

**Comment by DKosatov** [comment]
Since the objects in the image were of the same class, it was necessary to add
`max_detections_per_class=400`
After that, everything works correctly.

**Comment by Atharv-02** [comment]
Why have you marked this as completed ?
