### ISSUE TITLE
Not able to run `CLIP Model` using `from_present` 

### ISSUE THREAD

**Issue by carrycooldude** [keras-team/keras-cv#2472]
### Current Behavior:
![Screenshot from 2024-08-06 21-21-59](https://github.com/user-attachments/assets/a7a2a07b-28f7-4425-935f-22358f25580d)

### Expected Behavior:
not able to load CLIP model even though I installed keras-nlp too

### Steps To Reproduce:

![Screenshot from 2024-08-06 21-23-59](https://github.com/user-attachments/assets/51e07fce-0935-455f-8465-b91da78ead30)

### Version:
![Screenshot from 2024-08-06 21-25-22](https://github.com/user-attachments/assets/c005a864-e118-471d-9cc9-8096534045e6)

### Anything else:
This is my colab [link](https://colab.research.google.com/drive/1ggkGIYW0_h5IDLDv5zO2e84-50Yamp7F?usp=sharing)

**Comment by sachinprasadhs** [comment]
You need to install the dependencies and load the clip model as below.

```python
!pip install -U keras-cv
!pip install -U keras-nlp
!pip install -U keras

import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, Concatenate
from tensorflow.keras.models import Model
from keras_cv.models import CLIP
import numpy as np

# Load the pre-trained CLIP model from KerasCV
clip_model = CLIP.from_preset("clip-vit-base-patch16")
```

for Image and Text encoder, you can use as below.

```python
# Define inputs
image_input = Input(shape=(224, 224, 3), name='image_input')
text_input = Input(shape=(77,), name='text_input', dtype=tf.int32)

# Process image through CLIP
image_embeds = clip_model.image_encoder(image_input)

# Process text through CLIP
text_embeds = clip_model.text_encoder(text_input)
```

**Comment by carrycooldude** [comment]
thanks @sachinprasadhs , it's working but I guess it's not in docs 
Can I contribute to it?

**Comment by sachinprasadhs** [comment]
Sure
