### ISSUE TITLE
`value_range` must be required, not optional for all KPLs that use it.

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#248]

**Comment by innat** [comment]
why? can you explain more?

**Comment by LukeWood** [comment]
We want to avoid the possibility of silent failures. Consider you have a data preprocessing pipeline with values [0, 1] - quite common after Rescaling. If you passed this and didn't know about value_range, RandAugment would output gibberish

**Comment by kartik4949** [comment]
I can second this @LukeWood, silent errors are really tough to debug, really gives a bad impression on lib

**Comment by innat** [comment]
@LukeWood yes, this makes sense. Thanks.
