### ISSUE TITLE
Videoswin cannot load from preset

### ISSUE THREAD

**Issue by pass-lin** [keras-team/keras-cv#2485]
I followed the instructions in the document at https://keras.io/api/keras_cv/models/tasks/deeplab_v3_segmentation/ and encountered an error when I input the following code:
```python
from keras_cv.models import DeepLabV3Plus  
model = DeepLabV3Plus.from_preset("videoswin_tiny_kinetics400")
```
error is
```python
Traceback (most recent call last):

  Cell In[2], line 2
    model = DeepLabV3Plus.from_preset("videoswin_tiny_kinetics400")

  File F:\anaconda\Lib\site-packages\keras_cv\src\models\task.py:184 in from_preset
    return super(cls, calling_cls).from_preset(*args, **kwargs)

  File F:\anaconda\Lib\site-packages\keras_cv\src\models\task.py:134 in from_preset
    preset = cls.presets[preset]["kaggle_handle"]

KeyError: 'kaggle_handle'
```

**Comment by barrypitman** [comment]
I'm running into the same issue

**Comment by innat** [comment]
The video-swin checkpoints are not added to keras-application, so you likely can't call it. If you're working with video modelling and require video-swin in keras-v3, you can try [this](https://github.com/innat/VideoSwin). 

Also, video-swin is a 3D model and you're attempting to load it in 2D segmentation model, which is not supported in keras yet.
