### ISSUE TITLE
SaltAndPepper preprocessing layer

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#25]

**Comment by bhack** [comment]
Is this going to be another noise layer impl:
https://github.com/keras-team/keras/blob/master/keras/layers/noise.py

**Comment by bhack** [comment]
Check also 
https://github.com/keras-team/keras/pull/335#issuecomment-118661067

**Comment by LukeWood** [comment]
I'm closing this out for now, we can reopen if anyone requests this.
