### ISSUE TITLE
Equalization should support a dynamic # of channels

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#255]
we shouldn't have to tell the layer this before hand.

**Comment by quantumalaviya** [comment]
@LukeWood Isn't this covered as part of #201?  Or am I missing something?

**Comment by LukeWood** [comment]
Ah awesome.  Looks like you’re right.  I just opened this when experimenting with the later a bit and encountering this with a grayscale image.

**Comment by LukeWood** [comment]
> @LukeWood Isn't this covered as part of #201? Or am I missing something?

Sorry that or slippedn
