### ISSUE TITLE
 LookupError: gradient registry has no entry for RandomShuffle

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#259]
## ChannelShuffle

[Issue: Details](https://github.com/keras-team/keras-cv/pull/218#discussion_r840739049).

**Comment by LukeWood** [comment]
We should fix this by implementing a custom shuffle operation using get random transformation and gather

**Comment by innat** [comment]
Is such error espected? Why does it cause in the first place?

**Comment by LukeWood** [comment]
>  LookupError: gradient registry has no entry for RandomShuffle
looks like TensorFlow doesn't differentiate over the random_shuffle operation.

**Comment by innat** [comment]
> looks like TensorFlow doesn't differentiate over the random_shuffle operation.

I will raise an issue in tensorflow to get a more concrete reason. 

> Not using get_random_transformation() isn't idiomatic to KerasCV anyways, so the code is more consistent with a custom shuffle using get_random_transformation() and tf.gather().

Agree. But as the tensorflow is the backend of keras, it should be ok to use the existing operation from tensorflow. It's not violating any idiomatic rules (IMO).

**Comment by bhack** [comment]
@innat Other in the case you have mentioned where it was working without problema have you tried to see the effect on the device placement with:

https://www.tensorflow.org/api_docs/python/tf/debugging/set_log_device_placement

**Comment by innat** [comment]
@bhack no, I didn't use any `tf.debugging.*`, thanks for bringing it up. I will surely try next.

**Comment by bhack** [comment]
Yes as I have some doubt also when it Is working if we are implcitly creating some constrain to be placed on CPU

**Comment by innat** [comment]
@bhack 
Okay, I test with `tf.debugging.set_log_device_placement` to check the placement of tf operation on devices in the backend. Shortly, I didn't find any suspicious behavior.  Here is the model 

```python
model = keras.Sequential(
    [
        keras.Input(shape=input_shape),
        ChannelShuffle(groups=3),

        layers.Conv2D(32, kernel_size=(3, 3), activation="relu"),
        ChannelShuffle(groups=4), 

        layers.MaxPooling2D(pool_size=(2, 2)),
        ChannelShuffle(groups=8), 

        layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
        layers.MaxPooling2D(pool_size=(2, 2)),
        layers.Flatten(),
        layers.Dropout(0.5),
        layers.Dense(num_classes, activation="softmax"),
    ]
)
```

**Note:** 

In the above model, there are 3 channel shuffling layers. The first one is right after the input. And the rest of them are in the middle. 

- But. When I checked `ChannelShuffle` with `keras_cv`,  it didn't run anything at all, showing some breaking error. 
- So, I use a standalone implementation of this layer. And it successfully runs if I use this layer right after the input (the first one in the above model) but it doesn't work with the rest of the channel shuffle layer that is in the middle of the net.

[HERE](https://colab.research.google.com/drive/1VMWgBF49_G_5QIbcMmTo7KOmDGsbpXdo?usp=sharing) is the reproducible colab. In the file, the below two parameters you need to set 

```python
# if True, the chan_shuffle will be imported from keras-cv -
# which doesn't work at all (may be due to upcoming tensorflow 2.10 dev. 
use_keras_cv = False 

# to check operation placement.
device_palcement_logging = True 
```

**Comment by bhack** [comment]
I don't know if I've checked correctly but it seems that on GPU is always failing with:

`UnimplementedError: Graph execution error:`

With a CPU runtime is always ok.

I suppose that we don't have a random_shuffle GPU kernel.

**Comment by innat** [comment]
Yes, if you use `tf-nightly` (version: `2.10.0-dev20220404`), it will give that error:`UnimplementedError: Graph execution error:`

But if we try the stable tf version (2.8), it works at least for the first channel shuffle of the above-mentioned model. You can verify this by running the above colab file.

**Comment by LukeWood** [comment]
Is this still an issue?  I think we need to implement a custom random shuffle.  ShuffleNet is a legitimate use case.

**Comment by bhack** [comment]
Other then opening a Ticket on Github for the GPU case can we check if we could workaround it with:

https://www.tensorflow.org/api_docs/python/tf/random/experimental/index_shuffle

**Comment by bhack** [comment]
@innat Have you tried with `index_shuffle`?. 
Other then the GPU issue we are going in fallback just for this op also on CPU:

```
WARNING:tensorflow: Using a while_loop for converting RandomShuffle cause has no variant outputs and has no vectorized variant inputs
``

**Comment by innat** [comment]
@bhack not yet. 
Anyway, just wondering, both functions not only derive from `tf.random.*` but also serve samething in nature`, will there be any differences?

**Comment by bhack** [comment]
What I see from the doc is that this one has an explicit claim:
> This operation is stateless (like other tf.random.stateless_* functions),

**Comment by innat** [comment]
With `tf.random.shuffle`, if we use `tf.stop_gradient` it works in most cases ( with some frightening warning message. )

**Comment by bhack** [comment]
I suppose we still have a fallback:

`WARNING:tensorflow: Using a while_loop for converting RandomShuffle cause has no variant outputs and has no vectorized variant inputs`

**Comment by innat** [comment]
@bhack I tried `index_shuffle`, and it works. But same as `tf.random.shuffle`, it also gives 

> WARNING:tensorflow:Using a while_loop for converting RandomIndexShuffle cause has no variant outputs and  has no vectorized variant inputs

( Unlike `tf.random.shuffle`, I didn't need to stop gradient flow. )

**Comment by innat** [comment]
[Code.](https://colab.research.google.com/drive/1VMWgBF49_G_5QIbcMmTo7KOmDGsbpXdo?usp=sharing)

**Comment by bhack** [comment]
Thanks for testing.

> WARNING:tensorflow:Using a while_loop for converting RandomIndexShuffle cause has no variant outputs and has no vectorized variant inputs

This is the new message that I've added in Tensorflow master on why an specific op has fallback in a while loop.  
It is not so useful for an external developer for the action item/workaround and we are trying to collect feedback at https://github.com/tensorflow/tensorflow/issues/55425

> ( Unlike tf.random.shuffle, I didn't need to stop gradient flow. )

This is a marginal problem also with `tf.random.shuffle` if/when https://github.com/tensorflow/tensorflow/pull/55529 will be merged.

**Comment by bhack** [comment]
@innat What I have seen is that many ops are failing cause they don't have their stateless property `is_stateful: true` defined in the protobuf. 

I don't know for `tf.random.shuffle` but for `index_shuffle` it was explicitly declared stateless in the docstring (but not in protobuf) so it is quite strange:

>  This operation is stateless (like other tf.random.stateless_* functions),

Protobufs are in:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/core/ops/compat/ops_history_v2

See the protobuf check at line `203`:

https://github.com/tensorflow/tensorflow/blob/55645ca964508507890529a71591f51a344a6356/tensorflow/python/ops/parallel_for/pfor.py#L193-L204

/cc @wangpengmit

**Comment by bhack** [comment]
@innat So a small update to confirm the hypothesis.

`RandomShuffle` is stateful:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/compat/ops_history_v2/RandomShuffle.pbtxt#L29

`tf.random.experimental.index_shuffle` instead is stateless.

Like other ops that we have used in ChannelShuffle (and more in general in other KPLs) is going to fallback cause [we don't have  implemented a converter yet](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/parallel_for/pfor.py#L920-L997).

This is the list of missing converters just for the ops we have used in `ChannelShuffle` (your colab):

- `Bitcast`
- `PadV2`
- `RandomIndexShuffle`
- `RngReadAndSkip`
- `StatelessRandomUniformFullIntV2`
- `RandomShuffle` (in the current implementation)

**Comment by innat** [comment]
Partially related. https://github.com/tensorflow/tensorflow/issues/55646

**Comment by bhack** [comment]
https://github.com/tensorflow/tensorflow/pull/55529 was just merged, you need to wait the next nightly.

`while_loop` fallbacks are handled instead at https://github.com/keras-team/keras-cv/issues/291

**Comment by LukeWood** [comment]
> [tensorflow/tensorflow#55529](https://github.com/tensorflow/tensorflow/pull/55529) was just merged, you need to wait the next nightly.
> 
> `while_loop` fallbacks are handled instead at #291

Woot.  Great news.

**Comment by innat** [comment]
@bhack (cc. @LukeWood )
So, it will be ok with `tf.random.shuffle`? With the current implementation, as far as I remember, we have two issues, (a) `shuffle` function fallback to CPU, and (b). it requires wrapping with [`tf.stop_gradient`](https://github.com/keras-team/keras-cv/issues/259#issuecomment-1091127096). So, with [this](https://github.com/keras-team/keras-cv/issues/259#issuecomment-1101460128) update, all will be solved?

Also, implementation with `tf.random.shuffle` requires two times `tf.transpose`, which I've read somewhere is computationally expensive. And implementation with `tf.random.index_shuffle` requires (maybe less) simpler tf operation. Any thoughts on this? 

```python
indices = tf.random.index_shuffle(..)
image  = tf.reshape(image, [h, w self.groups, ch_per_grp])
image  = tf.gather(image, indices, axis=2)
image  = tf.reshape(image, [height, width, num_channels])

----

image = tf.transpose(image, perm=[2, 0, 1, 3])
image = tf.random.shuffle(image, seed=self.seed)
image = tf.transpose(image, perm=[1, 2, 3, 0])
image = tf.reshape(image, [height, width, num_channels])
```

**Comment by bhack** [comment]
> So, it will be ok with tf.random.shuffle? With the current implementation, as far as I remember, we have two issues, (a) shuffle function fallback to CPU, and (b). it requires wrapping with tf.stop_gradient. So, with this update, all will be solved?

(a) It fallback on while_loop not a CPU fallback
(b) It Is solved but we don't have a gradient.

**Comment by bhack** [comment]
@bhack Also if we don't have already XLA compile control API with its own CI coverage (last point in https://github.com/keras-team/keras-cv/issues/291) I propose to use `tf.random.shuffle` if the stateless nature of `tf.random.index_shuffle` isn't mandatory for this project (see https://github.com/keras-team/keras-cv/issues/258). 

Both don't have a PFOR converter (see again https://github.com/keras-team/keras-cv/issues/291) but at least `tf.random.shuffle` has XLA coverage already (`jit_compile`) when instead `tf.random.index_shuffle` isn't not covered by XLA:
```
XLA_CPU_JIT: RandomIndexShuffle (No registered 'RandomIndexShuffle' OpKernel for XLA_CPU_JIT
```

**Comment by innat** [comment]
Can we close this issue if the issue with `tf.random.shuffle` is fixed? 
cc. @bhack

**Comment by bhack** [comment]
The fallback is tracked in another ticket so if you don't care about the lack of differentiability of this op, as we don't care about the same on other ops that we have already used in this library, you could close this.

**Comment by LukeWood** [comment]
> The fallback is tracked in another ticket so if you don't care about the lack of differentiability of this op, as we don't care about the same on other ops that we have already used in this library, you could close this.

I think this one is unique in that ShuffleNet needs this layer to be differentiable.

Is there a Keras shufflenet implementation somewhere around?  We could try taking their shuffle logic.

**Comment by bhack** [comment]
Isn't channel_shuffle in that case?

**Comment by bhack** [comment]
https://github.com/tensorpack/tensorpack/blob/master/examples/ImageNetModels/shufflenet.py#L41

**Comment by bhack** [comment]
@LukeWood What I meant is that, if I remember, correctly that `channel_shuffle` was not a random one an in the KLP semantic.

**Comment by LukeWood** [comment]
The KerasCV team is attempting to narrow the package scope in order to more efficiently use our limited resources. As such, we are only accepting contributions directly related to items on the 6 month roadmap for the package.

If you feel this feature could be particularly useful, or would like to contribute it - please feel free to re-open this issue and ping LukeWood, ianstenbit or tanzhenyu

Feel free to read more on the roadmap:
https://github.com/keras-team/keras-cv/blob/master/.github/ROADMAP.md
