### ISSUE TITLE
GaussianBlur preprocessing layer

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#26]

**Comment by bhack** [comment]
Se have both 2d and 3d:

https://github.com/tensorflow/models/blob/master/official/vision/beta/projects/video_ssl/ops/video_ssl_preprocess_ops.py#L248


And:
https://github.com/tensorflow/models/blob/master/official/vision/beta/projects/simclr/dataloaders/preprocess_ops.py#L233

**Comment by LukeWood** [comment]
We can also use: https://github.com/google-research/simclr/blob/master/tf2/data_util.py#L326 if we want

**Comment by bhack** [comment]
But If you need to support a 4d tensor with batch size you need to look at addons:

https://github.com/tensorflow/addons/blob/master/tensorflow_addons/image/filters.py#L232

**Comment by artu1999** [comment]
Happy to look into this if no one has started working on it

**Comment by LukeWood** [comment]
@artu1999 thanks for offering to take this on.  Please feel free.

we may also want to support:

- [MedianBlur](https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.MedianBlur)
- [MotionBlur](https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.MotionBlur)

but I consider these to be lower priority.  So focus on Gaussian first is recommended.

**Comment by artu1999** [comment]
Awesome! After implementing GaussianBlur it should be fairly easy to implement the others as well. In terms of input args, I guess we want to keep it similar to this?

https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.GaussianBlur

**Comment by LukeWood** [comment]
I'd like to match the mathematical definition of GaussianBlur.  If theirs matches that, then that is a great reference.  Thanks

**Comment by bhack** [comment]
Gaussian Blur Is already available in TFA. If you want you could port/adapt from there.
