### ISSUE TITLE
Bounding box support in MixUp augmentation

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#261]

**Comment by LukeWood** [comment]
this is used in YoloX training.

**Comment by quantumalaviya** [comment]
I would love to work on this.

**Comment by LukeWood** [comment]
Thanks!  @quantumalaviya I have made you the assignee.  Please include references regarding the "how" as to how this works as we discussed via LinkedIn messenger. Cheers!

**Comment by quantumalaviya** [comment]
Will do. 
Also, the MixUp demo doesn't seem to be working since the migration to BaseImageAugmentationLayer. Should I also fix that in this PR? @LukeWood

**Comment by quantumalaviya** [comment]
Went ahead and did it anyway

**Comment by LukeWood** [comment]
> Went ahead and did it anyway

Oh thank you.  Sorry for not seeing this.
