### ISSUE TITLE
Mute warning messages on vectorized_map

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#264]

**Comment by kartik4949** [comment]
```
def mute_tf_warnings(func):
    def wrapper_func():
        _level = tf.get_logger().level
        tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.FATAL)
        #  tf.autograph.set_verbosity(tf.compat.v1.logging.FATAL)
        func()
        tf.compat.v1.logging.set_verbosity(_level)
        #  tf.autograph.set_verbosity(level)
    return wrapper_func
```

@bhack @LukeWood 
idk if it will works...

**Comment by LukeWood** [comment]
Ideally the TensorFlow side will mute it because some of these should not really be warnings, but yes we might have to do a hack like above.  This isn't blocking for v1 though so we can take time to figure it out.

**Comment by bhack** [comment]
I hope at least we don't mute this when we are in "development mode" as it is important  to know when we rely on fallback also with new KPL.

**Comment by LukeWood** [comment]
> I hope at least we don't mute this when we are in "development mode" as it is important to know when we rely on fallback also with new KPL.

Good point - yeah, I think the true issue is we don't want users thinking the code is bugged if the warning is a no-op.

**Comment by bhack** [comment]
We have already a bool param in TF but it is not exposed in the public API:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/parallel_for/pfor.py#L1080

**Comment by bhack** [comment]
You could try to comment and ask to expose that arg in https://github.com/tensorflow/tensorflow/pull/55562

**Comment by bhack** [comment]
We can close this.
