### ISSUE TITLE
RandomErasing preprocessing layer

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#27]

**Comment by bhack** [comment]
https://github.com/tensorflow/models/blob/master/official/vision/beta/ops/augment.py#L2021

**Comment by innat** [comment]
RadomErasing and Cutout augmentation are almost alike, except in RandomErasing, the cutout happens with random sizes. 

cutout: [tfa.image.cutout](https://www.tensorflow.org/addons/api_docs/python/tfa/image/cutout)

![image](https://user-images.githubusercontent.com/17668390/148637871-fef66b41-5fad-4377-b0f5-7df1cec6a7ff.png)

![image](https://user-images.githubusercontent.com/17668390/148637876-1219155c-1e9f-4e13-af8f-dde80d92e7fa.png)

**Comment by LukeWood** [comment]
A comment from @sayakpaul:

> Random Erasing [1] is another essential augmentation transform for controlling the amount of regularization when training models on ImageNet. It's also used by the recent line of papers [2, 3]. Short explanation: https://paperswithcode.com/method/random-erasing.
> [1] Random Erasing: https://arxiv.org/abs/1708.04896
> [2] ResNet Strikes Back: https://arxiv.org/abs/2110.00476
> [3] A ConvNet for the 2020s: https://arxiv.org/abs/2201.03545

**Comment by LukeWood** [comment]
Thanks @chjort
