### ISSUE TITLE
Simple Copy-Paste Augmentation (Instance Segmentation)

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#28]
Demo:
![ds](https://user-images.githubusercontent.com/17668390/148637175-abb63833-85b9-4af9-ab67-0753212b89af.jpeg)

Ref: https://github.com/tensorflow/tpu/tree/master/models/official/detection/projects/copy_paste

**Comment by frostbyte012** [comment]
Can you explain a bit more I wanna know how this issue can be solved I want to contribute and I'm a first time contributor

**Comment by bhack** [comment]
> Can you explain a bit more I wanna know how this issue can be solved I want to contribute and I'm a first time contributor

You need to read the related paper at https://arxiv.org/abs/2012.07177

**Comment by innat** [comment]
@frostbyte012 In addition to the above-mentioned paper, you can also look into pytorch implementation. 

- [implementation 1](https://github.com/RocketFlash/CAP_augmentation)
- [implementation 2](https://github.com/conradry/copy-paste-aug)

![all](https://user-images.githubusercontent.com/17668390/158065025-27e02e19-36eb-4074-9ae9-2004130a6252.png)

**Comment by MrinalTyagi** [comment]
@innat @bhack Can I pick this up if no one else is working on it currently? Thank you

**Comment by innat** [comment]
@MrinalTyagi of course, anyone can. That would be great.

**Comment by frostbyte012** [comment]
@innat @bhack  is it possible to get the starting template / implementation in TensorFlow or Keras ? Any source or link?

**Comment by innat** [comment]
It's mentioned already 
ref. https://github.com/keras-team/keras-cv/issues/28#issue-1094848083

**Comment by MrinalTyagi** [comment]
@innat @bhack If I am not wrong, in this we will be adding a new data augmentation layer named CopyPasteAugmentation. In that, we will have initialization of parameters including sigma, blend, max objects that we can paste in an image, paste images, source images, x and y from which we have can apply copy-paste augmentation. This is the current scenario in my mind regarding it. Will update it accordingly during the course of time. Additionally, we should also provide a possible option to the users to save these augmented images as well as the information by how much the dataset was augmented as that can be really useful in some cases.

**Comment by bhack** [comment]
@MrinalTyagi use existing merged layers as a reference to grasp some code conventions.

@frostbyte012 Please coordinate with @MrinalTyagi you could collaborate on his branch if you are both interested.

**Comment by MrinalTyagi** [comment]
Got it. @frostbyte012 will share details of the draft pr with you soon with a basic template.

**Comment by frostbyte012** [comment]
@MrinalTyagi I'm a newbie. Having a little difficulty in understanding it. If you can kindly help me together we can contribute and learn. 
@bhack I'd love to coordinate.

**Comment by bhack** [comment]
@LukeWood Can we temp. assign to them? So we could keep track on `contribution-welcome` assigned ticket vs the ones still looking for contribution.

**Comment by LukeWood** [comment]
> @LukeWood Can we temp. assign to them? So we could keep track on `contribution-welcome` assigned ticket vs the ones still looking for contribution.

Sure thing

**Comment by adhadse** [comment]
@frostbyte012 Are you working on this issue? If not I would like to give this a try.

**Comment by frostbyte012** [comment]
I'm not currently working on this, but it was taken by @MrinalTyagi  I guess. I'm working on other issues.

**Comment by adhadse** [comment]
@frostbyte012 Sure, Give this a try. Mrinaltyagi has left this issue as said in his PR. Good Luck.

**Comment by frostbyte012** [comment]
@adhadse Thanks!

**Comment by tanzhenyu** [comment]
> @innat @bhack Can I pick this up if no one else is working on it currently? Thank you

I'm opening up this for contribution. Do you want to pick this up?
It will be a little more complicated than other KPLs, given it requires some additional Tensor. But we already have copy paste augmentation in 3D KPL
