### ISSUE TITLE
Equalization is the slowest layer.

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#286]
Noticeably so when running pytest .

We should look into this.  not blocking of v1, but it is noteworthy.

**Comment by bhack** [comment]
I suppose problem is always the same. A critical op like  [`tensorflow::ops::HistogramFixedWidth`](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/histogram-fixed-width)  is not supported for autovectorization in `PFOR`/`tf.vectorized_map`

When the fallback is disable we have
`ValueError: No pfor vectorization defined for HistogramFixedWidth`

Also eventually XLA/jit compilation will fail for:

```
on XLA_CPU_JIT: TensorListReserve (No registered 'TensorListReserve' OpKernel for XLA_CPU_JIT devices compatible with node {{function_node __inference_while_fn_18515}}{{node while_init/TensorArrayV2_3}}
E                                                (OpKernel was found, but attributes didn't match) Requested Attributes: element_dtype=DT_VARIANT, shape_type=DT_INT32)
```

**Comment by bhack** [comment]
For XLA:
"Only non-nested TensorList is supported for TensorListReserve."

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/tf2xla/kernels/tensor_list_ops.cc#L139-L144

**Comment by LukeWood** [comment]
Closing as this is probably more a TensorFlow issue than a KerasCV issue
