### ISSUE TITLE
RandAug preprocessing layer

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#29]
https://keras.io/examples/vision/randaugment/

**Comment by LukeWood** [comment]
This will require rewriting from numpy to TensorFlow

**Comment by sebastian-sz** [comment]
> This will require rewriting from numpy to TensorFlow

I have been using this implementation. Maybe it can help:
https://github.com/tensorflow/models/blob/ded32f0500604928e52e27fd3f678e694e5133b7/official/vision/image_classification/augment.py#L905

**Comment by LukeWood** [comment]
A batched implementation exists in imgaug:

https://github.com/aleju/imgaug

**Comment by bhack** [comment]
> A batched implementation exists in imgaug:
> 
> https://github.com/aleju/imgaug

But it Is not the best solution as it needs to be `tf.py_function` wrapped as It handle Numpy arrays not Tensor.

https://keras.io/examples/vision/randaugment/

**Comment by LukeWood** [comment]
I'll be contributing this shortly

**Comment by chjort** [comment]
If it could be to any inspiration, I also have a keras layer implementation of RandAug in my own toolbox:
https://github.com/chjort/chambers/tree/master/chambers/augmentations
specifically at this [line](https://github.com/chjort/chambers/blob/637be5ac8d76bb8d16adb53b5a1c6dd2b963b894/chambers/augmentations/augmentation_schemes.py#L175).


It is based on https://github.com/tensorflow/tpu/blob/master/models/official/efficientnet/autoaugment.py, but my implementation includes vectorized implementations of all transforms, although some of the layers make use of tensorflow-addons.

**Comment by LukeWood** [comment]
Thanks for the links!  I’ll let you know if I used them.  I’ll likely base mine on tensorflow similarity’s

**Comment by LukeWood** [comment]
https://github.com/tensorflow/similarity/blob/906d141b75acf00d0e1d37dd0d88c432bbb30f57/tensorflow_similarity/augmenters/img_augments.py
