### ISSUE TITLE
Support for Augmentation for Object Detection pipeline

### ISSUE THREAD

**Issue by pranavjadhav001** [keras-team/keras-cv#290]
### Discussed in https://github.com/keras-team/keras-cv/discussions/277

<div type='discussions-op-text'>

<sup>Originally posted by **pranavjadhav001** April  7, 2022</sup>
Going through the repo, I saw mostly image preprocessing and augmentation layers which allows only image transformations. Is there any scope for augmentation transformation of image and bbox for object detection like albumentations library. https://albumentations.ai/docs/getting_started/bounding_boxes_augmentation/ 
I also see image preprocessing operations have been created as layers to make it more as 1 single coherent model. Not sure, how the support must be added for object detection preprocessing layers where the input is image and labels. </div>

**Comment by pranavjadhav001** [comment]
Would love to Contribute to this.

**Comment by innat** [comment]
@pranavjadhav001 
As mentioned, including object detection, instance or semantic segmentation are on the to-do list.  You can start from [THIS](https://github.com/keras-team/keras/blob/dd0f1f480613ceffd994658e5632d54c660d1e73/keras/layers/preprocessing/image_preprocessing.py#L213) class. Here you will find [augment_bounding_box](https://github.com/keras-team/keras/blob/dd0f1f480613ceffd994658e5632d54c660d1e73/keras/layers/preprocessing/image_preprocessing.py#L347) to augment the bonding box labels. You can also look into this ongoing [PR](https://github.com/keras-team/keras-cv/pull/282) on MixUp augmentaiton for bonding box task. 

There are many issues are created, you can start from any.

**Comment by LukeWood** [comment]
> ### Discussed in #277
> Originally posted by **pranavjadhav001** April 7, 2022 Going through the repo, I saw mostly image preprocessing and augmentation layers which allows only image transformations. Is there any scope for augmentation transformation of image and bbox for object detection like albumentations library. https://albumentations.ai/docs/getting_started/bounding_boxes_augmentation/ I also see image preprocessing operations have been created as layers to make it more as 1 single coherent model. Not sure, how the support must be added for object detection preprocessing layers where the input is image and labels.

Thanks for your interest in a contribution!  @pranavjadhav001 feel free to open PRs to add an augment_bounding_box to the image augmentation layers.  Please do so one at a time!  @innat posted some great links.

Thanks for opening this, I will open more specific issues.

Cheers!
