### ISSUE TITLE
Robustness evaluation [API]

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#293]

**Comment by bhack** [comment]
What is this?

**Comment by LukeWood** [comment]
Sorry this should not have had the contribution welcome label.  I will post a more thorough explanation when it is ready.  I try to use GitHub for all things KerasCV - this includes notekeeping.

**Comment by LukeWood** [comment]
Basically @bhack the goal of this is to go from model  and dataset -> a table telling you how robust your model is to various perturbations including blurs/gradient attacks/etc

**Comment by bhack** [comment]
Are these a sort of ablation studies? 
Do you want to use KLPs on the test set as a sort of adversarial?

**Comment by bhack** [comment]
Or something more complete like:

https://github.com/Trusted-AI/adversarial-robustness-toolbox

**Comment by bhack** [comment]
A fresh Deepmind paper:
[A Fine-Grained Analysis on Distribution](Shifthttps://arxiv.org/abs/2110.11328)

**Comment by bhack** [comment]
https://shift-happens-benchmark.github.io/

https://github.com/shift-happens-benchmark/icml-2022

**Comment by LukeWood** [comment]
The KerasCV team is attempting to narrow the package scope in order to more efficiently use our limited resources. As such, we are only accepting contributions directly related to items on the 6 month roadmap for the package.

If you feel this feature could be particularly useful, or would like to contribute it - please feel free to re-open this issue and ping LukeWood, ianstenbit or tanzhenyu

Feel free to read more on the roadmap:
https://github.com/keras-team/keras-cv/blob/master/.github/ROADMAP.md
