### ISSUE TITLE
Write guide on using KerasCV KPLs

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#299]
https://github.com/keras-team/keras-io/pull/851

**Comment by Tony363** [comment]
@LukeWood I would also like to write tutorials, how may I contribute?

**Comment by LukeWood** [comment]
Thanks for offering @Tony363!  I’m compiling a list of keras.io tutorials that need to be updated to use our components.  I will create a tracking list and from there you can pick some up.

**Comment by Tony363** [comment]
I'm currently writing up a proposal for Google Summer of Code. Shall I write a new proposal specifically for documenting and writing tutorials or just add a sub section on my proposal?

**Comment by LukeWood** [comment]
> I'm currently writing up a proposal for Google Summer of Code. Shall I write a new proposal specifically for documenting and writing tutorials or just add a sub section on my proposal?

No need to duplicate the effort, just mention you're interested in contributing tutorials.

**Comment by LukeWood** [comment]
https://github.com/keras-team/keras-io/pull/852
