### ISSUE TITLE
Implement visualize bounding box method

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#300]
https://github.com/keras-team/keras-cv/pull/220

**Comment by kartik4949** [comment]
@LukeWood 
wrapper around https://www.tensorflow.org/api_docs/python/tf/image/draw_bounding_boxes ?

**Comment by LukeWood** [comment]
Oh very nice, maybe we can just rely on this function instead.  FYI @divyashreepathihalli

**Comment by divyashreepathihalli** [comment]
@LukeWood  thanks!

**Comment by divyashreepathihalli** [comment]
Due to inconsistent formats between `tf.image` and `kerasCV` having visualization utils for `kerasCV'  allows us:
- to have consistency between formats for our users
- ability to ship an extension type should we ever decide this is a necessity
- control of the drawing API

**Comment by bhack** [comment]
@divyashreepathihalli Do you mean that we are going to just create a wrapper around the native ops here?

Cause if this is not the case, all these points are fantastic, but as we are a python only repo  what will be the Keras CV performance impact of this design choice against native TF kernels performance?

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/image/draw_bounding_box_op.cc

**Comment by divyashreepathihalli** [comment]
We will have an implementation consistent with formats kerasCV works with. I don't think the visualization utils will have much performance difference compared to native TF kernels.

**Comment by bhack** [comment]
>  don't think the visualization utils will have much performance difference compared to native TF kernels.

I have some doubt on this point, but I will check this when it will land in the repo.

**Comment by LukeWood** [comment]
> @divyashreepathihalli Do you mean that we are going to just create a wrapper around the native ops here?
> 
> Cause if this is not the case, all these points are fantastic, but as we are a python only repo what will be the Keras CV performance impact of this design choice against native TF kernels performance?
> 
> https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/image/draw_bounding_box_op.cc

It isn't out of the realm of possibility to just solve this with a where function and leave plotting to users.

i.e.
```
bbox_mask = convert_bbox_to_segmap(bbox, width)
result = tf.where(bbox_mask, color*bbox_mask, image)
plt.imshow(result.numpy())
```

**Comment by bhack** [comment]
> and leave plotting to users.

If we leave the plotting to the users in the training loop what performance impact we will have when the user probably will require to use this for TB image summaries?

https://www.tensorflow.org/api_docs/python/tf/summary/image

**Comment by LukeWood** [comment]
that is a plotting function.  

tf.summary.write(result) works with the Tensor I have specified above.  performance concerns are valid.
