### ISSUE TITLE
RandomShear bounding box support

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#308]

**Comment by Tony363** [comment]
Would this feature hope to augment videos as a data point as well? I see no description provided?

**Comment by pranavjadhav001** [comment]
@LukeWood @divyashreepathihalli Didn't notice this issue was already created and assigned. I've implemented it. Let me know if this works.
https://github.com/keras-team/keras-cv/pull/373

**Comment by divyashreepathihalli** [comment]
Thank you @pranavjadhav001, we will review it soon.
