### ISSUE TITLE
Write keras-io guide on augmenting bounding box datasets with KerasCV

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#309]

**Comment by Tony363** [comment]
Shall I be the one writing the description and proposal this? I have no prior information?

**Comment by LukeWood** [comment]
Hey @Tony363!  Thanks for your excitement about the project!  As of now this is assigned to @divyashreepathihalli  as of now as she will be working on adding bounding box augmentation to many KPLs.  Check out our contributors guide on how to get started contributing!  I maintain a "Contributions welcome" label for contributors here:

https://github.com/keras-team/keras-cv/issues?q=is%3Aopen+is%3Aissue+label%3Acontribution-welcome

Let me know if you have any more questions

**Comment by Tony363** [comment]
@LukeWood where do i find the contributors guide? should I find it from the GSOC organizations information or the KerasCV repository readme?

**Comment by Tony363** [comment]
@LukeWood So the next thing i should do is the fork Keras-CV and start familiarizing myself with the code and communicate with possible individuals involved to understand the changes I should make?

**Comment by LukeWood** [comment]
> @LukeWood So the next thing i should do is the fork Keras-CV and start familiarizing myself with the code and communicate with possible individuals involved to understand the changes I should make?

Sure sounds great!  Picking issues up off that list is the way I would recommend starting your path to contributing!

**Comment by LukeWood** [comment]
This is done in the overview RetinaNet guide!
