### ISSUE TITLE
GridMask Augmentation

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#31]
Paper: [GridMask Data Augmentation](https://arxiv.org/abs/2001.04086)
Citation: ~70
Code: https://github.com/google/automl/blob/master/efficientdet/aug/gridmask.py

Demo: 

![image](https://user-images.githubusercontent.com/17668390/148650732-7045a49d-a60e-4f8f-8b5c-cf21551d1ae3.png)

---

@LukeWood Is it possible to add a Discussion tab, [like](https://github.com/facebookresearch/detectron2/discussions).

**Comment by LukeWood** [comment]
@innat I added a discussion tab, let's discuss whether this augmentation is a good fit there.

**Comment by innat** [comment]
@LukeWood that would be cool. I think you can create a new discussion post for collecting/discussing suitable cv augmentation methods in general.

**Comment by LukeWood** [comment]
https://www.kaggle.com/c/flower-classification-with-tpus/discussion/132986

**Comment by LukeWood** [comment]
Thanks!
