### ISSUE TITLE
RandomColorAffine preprocessing layer

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#32]
https://keras.io/examples/vision/semisupervised_simclr/

**Comment by LukeWood** [comment]
This is really useful for self supervised models.

**Comment by qlzh727** [comment]
Looking at https://keras.io/examples/vision/semisupervised_simclr/, it seems that the layer has quite some overlap for what we are about to have in https://github.com/keras-team/keras-cv/issues/142. @LukeWood let me know if we want to keep this layer or not.
