### ISSUE TITLE
Including All Components to Train State of the Art Imagenet-1k models

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#33]
https://pytorch.org/blog/how-to-train-state-of-the-art-models-using-torchvision-latest-primitives

Two papers to reference:
* ResNet-RS
* ResNet Strikes Back

**Comment by bhack** [comment]
https://discuss.tensorflow.org/t/resnet-rs-rewritten-in-tensorlfow-keras/5733

https://github.com/keras-team/keras/issues/15780

**Comment by LukeWood** [comment]
Components should be done, we still need to bundle these intro training scripts.  @ianjjohnson is working on this.
