### ISSUE TITLE
Create a CONTRIBUTING.MD guide

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#34]
From a PR review:

> Do we want to have a paper citation treshold or any other evalustion metric?

We want an adoption metric of some kind, and a citation threshold (~50) is a convenient metric.

> What about the component maintainership policiy? Can we scale over the community maintainership/ownership of the components?

We'll try. Someone who contributes a component will be called to fix issues with it if any arise.

> I think also that we could not go to only accumulate components over time how we are going to evaluate and handle deprecations?

Deprecation decisions are always the result of cost/benefits analysis. The picture varies from component to component and over the lifetime of the repo. It's a case by case basis.

> I suppose that we could partially use the README.MD for this and partially CONTRIBUTING.MD

Yes, this is mostly information that should go in the contributors' guide.

**Comment by bhack** [comment]
I think that we need to add a `CODEOWNERS` policy to promote `Organizational Diversity`  and adopt a good `Issue Label Inclusivity`.

See pages 41 and 85 in: https://chaoss.community/wp-content/uploads/2021/10/English-Release-2021-10-21.pdf

**Comment by LukeWood** [comment]
Additional notes:
- I'll be creating guidelines on __init__.py management, performance considerations, style guide, etc.

**Comment by LukeWood** [comment]
Done.
