### ISSUE TITLE
Fix Dropblock2d's serialization issue.

### ISSUE THREAD

**Issue by sebastian-sz** [keras-team/keras-cv#343]
Two things:

1. I noticed recently most preprocessing layers have been decorated with:  
`@tf.keras.utils.register_keras_serializable(package="keras_cv")`  
this could also be added to DropBlock I think.

2. When attempting to deserialize a model with this layer, one will encounter error, most likely **kwargs are missing from init.
```python
import tensorflow as tf
from keras_cv.layers.regularization.dropblock_2d import DropBlock2D

model = tf.keras.Sequential([DropBlock2D(0.1, 7)])
model.build(input_shape=(224, 224, 3))
tf.keras.models.save_model(model, "model.h5")
with tf.keras.utils.custom_object_scope({"DropBlock2D": DropBlock2D}):
    loaded = tf.keras.models.load_model("model.h5")
```

`TypeError: __init__() got an unexpected keyword argument 'trainable'`

If you give a green light for these changes I'd be happy to submit a PR.

**Comment by LukeWood** [comment]
Definitely looks like a bug!  We should add a serialization test to its unit tests as well.
