### ISSUE TITLE
random shear demo input parameters wrong

### ISSUE THREAD

**Issue by pranavjadhav001** [keras-team/keras-cv#349]
class RandomShear [https://github.com/keras-team/keras-cv/blob/master/keras_cv/layers/preprocessing/random_shear.py](url) takes x_factor and y_factor as parameters but in random_shear_demo.py [https://github.com/keras-team/keras-cv/blob/master/examples/layers/preprocessing/random_shear_demo.py](url) it is x and y, throws TypeError: ('Keyword argument not understood:', 'x') error

**Comment by LukeWood** [comment]
Yes this looks like a bug.  Thanks @pranavjadhav001 for pointing this out!  Feel free to submit a fix.

**Comment by pranavjadhav001** [comment]
Sure @LukeWood . Will take it up.
