### ISSUE TITLE
CutMix augmentation for Object Detection task.

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#35]
[Reposting from [here](https://github.com/keras-team/keras-cv/issues/19#issuecomment-1007919637) as a future reference for potential contributor].

CutMix - Paper - Cited by ~ 865
MixUp - Paper - Cited by ~ 2675

---

Currently, [this aug](https://github.com/keras-team/keras-cv/pull/24) can be applied to classification tasks but as the `kerascv` sets the target to general vision task, that's why to support vision tasks like object detection, we may need to add utility to accept the `bbox_params` argument too. 

**example of mixup-object-detection - region=full-images**
![image](https://user-images.githubusercontent.com/17668390/148638376-4d5cdb33-78d3-4a7b-bdab-f734f09fb39e.png)

**example of mixup-object-detection - region=random**
![image](https://user-images.githubusercontent.com/17668390/148638418-705a7a01-e25a-411b-9b66-1cb114b0be8b.png)

**example of cutmix-object-detection**
![Screenshot 2022-01-08 214414](https://user-images.githubusercontent.com/17668390/148650542-6c722a84-45a3-4812-84a0-3682402edf02.png)

ref: https://www.kaggle.com/ankursingh12/data-augmentation-for-object-detection
ref: https://www.kaggle.com/shonenkov/oof-evaluation-mixup-efficientdet

**Comment by bhack** [comment]
I suppose these are just sparse experiments. Do we have some reference paper for CutMix and Mixup for object detection?

**Comment by bhack** [comment]
I found a reference in 2.3.9 section of:

https://arxiv.org/abs/2106.07085

**Comment by innat** [comment]
@bhack 
Thanks for bringing up this reference, just skimmed through some content and it looks interesting. Also If you look at the original [cut-mix](https://openaccess.thecvf.com/content_ICCV_2019/papers/Yun_CutMix_Regularization_Strategy_to_Train_Strong_Classifiers_With_Localizable_Features_ICCV_2019_paper.pdf) paperwork, you would find that they have actually included object detection tasks too. But I didn't find any section in the original [mixup](https://arxiv.org/pdf/1710.09412.pdf) paperwork. But another [paper](https://arxiv.org/pdf/1902.04103.pdf) does (also the cutmix too). Here I've just found an interesting [document](https://github.com/JasonZhang156/awesome-mixed-sample-data-augmentation#object-detection-and-localization) regarding the mixup type augmentation paper list in various domains.

**Comment by bhack** [comment]
I think in the original paper It was something different:

> CutMix pre-trained model when it is
fine-tuned for object detection

**Comment by bhack** [comment]
> Here I've just found an interesting document regarding the mixup type augmentation paper list in various domains.

If you check the first in the list (2d object) was exactly the reference mentioned in the survey.

**Comment by LukeWood** [comment]
This is now available for MixUp, need CutMix still
