### ISSUE TITLE
Expose `BaseImageAugmentationLayer` to users

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#352]
I'd like to offer BaseImageAugmentationLayer as a KerasCV API.  This will allow our users to subclass this layer and use their own BaseImageAugmentationLayers within `RandomAugmentationPipeline`s.

Additionally: this is fantastic for us as a library because if people start using this layer, we may integrate their implementations into the library!

I will write a keras.io tutorial on how to do this.  This will double as a resource for repo contributors.

**Comment by kartik4949** [comment]
Yup, Really good idea!
 its like user can implement his niche augmentation layer, and use it.
while we can hook it up with library if it is useful.
