### ISSUE TITLE
Add RandomRain preprocessing layer

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#355]
## Weather Augmentation 

One of the real-world scenarios that pose challenges for training neural networks of Autonomous vehicles

![output_27_0](https://user-images.githubusercontent.com/17668390/164973608-66059cd2-9920-4447-99fa-a996fb94cd79.png)

Impl. Ref. 

- https://github.com/UjjwalSaxena/Automold--Road-Augmentation-Library
- https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.RandomRain

**Comment by LukeWood** [comment]
Great ideas @innat!  Thank you!

**Comment by LukeWood** [comment]
If we strong references regarding the usefulness of these lets re-open, but for now I'd like to wait for a user feature request
