### ISSUE TITLE
Add RandomFog preprocessing layer

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#356]
## Weather Augmentation

One of the real-world scenarios that pose challenges for training neural networks of Autonomous vehicles

![output_30_0](https://user-images.githubusercontent.com/17668390/164973684-3b203d52-7e92-473f-b14c-877d0a88e5bb.png)

Impl. Ref
- https://github.com/UjjwalSaxena/Automold--Road-Augmentation-Library
- https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.RandomFog

**Comment by LukeWood** [comment]
If we strong references regarding the usefulness of these lets re-open, but for now I'd like to wait for a user feature request
