### ISSUE TITLE
Add RandomSunFlare preprocessing layer

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#358]
## Weather Augmentation

One of the real-world scenarios that pose challenges for training neural networks for Autonomous vehicle

![output_39_0](https://user-images.githubusercontent.com/17668390/164973817-fee5266c-bbfb-4424-a502-6cb56f8b8b6d.png)

Ref. Imple. 

- https://github.com/UjjwalSaxena/Automold--Road-Augmentation-Library
- https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.RandomSunFlare

**Comment by innat** [comment]
It can be broken down into two sub-task

- create synthetic flare programmatically 
- add flare realistically 

To add flare, one may check [Flare Removal](https://yichengwu.github.io/flare-removal/) project, and code [HERE](https://github.com/google-research/google-research/blob/cc541f305573bdac0ccd93420e797ac898e0b4d1/flare_removal/python/synthesis.py#L24). 

(syth. data - flare added)
![image](https://user-images.githubusercontent.com/17668390/164994770-ce4ffe44-6153-4a76-b8f2-9e015ee11b12.png)

**Comment by kartik4949** [comment]
quite useful augmentation for Adas systems

**Comment by innat** [comment]
yes, it's also useful for the agricultural-based solution, for example, [wheat detection.](http://www.global-wheat.com/2020-challenge/), [samples](https://www.kaggle.com/competitions/global-wheat-detection/data?select=train)

**Comment by LukeWood** [comment]
The KerasCV team is attempting to narrow the package scope in order to more efficiently use our limited resources.  As such, we are only accepting contributions directly related to items on the 6 month roadmap for the package.

Feel free to read more on the roadmap:
https://github.com/keras-team/keras-cv/blob/master/.github/ROADMAP.md
