### ISSUE TITLE
Add CLAHE preprocessing layer

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#359]
CLAHE is a variant of Adaptive histogram equalization (AHE) which takes care of over-amplification of the contrast. It's well-used in medical imaging practice. 

![image](https://user-images.githubusercontent.com/17668390/164974125-050b7c10-4525-47a9-9441-335c00b08c17.png)

(original image (left) - HE (middle) - CLAHE (right))
[source.](https://chowdera.com/2021/09/20210930171712779O.html)

**Comment by innat** [comment]
@isears 
Isaac made a [PR](https://github.com/tensorflow/addons/pull/2362) about CLAHE on TensorFlow-Addons. It's not merged yet. I think we can move it to KerasCV. His implementation produced 

![105634900-e98c0280-5e25-11eb-8ce7-ed7d7b09f5ec](https://user-images.githubusercontent.com/17668390/164974250-760f5223-11c1-416b-8363-16382add69c6.png)
(his o/p on the most right side).

**Comment by LukeWood** [comment]
Yep!   medical imaging is in scope.  Happy to take a PR for medical imaging related preprocessing layers.

**Comment by isears** [comment]
@innat It will be at least a month before I can work on porting my tensorflow-contrib PR to keras-cv. If you would like, you could use my code to open up your own PR.

**Comment by innat** [comment]
@isears thanks for the update. I'm screening some other components to send PR. So, I can move forward with clahe after that. In the meantime, if you start working on your implementation, please feel free to send PR. -)

**Comment by LukeWood** [comment]
The KerasCV team is attempting to narrow the scope of the package to improve the health of our repository.  As such, we are no longer looking to accept anything not currently on the roadmap without explicit support from a team member:

Please see the roadmap for more details: https://github.com/keras-team/keras-cv/blob/master/.github/ROADMAP.md

**Comment by innat** [comment]
@LukeWood could you please reopen this ticket?
