### ISSUE TITLE
Update the benchmarking script to accept an arbitrary BaseImageAugmentationLayer subclass

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#361]
This will allow us to make the decision on whether or not to JIT compile specific layers

**Comment by bhack** [comment]
Also when will we have the new benchmark I hope that:

- We still let the user to control XLA jit compilation as discussed in https://github.com/keras-team/keras/issues/16403#issuecomment-1099591164
- We could maintain an update inventory txt (or MD) in the repository for the layers that could not be compiled for the missing XLA ops coverage as in the last point at https://github.com/keras-team/keras-cv/issues/291#issue-1199029473

**Comment by LukeWood** [comment]
Closing this for now, we do some benchmarking internally, but I don't think we want to benchmark these at this time due to resource constraints.
