### ISSUE TITLE
Random Shadow

### ISSUE THREAD

**Issue by kartik4949** [keras-team/keras-cv#374]
Add artificial shadow on image.
![image](https://user-images.githubusercontent.com/38289341/165721723-e8abefb3-b98f-4dde-83c4-bd9242dc7f96.png)

**Comment by kartik4949** [comment]
reference 
https://brunokrinski.github.io/awesome-data-augmentation/

**Comment by LukeWood** [comment]
at this time I think we should deprioritize these and focus on our ongoing efforts.  Perhaps in the future we can pick this back up if the need arises.
