### ISSUE TITLE
Multiplicative Noise

### ISSUE THREAD

**Issue by kartik4949** [keras-team/keras-cv#375]
Multiplicative Noise is a Noise KPL which multiplies image with random number array

![image](https://user-images.githubusercontent.com/38289341/166055547-ad919e95-94cf-4e6d-895d-440116eb0517.png)

References:
https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.MultiplicativeNoise

**Comment by LukeWood** [comment]
Hi @kartik4949 - we need a description on this!  Thanks!

**Comment by LukeWood** [comment]
at this time I think we should deprioritize these and focus on our ongoing efforts.  Perhaps in the future we can pick this back up if the need arises.
