### ISSUE TITLE
image temperature change

### ISSUE THREAD

**Issue by kartik4949** [keras-team/keras-cv#376]
Image temperature change is a KPL, which changes color of the image.

![image](https://user-images.githubusercontent.com/38289341/166004101-d9fe0caf-2959-44ae-beae-c09675beaa55.png)

factor can be -1 to 1

Reference:
https://brunokrinski.github.io/awesome-data-augmentation/

**Comment by LukeWood** [comment]
Hey @kartik4949! Please provide descriptions on all new issues.  Thanks a ton for the issue ideas :)

**Comment by LukeWood** [comment]
at this time I think we should deprioritize these and focus on our ongoing efforts.  Perhaps in the future we can pick this back up if the need arises.
