### ISSUE TITLE
Image Contrast

### ISSUE THREAD

**Issue by kartik4949** [keras-team/keras-cv#377]
* sigmoid contrast
* log contrast
* linear contrast

This KPL can support multiple backend algorithms (like above)

preprocessing.RandomContrast(function=("sigmoid"/"log"/"linear") )

**Comment by LukeWood** [comment]
at this time I think we should deprioritize these and focus on our ongoing efforts.  Perhaps in the future we can pick this back up if the need arises.

**Comment by LukeWood** [comment]
(This can already be done with FactorSamplers)
