### ISSUE TITLE
Image Embossing

### ISSUE THREAD

**Issue by kartik4949** [keras-team/keras-cv#378]
Image embossing augmentation
![image](https://user-images.githubusercontent.com/38289341/165721879-13a9d231-2e9f-44fb-af1c-5f56c997fa6b.png)

**Comment by kartik4949** [comment]
https://brunokrinski.github.io/awesome-data-augmentation/

**Comment by LukeWood** [comment]
at this time I think we should deprioritize these and focus on our ongoing efforts.  Perhaps in the future we can pick this back up if the need arises.
