### ISSUE TITLE
Image Noise with multiple backends

### ISSUE THREAD

**Issue by kartik4949** [keras-team/keras-cv#379]
![image](https://user-images.githubusercontent.com/38289341/165721536-544ddb74-7792-42f0-8c39-5dc6341f98ea.png)

**Comment by kartik4949** [comment]
Noise backend functions could be 

* ISO
* Gaussian
* Multiplicative
* Shot

**Comment by kartik4949** [comment]
reference
https://brunokrinski.github.io/awesome-data-augmentation/

**Comment by LukeWood** [comment]
at this time I think we should deprioritize these and focus on our ongoing efforts.  Perhaps in the future we can pick this back up if the need arises.
