### ISSUE TITLE
Canny Edge detection preprocessing layer.

### ISSUE THREAD

**Issue by kartik4949** [keras-team/keras-cv#380]
![image](https://user-images.githubusercontent.com/38289341/165721353-247cf320-1fa9-4e1f-a259-426f7664c005.png)

**Comment by kartik4949** [comment]
Yup, ill add tonite 
Thanks

**Comment by kartik4949** [comment]
reference
https://brunokrinski.github.io/awesome-data-augmentation/

**Comment by LukeWood** [comment]
at this time I think we should deprioritize these and focus on our ongoing efforts.  Perhaps in the next 6 months or so we can pick this back up.
