### ISSUE TITLE
Voronoi Image segmentation with multiple backends

### ISSUE THREAD

**Issue by kartik4949** [keras-team/keras-cv#381]
Average colors of an image within Voronoi cells
![image](https://user-images.githubusercontent.com/38289341/165721104-e4966201-026a-493c-aa41-ccd82040306e.png)

**Comment by kartik4949** [comment]
https://brunokrinski.github.io/awesome-data-augmentation/

**Comment by LukeWood** [comment]
Lets close this for now until we have a stronger verification that this is impactful.
