### ISSUE TITLE
Create a bounding box dataclass

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#384]
Bounding box format conversion is difficult to track, and could potentially be abstracted from users.  This is an opportunity to offer something better than other ML ecosystems.  I'll be designing this.

TF similarity does something similar:
https://github.com/tensorflow/similarity/blob/9803dc3ff9d4f9f434a0f02b0c0c57affb603726/tensorflow_similarity/types.py#L92

**Comment by kartik4949** [comment]
https://github.com/keras-team/keras-cv/issues/154
:) @LukeWood we had similar discussion I guess

**Comment by LukeWood** [comment]
Ended up going with a different design.  I will publicize this when it is done.
