### ISSUE TITLE
`SetuptoolsDeprecationWarning`: `setup.py` install is deprecated. Use build and pip and other standards-based tools.

### ISSUE THREAD

**Issue by adhadse** [keras-team/keras-cv#385]
Following the issue, I resolved at Keras-NLP [#112](https://github.com/keras-team/keras-nlp/issues/112).

We need to remove the `setup.py` instruction for development environment setup, and recommend to add virtual environment directory.

**Comment by bhack** [comment]
If can prepare a PR over https://github.com/keras-team/keras-cv/blob/master/.github/CONTRIBUTING.md#setup-environment

**Comment by LukeWood** [comment]
closed per the submitted PRs
