### ISSUE TITLE
Add WSL related link for Windows development environment.

### ISSUE THREAD

**Issue by adhadse** [keras-team/keras-cv#387]
As discussed in issue [#104](https://github.com/keras-team/keras-nlp/issues/104) for Keras-NLP, the bash scripts do not support windows shell/Powershell.

We need to recommend the developer to install WSL as the preferred terminal + LF is the default line ending.

**Comment by innat** [comment]
> the bash scripts do not support windows shell/Powershell.

For this purpose, I think, using `git bash` is more feasible than installing `WSL`.  But in general, it's good to have `WSL` installed.

**Comment by adhadse** [comment]
That is also perfectly fine, but we can make sure that developers don't run the bash scripts in Windows CMD/PowerShell, letting them know either to use Git Bash or WSL.

**Comment by LukeWood** [comment]
Maybe a section in the appendix of contributing or setup is fine; though I think it’s pretty standard in OSS for the default environment to be unix based.

**Comment by LukeWood** [comment]
Closing for now as this doesn't relate to our roadmap.  If you want to send a PR feel free.  Just an appendix is fine.
