### ISSUE TITLE
List of GitHub supported files

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#398]
Opening this ticket to find out the best place to keep files like .github/CONTRIBUTING.md

I know github supports a specific set of files (i.e. LICENSE).  Any other files we should know about in this repo?  Thanks

@bhack

**Comment by zhiqwang** [comment]
Hi, as described in https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors#adding-a-contributing-file , the CONTRIBUTING guidelines can be placed in a repository's root, docs, or .github directory.

**Comment by bhack** [comment]
Out code of conduct is just a small edit of the [code covenant](https://www.contributor-covenant.org/adopters/)

See:
https://github.com/tensorflow/tensorflow/pull/29090

**Comment by Nyandwi** [comment]
I am thinking that having `CONTRIBUTING.md` in the `docs` directory seems plausible since you may have other similar files that can go with it and hence avoid having many individual files in the `root` directory.

**Comment by LukeWood** [comment]
For now we can close as we've moved the license.  We can add a code of conduct and what not; mainly we should just link to governance.
