### ISSUE TITLE
AugMix image augmentation 

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#40]
Paper: https://arxiv.org/abs/1912.02781 Cited by 308
Code: 
- src 1: https://github.com/google-research/augmix
- src 2: https://github.com/AakashKumarNain/AugMix_TF2

![](https://raw.githubusercontent.com/google-research/augmix/master/assets/augmix.gif)

**Comment by bhack** [comment]
https://github.com/google/automl/pull/362

https://github.com/google/uncertainty-baselines/commit/274772f3b379fc2f348d3efc3a5f71ef1edf382d

**Comment by innat** [comment]
What is **Applies Confidence Adjusted Mixup ([CAMixup](https://github.com/google/uncertainty-baselines/blob/1de7aa452ce0d4364b98902177934c643ffacfba/uncertainty_baselines/datasets/augmix.py#L206))** regularization!

**Comment by bhack** [comment]
> What is **Applies Confidence Adjusted Mixup ([CAMixup](https://github.com/google/uncertainty-baselines/blob/1de7aa452ce0d4364b98902177934c643ffacfba/uncertainty_baselines/datasets/augmix.py#L206))** regularization!

Is `CONFIDENCE ADJUSTED MIXUP ENSEMBLES` in:

https://arxiv.org/abs/2010.09875

**Comment by LukeWood** [comment]
Thanks for opening this.  I'll be including this soon from tf similarity

**Comment by innat** [comment]
cc. @AakashKumarNain 
[Ref.](https://github.com/AakashKumarNain/AugMix_TF2)

**Comment by quantumalaviya** [comment]
I was looking to implement this but there seems to be no implementation of Dirichlet outside tensorflow_probability (which I assume can't be used). The only other option seems to be the implementation of the distribution as part of utils (which seems unnecessarily tedious).

I would love any suggestions here!

**Comment by bhack** [comment]
There is also in Tensorflow but It is a v1 symbol (TF 1.x/compat) so we cannot use It:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/distributions/dirichlet.py#L44

I suppose that it was not maintained as an API in TF2 cause these kind of things are handled in TFP.

**Comment by quantumalaviya** [comment]
We can't use tfp here though, right?

**Comment by LukeWood** [comment]
> I was looking to implement this but there seems to be no implementation of Dirichlet outside tensorflow_probability (which I assume can't be used). The only other option seems to be the implementation of the distribution as part of utils (which seems unnecessarily tedious).
> 
> I would love any suggestions here!

Good question.  I have not given the interaction with TFP any thought.  My instinct is if the only extra offering we get by adding it is Augmix that it may not be worth adding it as a dep.

**Comment by innat** [comment]
@quantumalaviya 
> The only other option seems to be the implementation of the distribution as part of utils (which seems unnecessarily tedious).

If using tfp is not an option, I think it may be needed to add this distribution as part of utils (sounds unpleasant, agree). 
Because who knows, we may need it for other cases, [LIKE](https://github.com/keras-team/keras-cv/issues/250#issue-1189457586).

**Comment by quantumalaviya** [comment]
Yeah, turns out the implementation is rather trivial when implemented on its own. This shouldn't be a problem. 
However, instead of adding it to the utils, I have added it as a static function inside the layer (see PR #407) similar to Beta sampling in `MixUp` and `FourierMix`.
