### ISSUE TITLE
[AutoAugment] Add Rotate operation. 

### ISSUE THREAD

**Issue by sebastian-sz** [keras-team/keras-cv#402]
**Short Description**
Rotate is one of the operations used by AutoAugment. Currently it's not present in `keras_cv`, so AutoAugment cannot be implemented.

**What it does**
From Tensorlfow Addons docs: Rotate image(s) counterclockwise by the passed angle(s) in radians.

**Papers**
AutoAugment: Learning Augmentation Strategies from Data
[arxiv link](https://arxiv.org/pdf/1805.09501.pdf)

**Existing Implementations**
[Tensorflow addons](https://www.tensorflow.org/addons/api_docs/python/tfa/image/rotate)
[tensorflow/tpu](https://github.com/tensorflow/tpu/blob/8aac591077e5781785aa6c22bc400472ba14dada/models/official/efficientnet/autoaugment.py#L228)

**Other Information**
* This is different from keras `RandomRotation` as we need to be able to control the probability at which the op is applied.
* Following standard Keras layer naming this could probably be called `Rotation`?

**Comment by sebastian-sz** [comment]
It looks like linked implementation uses `ImageProjectiveTransformV3` which will fail with XLA: https://github.com/tensorflow/tensorflow/issues/55194#

**Comment by bhack** [comment]
Yes it will also already fail on master to optimize the performance without XLA (as many other ops that we already use):

https://github.com/keras-team/keras-cv/issues/291#issuecomment-1112210556

See also my rationale at:
https://github.com/keras-team/keras-cv/issues/361#issuecomment-1110925900

**Comment by bhack** [comment]
P.s there is a partial coverage effort (translation only) with https://github.com/tensorflow/tensorflow/pull/55335  but for MLIR (as XLA is still a different code path today in TF)

**Comment by LukeWood** [comment]
Hi @sebastian-sz!  Is this different from the RandomRotation KPL?  We can use utils.transform however needed if we must.

**Comment by sebastian-sz** [comment]
@LukeWood In terms of using the layer as a part of AutoAugment I do believe this is different. For instance, with default KLP we cannot directly control the probability as well as "angles" parameter at which the Rotation's are applied, which is necessary in the AutoAugment pipeline.

**Comment by quantumalaviya** [comment]
I have added some utils from keras that are required for the rotation and the translation as part of #407, if that's any help. I too had to code the rotate operation for AugMix. This layer may be useful.

**Comment by LukeWood** [comment]
> I have added some utils from keras that are required for the rotation and the translation as part of #407, if that's any help. I too had to code the rotate operation for AugMix. This layer may be useful.

Is there any use case we can think of that requires this to be a layer; in particular: will you ever want to preprocess your inputs by ALWAYS rotating by X deg?  If not, maybe it is best as a preprocessing util

**Comment by quantumalaviya** [comment]
True, it makes no sense to rotate images at a fixed angle. 

This util may be useful*

**Comment by sebastian-sz** [comment]
> will you ever want to preprocess your inputs by ALWAYS rotating by X deg?

@LukeWood yes - this is actually the case in AutoAugment, where you want to rotate the image by X degrees based on subpolicy's magnitude:
![rotate_autoaugment](https://user-images.githubusercontent.com/58402418/166412649-a2c10ef4-4a2a-41fa-8056-a3639ee6cbf8.png)

@quantumalaviya Thanks for linking #407 I didn't know about it and it looks like exactly the thing needed.

I agree that this function **doesn't need** to be a KLP and is good enough as a utility function.
From my perspective this issue can be closed.

**Comment by LukeWood** [comment]
Cool, let’s leave it open until we can merge @quantumalaviya ’s PR and actually include the utility to rotate an image a fixed amount

**Comment by LukeWood** [comment]
Hey @sebastian-sz for now lets close this until we decide to fully pursue AutoAugment!  If someone wants to pursue it, we can discuss but for now we are just recommending the use of RandAugment as it's search space is MUCH easier to traverse.

Cheers!

**Comment by sebastian-sz** [comment]
@LukeWood absolutely! Upon further reading I even think that current Rotate ops are sufficient for this.
