### ISSUE TITLE
Refactoring redundant code blocks in demo files.

### ISSUE THREAD

**Issue by kartik4949** [keras-team/keras-cv#403]
@bhack @LukeWood @innat 
Guys, You think it make sense to refactor demo py files
with something like

```
# examples/prepare_dataset.py
# prepare dataset utility function

# examples/plot_images.py
# plotting demo results.
```
I think it might hurt the readablitity of demo file a bit!

**Comment by innat** [comment]
Yes, I think there's room to improve the representation of the examples or demo files. But I'm wondering will it be continued to host `examples/*` in the future? (as `keras` repo doesn't provide such a thing in repo). Isn't this directory temporary?

**Comment by LukeWood** [comment]
> Yes, I think there's room to improve the representation of the examples or demo files. But I'm wondering will it be continued to host `examples/*` in the future? (as `keras` repo doesn't provide such a thing in repo). Isn't this directory temporary?

To be completely honest, I haven't decided what to do with this directory!  The visualizations for KPLs are definitely valuable; as are examples for things like visualization and model explainability tools.  We need *something* like this, but where to keep it - of that I am unsure.  

For now we can probably keep it in the project root.

**Comment by LukeWood** [comment]
Per the original issue - yeah I agree that setting up the tf.data.dataset and showing the samples for the KPLs could be extracted into a helper file.

**Comment by kartik4949** [comment]
> Per the original issue - yeah I agree that setting up the tf.data.dataset and showing the samples for the KPLs could be extracted into a helper file. 

Cool I have the helpers ready
Let me file a PR!
Thanks

**Comment by tanzhenyu** [comment]
Closing as this PR is merged
