### ISSUE TITLE
Support `RandomChoice` - randomly pick from list!

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#408]
**Short Description**

Let's say in your training, you want to use all of the follows:

- `cutmix-mixup-fmix-mosaic` 
- `gaussian_blur-zoom_blur-motion_blur-median-blur`
- `optical_distortion-elastic-transform-grid_distortion`
- `equalization-clahe`
- `grid_mask-cutput`
- etc.

then it's required to randomly pick one among others (in general) in a single pass during training, for example: `[cutmix-zoom_blur-optical_distortion-clahe-cutput]`. So, it would be nice to have a functionality to feasibly do this task.

**Papers**
Most of the top used libraries/frameworks offer similar strategies.

**Existing Implementations**
- https://pytorch.org/vision/main/generated/torchvision.transforms.RandomChoice.html

**Other Information**
In the title, the name `RandomChoice` is picked for demonstration purposes. The thing is, we may need to introduce or modify any of the existing functionality if it's reasonable to take.

**Comment by LukeWood** [comment]
Yeah this seems like a reasonable API to me.  Actually, `RandomAugmentationPipeline` could even use this under the hood.

**Comment by LukeWood** [comment]
@innat should this always pick equally between augmentations, or should we support weighted sampling?

**Comment by innat** [comment]
I think weighted sampling would be better.

**Comment by sebastian-sz** [comment]
I think @chjort had something like that in his repository:
https://github.com/chjort/chambers/blob/b796f507b7353fb141b5c8b026b811a023d303e6/chambers/augmentations/image_augmentations.py#L549

**Comment by chjort** [comment]
> I think chjort had something like that in his repository: https://github.com/chjort/chambers/blob/b796f507b7353fb141b5c8b026b811a023d303e6/chambers/augmentations/image_augmentations.py#L549

Thanks @sebastian-sz, you are right.

In order to have this layer support weighted sampling, the `transform_idx` at [L608](https://github.com/chjort/chambers/blob/b796f507b7353fb141b5c8b026b811a023d303e6/chambers/augmentations/image_augmentations.py#L608) should simply be drawn from the weighted distribution.

I would be happy to contribute this layer if we want it in Keras-CV.

**Comment by LukeWood** [comment]
Awesome, thanks for the links @sebastian-sz and @chjort. 

Here is my thought:
- right now, we have [RandomAugmentationPipeline](https://github.com/keras-team/keras-cv/blob/master/keras_cv/layers/preprocessing/random_augmentation_pipeline.py#L18), which couples two ideas: repeated augmentation, and Randomly selecting from a list
- we can extract this functionality into two separate pieces: a RandomChoice(), and a for loop
- after this, the functionality of RandomAugmentationPipeline will just be to wrap a RandomChoice() in a for loop + support a `rate` parameter.

So for a PR I'd like:
- a RandomChoice layer that selects an augmentation from a list; basically what is in https://github.com/keras-team/keras-cv/blob/master/keras_cv/layers/preprocessing/random_augmentation_pipeline.py#L86 without rate
- update RandomAugmentationPipeline to use the RandomChoice layer internally.

Feel free to send this PR @chjort

**Comment by LukeWood** [comment]
I like the way Albumnations `OneOf` works; but I don't like that they take a `p` parameter in their constructor for the augmentations themselves that behaves differently depending on context;  very unintuitive.

We should strive to support custom probabilities, but not in that way.

**Comment by LukeWood** [comment]
Labelled this contribution welcome, @chjort has a PR open and I think this will be a useful feature.  Thank!
