### ISSUE TITLE
AutoAugment image augmentation 

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#41]
Paper: https://arxiv.org/abs/1805.09501 Cited by 832 
Ref code. https://github.com/tensorflow/models/blob/ded32f0500604928e52e27fd3f678e694e5133b7/official/vision/image_classification/augment.py#L731

**Comment by LukeWood** [comment]
I've been weighing adding this layer.  

Thoughts on what it adds over RandAugment?  

It looks as though it's much more customizable, which could be good to have.

@innat

**Comment by bhack** [comment]
I think that we could also evaluate differentiable augmentations like:

https://arxiv.org/abs/2104.04282
https://arxiv.org/abs/2109.15273
https://openreview.net/forum?id=St-53J9ZARf

**Comment by innat** [comment]
(AFAIK), the advantages of auto-augment over rand-augment also bring computational costs. I think both of them are used and maintained in research, so it's ok to have them both. 

- [AutoAugment](https://paperswithcode.com/paper/autoaugment-learning-augmentation-policies) - [Code](https://github.com/tensorflow/models/blob/ded32f0500604928e52e27fd3f678e694e5133b7/official/vision/image_classification/augment.py#L731). 
- [RandAugment](https://paperswithcode.com/paper/randaugment-practical-data-augmentation-with) - [Code](https://github.com/tensorflow/models/blob/ded32f0500604928e52e27fd3f678e694e5133b7/official/vision/image_classification/augment.py#L905)
- [Review](https://medium.com/%E5%B7%A5%E4%BA%BA%E6%99%BA%E6%85%A7/review-autoaugment-and-randaugment-f1fbd7e7a661).

**Comment by bhack** [comment]
> I think that we could also evaluate differentiable augmentations like:
https://arxiv.org/abs/2104.04282
https://arxiv.org/abs/2109.15273
https://openreview.net/forum?id=St-53J9ZARf

/cc @haifeng-jin

**Comment by LukeWood** [comment]
this should probably use RandomAugmentationPipeline.

**Comment by bhack** [comment]
> I think that we could also evaluate differentiable augmentations like:
> .....
>  https://openreview.net/forum?id=St-53J9ZARf

https://github.com/MSU-MLSys-Lab/DeepAA

**Comment by LukeWood** [comment]
I've received numerous inquiries about AutoAugment, so I definitely think we want this component.

**Comment by bhack** [comment]
Has https://github.com/keras-team/keras-cv/issues/900 was cloud I will unify the references on this ticket.

**Comment by LukeWood** [comment]
Lets deprioritize in favor of RandAugment; which serves a similar purpose but is much easier to tune.
