### ISSUE TITLE
Keras.io tutorial on implementing PixMix data augmentation layer

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#412]
Dan recommended this to me:

https://arxiv.org/pdf/2112.05135.pdf

In his words:

"Also, it's worth mentioning that [PixMix](https://arxiv.org/pdf/2112.05135.pdf) (CVPR 2022) is faster and stronger than AugMix, even without using other images in my experience."

We can offer this as a Keras.io tutorial "how to implement PixMix using BaseImageAugmentationLayer" based on the tutorial https://keras.io/guides/keras_cv/custom_image_augmentations/

Here is a sample implementation:

https://github.com/andyzoujm/pixmix

**Comment by quantumalaviya** [comment]
Should the layer expect the path to the mixing set (location of the fractal dataset) as an input?

**Comment by bhack** [comment]
> Should the layer expect the path to the mixing set (location of the fractal dataset) as an input?

Yes, if we compare this with the other KPLs we have with a "pure online" approach this has a quite relevant offline asset (1.6GB).

Also it is still has only 2 citations (it is quite fresh).

**Comment by LukeWood** [comment]
Yeah; this technique is also pretty complex so maybe we should hold off on implementing it for now until we see a few other implementations.  I'll also discuss this with Dan and go over the pros and cons a bit.

**Comment by LukeWood** [comment]
Reference impl:

https://github.com/andyzoujm/pixmix

**Comment by LukeWood** [comment]
@blank0043

**Comment by LukeWood** [comment]
Closing unless someone pursues this again - in any case its a keras-io bug
