### ISSUE TITLE
Documentation or tutorial for .train_on_batch or .fit_generators 

### ISSUE THREAD

**Issue by Tony363** [keras-team/keras-cv#419]
Documentation or tutorial for .train_on_batch or .fit_generators is very hard to find for tensorflow keras. Might there be some already? May be I can learn to use them and write a tutorial?

**Comment by LukeWood** [comment]
Hey @Tony363!  This is a documentation issue with core Keras, right?  Fit generator I think is deprecated, but train_on_batch perhaps some better docs would be useful.

can you open an issue on the Keras repo?

**Comment by Tony363** [comment]
okay, I'll do that! it's the very issue I'm having with building my keras pipeline right now
