### ISSUE TITLE
`MaybeApply` high order abstraction

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#422]
We should consider an implementation for a `MaybeApply` layer:

```
maybe_solarize = MaybeApply(Solarization(), rate=0.5)
# maybe_solarize solarizes half of the images passed to it
```

https://github.com/chjort/chambers/blob/b796f507b7353fb141b5c8b026b811a023d303e6/chambers/augmentations/image_augmentations.py#L514

Notes:
- we can rely on this in RandomAugmentationPipeline
- this must be element-wise, not batch wise!

**Comment by sebastian-sz** [comment]
@LukeWood I would like to work on this, if possible.

**Comment by LukeWood** [comment]
> @LukeWood I would like to work on this, if possible.

Let me confirm we want to take the approach of offering high order abstractions like this first!  Still brainstorming a bit

**Comment by sebastian-sz** [comment]
Got it, please let me know if you decide. 

Personally I wouldn't mind an option to create custom random layers.

**Comment by LukeWood** [comment]
> Got it, please let me know if you decide.
> 
> Personally I wouldn't mind an option to create custom random layers.

It seems to me this is such a common pattern that we should include it.

I've seen:

```
if tf.random.uniform() > 0.5:
    # apply some augmentation
```

many times in my life, and this is actually incorrect if you are performing batched augmentation.  By providing a proper implementation that does this on an element-wise basis, we are providing some value.  I'm fairly sure we want this, let me confirm one more time tomorrow, but I am 90% sure this is an abstraction we want.

**Comment by LukeWood** [comment]
FYI @sebastian-sz I've tagged this contribution welcome.  

These high order components that take other components are a nice pattern.
