### ISSUE TITLE
Upgrade action CI and .devcontainer to TF 2.9 final

### ISSUE THREAD

**Issue by bhack** [keras-team/keras-cv#440]

**Comment by bhack** [comment]
more in general:
are we going to switch again on nightly between two TF releases or we will switch only to next RC and stable release?

**Comment by LukeWood** [comment]
I hope that we don’t have to switch back to nightly.  Unfortunately the reality is we might have to which will freeze our releases (excluding cherry picks).  I hope this doesn’t happen, but it is possible.

**Comment by bhack** [comment]
Also we need to consider that Keras master tracks `tf-nightly`:
https://github.com/keras-team/keras/blob/master/requirements.txt#L6

But it is still not clear what nightly >= version (/cc @qlzh727) so the dependency it could be "wrongly" satisfied also with years TF old nighties without a minimal constrain:
https://github.com/keras-team/keras/issues/14867#issuecomment-962123047
