### ISSUE TITLE
cut_mix output is in dictionary

### ISSUE THREAD

**Issue by johnypark** [keras-team/keras-cv#447]
https://github.com/keras-team/keras-cv/blob/40a9fbf81a5a1689590885ceaefaf927b4a98292/keras_cv/layers/preprocessing/cut_mix.py#L52-L64

The current output of cut_mix is in dictionary form. Is this intended? I haven't tested it, but if the output is a dictionary, then I am not sure if it would work for the data pipeline.

I think 
```
inputs["images"] = images 
inputs["labels"] = labels 
return inputs
```

can be changed to 
```
return images, labels
```

which would work fine. I wonder if there is any particular reason that the output is in dictionary format.

**Comment by LukeWood** [comment]
This is actually intended behavior.  All of the layers return either a single image if they only get an image:

image = RandAugment()(image)

or a dictionary in the above specified format:

outputs = RandAugment()({images: images, labels: labels, bounding_boxes: bounding_boxes})

**Comment by johnypark** [comment]
@LukeWood  Thank you for the clarification.
