### ISSUE TITLE
CutMix gives wrong error when input is not a dict

### ISSUE THREAD

**Issue by artu1999** [keras-team/keras-cv#450]
When CutMix layer is executed as:

```
train_ds = train_ds.map(lambda x, y: cutmix(x, y), num_parallel_calls=tf.data.AUTOTUNE)
```

Rather than telling the user the input should be a dict it throws this error:

    File "<ipython-input-1-91c57220b1e3>", line 30, in None  *
        lambda x, y: cutmix(x, y),
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler  **
        raise e.with_traceback(filtered_tb) from None

    OperatorNotAllowedInGraphError: Exception encountered when calling layer "cut_mix" (type CutMix).
    
    Using a symbolic `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.
    
    Call arguments received by layer "cut_mix" (type CutMix):
      • inputs=tf.Tensor(shape=(None, 224, 224, 3), dtype=float32)
      • training=tf.Tensor(shape=(None, 102), dtype=float32)

See [notebook](https://colab.research.google.com/drive/1Z9m2hoHtN20APhbt4spgHF2Nd8AmGAc2?usp=sharing) to reproduce the issue. 

Having a look at CutMix, I think [this](https://github.com/keras-team/keras-cv/blob/4c300f564d8ec99cd1351c445e1803ee6664915a/keras_cv/layers/preprocessing/cut_mix.py#L54-L66) should check if input type is a dict first.

**Comment by LukeWood** [comment]
Thanks for the error report.  I'm working on a PR to improve error messages and I'll add this to the list.

**Comment by LukeWood** [comment]
Fixed this
