### ISSUE TITLE
CutMix and MixUp should support "targets" in addition to "labels"

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#452]
we are renaming "labels" to "targets" as the one hot encoded labels are in fact targets, not labels.  This verbature distinction is made with respect to the fact that the target space is continuous, whereas labels represent the literal labels such as "cat", "dog".

CutMix and MixUp should support both temporarily via a helper method.  In Keras core we do this in BaseImageAugmentationLayer; we can follow this pattern here.

**Comment by sachinprasadhs** [comment]
Does the commit here https://github.com/keras-team/keras-cv/commit/bc8e824eef30876f8a468da7bc14e04ecb38affa#diff-5ab3d5b763923c49951584b8753980fcc08f4999c47e116d14f4b6791c7c84fb which adds the `BaseImageAugmentationLayer` address this issue?
