### ISSUE TITLE
`ReviewNB` - for notebook PR`!

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#454]
**Short Description**

For the notebook PR, it's not possible to review but service can be used for this. 

- [ReviewNB](https://app.reviewnb.com/)

**Existing Implementations**

For example, check: https://github.com/tensorflow/models/pull/10640#issuecomment-1127970171

**Comment by bhack** [comment]
Already discussed some months ago https://github.com/keras-team/keras-cv/pull/147#issuecomment-1052867691

**Comment by innat** [comment]
@bhack thanks for the info, didn’t know that. Closing it.

**Comment by bhack** [comment]
I wasn't saying that to get you to close the ticket. They could have changed their opinion after 3 months.

**Comment by LukeWood** [comment]
Is there some sort of action I need to take to opt our repo in?

**Comment by innat** [comment]
I think demonstrating the [example or tutorials](https://github.com/keras-team/keras-cv/tree/master/examples/layers/preprocessing) in a jupyter notebook might be useful for visual look rather than script. If so, then ReviewNB would be helpful. What do you think?

**Comment by LukeWood** [comment]
As of now we don’t have any notebooks.  Maybe at some point we move this way, but I find using tutobooks much nice.  Let’s do that if we ever move this direction.  Tutobooks are also consistent with keras-io
