### ISSUE TITLE
Produce marketing image for keras.io docs

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#456]
We can use this, but also should include CutMix and MixUp.

https://colab.research.google.com/drive/1cKAM7R7I2GO6OzfkxwLH6TTpXL5-_q7u?usp=sharing

**Comment by ishangala16** [comment]
Luke, can you provide something for reference? I'll make something similar

**Comment by LukeWood** [comment]
Hey @ishangala16!  This is more of a tracking issue that I'll likely take on!  Check out our contributions welcome hotlist!

**Comment by ishangala16** [comment]
@LukeWood Okay no problem I'll check out the list
