### ISSUE TITLE
NonMaxSupression Layer

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#461]
This should return a KerasCV bounding box format instead of a custom object.

https://github.com/LukeWood/reef-net/blob/master/reef_net/model.py#L247

**Comment by quantumalaviya** [comment]
Hey @LukeWood I think you can assign this one to me.

**Comment by LukeWood** [comment]
Cool, the idea here is to go from the format the NMSSuppression returns to a specified `bounding_box_format` using the API I created in my bounding box PR!
