### ISSUE TITLE
Migrate BaseImageAugmentationLayer to Keras_CV

### ISSUE THREAD

**Issue by divyashreepathihalli** [keras-team/keras-cv#465]
Duplicate BaseImageAugmentationLayer in Keras_CV.

**Comment by bhack** [comment]
Can you explain this for the community?

**Comment by divyashreepathihalli** [comment]
@bhack , as Keras_CV continues to grow, we would like the package to be more self contained.  We want to make sure that updates to Keras_CV is not tied to Keras releases. BaseImageAugmentationLayer is subclassed by all Image preprocessing layers. Migrating BaseImageAugmentationLayer with help us make updates to Keras_CV easier and faster.

**Comment by bhack** [comment]
This will imply that all the KLP layers still in Keras will migrate here. Are these going to be detracted over multiple releases in Keras or this will happen in a single release?

**Comment by LukeWood** [comment]
> This will imply that all the KLP layers still in Keras will migrate here. Are these going to be deprecated over multiple releases in Keras or will this happen in a single release?

They won’t be deprecated or removed.  Mirrored here, with the KerasCV layers being a strict superset of the Keras core layers.

**Comment by bhack** [comment]
Ok probably we could rename all the "migrate" ticket.
