### ISSUE TITLE
Implementing Stochastic Depth

### ISSUE THREAD

**Issue by AdityaKane2001** [keras-team/keras-cv#473]
@sayakpaul @LukeWood 

A continuation of #130, here I would like to clear some nitty-gritties regarding the implementation. 

Abiding to the [original paper](https://arxiv.org/pdf/1603.09382.pdf), TFA has the most appropriate implementation ([here](https://github.com/tensorflow/addons/blob/v0.17.0/tensorflow_addons/layers/stochastic_depth.py#L5-L90)) in my opinion. The timm and tensorflow/tpu implementations aim to randomly occlude some elements of every batch. However, if I understand correctly, the original paper aims to occlude entire batch, given by the probability. I believe this is the implementation we should go for.

**Comment by AdityaKane2001** [comment]
Great! In that case I will have a PR up by EoD today.

**Comment by sebastian-sz** [comment]
Do we want to have both StochasticDepth (TFAddons like) and DropBlock variant or only one of the two?

**Comment by sayakpaul** [comment]
Hi @sebastian-sz! Great suggestion. 

This is a bit specific to Adtiya's contribution to GSoC. We haven't yet factored in DropBlock but that should be relatively easy to do. I don't mind including it. @AdityaKane2001 WDYT given DropBlock is more commonly used these days?

**Comment by sayakpaul** [comment]
It should not be.

**Comment by sebastian-sz** [comment]
@AdityaKane2001 yes, I meant DropPath not DropBlock. Sorry for the confusion.

**Comment by AdityaKane2001** [comment]
@sayakpaul which one do we want to include? 

I think StochasticDepth (dropping entire batch) and DropPath (dropping some samples) are more relevant and can be easily implemented here. If it's okay, I'll implement these two and have the PR ready by EoD. Then we can move on to DropBlock.

**Comment by sayakpaul** [comment]
I'd prefer separate PRs for the two. I think that would make the review a bit more streamlined.

**Comment by sayakpaul** [comment]
@AdityaKane2001 can we close it?

**Comment by AdityaKane2001** [comment]
I was hoping to close it after we merge DropPath.
