### ISSUE TITLE
WideResNet architecture

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#49]
Best resnet for Cifar10/Cifar100

 https://arxiv.org/abs/1605.07146

**Comment by MrinalTyagi** [comment]
Would like to work on this.

**Comment by blackhat-coder** [comment]
Hi @LukeWood ,I would love to implement WideResNet duing GSoC. I'm currently drafting my proposal and would love to know if I could implement this during GSoC ?

**Comment by innat** [comment]
Any update on this feature? cc @blackhat-coder

**Comment by blackhat-coder** [comment]
Hi @innat, This feature proposal wasn't accepted, however I can still work on implementing this architecture.

**Comment by DavidLandup0** [comment]
Can you assign this to me as well? :)

**Comment by DavidLandup0** [comment]
Thanks!

**Comment by DavidLandup0** [comment]
Seems to be done, just waiting for the training to finish to validate whether it behaves the same as in the paper. Sending the pull request in a few hours!

**Comment by LukeWood** [comment]
Lets deprioritize this until theres a strong use case; and focus on migrating the existing backbones!

**Comment by innat** [comment]
@LukeWood this network is cited by 6776 times, here is the pwc [report](https://paperswithcode.com/method/wideresnet).
