### ISSUE TITLE
Add MLP Mixer classes to the `models` module

### ISSUE THREAD

**Issue by sayakpaul** [keras-team/keras-cv#496]
MLP Mixers [1] are a cool architecture that does not involve convs, attention, or transformers -- just `Dense` layers 🤯! I have worked with MLP Mixer before (see [here](https://github.com/sayakpaul/MLP-Mixer-CIFAR10) and [here](https://github.com/sayakpaul/MLPMixer-jax2tf)). Therefore, would love to contribute them to `keras_cv.models`. 

## References

[1] MLP-Mixer: An all-MLP Architecture for Vision: https://arxiv.org/abs/2105.01601

**Comment by LukeWood** [comment]
MLPMixer is a very unique architecture!  I think it would be great to offer this from keras_cv.models

**Comment by sayakpaul** [comment]
> i wonder if it is worth offering the patch extractor as an API, or if it is too specific to MLPMixer.


In my experience of working with similar architectures (i.e., the ones that don't reply on convs to process images and build representations) usually benefit from the patch extractor module. For the first iteration, I will include the patch extractor in the model itself. But can do the changes necessary to offer it as a separate API.

**Comment by LukeWood** [comment]
sounds good, as long as we write it as an independent layer it shouldn’t be hard to migrate it to the layers API should it turn out to be useful to do so.

**Comment by bhack** [comment]
We could also expore if it is useful to access to surveys to have a good overview of the specific domain on reusable components/API design:

https://arxiv.org/abs/2111.04060

https://arxiv.org/abs/2112.04453

**Comment by bhack** [comment]
We could also expore if it is useful to access to surveys to have a good overview of the specific domain on reusable components/API design:

https://arxiv.org/abs/2111.04060

https://arxiv.org/abs/2112.04453

![IMG_20220616_163457.jpg](https://user-images.githubusercontent.com/1710528/174094079-829ce418-f8b7-44d4-8530-73bdc35490ad.jpg)
