### ISSUE TITLE
AugMix does not respect seed

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#500]
Two runs of `examples/layers/preprocessing/aug_mix_demo.py` on the same seed produce two different sets of images

**Comment by LukeWood** [comment]
Root cause is here: https://github.com/keras-team/keras-cv/blob/master/keras_cv/layers/preprocessing/aug_mix.py#L100

@qlzh727 should we use [make_legacy_seed()] to seed this op?

**Comment by qlzh727** [comment]
yes. You could use make_legacy_seed() in this case. It could return None if user didn't provide any seed, which I think is ok.

**Comment by LukeWood** [comment]
yes absolutely, I only raised this because a specific user wants to use augmix internally with consistency between runtimes.

**Comment by quantumalaviya** [comment]
Should it not be a static method, in that case?

**Comment by LukeWood** [comment]
Good point,  yeah it won't be a static method anymore.
