### ISSUE TITLE
AugMix should use the get_random_transformation() API

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#501]
all random samples should be drawn inside of get_random_transformation()

https://github.com/keras-team/keras-cv/blob/master/keras_cv/layers/preprocessing/aug_mix.py#L282

**Comment by sachinprasadhs** [comment]
`get_random_transformation()` has been included in the `aug_mix.py` in the commit here https://github.com/keras-team/keras-cv/commit/d14c16d1b6a3068460ad1b9051cb179e1c4dc729#diff-f64af1cdeefc739aa89da545633f82e4c0f63c331e3d3df2224a55b757605955
Could you please confirm and close the issue. Thanks!
