### ISSUE TITLE
Include `yxyx` format in `converters.py`

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#506]
https://github.com/keras-team/keras-cv/blob/master/keras_cv/bounding_box/converters.py

**Comment by LukeWood** [comment]
The yxyx format is used in model garden, tf.io and tf.image

**Comment by innat** [comment]
IMO, the `xyxy` notation is a bit more readable. Not sure why `yxyx` is followed there. And what about `xywh`?
