### ISSUE TITLE
Ragged random resize

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#515]
We should be able to randomly resize image batches into a ragged batch with random shapes.  Perhaps randomheight and random width once migrated to KerasCV could support this via a ragged keyword

**Comment by qlzh727** [comment]
@divyashreepathihalli

**Comment by sachinprasadhs** [comment]
I think this issue can be closed since it is already addressed in the commit [here](https://github.com/keras-team/keras-cv/commit/4ef3ea1148d6182d6f2efb330d9e11a3b4407c67#diff-6385d145862b6975c81f47e560e86bb95f62c3497eeaa245386e5ee96bbf3a9b)  for the API `JitteredResize layer`
