### ISSUE TITLE
Include EfficientNet models

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#520]
This should be ported from the core Keras API: keras.applications following the example set in: https://github.com/keras-team/keras-cv/pull/476

**Comment by AdityaKane2001** [comment]
@LukeWood I'm interested to work on this.

**Comment by AdityaKane2001** [comment]
@sayakpaul @LukeWood I'm interested to work on this.

**Comment by Rishit-dagli** [comment]
Is this the umbrella issue for EfficientNet and EfficientNetv2?

If so, @AdityaKane2001 would you mind if each of us takes one up, I would love to contribute too?

**Comment by ayyucedemirbas** [comment]
I added EfficientNet models with [this PR](https://github.com/keras-team/keras-cv/pull/570). Could you please take a look at it? @LukeWood @sayakpaul Thanks!
