### ISSUE TITLE
Include ResNetV2 models

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#521]
This should be ported from the core Keras API: keras.applications following the example set in: https://github.com/keras-team/keras-cv/pull/476

**Comment by AdityaKane2001** [comment]
@LukeWood I'm interested to work on this.

**Comment by LukeWood** [comment]
Great Aditya!  Feel free to take it on!

**Comment by AdityaKane2001** [comment]
Should I go for ResNetV1 and ResNetV2 both for completeness?

**Comment by LukeWood** [comment]
These have been included 🎉
