### ISSUE TITLE
DenseNet docstring should be fixed

### ISSUE THREAD

**Issue by quantumalaviya** [keras-team/keras-cv#528]
There are some minor inconsistencies in DenseNet compared to the other layers and keras applications:

Firstly, in the argument description for `include_top`, it says,
```
include_top: whether to include the fully-connected
layer at the top of the network.  If provided, num_classes must be provided.
```
However, for keras_cv there is no `num_classes` attribute. We use `classes`. Either the `classes` attribute name or this description needs to be changed. Personally, I feel that `num_classes` is more descriptive.

Secondly, the DenseNet docstring is copied to all versions of the DenseNet architecture. This may be confusing in some cases. For example, the `name` is supposed to default to "DenseNet" according to the docstring. However, in practice, it changes for every DenseNet version. We can opt to have a base docstring that is edited in each case (see the [EfficientNet implementation from Keras](https://github.com/keras-team/keras/blob/07e13740fd181fc3ddec7d9a594d8a08666645f6/keras/applications/efficientnet.py#L145)).

Lastly, the DenseNet docstring can be edited to follow the same formatting as followed across the other keras_cv layers

**Comment by LukeWood** [comment]
Thanks for pointing this out!

**Comment by quantumalaviya** [comment]
@LukeWood Did you decide on whether the `classes` arg should be renamed to `num_classes`?
