### ISSUE TITLE
Explore model visualization tools

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#53]
e.x.

https://tf-explain.readthedocs.io/en/latest/

**Comment by bhack** [comment]
https://arxiv.org/abs/2012.09838

**Comment by innat** [comment]
This would be really nice to have. But I remember some folk requested such a feature ([issue](https://github.com/keras-team/keras/issues/15704)) but it was [closed](https://github.com/keras-team/keras/issues/15704#issuecomment-984897075) anyway. And it would be great to reconsider.

**Comment by MrinalTyagi** [comment]
@innat Here I am requesting it [issue](https://github.com/keras-team/keras/issues/15704). Would love to work on this if it's available for contributions. Also proposed this as my GSoC idea proposal. :)

**Comment by innat** [comment]
Some reference implementation 
https://github.com/keisen/tf-keras-vis#overview

**Comment by LukeWood** [comment]
> @innat Here I am requesting it again [issue](https://github.com/keras-team/keras/issues/15704). Would love to work on this if it's available for contributions. Also proposed this as my GSoC idea proposal. :)

Thanks for the proposal.  I think model visualization tools belong in this repo.  Lets start a subdirectory `visualization`.  GradCam can be a first component.
