### ISSUE TITLE
Support for augmention in segmentation task

### ISSUE THREAD

**Issue by old-school-kid** [keras-team/keras-cv#533]
**Short Description**
Sort of duplicate of [#16117](https://github.com/keras-team/keras/issues/16117)

RandomRotation has utility for [augmenting bounding boxes](https://github.com/keras-team/keras-cv/blob/master/keras_cv/layers/preprocessing/random_rotation.py#L139) which is again missing in random shear layer. Also there is no support for augmenting target in case of a segmentation task. 

**Other Information**
possible solution: augment_label function can be used to check if the label is an image and carry out the same augmentation as on image.

**Comment by LukeWood** [comment]
Hey @ayulockin thanks for checking in on this.  

If you can provide an in depth overview of the different segmentation map formats we can start with utilities to convert between formats.

Does that sound like a plan?

**Comment by ayulockin** [comment]
That sounds like a plan. Should we have a different issue to capture it? I can create one and self assign + assign Soumik.

**Comment by LukeWood** [comment]
No thanks, I can just assign to you for now.  Lets keep it here.

**Comment by LukeWood** [comment]
Soumik must comment to be assigned!

**Comment by innat** [comment]
@LukeWood 
> If you can provide an in depth overview of the different segmentation map formats we can start with utilities to convert between formats.

There may be three most common formats: 
- png as image format, 
- polygon and 
- rle https://github.com/keras-team/keras-cv/issues/327. 

cc. @ayulockin @old-school-kid @soumik12345

**Comment by LukeWood** [comment]
> @LukeWood
> 
> > If you can provide an in depth overview of the different segmentation map formats we can start with utilities to convert between formats.
> 
> There may be three most common formats:
> 
> * png as image format,
> * polygon and
> * rle [Run Length Encoding/Decoding utility #327](https://github.com/keras-team/keras-cv/issues/327).
> 
> cc. @ayulockin @old-school-kid @soumik12345

Cc @sayakpaul @tanzhenyu @innat

**Comment by sayakpaul** [comment]
I agree with @innat. 

The proposal that @innat made in https://github.com/keras-team/keras-cv/issues/327 is really solid. I see two ways:

* We first create the RLE utilities. Then work on supporting different Segmentation formats.
* We first develop utilities to support the first two formats - images and polygons as they are relatively easier. 

This way we should be able to better isolate the components. But keen to know what others think.

**Comment by ayulockin** [comment]
I agree with the suggestion @sayakpaul made. Supporting `rle2mask2d` and `mask2d2rle` should be an excellent place to begin.

**Comment by sayakpaul** [comment]
Note we'd prefer `rle_to_mask2d()` and `mask2d_to_rle()` to the ones you mentioned. Minor nit but just wanted to mention.

**Comment by LukeWood** [comment]
So, do we consider these two formats to both be segmentation map formats, or are they distinct label types?

**Comment by sayakpaul** [comment]
@LukeWood could you elaborate more? Couldn't really get your question.
