### ISSUE TITLE
COCORecall should support XLA compilation

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#54]
Current error when running in mirrored mode:
> ValueError: SyncOnReadVariable does not support `assign_add` in cross-replica context when aggregation is set to `tf.VariableAggregation.SUM`.

If we can compile to XLA we can also run on TPUs.

**Comment by bhack** [comment]
You aren't alone:
https://github.com/tensorflow/tensorflow/issues/50407

https://github.com/tensorflow/tensorflow/issues/40366

**Comment by LukeWood** [comment]
not possibly for now
