### ISSUE TITLE
[For Aditya and RRC reviewers] Add a guide on RRC

### ISSUE THREAD

**Issue by sayakpaul** [keras-team/keras-cv#549]
Now that https://github.com/keras-team/keras-cv/pull/499 is merged let's write a comprehensive guide on it. I'd want to include the following in the guide:

* Showing how changing different parameters of the layer affect the outputs. 
* Provide recommendations from the literature. Here, we could provide recommended values for the important parameters of the layer for a given task at hand. For example, image classification models usually have a different area factor than self-supervised models. Of course, we can't exhaust ourselves here but let's try our best. 

@AdityaKane2001 @LukeWood @tanzhenyu

**Comment by LukeWood** [comment]
great idea Sayak!

**Comment by sayakpaul** [comment]
@LukeWood is the guide live?

**Comment by LukeWood** [comment]
we can reopen if we’re still interested in it.  Are you guys interested?

**Comment by sayakpaul** [comment]
@AdityaKane2001 WDYT? I think after all the hard work that was put into creating the RRC API, it deserves a guide. 

Cc: @martin-gorner

**Comment by LukeWood** [comment]
Feel free to open this back up if you'd like to do this @AdityaKane2001  - but closing for  now until theres a strong interest

**Comment by AdityaKane2001** [comment]
Sorry this slipped my mind. I'll circle back to this next week and reopen the issue then. Thanks.
