### ISSUE TITLE
Support for extra keys in dictionary input.

### ISSUE THREAD

**Issue by sebastian-sz** [keras-team/keras-cv#565]
**Short Description**
Currently, preprocessing layers support dictionary input, but only if the dictionary contains a predefined set of keys.

```python
import tensorflow as tf

data = {"images": tf.random.uniform((1, 224, 224, 3))} 
extra_data = {"images": tf.random.uniform((1, 224, 224, 3)), "filenames":tf.constant(["path/to/my/data"])}
```
For example, let's apply `RandomSaturation` to `data` and `extra_data`:
```python
from keras_cv.layers.preprocessing import RandomSaturation

layer = RandomSaturation(0.5)
output = layer(data)  # OK
print(output.keys())  # dict_keys(['images'])
output = layer(extra_data)  # dict_keys(['images']) -> we lost "filenames"
```

The above will remove my extra key from the input.

### Possible solution:
I was thinking about modyfing the `_augment` method od `BaseImageAugmentationLayer`, to preserve all the keys that have not been modified and update the ones that have:
```python
# instead of returning results:
(...)
# return result
inputs.update(result)
return inputs
```

### Summary
Would the proposed feature be possible? What do you think?

**Comment by LukeWood** [comment]
cool, me too.  Go ahead @sebastian-sz if you want to contribute this.
