### ISSUE TITLE
Standardized / preferred way to implement blocks and models.

### ISSUE THREAD

**Issue by sebastian-sz** [keras-team/keras-cv#59]
Given the models requirements are being gathered in the [discussion](https://github.com/keras-team/keras-cv/discussions/52), is there a preferred way to implement them?

There are multiple ways, to implement blocks and models:
1. `keras.applications` way -> Models and blocks are functional [Example](https://github.com/keras-team/keras/blob/2c48a3b38b6b6139be2da501982fd2f61d7d48fe/keras/applications/resnet.py#L440-L459).
2. Model Garden way -> Model is [functional](https://github.com/tensorflow/models/blob/c8a402fc7fc0cc391a9e3ac56fb7b3ea6f9d202e/official/vision/beta/modeling/backbones/resnet.py#L99), but blocks are [layer subclasses](https://github.com/tensorflow/models/blob/c8a402fc7fc0cc391a9e3ac56fb7b3ea6f9d202e/official/vision/beta/modeling/layers/nn_blocks.py#L56). (even though the model is a direct subclass, it does not override call method).
3. Blocks are layer subclasses, and models are model subclasses of `keras.layers.Layer` and `keras.Model` respectively. Both implement `call` method.

Each way has it's own benefits and drawbacks. Is one of the above preferred? Or maybe something entirely different?

**Comment by chjort** [comment]
Personally, I would prefer the `keras.applications` way, where the model is purely functional. Functional models are validated and built during construction. So if a functional models is constructed, the forward pass is guaranteed to work. This also makes `model.summary()` available right away.

Some applications will require non-standard keras layers, so these can be implemented by subclassing `keras.layers.Layer`, and then included in the functional model building.

**Comment by sebastian-sz** [comment]
@chjort Yes, personally I would also prefer `keras.applications` way. This works well with Tensorflow Model Optimization (I'm not sure about subclassed model's) and the flat structure allows for easy layer modifications.

**Comment by LukeWood** [comment]
We will be following the keras.applications standard.  For example, ResNetBlock will be a functional model.

**Comment by sebastian-sz** [comment]
@LukeWood thank you, that answer's the question.
