### ISSUE TITLE
Fix documentation and test it

### ISSUE THREAD

**Issue by ebursztein** [keras-team/keras-cv#592]
The keras_cv starting documentation is broken as the code it contains is invalid:
```
import keras_cv
from tensorflow import keras

preprocessing_model = keras.Sequential([
    keras_cv.layers.RandAugment(value_range=(0, 255))
    keras_cv.layers.CutMix(),
    keras_cv.layers.MixUp()
], name="preprocessing_model")
```
There is a missing `,`  after rand aug,

I suggest to fix it and add a unit test to make sure the code used in the documentation pass.

**Comment by LukeWood** [comment]
Thanks for the bug report Elie! There is also a bug that occurs when using a sequential model with dictionary inputs.  I will update both, and I like the idea to unit test these.

**Comment by ebursztein** [comment]
Additionally be careful to not trigger the augmentation when in test mode (trainable will be false) - otherwise eval results are going to be interesting. Currently I do use two function but with KCV it should just work?

**Comment by divyashreepathihalli** [comment]
@ebursztein closing the issue since the code has changed significantly since this issue was filed.
