### ISSUE TITLE
investigate the impact of changing arguments in map_fn/vmap for preprocessing layers

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#595]
https://www.tensorflow.org/api_docs/python/tf/map_fn

**Comment by tanzhenyu** [comment]
@bhack

**Comment by bhack** [comment]
https://github.com/tensorflow/tensorflow/issues/55639

Benchmark at:
https://github.com/tensorflow/tensorflow/issues/55639#issuecomment-1271581415

**Comment by bhack** [comment]
https://github.com/keras-team/keras-cv/issues/291

https://github.com/keras-team/keras-cv/issues/581
