### ISSUE TITLE
TokenMix: Rethinking Image Mixing for Data Augmentation in Vision Transformers

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#617]
https://arxiv.org/pdf/2207.08409v1.pdf

**Comment by innat** [comment]
Here is another augmentation strategy for ViT model. 
[TransMix: Attend to Mix for Vision Transformers](https://github.com/beckschen/transmix)

![pic1](https://user-images.githubusercontent.com/17668390/180937533-9f7d587d-7f27-4a00-8b85-67aafe7658be.png)

**Comment by bhack** [comment]
RecursiveMix: Mixed Learning with History

https://arxiv.org/abs/2203.06844
https://github.com/implus/RecursiveMix-pytorch

**Comment by LukeWood** [comment]
Closing issues out that we don't intend to pursue anytime soon.
