### ISSUE TITLE
Add RetinaNet model

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#621]
**Short Description**

**RetinaNet**, an object detection as described in the following paper.

**Papers**

https://arxiv.org/abs/1708.02002
publish date: 2017
Cited by 14612 (until)

**Existing Implementations**

Here is one well known and strong reference: 
[fizyr/keras-retinanet](https://github.com/fizyr/keras-retinanet)

**Other Information**
- https://github.com/srihari-humbarwadi/retinanet-tensorflow2.x
- https://github.com/tensorflow/models/tree/master/official/vision#COCO-Object-Detection-Baselines

**Comment by ayulockin** [comment]
Hey @innat, @LukeWood already has an active PR #609 for this.

**Comment by LukeWood** [comment]
This is done now
