### ISSUE TITLE
Add EfficientNet Lite model variants.

### ISSUE THREAD

**Issue by sebastian-sz** [keras-team/keras-cv#630]
**Short Description**
EfficientNet Lite models are lighter variants of EfficientNets more suitable for mobile deployment. 

**Existing Implementations**
Original implementation - [link](https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet/lite)
My reimplementation - [link](https://github.com/sebastian-sz/efficientnet-lite-keras)

**Other Information**
EfficientNet Lite's have been requested multiple times in the Tensorflow/Keras ecosystem:

https://github.com/keras-team/keras/issues/16835
https://github.com/tensorflow/tensorflow/issues/45091
https://github.com/tensorflow/tensorflow/pull/48400

Let me know what you think!

**Comment by MrinalTyagi** [comment]
Would love to pick this up if noone else is currently working on this. @sebastian-sz

**Comment by sebastian-sz** [comment]
@MrinalTyagi I actually wanted to add these models, but I'm waiting for:
1. Acceptance / contribution welcome tag from the repo authors.
2. When #570 is merged

There should also be some API discussion: do we want these as separate models, like `EfficientNetLiteB0` or kind of like `MobilenetV3` add a `minimalistic` or `lite` flag to existing implementation.
