### ISSUE TITLE
Unit test NonMaxSuppressionLayer output shapes

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#632]
We should heavily cover the exact output shapes of the ragged tensors for this layer.

**Comment by LukeWood** [comment]
Tests to cover: 

1.) batch_size axis is preserved and does not turn into a Ragged None shape dimension

(i.e. [3, None, 6] is an expected shape for a batch_size of 3, [None, None, 6] is unexpected)

2.) test differing # of boxes per dimension, index into each dimension and explicitly check # of boxes

**Comment by LukeWood** [comment]
3.) case where there are no boxes above confidence threshold.  Result shape should be [batch_size, 0, 6]

**Comment by LukeWood** [comment]
4.) case where one image has no boxes above confidence threshold.  Result shape should be [batch_size, None, 6]

**Comment by quantumalaviya** [comment]
> 1.) batch_size axis is preserved and does not turn into a Ragged None shape dimension
>
> (i.e. [3, None, 6] is an expected shape for a batch_size of 3, [None, None, 6] is unexpected)

@LukeWood Can this be considered covered under the existing shape check test cases?
