### ISSUE TITLE
Improve assertions in old test cases

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#637]
Examples:

```
    def test_constant_channels_dont_get_nanned(self):
        img = tf.constant([1, 1], dtype=tf.float32)
        img = tf.expand_dims(img, axis=-1)
        img = tf.expand_dims(img, axis=-1)
        img = tf.expand_dims(img, axis=0)

        layer = preprocessing.AutoContrast(value_range=(0, 255))
        ys = layer(img)

        self.assertTrue(tf.math.reduce_any(ys[0] == 1.0))
        self.assertTrue(tf.math.reduce_any(ys[0] == 1.0))
```

the:

```
self.assertTrue(tf.math.reduce_any(ys[0] == 1.0))
self.assertTrue(tf.math.reduce_any(ys[0] == 1.0))
self.assertAllClose(ys, [1.0, 1.0])
```

**Comment by MrinalTyagi** [comment]
@LukeWood Can you describe how to proceed with this?

**Comment by LukeWood** [comment]
> @LukeWood Can you describe how to proceed with this?

Yes absolutely, basically in layers/prepreprocessing/*_test.py we can look for instances of “assertTrue” or “assertFalse” and attempt to replace them with more idiomatic assertions from the class tf.testing.TestCase.

Then re-run tests and send a PR!

**Comment by LukeWood** [comment]
@MrinalTyagi this would be a great first issue

**Comment by MrinalTyagi** [comment]
Cool. Picking this up.

**Comment by LukeWood** [comment]
Not specific enough - should be re-opened if we identify this  issue in specific unit tests
