### ISSUE TITLE
version check fails for TF 2.9.0, which is a valid version

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#643]

**Comment by ayulockin** [comment]
To add more context, I got this when I tried running the RetinaNet example from Luke's fork of the repo.

<img width="930" alt="image" src="https://user-images.githubusercontent.com/31141479/182311698-429487b5-586d-4c25-9658-2c27eac6a318.png">

I resolved this temporarily by commenting out L18 in `./keras-cv/__init__.py` file (`version_check.check_tf_version()`).

**Comment by LukeWood** [comment]
I fixed this
