### ISSUE TITLE
Renam `num_classes` to `classes` for API consistency

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#653]
Idea by @fchollet, we will need to update all instances of `num_classes` to be `classes` in API surfaces.

This issue also will be used to track keras.io updates as well.

**Comment by MrinalTyagi** [comment]
@LukeWood Can I pick this up? If yes would surely appreciate some guidance on how to proceed.

**Comment by LukeWood** [comment]
actually already fixed this!  Thanks
