### ISSUE TITLE
Introduce serialization test for models

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#654]
This should be based on keras_cv/layers/serialization_test.py

**Comment by MrinalTyagi** [comment]
@LukeWood can i pick this up? Also would love some guidance around this.

**Comment by LukeWood** [comment]
Sure, feel free!

**Comment by MrinalTyagi** [comment]
@LukeWood Added a draft pr. Please have a look at it and let me know in case any modifications are required in the basic structure. I am having an issue in getting the init parameter of the model from config. Would appreciate some help from your end on this.

**Comment by MrinalTyagi** [comment]
In all the currently written serialization test files, they are writing for a class where the get_config function is subclassed specific for parameter signature for that class and requirement but in models we are returning from function and hence there is no get_config function available for that. Is there any way to get hold of initialising parameter of a constructed model. Do i have to restructure the whole function format into a class format?

**Comment by tanzhenyu** [comment]
@MrinalTyagi Is this still ongoing?

**Comment by LukeWood** [comment]
fixed
