### ISSUE TITLE
serialization_test.py for keras_cv/applications

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#655]
This should be based on keras_cv/layers/serialization_test.py

**Comment by MrinalTyagi** [comment]
@LukeWood Can i pick this up?

**Comment by LukeWood** [comment]
hold off on this one

**Comment by qlzh727** [comment]
This seems to be a duplication of https://github.com/keras-team/keras-cv/issues/654. Closing this for now.
