### ISSUE TITLE
Override fit() and train_on_batch() for OD models

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#662]
I will do this as a base object detection model class.  This will allow us to perform label encoding async on the host CPUs

**Comment by LukeWood** [comment]
Note to self: Check with tf.data() team

**Comment by LukeWood** [comment]
- map from raw x and y (and validation data) to tf.data.DataSets
- call .map() to call LabelEncoder
- call super().fit() with the constructed datasets

**Comment by LukeWood** [comment]
- numpy array for x and y (and EagerTensors)
- tf.data.DataSet
- sample weights
- DataFrames from pandas (tf.data may already have a method for this)
- input list of scalars (not super relevant to RetinaNet)

I will create a standalone utility function, construct a dataset, and then do the same for validation

**Comment by LukeWood** [comment]
we can also make sure to export:

https://source.corp.google.com/piper///depot/google3/third_party/py/keras/engine/data_adapter.py;l=1642;rcl=467572989

**Comment by tanzhenyu** [comment]
This is done through recent series of refactoring
