### ISSUE TITLE
Specifying the probability of applying an augmentation layer

### ISSUE THREAD

**Issue by ariG23498** [keras-team/keras-cv#664]
**Short Description**
The idea is to specify the **probability rate** at which a generic augmentation layer will be applied to the inputs. This can be achieved in two ways:
1. Having a `RanomApply` layer which accepts the Augmentation Layer and the probability rate. The augmentation layer will be applied in accordance to the probability provided.

Pseudocode:
```python
custom_random_flip = RandomApply(
    layer=RandomFlip(),
    rate=0.8
)
```
This would signify that we want our `custom_random_flip` layer to be applied with a probability of `0.8`.

2.  Accepting a `rate` argument for all the augmentation layers prefixed `Random`. The suggestion is based on the assumption that these layers have a without `Random` counterpart, which does not need any probability rate. The `Random<AUGMENATION_LAYER>` would accept the `rate` argument which would define with what probability should this layer be applied to the inputs.

**Existing Implementations**

- [PyTorch transform RandomApply](https://pytorch.org/vision/stable/generated/torchvision.transforms.RandomApply.html)
- [PyToch transform RandomHorizontalFlip](https://pytorch.org/vision/main/generated/torchvision.transforms.RandomHorizontalFlip.html) with the `p` arguments.

**Comment by sayakpaul** [comment]
```
custom_random_flip = RandomApply(
    layer=RandomFlip(),
    rate=0.8
)
```

An extension of this could be to allow the users to specify a list of augmentation transforms and the ability to set their probabilities. If individual probabilities are not specified default will be picked.

**Comment by sebastian-sz** [comment]
There is something similar in keras-cv: `MaybeApply`:
https://github.com/keras-team/keras-cv/blob/master/keras_cv/layers/preprocessing/maybe_apply.py 

> Apply provided layer to random elements in a batch.

**Comment by ariG23498** [comment]
Some pointers with `MaybeApply`:
- The `rate` parameter does not provide the probability of whether or not a layer is applied to the input
- The `rate` is a percentage of inputs on which the augmentation will be applied, the sample of selected inputs is random


If my understanding is correct, then `MaybeApply` deviates from the use case of `RandomApply`. The `RandomApply` or the `rate` parameter should signify whether _each_ input should be passed through a layer or not with a certain amount of probability.

CC: @AdityaKane2001 who has contributed to `MaybeApply`.

**Comment by ariG23498** [comment]
I am thinking of something like this. The code snippet is inspired from [TensorFlow blog-post on Augmentation](https://www.tensorflow.org/tutorials/images/data_augmentation#custom_data_augmentation).

```python
# This layer is similar to the `nn.Identity` layer
class Identity(keras.layers.Layer):
  def __init__(self, **kwargs):
    super().__init__(**kwargs)
  def call(self, inputs):
    return inputs

# The `random_apply` function takes the layer and the probability rate
# as its inputs. The layer will be applied to all the inputs with the probability
# of the rate provided.
def random_apply(layer: tf.keras.layers.Layer, p: Optional[float] = 0.5):
    if tf.random.uniform([]) < p:
      return layer
    else:
      return Identity()
```

**Comment by AdityaKane2001** [comment]
@ariG23498 

> Some pointers with MaybeApply:

> The rate parameter does not provide the probability of whether or not a layer is applied to the input
The rate is a percentage of inputs on which the augmentation will be applied, the sample of selected inputs is random
If my understanding is correct, then MaybeApply deviates from the use case of RandomApply. The RandomApply or the rate parameter should signify whether each input should be passed through a layer or not with a certain amount of probability.

It sounds that `RandomApply` is a special case of `MaybeApply`. `MaybeApply` seems to be a more robust option than `RandomApply`. WDYT?

**Comment by ariG23498** [comment]
@AdityaKane2001 

> It sounds that RandomApply is a special case of MaybeApply. MaybeApply seems to be a more robust option than RandomApply. WDYT?

Could you elaborate on this point a little more?

I have provided a code-walkthrough of `random_apply` as I think of it in this [comment](https://github.com/keras-team/keras-cv/issues/664#issuecomment-1207134454).

If we can mould `MaybeApply` to `RandomApply` it would be a great!

**Comment by sebastian-sz** [comment]
I think you mean that `RandomApply` works similar to `MaybeApply`, but `RandomApply` works on the entire batch, while `MaybeApply` works on individual inputs within the batch?

I think `RandomApply` would be interesting addition :)

**Comment by AdityaKane2001** [comment]
> I think you mean that RandomApply works similar to MaybeApply, but RandomApply works on the entire batch, while MaybeApply works on individual inputs within the batch?

Exactly. MaybeApply works on individual samples in the batch, whereas RandomApply works on the entire batch. IMO MaybeApply seems a better approach. Hence I am not sure if it is a worthwhile addition. Please feel free to correct me if I'm missing something. 

> I am thinking of something like this. The code snippet is inspired from [TensorFlow blog-post on Augmentation](https://www.tensorflow.org/tutorials/images/data_augmentation#custom_data_augmentation).

In case RandomApply is added to keras-cv, I believe a more object oriented approach is better than the functional approach. We would take a layer as an argument to the constructor and apply it randomly. See [RandomAugmentationPipeline](https://github.com/keras-team/keras-cv/blob/35b9f9534fc193e00b4fa850963a05b331467065/keras_cv/layers/preprocessing/random_augmentation_pipeline.py#L23), it is done in a similar fashion.

**Comment by sebastian-sz** [comment]
I'm thinking, maybe extend `MaybeApply` with a "mode" parameter that specifies, whether the augmentation should happen on batch or sample level?

**Comment by AdityaKane2001** [comment]
> I'm thinking, maybe extend MaybeApply with a "mode" parameter that specifies, whether the augmentation should happen on batch or sample level?

Yes, the though crossed my mind as well, but I think it would be slightly unintuitive. A separate layer makes more sense IMO.

**Comment by LukeWood** [comment]
Looks like we went with MaybeApply.

MaybeApply is a nice high order abstraction - thanks everyone!
