### ISSUE TITLE
RandomResizedCrop bounding box support

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#667]

**Comment by LukeWood** [comment]
@AdityaKane2001 will tackle this

**Comment by AdityaKane2001** [comment]
Yup, on it.

**Comment by AdityaKane2001** [comment]
@LukeWood do we assume the bounding boxes to be of a specific type? Like `xyxy` or `rel_xyxy`?

**Comment by LukeWood** [comment]
> @LukeWood do we assume the bounding boxes to be of a specific type? Like `xyxy` or `rel_xyxy`?

You’ll need to accept a bounding_box_format argument and convert internally.  After conversion you can perform the transformation, then convert back to the user’s specified format.  Check out how shear does this.

**Comment by ariG23498** [comment]
I was wondering if this layer was renamed to `RandomCropAndResize`.

If yes, the layer already supports bounding boxes and we can safely close this issue.
https://github.com/keras-team/keras-cv/blob/46e27acd40edcd9486e67ca3adfbd315ae6406fb/keras_cv/layers/preprocessing/random_crop_and_resize.py#L144

(Apologies if I misread something)
