### ISSUE TITLE
Support ViT model

### ISSUE THREAD

**Issue by tanzhenyu** [keras-team/keras-cv#668]
Transformer models are becoming more and more relevant. Let's support it by having ViT first.
citing https://arxiv.org/pdf/2010.11929.pdf

**Comment by sayakpaul** [comment]
Happy to work on it.

**Comment by ariG23498** [comment]
I am willing to work on this as well.

**Comment by tanzhenyu** [comment]
> I am willing to work on this as well.

Thanks for providing the help! This is currently assigned, would you be open to contributing other transformer based vision models? for example, swin transformer

**Comment by ariG23498** [comment]
Sure!

**Comment by tanzhenyu** [comment]
> Sure!

https://github.com/keras-team/keras-cv/issues/671

Somehow I can't assign to you through user name...

**Comment by ariG23498** [comment]
> Somehow I can't assign to you through user name...

I think we need to comment on the issue to be assigned?

**Comment by deepwilson** [comment]
If this is not assigned I would love to take this up or help if needed.

**Comment by sayakpaul** [comment]
It's assigned.

![image](https://user-images.githubusercontent.com/22957388/183631170-ec90960f-77bc-46cb-902d-e1ce95f2da61.png)

**Comment by sayakpaul** [comment]
Sorry for the delay. But I still have it planned to contribute to this.

**Comment by cybergeekgyan** [comment]
I want to contribute to this issue, Can anyone guide me through. How to proceed with it..

**Comment by bhack** [comment]
> I want to contribute to this issue, Can anyone guide me through. How to proceed with it..

There is a PR at https://github.com/keras-team/keras-cv/pull/1014
