### ISSUE TITLE
Supporting FasterRCNN object detection model

### ISSUE THREAD

**Issue by tanzhenyu** [keras-team/keras-cv#669]
Other than RetinaNet, the library should support a heavier model that allows trade-off between performance / speed.
We will start with core components first, and decide what kind of meta architecture API we should provide that allows a keras.application-like experience.
For detailed design decisions, please comment on this [RFC](https://github.com/keras-team/governance/pull/38).

**Comment by MrinalTyagi** [comment]
@tanzhenyu Would like a lot to help on this issue.

**Comment by tanzhenyu** [comment]
This is currently supported. Will be public API in 0.4 release. Closing it
