### ISSUE TITLE
Difference to MaP and upstream pycocotools metrics

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#684]
Area range happens after matching/before, this can make a numerical difference.  Line reference:

https://github.com/keras-team/keras-cv/blob/master/keras_cv/metrics/coco/mean_average_precision.py#L237

**Comment by LukeWood** [comment]
Can be either fixed or just documented in the white paper

**Comment by tanzhenyu** [comment]
Closing this as duplicate of https://github.com/keras-team/keras-cv/issues/915
