### ISSUE TITLE
RetinaNet needs images of at least 512x512 to run properly

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#696]
this should either error out, or automatically pad

**Comment by LukeWood** [comment]
I think this should error out, I’ll add unit tests for this

**Comment by sachinprasadhs** [comment]
Thanks for reporting the issue.

`RetinaNet` with the new implementation is now part of [KerasHub](https://github.com/keras-team/keras-hub) a consolidated `KerasNLP` and `KerasCV` package.
The model weights are available in `Kaggle`, for details and usage refer https://www.kaggle.com/models/keras/retinanet

We will not be making any changes to the models in `KerasCV` which are made available in `KerasHub` or the APIs/Utils made available in `Keras`.
If you still face any issue, please file a new issue in [keras-hub](https://github.com/keras-team/keras-hub)
