### ISSUE TITLE
Make `keras_cv.layers.Resizing` support bounding_boxes

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#702]

**Comment by DB11051998** [comment]
Hi! is anyone working on this issue?  if noone, i would like to work on this.

**Comment by LukeWood** [comment]
No, please feel free to contribute this.  You should port the Keras layer to the repo, update to use the KerasCV style, and add bounding box support.  thank you!

**Comment by DB11051998** [comment]
Thanks @LukeWood for assigning me this.

**Comment by DB11051998** [comment]
@LukeWood 

![image](https://user-images.githubusercontent.com/43936231/192819388-eded1c3b-4c43-4e3f-b9ea-085951b52aea.png)

when u say "port  the keras layer to the repo" do you mean importing the resizing class present in the keras in the __init__.py code of the boundingbox  package(I have attached the screenshot of it). Could you please correct me here. If i am wrong, could you please explain me the objective?

**Comment by LukeWood** [comment]
This is what I mean:

This PR is incomplete, but you can use it as a starter
https://github.com/keras-team/keras-cv/pull/861

**Comment by DB11051998** [comment]
Thanks @LukeWood !! it's a good starter code.

**Comment by DB11051998** [comment]
![image](https://user-images.githubusercontent.com/43936231/193401964-9076b6cf-8ad4-45e2-8baf-93be4922c1a6.png)


 whenever i am calling the Resizing class, it is calling from the keras package, which is ultimately throwing an error, to it. why it is going to that package??....whereas in the __init__.py, i am importing this Resizing class

![image](https://user-images.githubusercontent.com/43936231/193402116-d9fe6fed-69ef-4f24-8083-4255a182885b.png)
this is the Resizing class, by taking the refernce from your code.

**Comment by tre3x** [comment]
Hi, can i work on this issue?

**Comment by LukeWood** [comment]
Yes, feel free to open a PR.  You’ll need to port the layer as I have done in the linked PR, then add bounding box support to it.

**Comment by Snimm** [comment]
Hi, I want to work on this. Or is it done?

**Comment by LukeWood** [comment]
> Hi, I want to work on this. Or is it done?

It works in pad to aspect ratio mode.  Support for other modes is more than welcome!

**Comment by arcAman07** [comment]
Hey is this issue still open? I was looking forward to contribute to keras_cv

**Comment by LukeWood** [comment]
I've actually completed this! Sorry, forgot to mark complete.
