### ISSUE TITLE
Unit test GPU utilization of popular configurations using NVIDIA-smi 

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#706]

**Comment by LukeWood** [comment]
I’ll kick this effort off with a RetinaNet training loop test.

**Comment by bhack** [comment]
If you need we could also retrieve the achieved occupancy (and other metrics):

https://docs.nvidia.com/gameworks/content/developertools/desktop/analysis/report/cudaexperiments/kernellevel/achievedoccupancy.htm


With a light python ctype wrapper over Nvidia cupti:
https://github.com/sree314/pycupti/tree/trunk/pycupti

**Comment by LukeWood** [comment]
Cool 😎 thanks for the references!  This will be really useful for making some performance guarantees to our users.

**Comment by tanzhenyu** [comment]
We track utilization through our model training benchmarks
