### ISSUE TITLE
Add Seam Carving preprocessing layer

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#707]
**Short Description**

Seam Carving: A Content-Aware Image Resizer
![image](https://user-images.githubusercontent.com/17668390/185799551-a2db2723-a048-4a57-9798-461f44cfa889.png)

**Papers**

[Paper-link.](https://www.researchgate.net/publication/215721610_Seam_Carving_for_Content-Aware_Image_Resizing)
Citation:  2242

**Existing Implementations**

- https://github.com/yu4u/seam-carving

**Other**

Maybe! 

```python
tf.keras.layers.Resizing(interpolation=seam_carving)
```

**Comment by tanzhenyu** [comment]
@innat can you help us verify how this augmentation would help some of our main downstream tasks? (detection / segmentation)

**Comment by innat** [comment]
@tanzhenyu 
I raised this ticket as a image processing layer (KPL). Mostly inspired from this application  https://www.kaggle.com/code/ren4yu/mayo-clinic-removing-background-via-seam-carving.
