### ISSUE TITLE
Document weight management for KerasCV

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#71]
This includes:
- default values
- code locations
- GCS upload
- how to reproduce weights
- where to store reproduction scripts

**Comment by bhack** [comment]
Some of this points are really important as they are really going to expand over the limited reporducbility of the train process. A topic that wasn't handled in the recent PR review at:
https://github.com/keras-team/keras/pull/15447

**Comment by bhack** [comment]
As an extra point I hope that we could evaluate to have some free CI ltraining job resoruces for the community integrated with Github Action.
But I know that it could be partially connected to this:
https://github.com/tensorflow/build/issues/61#issuecomment-991244641

**Comment by bhack** [comment]
Why we are closing this?

**Comment by LukeWood** [comment]
> Why we are closing this?

Project direction has continued to evolve, and while this is still something we will do, this bug is not actionable at this time.

**Comment by bhack** [comment]
Ok please put a short sentence when you are closing a ticket if it is not super trivial to understand why we are closing it without participating to the internal meetings.  So that we could keep the "external" community on the same page. Thanks
