### ISSUE TITLE
IoU Object Detection Metric

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#713]
The IoU metric for object detection is an essential.  We need to offer this under `keras_cv.metrics`.

**Comment by LukeWood** [comment]
Great first issue!

**Comment by silvererudite** [comment]
Hi..I would like to work on this pls.

**Comment by DavidLandup0** [comment]
Can you assign this to me? :)

**Comment by tanmaypandey7** [comment]
I guess we can close this issue as per https://github.com/keras-team/keras-cv/pull/1226#issuecomment-1374338721?
