### ISSUE TITLE
bounding_box.convert_format should keep the dtype by default

### ISSUE THREAD

**Issue by atuleu** [keras-team/keras-cv#720]
**Short Description**

Currently, `bounding_box.convert_format` always cast the passed object to a tf.float32. This cast should remain optional. 
When you develop a complex layer depending on this function, as soon as you change from `float32` precision to `mixed_float16`, you literally need to change every call to this function to add a `dtype=boxes.dtype` argument.

I think it would be a much better API if this function should optionally cast the input tensor if a dtype is specified.

**Papers**
None
**Existing Implementations**

**Other Information**
happy to contribute to this change of API

**Comment by ianstenbit** [comment]
@LukeWood can you please confirm that there isn't a need to perform casting (this can be an optional param so we don't always cast)

**Comment by LukeWood** [comment]
Sorry for the delay @ianstenbit on this.  

convert_format() does actually need a dtype, as `rel_xywh` CANNOT be represented in `int` dtypes.  We could require floats in, but this is a bit annoying for users to have to cast to floats.   I think accepting a dtype as we do: https://github.com/keras-team/keras-cv/blob/master/keras_cv/bounding_box/converters.py#L298 is more optimal.

We can, however, pass `self.compute_dtype` to the `dtype` argument whenever we use this.
