### ISSUE TITLE
Add augment_bounding_boxes support to RandomCutOut layer

### ISSUE THREAD

**Issue by divyashreepathihalli** [keras-team/keras-cv#730]
The augment_bounding_boxes should be implemented for RandomCutOut Layer in keras_cv. The PR should contain implementation, test scripts and a demo script to verify implementation.

Example code for implementing augment_bounding_boxes() can be found here

- https://github.com/keras-team/keras-cv/blob/master/keras_cv/layers/preprocessing/random_flip.py#:~:text=def%20augment_bounding_boxes(,)%3A
- https://github.com/keras-team/keras-cv/blob/master/keras_cv/layers/preprocessing/random_rotation.py#:~:text=def%20augment_image(self%2C%20image%2C%20transformation%2C%20**kwargs)%3A
- The implementations can be verified using demo utils in keras_cv.bounding_box - Example of demo script can be found here : https://github.com/keras-team/keras-cv/blob/master/examples/layers/preprocessing/bounding_box/random_rotation_demo.py

**Comment by soma2000-lang** [comment]
@divyashreepathihalli  I am working on this one.

**Comment by soma2000-lang** [comment]
@divyashreepathihalli  It would be great if you can review my PR

**Comment by divyashreepathihalli** [comment]
@soma2000-lang I have reviewed the PR. Thank you for your contribution.

**Comment by ariG23498** [comment]
@soma2000-lang do you wanted to continue working on this?

If yes, you can claim this #1992 and get started. Apologies is you are already on it 🤗
