### ISSUE TITLE
Add augment_bounding_boxes support to RandomTranslation layer

### ISSUE THREAD

**Issue by divyashreepathihalli** [keras-team/keras-cv#732]
The augment_bounding_boxes should be implemented for RandomTranslation Layer in keras_cv. The PR should contain implementation, test scripts and a demo script to verify implementation.

Example code for implementing augment_bounding_boxes() can be found here

- https://github.com/keras-team/keras-cv/blob/master/keras_cv/layers/preprocessing/random_flip.py#:~:text=def%20augment_bounding_boxes(,)%3A
- https://github.com/keras-team/keras-cv/blob/master/keras_cv/layers/preprocessing/random_rotation.py#:~:text=def%20augment_image(self%2C%20image%2C%20transformation%2C%20**kwargs)%3A
- The implementations can be verified using demo utils in keras_cv.bounding_box - Example of demo script can be found here : https://github.com/keras-team/keras-cv/blob/master/examples/layers/preprocessing/bounding_box/random_rotation_demo.py

**Comment by akucia** [comment]
Hi! I'm currently working on implementation of this layer. I should be able to submit a PR this week.

**Comment by ariG23498** [comment]
https://github.com/keras-team/keras-cv/blob/46e27acd40edcd9486e67ca3adfbd315ae6406fb/keras_cv/layers/preprocessing/random_translation.py#L204

I have noticed that this layer already has the `augment_bounding_boxes`. We should be able to close it.

CC: @ianstenbit
