### ISSUE TITLE
Is mixed precision, mixed_float16, not supported for certain augmentations

### ISSUE THREAD

**Issue by sfleisch** [keras-team/keras-cv#734]
I found that certain augmentations fail when the mixed precision policy is set to mixed_float16 but work with float32.  So far I've found this to be true for RandomColorDegeneration and Solarization - both run individually and within the RandAugment layer.

Is there a work around? I did try specifying the dtype for the RandAugment layer but that didn't change the outcome.

**Comment by sfleisch** [comment]
I think I have the workaround:

1. set the floating point global policy to float32
3. create the dataset with the randaugment (or any keras_cv augmentation layer(s)) mapping
4. set the global policy to mixed_float16
5. create the model and proceed.
    The dtype policy for the model layers are float16 where keras so deems fit.
    At this point looping through the layers of the randaugment layer shows a float32 dtype_policy for each one.
    Running the model in the flower demo returned float16 predictions also indicating a float16 model.

**Comment by LukeWood** [comment]
Internally we don't have the bandwidth to audit all of the layers right now, but I'm happy to review PRs to fix this.

Absolutely a great bug report.  If you can provide a list of layers that do not support this I bet it would streamline the contribution process.

**Comment by LukeWood** [comment]
> Is there a work around? I did try specifying the dtype for the RandAugment layer but that didn't change the outcome.

at the moment I'd guess not.  We are probably casting to the wrong data type in one of our layers.  I'm also happy to add a test case to catch this if you (or any contributor!) can come up with one.

Let me know how you'd want to proceed @sfleisch

**Comment by bhack** [comment]
@sfleisch Can you share a minimal but complete gist/colab to reproduce your issue?
