### ISSUE TITLE
RandomShear can push bounding boxes full outside of the frame

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#744]
We need to filter these.

This can be done via a check at the end of augment_bounding_boxes using a `tf.where()` condition.  In this condition, check if the coordinates are inside of the image, if they are not set class_id to -1 so they are filtered out.

**Comment by pranavjadhav001** [comment]
@LukeWood I can take this up,since i've made this feature. Can you tell me how were you able to reproduce this case?
