### ISSUE TITLE
Sync Dockerfile with setup.py

### ISSUE THREAD

**Issue by bhack** [keras-team/keras-cv#746]
@LukeWood are we able to maintain in sync the `Dockerfile` with `setup.py` dependecies changes? Or do we want to find another solution?

https://github.com/keras-team/keras-cv/commit/50512ef0238633dc8cae68bf7819c1220c0d0cc9#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R34

https://github.com/keras-team/keras-cv/blob/f1f1b8207c791c33106aad84dbe7602b7b4904d3/.devcontainer/Dockerfile#L9

P.s. I think also that `tensorflow_datasets`  is a test dependency or not?

**Comment by LukeWood** [comment]
we can fix it with a PR if anyone is interested!

**Comment by bhack** [comment]
> we can fix it with a PR if anyone is interested!
Yes sure but what I meant is:

Do you think that the team will go to care also this file when it add dependency? 

As it is already the 2nd time:
https://github.com/keras-team/keras-cv/pull/436
