### ISSUE TITLE
Specify to install tensorflow in the contributing guidelines

### ISSUE THREAD

**Issue by zaccharieramzi** [keras-team/keras-cv#806]
Right now the contributing guidelines do not specify that tensorflow needs to be installed in [the environment setup](https://github.com/keras-team/keras-cv/blob/master/.github/CONTRIBUTING.md#setup-environment) (as is done in [the github actions](https://github.com/keras-team/keras-cv/blob/master/.github/workflows/actions.yml#L35)).

It could be nice to have it so that the developers do not even have to think twice about it.

**Comment by bhack** [comment]
Is this a duplicate of https://github.com/keras-team/keras-cv/issues/489 ?

**Comment by zaccharieramzi** [comment]
No, it's really about making sure that the contributing guidelines are complete when it comes to setting up the dev environment.

**Comment by bhack** [comment]
I think it is the same as we don't need any extra info on the guidelines if we correctly depend on Keras:

https://github.com/keras-team/keras/blob/master/requirements.txt#L6

**Comment by zaccharieramzi** [comment]
Yes sorry, hadn't read that carefully, closing
