### ISSUE TITLE
Add bounding box support for RRC

### ISSUE THREAD

**Issue by AdityaKane2001** [keras-team/keras-cv#809]
Current implementation of RandomResizedCrop (#738) does not have bounding box support. 

Need to add bounding box support while taking special care of fill_mode="reflect".

/cc @LukeWood

**Comment by sachinprasadhs** [comment]
Hi, Bounding box support for RandomCropAndResize has been implemented in the commit here https://github.com/keras-team/keras-cv/commit/17bc73ee8a0afe8702137e674c714e7a5c6fbedb 
Please verify and close this issue. Thanks!
