### ISSUE TITLE
AutoContrast preprocessing layer

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#81]
Reference implementation: https://github.com/tensorflow/similarity/blob/906d141b75acf00d0e1d37dd0d88c432bbb30f57/tensorflow_similarity/augmenters/img_augments.py#L542

**Comment by qlzh727** [comment]
@LukeWood, Is this related to RandomContrast in core keras? or we need to implement a new KPL.

**Comment by qlzh727** [comment]
oh I see https://github.com/keras-team/keras-cv/pull/194
