### ISSUE TITLE
Implement `bounding_box.smart_resize`

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#830]
This can be used in `keras_cv.layers.RandomCropAndResize` to implement the inference behavior.

**Comment by martin-gorner** [comment]
Please avoid names like "smart*" in favor of more descriptive names.

Example:
layers.Resizing(smart_resize=True)
was renamed
layers.Resizing(crop_to_aspect_ratio=True)

**Comment by tanzhenyu** [comment]
I think the recent KPL work accomplished this task by jitterandresize
