### ISSUE TITLE
Split API docs for `preprocessing/` into `preprocessing/` and `augmentation/`

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#835]
https://keras.io/api/keras_cv/layers/preprocessing/

**Comment by jacoverster** [comment]
Hi @LukeWood I'd like to give this a go please.

**Comment by jacoverster** [comment]
Hi @LukeWood, any comment on this maybe?

**Comment by sachinprasadhs** [comment]
Now we have differentiated the same into `preprocessing` and `augmentation` here https://keras.io/api/keras_cv/layers/.

Also, I have created PR to update the list with the new APIs here https://github.com/keras-team/keras-io/pull/1825
