### ISSUE TITLE
Posterize preprocessing layer

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#84]
https://github.com/tensorflow/similarity/blob/906d141b75acf00d0e1d37dd0d88c432bbb30f57/tensorflow_similarity/augmenters/img_augments.py#L494

**Comment by sebastian-sz** [comment]
I think PIL implementation assumes uint8 dtype, and TF's `bitwise` ops only support integers. 

Is it safe to assume that this layer's input will only accept integer values in range 0-255? Or should it accept any dtype, cast internally to uint8, posterize and cast back to original dtype?

**Comment by LukeWood** [comment]
Thanks so much @sebastian-sz
