### ISSUE TITLE
 StableDiffusion() model fails to reproduce same image from same prompt and seed

### ISSUE THREAD

**Issue by BFauber** [keras-team/keras-cv#844]
The `StableDiffusion()` model fails to reproduce the same image when provided with the same `seed` value and `prompt`. 

This issue is likely linked to inconsistency with the `tf.random.normal()` function. This function appears in line 187 of `stable_diffusion.py` https://github.com/keras-team/keras-cv/blob/master/keras_cv/models/generative/stable_diffusion/stable_diffusion.py. 

I recommend either 1) repair `tf.random.normal()` to consistently provide the same output with the same `seed` value, or 2) replace that function with `tf.random.stateless_normal()` on line 187 of `stable_diffusion.py` for consistent outputs with a fixed `seed` value.

An example of the inconsistency of `tf.random.normal()` is shown in the snippet below:
```python
import numpy as np
import tensorflow as tf
​
np.sum(tf.random.normal((1,2,3,4), seed=123))
OUT: -4.219632
np.sum(tf.random.normal((1,2,3,4), seed=123))
OUT: 1.8580852
```

Conversely, `tf.random.stateless_normal()` is consistent when using the same `seed` value:
```python
np.sum(tf.random.stateless_normal((1,2,3,4), seed=[123,1]))
OUT: 2.5994601
np.sum(tf.random.stateless_normal((1,2,3,4), seed=[123,1]))
OUT: 2.5994601
```

**Comment by BFauber** [comment]
Here is the code I am running (NOTE: this was pulled directly from line 57 of `stable_diffusion.py` at https://github.com/keras-team/keras-cv/blob/master/keras_cv/models/generative/stable_diffusion/stable_diffusion.py):

  ```python
from keras_cv.models import StableDiffusion
from PIL import Image

model = StableDiffusion(img_height=512, img_width=512, jit_compile=True)
img = model.text_to_image(
      prompt="A beautiful horse running through a field",
      batch_size=1,  # How many images to generate at once
      num_steps=25,  # Number of iterations (controls image quality)
      seed=123,  # Set this to always get the same image from the same prompt
)

display(Image.fromarray(img[0]))
  ```

Each time I run this code, I receive a different output image, even though the `seed` value is the same and should provide identical output images.

**Comment by ianstenbit** [comment]
Thanks for calling this out! I think we most likely want to switch to `stateless_normal` in this case. @LukeWood can you confirm please?

@BFauber feel free to send a PR switching to stateless_normal and linking to this issue!

**Comment by tanzhenyu** [comment]
https://github.com/keras-team/keras-cv/pull/962

**Comment by BFauber** [comment]
Thanks @ianstenbit, @LukeWood, @tanzhenyu, and @fchollet for addressing this topic via: https://github.com/keras-team/keras-cv/pull/962
