### ISSUE TITLE
Create a better workflow for dynamic image batch sizes in the RetinaNet guide

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#849]

**Comment by sachinprasadhs** [comment]
Thanks for reporting the issue.

`RetinaNet` with the new implementation is now part of [KerasHub](https://github.com/keras-team/keras-hub) a consolidated `KerasNLP` and `KerasCV` package.
The model weights are available in `Kaggle`, for details and usage refer https://www.kaggle.com/models/keras/retinanet

We will not be making any changes to the models in `KerasCV` which are made available in `KerasHub` or the APIs/Utils made available in `Keras`.
If you still face any issue, please file a new issue in [keras-hub](https://github.com/keras-team/keras-hub)
