### ISSUE TITLE
Get the frames for each step of the Stable Diffusion denoising process

### ISSUE THREAD

**Issue by ISipi** [keras-team/keras-cv#850]
**Short Description**
The `StableDiffusion().text_to_image()` could return the frames from each step of the denoising process in order to make a video of the training process. I've made a fork and have an implementation there.

**Papers**

NA

**Existing Implementations**

My inspiration for implementing was this [video](https://youtu.be/ltLNYA3lWAQ?t=1995).

**Other Information**

**Comment by LukeWood** [comment]
Thanks for the issue report!

If you contribute a notebook subclassing stable diffusion to do this I think evaluating the APIs general usefulness will be much easier!

**Comment by tanzhenyu** [comment]
@ianstenbit this might be relevant to your work

**Comment by LukeWood** [comment]
Probably not worth an API; this is probably more just a workflow for users to implement
