### ISSUE TITLE
Automatically compute number of output filters based on AnchorGenerator in RetinaNet

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#858]
Right now, you manually have to pass a `PredictionHead` to `box_head` and `classification_head` and manually ensure the number of `AnchorBoxes` matches the number of outputs from each head when called on every level of the feature pyramid.

Unfortunately, this is not always possible right now, but we can do some validation to make this more streamlined.

**Comment by sachinprasadhs** [comment]
Thanks for reporting the issue.

`RetinaNet` with the new implementation is now part of [KerasHub](https://github.com/keras-team/keras-hub) a consolidated `KerasNLP` and `KerasCV` package.
The model weights are available in `Kaggle`, for details and usage refer https://www.kaggle.com/models/keras/retinanet

We will not be making any changes to the models in `KerasCV` which are made available in `KerasHub` or the APIs/Utils made available in `Keras`.
If you still face any issue, please file a new issue in [keras-hub](https://github.com/keras-team/keras-hub)
