### ISSUE TITLE
Color degeneration preprocessing layer

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#86]
reference implementation: https://github.com/tensorflow/similarity/blob/906d141b75acf00d0e1d37dd0d88c432bbb30f57/tensorflow_similarity/augmenters/img_augments.py#L465

**Comment by LukeWood** [comment]
This basically blends between grayscale and that original color image.

**Comment by innat** [comment]
Is there any reference paper for this technique or reference of widely used cases? I think JpegCompression is more suitable alternative of this https://github.com/keras-team/keras-cv/issues/135

**Comment by bhack** [comment]
https://cvil.eecs.yorku.ca/projects/public_html/wb_emulation/index.html

**Comment by bhack** [comment]
Instead what we have linked in the similarity repo It was there for Randaugment:

https://arxiv.org/abs/1909.13719


But if you check ablation study on Table 5 it didn't have a significative delta in performance.

**Comment by innat** [comment]
It looks like a part of the RandAugment. Will it be included as a separate layer?

**Comment by LukeWood** [comment]
yes - I will be working on this next!

**Comment by qlzh727** [comment]
Ack. Assigned to you.
