### ISSUE TITLE
classification directory for classifier

### ISSUE THREAD

**Issue by pure-rgb** [keras-team/keras-cv#871]
I see that there are separate folder for each category. But the imagenet models are placed outside arbitrary. They should be placed under `classification` directory.

https://github.com/keras-team/keras-cv/tree/master/keras_cv/models

![image](https://user-images.githubusercontent.com/45315076/193246422-4024c068-fe28-4841-80d5-4397aefcca6b.png)

**Comment by LukeWood** [comment]
@tanzhenyu @ianstenbit @qlzh727 what do you think about this?  

On one hand, these are more than classification models.  They're modular backbones.

Perhaps we throw them in a backbones directory?  the line between classification model and backbone model is very rough.

**Comment by ianstenbit** [comment]
Since this won't affect our exported API (these should be exported as e.g. `keras_cv.models.ResNet50V2`), I don't think it's particularly important how we structure the folder. I think given that they are foundational and re-used in addition to being a user API on their own as classification models, they ought to stay where they are now, but I could be convinced otherwise.

**Comment by tanzhenyu** [comment]
I'm completely fine with it under `models/backbone` directory.

**Comment by qlzh727** [comment]
I think all the current classification models are mostly backbone plus a classification head. If we split the backbone from the head, then it will be a more split of directory, where backbone will be most of the model body, and classification can be light weighted.

**Comment by tanzhenyu** [comment]
> I think all the current classification models are mostly backbone plus a classification head. If we split the backbone from the head, then it will be a more split of directory, where backbone will be most of the model body, and classification can be light weighted.

So my take here is that in the long run, classification head will be history. So our backbones taking "include_top" is just a very thin wrapper to include the head, which is fine and shouldn't confuse users, I guess?

**Comment by bhack** [comment]
As we have now also transformers doing these task is backbone definition mainly valid for pure CNN networks?

**Comment by tanzhenyu** [comment]
> As we have now also transformers doing these tasks is backbone definition mainly valid for pure CNN networks?

IIUC, some of them are still backbones -- MaxVit, Swin, etc. Some of them are not. Putting those plug-and-play transformer-based backbones into `models/backbone` is fine with me

**Comment by tanzhenyu** [comment]
Summary: Let's move to `models/backbone` while not impacting APIs

**Comment by LukeWood** [comment]
This is done
