### ISSUE TITLE
Separate augmentations & preprocessing layers on keras.io

### ISSUE THREAD

**Issue by pure-rgb** [keras-team/keras-cv#872]
![image](https://user-images.githubusercontent.com/45315076/193281664-d90de2a9-8a29-48f7-ae7c-d64ad002666b.png)

Some are called random and some are not. Is it expected?

**Comment by bhack** [comment]
Semi duplicate @martin-gorner https://github.com/keras-team/keras-cv/issues/826#issuecomment-1256127121

**Comment by LukeWood** [comment]
This is a documentation bug really - some of these are NOT random, and are jut preprocessing layers.  Some are augmentation layers.

We should update our documentation to have a `preprocessing/` page and an `augmentation/` page
