### ISSUE TITLE
Stable diffusion benchmark

### ISSUE THREAD

**Issue by bhack** [keras-team/keras-cv#876]
Do we have a reference benchmark for our stable diffusion inference?

Meta claimed a 2.5x gain with AITemplate over XLA (I suppose Pytorch-XLA):
https://github.com/facebookincubator/AITemplate/tree/main/examples/05_stable_diffusion#results

**Comment by tanzhenyu** [comment]
There are some reports here:
https://news.ycombinator.com/item?id=33005585
But I don't think an "official" 3p benchmark is available.
