### ISSUE TITLE
FocalLoss

### ISSUE THREAD

**Issue by KyloRen1** [keras-team/keras-cv#877]
I am doing a multiclass classification model with FocalLoss

On the output of the model, I have a softmax with 4 classes. But the FocalLoss produces an error 
`ValueError: `logits` and `labels` must have the same shape, received ((None, 4) vs (None, 1)).`

**Comment by innat** [comment]
The error message above is self-explanatory. You can check this test scripts to realize your target shape and prediction shape. https://github.com/keras-team/keras-cv/blob/master/keras_cv/losses/focal_test.py

**Comment by LukeWood** [comment]
@innat is correct that the error message is correct.  I think you need to one hot encode your labels.

happy to help if this doesn’t work.
