### ISSUE TITLE
Evaluate augmentation policies and API

### ISSUE THREAD

**Issue by bhack** [keras-team/keras-cv#900]
**Short Description**
I think that we could re-evaluate if we need to introduce separated augmentation policies and eventually define their interaction with the preprocessing layers API:

https://github.com/keras-team/keras-cv/issues/108#issuecomment-1040626481
https://github.com/keras-team/keras-cv/issues/108#issuecomment-1043598240

**Papers**
https://arxiv.org/abs/2206.06544

**Other Information**
https://github.com/keras-team/keras-cv/pull/898#discussion_r991682613 (/cc @tanzhenyu)
https://github.com/keras-team/keras-cv/discussions/93

**Comment by LukeWood** [comment]
I'm not sure what this bug means - can you further elaborate?

**Comment by bhack** [comment]
Ask to @tanzhenyu as he requested me to open this at https://github.com/keras-team/keras-cv/pull/898#discussion_r991682613

But as we bulky closing all the (users) tickets a some PR you could close also this one if you want.

**Comment by LukeWood** [comment]
Ok, looking at the PR this looks like a duplicate.
