### ISSUE TITLE
Xception architecture

### ISSUE THREAD

**Issue by DavidLandup0** [keras-team/keras-cv#904]
**Short Description**

Do we want to add Xception to KerasCV? Seems like a natural fit, and I've had Xception perform quite similar to EfficientNets (1-3) in most cases. It has nearly 10k citations, isn't hard to implement, and can be ported with the same pre-trained weights from `keras.applications` if need be.

**Other Information**

If so, sign me up to port it!

**Comment by tanzhenyu** [comment]
This is Francois's domain, I will let him comment.
I think we should :-)

**Comment by jbischof** [comment]
Closing as stale for now. Xception is not a SoTA arch now.
