### ISSUE TITLE
MOAT networks

### ISSUE THREAD

**Issue by bhack** [keras-team/keras-cv#911]
**Short Description**
Are we interested in Google Research MOAT networks or are they too fresh for our standards?

**Papers**
https://arxiv.org/abs/2210.01820

**Existing Implementations**
https://github.com/google-research/deeplab2/blob/main/model/pixel_encoder/moat.py

https://github.com/google-research/deeplab2/blob/main/g3doc/projects/moat_imagenet_pretrained_checkpoints.md

**Other Information**
/cc @martin-gorner

**Comment by tanzhenyu** [comment]
Closing this as it is too fresh for us to evaluate how important it is to support. We should reopen it once we have a better understanding
