### ISSUE TITLE
Implement StableWorld Keras.Io tutorial using KerasCV

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#922]
Example Colab:

https://colab.research.google.com/drive/1RXRrkKUnpNiPCxTJg0Imq7sIM8ltYFz2?usp=sharing

**Comment by ADITYADAS1999** [comment]
hi [LukeWood](https://github.com/LukeWood)  this issue is still open for work? I looking for solving friendly issues.

**Comment by shireenchand** [comment]
Hi @LukeWood is this issue open? Could you explain what exactly are you looking for in this issue?
