### ISSUE TITLE
Preprocessing layers should take native box format

### ISSUE THREAD

**Issue by tanzhenyu** [keras-team/keras-cv#926]
Today, in order to augment_bbox, users are required to pass `[y_min, x_min, y_max, x_max, class_id]` to the layer input, i.e., concat `gt_boxes` and `gt_classes`.
This is a little anti user experience for the purpose of feeding our COCO metrics API. It also makes it hard to scale for other formats such as segmentation maps, if we need our COCO metrics API to support masking IOU computation later.
Instead, what is more user friendly is to accept `[y_min, x_min, y_max, x_max]` as this is usually what's being loaded from datasets, and either:
1) override `test_step` to concat gt_boxes and gt_classes before feeding the metrics
or 2) have metrics accept dictionary inputs

**Comment by LukeWood** [comment]
this is done
