### ISSUE TITLE
TensorPipe library integration in keras-cv

### ISSUE THREAD

**Issue by kartik4949** [keras-team/keras-cv#94]
Hi,
@LukeWood
I have built an library called TensorPipe, this is an ImageGenerator on steroids library.
Please take a look and let me know if we can integrate it :)
this is an input pipeline with all state of the art augmentation pipeline.
https://www.github.com/kartik4949/TensorPipe

So, idea is 
We will have something called pipeline, like layers, which user can use to make computer vision tensorflow tfdataset pipeline.

Thanks

**Comment by LukeWood** [comment]
Hey @kartik4949 - very cool.

In particular, I think your libraries ability to work with bounding boxes is really impressive and a useful reference.  

I'm not sure what would make far as far as integration goes - right now I'm planning to use `RandAugment` as the one stop shop for classification augmentation, perhaps we will introduce one for bounding boxes as well.

Please let me know if you have any ideas for integration you'd want me to consider - note everything will have to be written the "Keras" way.  For example, my RandAugment implementation will consist of many sub-layers that perform each individual augmentation.

**Comment by kartik4949** [comment]
Hey,
So by integration, we can copy the entire structure of tensorpipe.
And replace augmentations with layers in keras-cv.
We can start from scratch for this :)

Also let me know if you are free for brain storming over this as i have lot of ideas in the space :)
@LukeWood

**Comment by LukeWood** [comment]
Closing for now, we can discuss specific ideas in the future !
