### ISSUE TITLE
Devcontainer GPU support

### ISSUE THREAD

**Issue by jacoverster** [keras-team/keras-cv#945]
I propose a small update to devcontainer.json to enable GPU support.

This relates to [Issue 893](https://github.com/keras-team/keras-cv/pull/893).

I suggest adding "RunArgs" to devcontainer.json to allow GPU access inside the container otherwise the GPU might not be available inside the container.

```
// Uncomment this if GPU support it is required
// "runArgs": [
//     "--gpus=all"
// ],
```

**Comment by bhack** [comment]
Ok can you send a PR?

**Comment by jacoverster** [comment]
Hi @bhack, sure thing. Should I wait for your PR for [Issue 893](https://github.com/keras-team/keras-cv/pull/893) to be merged first?

**Comment by jacoverster** [comment]
Sure thing @bhack .
