### ISSUE TITLE
Move layer aliases to keras_cv.layers from keras_cv.layers.preprocessing

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#95]

**Comment by old-school-kid** [comment]
Can we have a boiler plate so users can add functionalities under right hood? Like preprocessing, attention units and so on.

**Comment by LukeWood** [comment]
Sure thing @old-school-kid - contributors shouldn’t sweat this for now, I’ll move all of these in a single PR pretty soon here.

**Comment by LukeWood** [comment]
I did this earlier this evening.
