### ISSUE TITLE
SSD - Single Shot Detector head component.

### ISSUE THREAD

**Issue by sebastian-sz** [keras-team/keras-cv#960]
**Short Description**
Given that Object Detection is currently on the roadmap I think it would be great to also include an SSD Head component, which we could attach to different backbones for Object Detection task.

**Papers**
[SSD: Single Shot MultiBox Detector](https://arxiv.org/abs/1512.02325)

**Existing Implementations**
[Pytorch implementation](https://github.com/pytorch/vision/blob/8e0e715700877bd252836772704f513f7ed48265/torchvision/models/detection/ssd.py#L56)
Nvidia's [Pytorch Implementation](https://github.com/NVIDIA/DeepLearningExamples/blob/40eeae756c2c8b7f1d9140a5c846063802f5e6c8/PyTorch/Detection/SSD/ssd/model.py#L55)

**Comment by tanzhenyu** [comment]
Marking this as contribution welcome. It is aligned with our roadmap.

**Comment by bhack** [comment]
/cc @oarriaga if he is interested to contribute his SSD implementation:
https://github.com/oarriaga/paz/

**Comment by AdonaiVera** [comment]
Hi @sebastian-sz Is this issue still welcoming contributions? If yes, then can I contribute ?

**Comment by innat** [comment]
@srikesh-07 some resource 
- https://github.com/srihari-humbarwadi/ssd_tensorflow 
- https://github.com/balancap/SSD-Tensorflow
