### ISSUE TITLE
Should IoU loss be pairwise?

### ISSUE THREAD

**Issue by quantumalaviya** [keras-team/keras-cv#969]
The implementation of IoU Loss which was merged as part of #634  works with the current implementation of `compute_iou`, i.e. it calculates pairwise IoUs and means over the IoU matrix. 

However, in some implementations (YoloX, for example), i<sup>th</sup> box of `y_true` is compared only to the i<sup>th</sup> box of `y_pred`.  Should the current KerasCV implementation be updated to mimic this?

This issue is also meant for the open GIoU loss PR (#682)

**Comment by LukeWood** [comment]
Summary from @quantumalaviya and I's discussion offline:

- we will support whatever YOLOx needs, if we need to support pairwise mode we will do so behind a kwarg.
