### ISSUE TITLE
format.sh doesn't format all linter cases

### ISSUE THREAD

**Issue by DavidLandup0** [keras-team/keras-cv#990]
The `format.sh` script formats almost all of the cases that makes the linter complain, but not all. In previous pushes, I've noticed two cases:

- Whitespace at the end of a docstring line
- f-string without placeholders

The second one is on the contributor to take care of, but the first one should probably be handled by the formatting script. Are there any other cases anyone's noticed?

**Comment by LukeWood** [comment]
Unfortunately we don't really control the format scripts' dependencies.  In my opinion black should remove whitespace at the end of docstring lines, but I am sure they have a good reason to not do it if they haven't done it yet. 

I dont think we would want to introduce custom python code to support this unless theres a nice package that is easy to use that already solves this problem.

**Comment by bhack** [comment]
It seems that they want these preserved or not?

https://github.com/psf/black/issues/1462

**Comment by DavidLandup0** [comment]
> Unfortunately we don't really control the format scripts' dependencies.

I thought it was customizable - my bad for not checking. Thanks for the clarification!

> It seems that they want these preserved or not?
Yeah, it looks like they want the whitespaces to be preserved. Honestly, not sure why? 

Closing the issue, thanks!
