### ISSUE TITLE
Support SD 1.5

### ISSUE THREAD

**Issue by achuinard** [keras-team/keras-cv#991]
SD 1.5 has been out for a few weeks, will this repo be updated to use it?

**Comment by LukeWood** [comment]
> SD 1.5 has been out for a few weeks, will this repo be updated to use it?

SD 1.5 is a set of upgraded weights for the same architecture, right?

**Comment by BFauber** [comment]
@LukeWood , yes, upgraded weights with the same architecture.

"The Stable-Diffusion-v1-5 checkpoint was initialized with the weights of the Stable-Diffusion-v1-2 checkpoint and subsequently fine-tuned on 595k steps at resolution 512x512 on "laion-aesthetics v2 5+" and 10% dropping of the text-conditioning to improve classifier-free guidance sampling." See: https://huggingface.co/runwayml/stable-diffusion-v1-5 for additional details.

**Comment by tanzhenyu** [comment]
We should probably have a more "structured" weights handling logic. Today it's mostly based on task / dataset / model, but it seems the dataset is a mixed of sources

**Comment by bhack** [comment]
> Let's investigate if we should have reproducible weights porting codelabs, similar to KerasNLP

Do we have the scripts contributed to the repo to reproduce h5 conversions in `https://huggingface.co/fchollet/stable-diffusion/`?

**Comment by LukeWood** [comment]
I'll be handling this, https://drive.google.com/corp/drive/folders/1Ld0YsScNLGKQYOaGxZPavbiVnAv3gyFR?resourcekey=0-kWzgH_0wlMSJ38yj4Y9Zjw

**Comment by bhack** [comment]
It is private.

**Comment by tanzhenyu** [comment]
> I'll be handling this, https://drive.google.com/corp/drive/folders/1Ld0YsScNLGKQYOaGxZPavbiVnAv3gyFR?resourcekey=0-kWzgH_0wlMSJ38yj4Y9Zjw

The discussion is more about "can other users copy our porting script to port the weights by themselves". It'd be a nice thing to have if we can provide it

**Comment by bhack** [comment]
> The discussion is more about "can other users copy our porting script to port the weights by themselves". It'd be a nice thing to have if we can provide it

Yes, I think the same it is why I have asked https://github.com/keras-team/keras-cv/issues/991#issuecomment-1310734615 also cause here we are talking about SD 1.5. but SD 2.0 and the relative checkpoint was just released right now in its github repo.

**Comment by bhack** [comment]
2.1 is out

**Comment by ianstenbit** [comment]
Closing this as we now offer SD 2
