### ISSUE TITLE
BUG: StableDiffusion() broken after recent update

### ISSUE THREAD

**Issue by BFauber** [keras-team/keras-cv#995]
Unfortunately, a recent update appears to have broken the `StableDiffusion()` class function found in `keras_cv.models.generative`.  Loading the  `StableDiffusion()` function now throws the following error and requires ~20 min to run, whereas it previously ran in <5 seconds (NVIDIA V100 GPU, CUDA v11.8) with the `keras-cv` version available on GitHub on Friday 11/4:

`WARNING:tensorflow:5 out of the last 54 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7fc4486947a0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.`

Here is the code that throws the error:

```python
from tensorflow import keras
from keras_cv.models import StableDiffusion

# Enable mixed precision
keras.mixed_precision.set_global_policy("mixed_float16")

model = StableDiffusion(
    img_height=512, 
    img_width=512, 
    jit_compile=True
)

prompt = "photograph of coffee beans"
seed = 44079

img0 = model.text_to_image(
    prompt=prompt,
    batch_size=1,
    num_steps=25,
    unconditional_guidance_scale=7.5,
    seed=seed,
)
```

Updates #973 and #989 appear to have occurred within the past few days, but it is unknown if these updates are related to the error.

**Comment by bhack** [comment]
Yes it was introduced with the `lazy_load` refactoring in https://github.com/keras-team/keras-cv/pull/989

**Comment by ianstenbit** [comment]
Thank you @BFauber  for posting the issue, and thank you @bhack for the fix (I'll merge once comments are resolved)
I agree that #989 is the cause of this issue.

**Comment by LukeWood** [comment]
Surprised that would be causing that.  Interested to hear the conclusion..

**Comment by bhack** [comment]
> Surprised that would be causing that. Interested to hear the conclusion..

It is that every time we access to the property we execute `.compile` and it is going to trigger the autograph and so on...

**Comment by LukeWood** [comment]
Ahhhh I see.
