### ISSUE TITLE
 AttributeError: 'StableDiffusion' object has no attribute 'inpaint'

### ISSUE THREAD

**Issue by oconnoob** [keras-team/keras-cv#996]
Hi there! I'm attempting to use Keras' Stable Diffusion for inpainting in Colab, and I'm running into the error I'm hoping someone has a solution to.

At the top of the notebook, I've updated both keras_cv and tensorflow with pip, and I'm working with the following versions:
  
  Versions:
  - **keras** = 2.10.0
  - **kerav_cv** = 0.3.4
  - **tensorflow** = 2.10.0
  - **pip** = 21.1.3
  - **python** = 3.7.15

I'm trying to inpaint an image with the following code

```python
# Imports
import keras_cv
import requests 
from PIL import Image
import numpy as np


# Fetch image
file_URL = "https://c0.wallpaperflare.com/preview/87/385/209/man-riding-on-the-skateboard-photography.jpg"
r = requests.get(file_URL)
with open("man-on-skateboard.jpg", 'wb') as f:
    f.write(r.content)


# Convert image to Tensor
img = Image.open("man-on-skateboard.jpg")
img = np.array(img)


# Create mask (not sure if I have to flip 1s and 0s)
mask = np.zeros((img.shape[:2]))
mask[240:605, 211:455] = 1


# Define inpainting options
inpaint_options = dict(
        prompt="An alien riding a skateboard, phororealistic, high quality, high resolution",
        image=img, 
        mask=mask,
        num_resamples=1,
        batch_size=1,
        num_steps=25,
        unconditional_guidance_scale=7.5,
        diffusion_noise=None,
        seed=1234,
        verbose=True,
)

# Instantiate the model
model = keras_cv.models.StableDiffusion(img_height=512, img_width=512, jit_compile=False)

# Attempt inpainting
inpainted = model.inpaint(**inpaint_options)
```

When I try to execute the above, I receive the following error: `AttributeError: 'StableDiffusion' object has no attribute 'inpaint'`

When I execute `dir(model)`, I indeed see that `inpaint` is not an attribute. 

```python
[ <PRIVATE ATTRIBUTES>,
'decoder',
 'diffusion_model',
 'encode_text',
 'generate_image',
 'img_height',
 'img_width',
 'text_encoder',
 'text_to_image',
 'tokenizer']
```

If anyone could clarify what the problem is here and how to fix it, that would be much appreciated!

**Comment by bhack** [comment]
It was just merged 2 days ago so you need to use `master` https://github.com/keras-team/keras-cv/pull/973#issuecomment-1306626887

**Comment by ianstenbit** [comment]
You can install the latest version from GitHub to get this functionality:

`pip install git+https://github.com/keras-team/keras-cv.git`

Note that you'll want to wait until #997 is merged (should be merged imminently)

**Comment by oconnoob** [comment]
Thank you @bhack and @ianstenbit !
